### ISSUE TITLE
Model.Close does not await CloseAsync

### ISSUE THREAD

**Issue by bollhals** [rabbitmq/rabbitmq-dotnet-client#1011]
From [#1008 comment](https://github.com/rabbitmq/rabbitmq-dotnet-client/pull/1008#discussion_r566646174) the model close method ignores the returned task of CloseAsync.

=> No exception on shutdown will be raised for this task, this should be fixed.

**Comment by lukebakken** [comment]
I searched the current `6.x` and `main` code for `_ =` and this issue does not appear to apply any more.
