### ISSUE TITLE
Semaphore Disposed Exception thrown in AsyncConsumerWorkService

### ISSUE THREAD

**Issue by ashneilson** [rabbitmq/rabbitmq-dotnet-client#1014]
## Problem

When under load, the ChannelReader can return a Work item after the `_limiter` has been Disposed resulting in a `System.ObjectDisposedException` being thrown.

https://github.com/rabbitmq/rabbitmq-dotnet-client/blob/d39bb71a0009784f1ebf64030bad404f067cee4d/projects/RabbitMQ.Client/client/impl/AsyncConsumerWorkService.cs#L131-L139

**Comment by michaelklishin** [comment]
Thank you for investigating the issue and contributing a fix!
