### ISSUE TITLE
Purpose of SoftProtocolException

### ISSUE THREAD

**Issue by bollhals** [rabbitmq/rabbitmq-dotnet-client#1019]
We have a [SoftProtocolException](https://github.com/rabbitmq/rabbitmq-dotnet-client/blob/master/projects/RabbitMQ.Client/client/exceptions/SoftProtocolException.cs) which is abstract, but no derived implementation for it. I was wondering is this a left over (and thus can be removed) or what is the use case for it? 🤔

**Comment by michaelklishin** [comment]
In the early days the client as designed after the concepts in the protocol. This represents a [channel-level error](https://www.rabbitmq.com/channels.html#error-handling. If we do not actually use it, it definitely can be removed.

**Comment by bollhals** [comment]
Currently if we do such a soft error (see #1020) the channel is closed by the server and the call (if it is a request) is returning an exception. So there is no need for such an exception for now. If you agree, I'll include the removal in one of my next PR.
