### ISSUE TITLE
Missing method: BasicPublish after update to latest mono and xamarin.ios sdk

### ISSUE THREAD

**Issue by bnikollov** [rabbitmq/rabbitmq-dotnet-client#1032]
We are using the RabbitMQ client library with Xamarin application. After the latest update of mono SDK and Xamarin.iOS SDK we got an issue on the iOS application. For some reason the BasicPublish method is missing. Here is the error:

"DeviceModel":"Apple iPhone","OS":"iOS 14.4.1","message":"Exception","ExceptionMessage":"Method not found: void RabbitMQ.Client.IModelExensions.BasicPublish(RabbitMQ.Client.IModel,string,string,RabbitMQ.Client.IBasicProperties,System.ReadOnlyMemory`1<byte>)","StackTrace":" at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1[TResult].Start[TStateMachine] (TStateMachine& stateMachine) [0x0002c] in /Library/Frameworks/Xamarin.iOS.framework/Versions/Current/src/Xamarin.iOS/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/AsyncMethodBuilder.cs:471 \n at Vapp.Services.Network.QueueApi.WebMessageClient.SendMessageAsync (Vapp.Models.Network.QueueApi.Outgoing.OutgoingWebMessage message) [0x0000c] in <8b277fb515eb472fb32c2af9d425a279>:0 \n 

We thought it could a Linker issue but the error is still there if turn off the Linker at all.

Thanks in advance! :)

**Comment by michaelklishin** [comment]
I will convert this issue to a GitHub discussion. Currently GitHub will [automatically close and lock the issue](https://github.com/github/feedback/discussions/3197) even though your question will be transferred and responded to elsewhere. This is to let you know that we do not intend to ignore this but this is how the current GitHub conversion mechanism makes it seem for the users :(
