### ISSUE TITLE
ModelBase.WaitForConfirmsOrDieAsync uses ShutdownInitiator.Application rather than Library

### ISSUE THREAD

**Issue by StevenBonePgh** [rabbitmq/rabbitmq-dotnet-client#1039]
I am using logic similar to that mentioned in #159 to recover connections, and it has worked great except for a recent case. The logic is:
```
model.ModelShutdown += (sender, args) =>
{
    if (args.Initiator == ShutdownInitiator.Application)
        return; //We closed it, do not attempt to recover.
    // Library/Peer closed it so recover. [Code snipped]
}; 
```
However, the code in `ModelBase.WaitForConfirmsOrDieAsync` does this:
https://github.com/rabbitmq/rabbitmq-dotnet-client/blob/66dc8ca4b18b3fcd2c5b28623a9109c4e177c468/projects/RabbitMQ.Client/client/impl/ModelBase.cs#L1098-L1121

Since it is using `ShutdownInitiator.Application`, my autorecovery code does not fire. I would expect the RabbitMq Client to use `ShutdownInitiator.Library` in this case. Is this a bug, or should I handle things differently?

**Comment by michaelklishin** [comment]
I doubt this was an intentional decision. Please submit a PR.
