### ISSUE TITLE
Error: The connection was lost from mosquitto_pub when worker runs in Kubernetes cluster

### ISSUE THREAD

**Issue by ninomllr** [rabbitmq/rabbitmq-dotnet-client#1041]
I am trying to get a system to work where we have the following setup through RabbitMQ: 

MQTT (IoT Devices) --> RabbitMQ <-- AMQP (.NET Worker)

The c# worker looks like this, as we deleted everything to find out what the issue could be. For faking the IoT devices we are testing with mosquitto_pub. When we run this code locally and publish to RabbitMQ with Mosquitto, everything works (even with more code where we subscribe and interpret the messages and write them to a database). We also tried to dockerize the applications and we run everything in Docker locally, with success. 

As soon as we install the .NET worker on our Kubernetes cluster though, we receive `Error: The connection was lost.` messages on publishing through Mosquitto. Every other message works and then we get the error again. This behaviour happens ONLY when we have a Worker running in Kubernetes (microk8s instance). 

We have tested the following setups:
* Worker in VSCode debugging --> RabbitMQ (on Microk8s) <-- MQTT Mosquitto = works
* Worker in Docker container run locally --> RabbitMQ (on Microk8s) <-- MQTT Mosquitto = works
* Worker in Kubernetes Pod --> RabbitMQ (on Microk8s) <-- MQTT Mosquitto = doesn't work (it works but Mosquitto gives the error every other message).

I would assume that it's maybe not even an error with RabbitMQ or RabbitMQ .NET client, but I am a bit lost on where to find the logs to actually start finding a solution to this. Can someone help out here?

**Worker.cs**
```
using System;
using System.Text;
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.Hosting;
using Microsoft.Extensions.Logging;
using Npgsql;
using RabbitMQ.Client;
using RabbitMQ.Client.Events;
using RabbitMQ.Client.Exceptions;
using System.Net;
using System.IO;

namespace RabbitMQWorkerService
{
	public class Worker : BackgroundService
	{
		private readonly ILogger<Worker> _logger;
		private readonly IConfiguration _configuration;
		private ConnectionFactory _connectionFactory;
		private IConnection _connection;
		private IModel _channel;
		private Timer _timer;
		private static object _lock = new object();

		private const string QueueName = "aaaa.smartbin.queue";

		/// <summary>
		/// Constructor
		/// </summary>
		/// <param name="logger"></param>
		public Worker(ILogger<Worker> logger, IConfiguration configuration)
		{
			_logger = logger;
			_configuration = configuration;
		}

		/// <summary>
		/// Create async connection with RabbitMQ broker
		/// It will be create one Channel pro Queue
		/// </summary>
		/// <param name="cancellationToken"></param>
		/// <returns></returns>
		public override Task StartAsync(CancellationToken cancellationToken)
		{
			_logger.LogInformation("START WORKER --------------------------.");

			_logger.LogInformation("AFTER TIMER --------------------------.");

			string rabbitHost = _configuration["RabbitHostName"];

			_logger.LogInformation("rabbitHost--------------------------." + rabbitHost);

			int rabbitPort = int.Parse(_configuration["RabbitPort"]);
			string rabbitUserName = _configuration["RabbitUserName"];
			string rabbitPassword = _configuration["RabbitPassword"];

			_connectionFactory = new ConnectionFactory
			{
				HostName = rabbitHost,
				Port = rabbitPort,
				UserName = rabbitUserName,
				Password = rabbitPassword,
				DispatchConsumersAsync = true
			};
			_connection = _connectionFactory.CreateConnection();
			_channel = _connection.CreateModel();



			string ExchangeName = "amq.topic";
			string RoutingKey = "aaaa.smartbin.*";

			return base.StartAsync(cancellationToken);

		}

		/// <summary>
		/// Subscriber / Consumer      
		/// Wait for request from smart bin 
		/// For now take only Topics ala RoutingKey
		/// Queue has more channels depends on IoT devices
		/// </summary>
		/// <param name="stoppingToken"></param>
		/// <returns></returns>
		protected override async Task ExecuteAsync(CancellationToken stoppingToken)
		{
			_logger.LogInformation("BEFORE CREATES CHannels --------------------------.");

			_logger.LogInformation("AFTER CREATES CHannels --------------------------.");
		}

		/// <summary>
		/// Stop connection
		/// </summary>
		/// <param name="cancellationToken"></param>
		/// <returns></returns>
		public override async Task StopAsync(CancellationToken cancellationToken)
		{
			System.Console.WriteLine("STOP ASYNC ------------------------");
			_logger.LogInformation("RabbitMQ connection is closed.");
		}

	}
}

```

**Comment by michaelklishin** [comment]
I will convert this issue to a GitHub discussion. Currently GitHub will [automatically close and lock the issue](https://github.com/github/feedback/discussions/3197) even though your question will be transferred and responded to elsewhere. This is to let you know that we do not intend to ignore this but this is how the current GitHub conversion mechanism makes it seem for the users :(
