### ISSUE TITLE
Misinformation in the RabbitMQ.Client.Events.AsyncEventingBasicConsumer summary

### ISSUE THREAD

**Issue by andyrkn** [rabbitmq/rabbitmq-dotnet-client#1044]
https://github.com/rabbitmq/rabbitmq-dotnet-client/blob/7557d0c169f1c123fc66509c20505ac4c82d3005/projects/RabbitMQ.Client/client/events/AsyncEventingBasicConsumer.cs#L29-L34

The event fires on consumer registration and not cancellation. The summary can be fixed to better reflect the method as it can cause confusion right now.

**Comment by michaelklishin** [comment]
Misinformation is a pretty strong word to describe a typo :D

You are welcome to submit pull request for such trivial changes in the future. This is open source software after all.
