### ISSUE TITLE
Release 6.2.2

### ISSUE THREAD

**Issue by michaelklishin** [rabbitmq/rabbitmq-dotnet-client#1052]
It's been a while for `6.x` releases.

**Comment by bollhals** [comment]
Wouldn't it be more useful to release current master as 6.3 or 7.0 (depending on breaking changes and your process)? I assume quite some improvements from master are not in the 6.x branch.

Also if master would be released, can we make sure to include #962 ?

**Comment by michaelklishin** [comment]
When should 7.0 be released and what it should include is a separate discussion. master has quite a few changes so at the very least we need to go through a few weeks of RCs.

**Comment by bollhals** [comment]
> When should 7.0 be released and what it should include is a separate discussion. master has quite a few changes so at the very least we need to go through a few weeks of RCs.

I think in master would be enough changes in that would warrant a 7.0/6.3 release, can this be started in parallel?

**Comment by michaelklishin** [comment]
We can produce 7.0 shortly but it would take some time to produce a decent change log. There are many changes in master right now.

**Comment by michaelklishin** [comment]
[`6.2.2` is up on nuget.org](https://www.nuget.org/packages/RabbitMQ.Client/6.2.2).
