### ISSUE TITLE
Release 7.0 RC1

### ISSUE THREAD

**Issue by michaelklishin** [rabbitmq/rabbitmq-dotnet-client#1056]
@bollhals has suggested that we should produce a 7.0 RC soon. The biggest outstanding item right now is the change log.

**Comment by ogxd** [comment]
Hello, any ETA on this?

**Comment by lukebakken** [comment]
No ETA. As you can see the remaining PRs for 7.0 are very large, affect huge amounts of the code, and need to be brought up-to-date with the current `master` branch.

**Comment by CrazyMushu** [comment]
Hello
Maybe there is at least an approximate release date for version 7.0?
