### ISSUE TITLE
Recover loop on known exception. While it is an exception which the code can not recover from.

### ISSUE THREAD

**Issue by Inlustris** [rabbitmq/rabbitmq-dotnet-client#1067]
When fixing #1064 I came to the conclusion while unit testing there is a problem within the recover loop. The fix for using a new channel to recover configurational settings instead of an closed or disposed channel. 
A closed channel results in a known exception "AlreadyClosedException".

When experiencing a known exception even when it is a non recoverable exception (A closed channel will never open again). It will run in a loop retrying the full recovery.

The function below will handle known exceptions. Even if these will result in a non-recoverable connection. Which means it will re-throw the exception originally catched.
```
        private static void HandleTopologyRecoveryException(TopologyRecoveryException e)
        {
            ESLog.Error("Topology recovery exception", e);
            if (e.InnerException is AlreadyClosedException || e.InnerException is OperationInterruptedException || e.InnerException is TimeoutException)
            {
                throw e;
            }
            ESLog.Info($"Will not retry recovery because of {e.InnerException?.GetType().FullName}: it's not a known problem with connectivty, ignoring it", e);
        }
```

This will result in the following function (AutorecoveringConnection.Recovery.cs) catching this exception. Like in the message explained "Will try again after retry interval." means several recover steps could be completed but it will try the whole recover again after the retry interval. 
```
 private bool TryPerformAutomaticRecovery()
 {
       try
       {
             Code....
       }
       catch (Exception e)
       {
           ESLog.Error("Exception when recovering connection. Will try again after retry interval.", e);
       }
```

This could be solved by not trying again or turning the already recovered steps back. This will still result in a never ending loop but it will not create thousands of connections and/or channels. Which would drain RabbitMQ of recourses.

This would result in real change that could impact people. I really would like to know the opinion of the main team on this. I could take a look at what could be done to fix this. But to stop retrying could impact people in a very wrong way and what would be a stop condition if it is a know error. Those known errors are implemented like this for a reason. 

By changing it you will probably kill the retry loop which is needed just for the case a connection gets killed.

**Comment by bollhals** [comment]
I do see your point, the thing though is that there are always going to be cases that should've been handled differently.

What I mean by that is you just discovered this due to a other bug. Once that is fixed it is "right" again.
On the other hand if we give up in certain condition, I'm fairly certain we'll eventually find a situation where we should've continued but stopped.

**Comment by Inlustris** [comment]
@bollhals Fair enough. Better try again then to stop. 

In case unrecoverable exception happened on declarations or channel restore. (My original Bug was declaration issues)

Only gap in this solution is for example: (Maybe not production wise but explains the issue correctly)
### starting conditions:
- 2 connections
- each connection 300 channels
- each channel 1 consumer

### recovery started 5 seconds in
- 2 connections
- 600 channels
- 0 consumers

### recovery started 10 seconds in
- 4 connections
- 1200 channels
- 0 consumers

### recovery started 15 seconds in
- 6 connections
- 1800 channels
- 0 consumers

Simple solution does a recover fail should we turn back the full recovery until start. Instead of creating new ones instead every 5 seconds. This will drain the recourses of both application and RabbitMQ server. 

I don't directly suggest stopping with recovery. But clean up the mess made so a new recovery can be a clean start.
