### ISSUE TITLE
ConnectionRecovery recovers models before consumers

### ISSUE THREAD

**Issue by bollhals** [rabbitmq/rabbitmq-dotnet-client#1076]
I have a reproduced state in our application, where the connection recovery leads to an unrecoverable error.

Situation:
- 1 AutorecoverConnection + Channel
- The connection dropped (plugged out the cable)
- The recovery procedure starts its loop to recover
- Cable is plugged in again
- Connection can be established again, and the recover starts.

Now the fun begins...
While the recovery is [within these lines here](https://github.com/rabbitmq/rabbitmq-dotnet-client/blob/6.x/projects/RabbitMQ.Client/client/impl/AutorecoveringConnection.cs#L420-L424) a RPC message gets tried to published. 

Since the models have already been recovered (Line 420), the publish actually succeeds, but the server will respond with `PRECONDITION_FAILED - fast reply consumer does not exist` because the consumer for the replies has not yet been recovered. (Line 424)

The outcome of this is that the channel will close and rendered unusable, while the connection recovery succeeds.

So the question is, should the AutorecoveringModel already be usable again prior to the recovery being finished?

It kind of is related to #1061 as it will touch similar area.
If a temporary model would restore the topology, then at least the time between the recovery of the models and the recovery of the consumers would be shortened. (Still possible tough)

**Comment by bollhals** [comment]
This is now fixed on 6.x branch and on main. 

Would it be possible to do a bugfix release for the 6.x and close this issue then?

**Comment by michaelklishin** [comment]
I'll try to do it today. There were some pipeline changes forced on us (e.g. expiring signing keys) so I cannot be certain releasing would just work.

**Comment by michaelklishin** [comment]
We had a go at doing a release, it required an internally used Docker image rebuild. Hopefully we can finalise it later this week. Sorry about the wait.

**Comment by bollhals** [comment]
Would it be possible to give a rough timeframe? (We're planning a release of our product, which we hit this issue)
