### ISSUE TITLE
How to cancel timed out queueBind

### ISSUE THREAD

**Issue by MartinKosicky** [rabbitmq/rabbitmq-dotnet-client#1078]
Hi my question is how do I recover from situation where the 
   
`_channel.QueueBind(`
returns timeout for some reason. Because for my situation, if i do many queueBind in a row and if one times out, the next returns Pipelining is not supported. How do I recover from such situation?

**Comment by michaelklishin** [comment]
I will convert this issue to a GitHub discussion. Currently GitHub will [automatically close and lock the issue](https://github.com/github/feedback/discussions/3197) even though your question will be transferred and responded to elsewhere. This is to let you know that we do not intend to ignore this but this is how the current GitHub conversion mechanism makes it seem for the users :(
