### ISSUE TITLE
Memory leak while closing AutorecoveringModel

### ISSUE THREAD

**Issue by idursun** [rabbitmq/rabbitmq-dotnet-client#109]
We have noticed that List of Channels in AutorecoveringConnection is growing as we use channels.

This is how we create channels: 
```csharp
using(IModel model = connection.CreateModel()) {
  
}
```
We looked into AutorecoveringConnection code and see that it is adding created models into a list, and unregistering it only when UnregisterModel method is called. UnregisterModel is used inside Close methods but in Dispose method m_delegate.Close is called instead of calling Close. So this is causing leaks. We created a memory dump and observed that there are 79k items in the list, there are fewer channels open to rabbitmq. This means channels are closed as expected but not removed from the list.

**Comment by michaelklishin** [comment]
@idursun thank you for the details. We'll take a look shortly.

**Comment by onatm** [comment]
:+1:

**Comment by michaelklishin** [comment]
#110 should fix it. @idursun can you please [build the client from source](https://github.com/rabbitmq/rabbitmq-dotnet-client/blob/master/RUNNING_TESTS.md#building) on the `stable` branch and see if the issue is resolved for you?

**Comment by hancengiz** [comment]
you guys rock! @idursun  @michaelklishin

**Comment by idursun** [comment]
Thanks for the quick fix. Unfortunately I'm not able to build code in stable branch because of Turkish capital I problem in auto code generation.
```
rabbitmq-dotnet-client\gensrc\RabbitMQ.Client\autogenerated-api-0-9-1.cs(883,28,883,41): error CS0115: 'RabbitMQ.Client.Framing.BasicProperties.Correlationİd': no suitable method found to override
```
Is there a nightly build repository that we can get NuGet packages to test?

**Comment by michaelklishin** [comment]
Nightly builds are produced once a day in the morning and not published to NuGet.

I'm not sure how non-ASCII characters may result in the above error, more likely you need to run `msbuild.exe /t:Clean` and then `msbuild.exe` to build from scratch.

Anyhow, here's a .dll built from the tip of `stable` a few moments ago (ce2f19198):
https://drive.google.com/file/d/0B12DYRM8lqNoTi1qZ1BQV2FGZEk/view

**Comment by michaelklishin** [comment]
@idursun @onatm @hancengiz can someone please try the above DLL and let me know how it goes? We plan on doing a release today.

**Comment by onatm** [comment]
@michaelklishin we don't have access to link you provided. However, we managed to build the source. Now we are testing it.

**Comment by michaelklishin** [comment]
Doh. Alright then!

**Comment by onatm** [comment]
It looks OK for us. When will you release it?

**Comment by michaelklishin** [comment]
RC today and `3.5.4` hopefully next week.

**Comment by vtortola** [comment]
Hi! sorry to write on an old issue, but I have been seeing a similar behavior on 5.1.0.

Our app creates a channel per websocket connection, and correctly disposes it when the connection dies. Connections lasts up to 10 min, and we never have more than 500 concurrent connections.

Despite of that, memory grows little but constant and after roughly a week, the application takes more than 512 Mb of RAM. We see that when concurrent connections count goes down, memory levels are the same, and keep growing on new connections.

I setup a local environment to test this behavior, and memory snapshot is kind of revealing:

![image](https://user-images.githubusercontent.com/704420/57066654-0f29bd80-6ccd-11e9-9269-9ed4bef8a872.png)

Setting `AutomaticRecoveryEnabled = false` on the connection factory, solves the problem. Memory consumption follows the concurrent connections count pattern now.

**Comment by michaelklishin** [comment]
Please post your questions to the mailing list. Our team does not use GitHub issues for discussions or investigations. There are 11.5K channels in the provided tree, which more often than not is an indication of [channel churn](https://www.rabbitmq.com/channels.html#high-channel-churn).
