### ISSUE TITLE
...

### ISSUE THREAD

**Issue by domicioam** [rabbitmq/rabbitmq-dotnet-client#1105]
...

**Comment by michaelklishin** [comment]
You are welcome to submit a pull request with the changes.

**Comment by domicioam** [comment]
> 
> 
> You are welcome to submit a pull request with the changes.

Is that your way of calling me lazy? I am not familiar with the library to provide a proper summary.

**Comment by domicioam** [comment]
"We are committed to making participation in this project a harassment-free experience for everyone."
