### ISSUE TITLE
Incorrect comments in some public member documentation

### ISSUE THREAD

**Issue by lukebakken** [rabbitmq/rabbitmq-dotnet-client#1109]
User @domicioam noticed the following incorrect comments in #1105:

![141652977-26c68741-38e0-4c48-b5fb-32cf4ab3bdb4](https://user-images.githubusercontent.com/514926/141805910-7a4082c0-d3bb-4fc3-8b0d-19d3cc36f554.jpg)

**Comment by lukebakken** [comment]
@domicioam please understand that when we suggest opening a pull request to fix issues it is to confirm that yes, the issue is valid and that yes, we would appreciate a contribution to fix it.

**Comment by lukebakken** [comment]
> I am not sure if that was the intention. I felt like the other guy was calling me lazy for reporting it instead of fixing it.

I am certain that @michaelklishin's intention is to suggest contributing to the library, _not_ suggest anyone is lazy. The RabbitMQ core team (I'm part of it) receives many issue reports across a large number of repositories here on GitHub. A fraction of those (like yours) are legitimate and we suggest opening pull requests in case people are hesitant to do so. If an issue doesn't require a fix we say so as well.

In general, open-source project maintainers may seem abrupt with their comments but it's best to take them at face value rather than reading into them. We're all busy with our day jobs!

**Comment by michaelklishin** [comment]
@domicioam I did not imply that anyone is lazy. It's a perfectly common thing to suggest for a maintainer: if the problem is well understood, the reporter might as well submit a PR.

**Comment by lukebakken** [comment]
These particular XML comments appear to be correct in `main`.
