### ISSUE TITLE
Bug fix AsyncEventHandler<ShutdownEventArgs> Shutdown

### ISSUE THREAD

**Issue by PetrosArgyrakis** [rabbitmq/rabbitmq-dotnet-client#1112]
There is a bug in the AsyncEventingBasicConsumer related to the Shutdown event handler, which can be reproduced with the following scenario:

===================================================

Create a ConnectionFactory that includes the following options:

                AutomaticRecoveryEnabled = true,
                TopologyRecoveryEnabled = true,
                DispatchConsumersAsync = true,
                ConsumerDispatchConcurrency = 20 (or anything greater than 1)

Then create an AsyncEventingBasicConsumer and register a ShutDown Handler (asyncEventingBasicConsumer.Shutdown += OnShutDown;).

Start consuming from a queue with manual ack, and double ack the messages with the same delivery tag. 

This will cause a soft protocol error which will cause the channel to shutdown, but the shutdown handler will not be called always.

===================================================

**Comment by lukebakken** [comment]
Fixed by #1113
