### ISSUE TITLE
Setting x-message-ttl Exception

### ISSUE THREAD

**Issue by Oleg26Dev** [rabbitmq/rabbitmq-dotnet-client#1114]
I have an existing Queue with messages and want to change the Queues TTL. 

Do it:
```
var args = new Dictionary<string, object>();
args.Add("x-message-ttl", 20000);
model.QueueDeclare("DoBeDo", false, false, false, args);

```

But receive: 
```
The AMQP operation was interrupted: AMQP close-reason, initiated by Peer, code=406, text='PRECONDITION_FAILED - 
inequivalent arg 'x-message-ttl' for queue 'DoBeDo' in vhost '/': 
received the value '20000' of type 'signedint' but current is none', classId=50, methodId=10

```

What is wrong? Is it possible to change the TTL for the existing Queue with messages?

**Comment by michaelklishin** [comment]
I will convert this issue to a GitHub discussion. Currently GitHub will [automatically close and lock the issue](https://github.com/github/feedback/discussions/3197) even though your question will be transferred and responded to elsewhere. This is to let you know that we do not intend to ignore this but this is how the current GitHub conversion mechanism makes it seem for the users :(
