### ISSUE TITLE
Make IBasicProperties.SetPersistent() a .NET property

### ISSUE THREAD

**Issue by cH40z-Lord** [rabbitmq/rabbitmq-dotnet-client#112]
While browsing the examples of the .NET Client for RabbitMQ I've noticed something that made me a bit curious: It is `IBasicProperties`'s `SetPersistent()` method.

I'm wondering why this is an actual method instead of a regular .NET property (`public bool Persistent { get; set; }`) like many others that are part of the `IBasicProperties` interface?

In fact the current `SetPersistent()` method doesn't throw any exceptions (which you should *never ever* do in a property) and it doesn't return `this` for method chaining. 

All typical candidates that I've mentioned above to transform a .NET property into a regular getter/setter method are not given.
So in my opinion there is no real reason why this method should remain as it is and not become a .NET property other than the fact that this is a backwards compatibility breaking change.

The benefits one would get is not only that it's more typical in .NET worlds to have regular properties but people could then also use the [object initializer](https://msdn.microsoft.com/en-us/library/bb384062.aspx) syntax to set that option.

Opinions?

**Comment by michaelklishin** [comment]
@cH40z-Lord it's a good idea but we should keep the old setter around (just make it delegate to the property). Feel free to submit a PR against the `stable` branch and add a basic test that uses the property.

Thank you.

**Comment by cH40z-Lord** [comment]
PR is opened. Btw do you guys have a Gitter channel? If my time allows me I'll probably have a lot more questions to refactor and improve the current code base. I don't want to spam-open a ticket for everything :)

**Comment by michaelklishin** [comment]
Fixed in #113, I will cherry-pick to `stable` by hand.

We don't have a Gitter channel. Please use [rabbitmq-users](https://groups.google.com/forum/#!forum/rabbitmq-users). The thing we need help with most at this point is publishing nightly builds of `master` and `stable` branches of the client to NuGet.
