### ISSUE TITLE
Release versions of 6.2.2 or 6.2.3 Milestones

### ISSUE THREAD

**Issue by HeadOnMartin** [rabbitmq/rabbitmq-dotnet-client#1134]
Hello,

is there an intention to also create an Release from the 6.2.2 Tag or from the 6.2.3 Milestone as we would be intrested in the TopologyRecovery fixes from #1050 and #1051.

Greetings Martin

**Comment by edubsi** [comment]
Is there an estimate when a new version either 6.2.3 or 7.X is expected to be released? As far as I can tell ~20 Sept. 2021 was mentioned in another Issue.
An estimate would help to decide how to move forward with the current issue we are having.
Thanks

**Comment by lukebakken** [comment]
There is no estimate, but I'll try to get it by the end of this week. I need to do some CI fixes.

**Comment by lukebakken** [comment]
@edubsi @HeadOnMartin there is one flaky test that is giving me headaches -

https://ci.appveyor.com/project/rabbitmq/rabbitmq-dotnet-client

I can't release the next version until I fix or understand why this is happening. Basically, during reconnection and topology recovery there is a call to `ReadByte()` on the TCP socket that should not block, yet it is.

**Comment by lukebakken** [comment]
This issue is still a head-scratcher.

**Comment by lukebakken** [comment]
No luck with fixing the issue - https://github.com/rabbitmq/rabbitmq-dotnet-client/issues/1140

**Comment by lukebakken** [comment]
https://www.nuget.org/packages/RabbitMQ.Client/6.2.3
