### ISSUE TITLE
Consistent hashing algorithm 

### ISSUE THREAD

**Issue by melfeqy** [rabbitmq/rabbitmq-dotnet-client#1138]
Hi 

I'm using  Consistent hashing Exchange to scale up with respect of messages ordering.

Will Consistent hashing algorithm be reset when a new broker is added or removed from the cluster or when the broker goes down "crash" ?

Will i lose the order of messages in the above cases ?

**Comment by michaelklishin** [comment]
I will convert this issue to a GitHub discussion. Currently GitHub will [automatically close and lock the issue](https://github.com/github/feedback/discussions/3197) even though your question will be transferred and responded to elsewhere. This is to let you know that we do not intend to ignore this but this is how the current GitHub conversion mechanism makes it seem for the users :(
