### ISSUE TITLE
Regression in 6.2.3: Semaphore Disposed Exception thrown in AsyncConsumerWorkService

### ISSUE THREAD

**Issue by ashneilson** [rabbitmq/rabbitmq-dotnet-client#1153]
Refer to the original issue for context #1014 

### Problem
When under load, stopping the `AsyncConsumerWorkService` can result in `System.ObjectDisposedException` being thrown due to a Disposed `_limiter`.

The Discarded Tasks `HandleConcurrent` started in `LoopWithConcurrency` may still be running after the finally block disposes of the `_limiter` Semaphore.

https://github.com/rabbitmq/rabbitmq-dotnet-client/blob/462892735b29e49068b168b77fe5572046b58604/projects/RabbitMQ.Client/client/impl/AsyncConsumerWorkService.cs#L125-L151

When the `HandleConcurrent` Tasks attempt to Release the Semaphore, the `System.ObjectDisposedException` is thrown.

https://github.com/rabbitmq/rabbitmq-dotnet-client/blob/462892735b29e49068b168b77fe5572046b58604/projects/RabbitMQ.Client/client/impl/AsyncConsumerWorkService.cs#L181-L186

The issue doesn't occur in `6.2.2` but does in `6.2.3`. It appears the PR #1113 might be the culprit.

### Recommended Fix
- Release a patch version (possibly 6.2.4) with PR #1113 reverted
- Release a patch version (possibly 6.2.4) with a fix applied to the 6.x branch

I'd be more than happy to submit a PR with a fix if that's the desired approach.

**Comment by michaelklishin** [comment]
@ashneilson please submit a PR if you understand what needs to be done (not just a revert).

**Comment by ashneilson** [comment]
@michaelklishin Thanks for the quick reply! PR submitted as requested

**Comment by lukebakken** [comment]
Thanks I'll get to this today.

**Comment by lukebakken** [comment]
Fixed by #1154 and will ship in 6.2.4.
