### ISSUE TITLE
Confirm Listeners (events)

### ISSUE THREAD

**Issue by barambani** [rabbitmq/rabbitmq-dotnet-client#116]
Java client has confirm listeners. .NET client should, too.

**Comment by michaelklishin** [comment]
It turns out that the client already has the events, see:

 * `IModel#BasicAcks`
 * `IModel#BasicNacks`

I will add a couple of tests since we only have coverage for these in the automatic recovery suite, otherwise it should be good to go.

**Comment by michaelklishin** [comment]
@barambani just making sure you have seen the comment above :)

**Comment by barambani** [comment]
hi @michaelklishin, yes I have. Thanks for it
