### ISSUE TITLE
Dispose method should not throw an exception

### ISSUE THREAD

**Issue by micdenny** [rabbitmq/rabbitmq-dotnet-client#119]
In [EasyNetQ](https://github.com/EasyNetQ/EasyNetQ) we're making some [important refactor](https://github.com/EasyNetQ/EasyNetQ/pull/461), and [we notice](https://github.com/EasyNetQ/EasyNetQ/pull/461#discussion-diff-37196714) that we had to wrap RabbitMQ.Client `ModelBase.Dispose` in a try-catch block because looking at [source code](https://github.com/rabbitmq/rabbitmq-dotnet-client/blob/master/projects/client/RabbitMQ.Client/src/client/impl/ModelBase.cs#L318) it could throws an exception.

This is the interested piece of code of [`ModelBase.cs`](https://github.com/rabbitmq/rabbitmq-dotnet-client/blob/master/projects/client/RabbitMQ.Client/src/client/impl/ModelBase.cs):

```csharp
        void IDisposable.Dispose()
        {
            Close();
        }

        public void Close()
        {
            Close(Constants.ReplySuccess, "Goodbye");
        }

        public void Close(ushort replyCode, string replyText)
        {
            Close(replyCode, replyText, false);
        }

        public void Close(ushort replyCode, string replyText, bool abort)
        {
            Close(new ShutdownEventArgs(ShutdownInitiator.Application,
                replyCode, replyText),
                abort);
        }

        public void Close(ShutdownEventArgs reason, bool abort)
        {
            var k = new ShutdownContinuation();
            ModelShutdown += k.OnConnectionShutdown;

            try
            {
                ConsumerDispatcher.Quiesce();
                if (SetCloseReason(reason))
                {
                    _Private_ChannelClose(reason.ReplyCode, reason.ReplyText, 0, 0);
                }
                k.Wait();
                ConsumerDispatcher.Shutdown(this);
            }
            catch (AlreadyClosedException ace)
            {
                if (!abort)
                {
                    throw ace;
                }
            }
            catch (IOException ioe)
            {
                if (!abort)
                {
                    throw ioe;
                }
            }
        }
```

As you can see the `abort` parameter is false when calling `Dispose` and this could end-up in an exception, and it is not the expected behavior, as [Microsoft states that](https://msdn.microsoft.com/en-us/library/bb386039.aspx):

>A IDisposable.Dispose method should not throw an exception. Dispose is often called as part of the clean up logic in a finally clause. Therefore, explicitly throwing an exception from Dispose forces the user to add exception handling inside the finally clause.
The Dispose(false) code path should never throw exceptions, because this is almost always called from a finalizer.

**Comment by michaelklishin** [comment]
@micdenny thank you for your help! We <3 EasyNetQ feedback :)

**Comment by micdenny** [comment]
thanks @michaelklishin :smile:
