### ISSUE TITLE
Automatic code formatting

### ISSUE THREAD

**Issue by lukebakken** [rabbitmq/rabbitmq-dotnet-client#1192]
In https://github.com/rabbitmq/rabbitmq-dotnet-client/pull/692, @stebet contributed an `.editorconfig` file that is based on this - https://github.com/dotnet/runtime/blob/main/.editorconfig

In this PR (https://github.com/rabbitmq/rabbitmq-stream-dotnet-client/pull/78) I added the `.editorconfig` from this project - https://github.com/dotnet/format/blob/main/.editorconfig

We should review the settings in these files and, perhaps, take some other configs into account (https://github.com/dotnet/roslyn/blob/main/.editorconfig)

...then format all the code and add code to the GH actions to verify formatting.

@stebet let me know if you'd like me to wait for #949 updates before running `dotnet format` on this project.

**Comment by stebet** [comment]
No worries. Go nuts :)
