### ISSUE TITLE
Application crashes & exists debugger while consumer is running & rabbit mq service restarts

### ISSUE THREAD

**Issue by jaminator21** [rabbitmq/rabbitmq-dotnet-client#122]
I have a C# application in which I am trying to test the resiliency of rabbit mq client. While the consumer is running, I stop the rabbit mq service to see how my consumer will handle this.

I have try and catch on almost all of my consumer code, yet because of a possible exception in background thread, my application prints below in output window and exists debugger.

> The thread 'AMQP Connection amqp://test.com:5671' (0x6da18) has exited with code 0 (0x0).

> A first chance exception of type 'System.Net.WebException' occurred in System.dll

The only thing I notice is the destructor of my consumer class is called before code exists.

```c#
using System;
using System.IO;
using System.Runtime.Serialization;
using System.Threading;
using RabbitMQ.Client;
using RabbitMQ.Client.Events;
using RabbitMQ.Client.Exceptions;
using RabbitMQ.Util;

namespace RabbitMQClient
{
  public class MessageQueueConsumer : IHealthVerifiable
  {
    public class TimeoutException : Exception { }

    // Have to do this because, somehow, SharedQueue implementation of IEnumerable is faulty
    // Count() method hangs, and never returns
    private class BufferQueue : SharedQueue<BasicDeliverEventArgs>
    {
      public int Count()
      {
        return this.m_queue.Count;
      }
    }

    private const int DEFAULT_ACK_COUNT = 1000;

    private String connString;
    private QueueingBasicConsumer consumer;
    private IConnection conn;
    private IModel channel;
    private String queueName;
    private BufferQueue buffer;
    private Object locker = new Object();
    private ushort prefetchCount;
    private ushort ackCount;

    public MessageQueueConsumer(String queueName, String connString, ushort? ackCount = null)
    {
      this.queueName = queueName;
      this.connString = connString;
      if (ackCount != null)
        this.ackCount = ackCount.Value;
      else
        this.ackCount = DEFAULT_ACK_COUNT;
      this.prefetchCount = (ushort)(this.ackCount * 2);

      InitConsumer();
    }

    ~MessageQueueConsumer()
    {
      Close();
    }

    public void Close()
    {
      try
      {
        channel.Close(200, queueName + " Goodbye");
        conn.Close();
      }
      catch { } //if already closed, do nothing
    }

    private void InitConsumer()
    {
      try
      {
        ConnectionFactory factory = new ConnectionFactory();
        factory.Uri = connString;
        conn = factory.CreateConnection();
        channel = conn.CreateModel();
        channel.BasicQos(0, prefetchCount, false);
        buffer = new BufferQueue();

        consumer = new QueueingBasicConsumer(channel, buffer);
        channel.BasicConsume(queueName, false, consumer);
      }
      catch (Exception e)
      {
        InitConsumer();
      }
    }

    /// <summary>
    /// Get the next event from the queue
    /// </summary>
    /// <returns>Event</returns>
    public byte[] Dequeue(int? timeout = null)
    {
      lock (locker)
      {
        try
        {
          return AttemptDequeue(timeout);
        }
        catch (EndOfStreamException)
        {
          // Network interruption while reading the input stream
          InitConsumer();
          return AttemptDequeue(timeout);
        }
        catch (OperationInterruptedException)
        {
          // The consumer was removed, either through channel or connection closure, or through the
          // action of IModel.BasicCancel().
          // Attempt to reopen and try again
          InitConsumer();
          return AttemptDequeue(timeout);
        }
        catch (ConnectFailureException)
        {
          //Problems connecting to the queue, wait 10sec, then try again. 
          Thread.Sleep(10000);
          InitConsumer();
          return AttemptDequeue(timeout);
        }
        catch (Exception e)
        {
          //Problems connecting to the queue, wait 10sec, then try again. 
          Thread.Sleep(10000);
          InitConsumer();
          return AttemptDequeue(timeout);
        }
      }
    }

    private byte[] AttemptDequeue(int? tomeout)
    {
      BasicDeliverEventArgs message;

      if (tomeout == null)
        message = (BasicDeliverEventArgs)consumer.Queue.Dequeue();
      else
      {
        if (!consumer.Queue.Dequeue(tomeout.Value, out message))
          throw new TimeoutException();
      }

      if (buffer.Count() == 0 || buffer.Count() == ackCount)
        channel.BasicAck(message.DeliveryTag, true);

      try
      {
        return message.Body;
      }
      catch (Exception e)
      {
        throw new SerializationException("Error deserializing queued message:", e);
      }
    }

    /// <summary>
    /// Attempt to connect to queue to see if it is available
    /// </summary>
    /// <returns>true if queue is available</returns>
    public bool IsHealthy()
    {
      try
      {
        if (channel.IsOpen)
          return true;
        else
        {
          InitConsumer();
          return true;
        }
      }
      catch
      {
        return false;
      }
    }
  }
}
```

**Comment by michaelklishin** [comment]
Please ask questions on rabbitmq-users. You haven't mentioned what "crashes" means but a pure C# library cannot be blamed for runtime termination. I/O thread termination is expected. .NET client supports automatic connection recovery as of [3.4.0](http://www.rabbitmq.com/changelog.html), however, we can't predict what kind of effect a debugger may have on its functionality.

**Comment by michaelklishin** [comment]
Oh, and don't use `QueueingBasicConsumer` if you want to use automatic recovery: that consumer implementation is not supported due to the way it is typically used (in a while loop).

**Comment by jaminator21** [comment]
I am only asking this (or running this in debugger) because on production we have consistently noticed that automatic recovery does not happen and the consumer is paused until application is restarted.

**Comment by michaelklishin** [comment]
@jaminator21 `QueueingBasicConsumer` **does not** support automatic recovery. This should be documented. There are no reasons to choose that consumer implementation over `EventingBasicConsumer` or subclassing `DefaultBasicConsumer` in this day and age.

Another couple of less-than-obvious points: your destructor uses `Connection#Close` and `Channel#Close`. Those will throw exceptions if the socket is already closed. Use `Connection#Abort` if you want to ensure connection is closed but ignore any potential exceptions from the closing method.

**Comment by jaminator21** [comment]
If you answer was,
> Oh, and don't use QueueingBasicConsumer
which is totally acceptable answer & appreciated. I fail to see how below was relevant:
> Please ask questions on rabbitmq-users.
And I did mention the word "Application" before "crashes":
> You haven't mentioned what "crashes"

**Comment by michaelklishin** [comment]
@jaminator21 this is relevant for two reasons:

 * We try hard to keep our issue trackers clean, only containing tickets that are obviously (to us) improvements and bugs. Everything else belongs to the mailing list. If there's a consensus that something can be treated as a bug or an area of improvement, we will file issues on GitHub.
 * We get *a lot* of noise from all kinds of channels where people claim they've discovered a bug. In 95 or more % of the cases the issue is not a bug but a user mistake, an environment-specific issue or people not reading the docs.
 * "Crashes" means different things to different people. To me this means .NET runtime termination. To many it means "there was an unhandled exception that looks scary."

**Comment by videlalvaro** [comment]
@jaminator21 we prefer this basically:

- library usage questions: they belong on the mailing list.
- library bug reports: they belong on this Github issue tracker. 

**Going to the mailing list first** helps us determine if we are talking of an actual bug, a misunderstanding of the library usage, lack of docs on our side, and so on.
