### ISSUE TITLE
No client-server backpressure with automatic acknowledgements

### ISSUE THREAD

**Issue by twatson83** [rabbitmq/rabbitmq-dotnet-client#123]
Hi,

Im getting out of memory exceptions since moving from nuget version 3.2.1 to 3.5.4. When using BasicConsume it seems like the client pulls all messages off the queue as fast as possible even if processing the messages is slow.  Therefore unacknowledged messages are being queued in memory by the consumer which causes memory to rapidly increase.

For example below you can see that there are a lot of messages in the unacknowledged state and that they are been delivered much faster than being acknowledged.  The consumer service memory increases rapidly until a System.OutOfMemoryException is thrown. We did not have this issue in version 3.2.1.

![image](https://cloud.githubusercontent.com/assets/810050/9759299/f85291e8-56e3-11e5-8069-1b60eacd9846.png)

**Comment by michaelklishin** [comment]
The right thing to do is to use QoS on your channels and manual acknowledgements. However, we could make the Java client use TCP backpressure (https://github.com/rabbitmq/rabbitmq-java-client/issues/19), may it would be reasonably straightforward for .NET.

**Comment by michaelklishin** [comment]
In `3.2.1` consumer method dispatch (e.g. for deliveries) was done on the I/O thread, so a slow consumer would block *everything*. It is no longer the case but now without QoS you indeed will get a stream of deliveries which may overwhelm consumers. This is why QoS exists (see tutorial 2) ;)

**Comment by twatson83** [comment]
QoS solved my issue.  Thanks.
