### ISSUE TITLE
IModel.WaitForConfirmsOrDie* methods don't document that they close

### ISSUE THREAD

**Issue by lukealbao** [rabbitmq/rabbitmq-dotnet-client#1234]
Hi there, thanks for this library.

I suppose many people could infer from the name (`OrDie`) that these methods close the channel. I however assumed that the documentation was clear enough to be complete:

```
Waits until all messages published since the last call have
been ack'd by the broker.  If a nack is received or the timeout
elapses, throws an OperationInterrupedException exception immediately.
```

I consider it extra dangerous because failures are rare enough that automated testing doesn't catch it, as ours did not. With long-lived channels, the first nack caused all subsequent publish attempts to fail.

I'd be happy to submit a PR, but I'm unclear on (1) if this is actually part of the interface or if it just so happens that the implementations do this, and (2) how would one submit a PR for documentation that would apply to all supported versions/branches? (We are using 4.x. I just noticed that the copied doc above also describes the wrong exception type; that's from the 4.x branch.)

Thank you again!

**Comment by michaelklishin** [comment]
4.x is no longer maintained. This change can be back ported to other branches just like any other.

**Comment by lukebakken** [comment]
FWIW, using `WaitForConfirmsOrDie` should be avoided and you should deal with publisher confirms this way:

https://www.rabbitmq.com/tutorials/tutorial-seven-dotnet.html
