### ISSUE TITLE
Connection to an IPv4 address fails in IPv6-enabled environments

### ISSUE THREAD

**Issue by biiiipy** [rabbitmq/rabbitmq-dotnet-client#126]
Trying to create a **remote** (for example ``` HostName = "192.168.10.10" ```) connection with ``` connectionFactory.CreateConnection(); ```, I get the following error: 
``` None of the discovered or specified addresses match the socket address family. Parameter name: context ```
My workaround for this is to override ``` SocketFactory ``` and force **IPV4**.
```
connectionFactory.SocketFactory = (addressFamily) =>
{
     return new System.Net.Sockets.TcpClient(System.Net.Sockets.AddressFamily.InterNetwork);
};
```

No problems with connecting to localhost. Client - RabbitMQ.Client v3.5.6 on Windows 7 machine.

A similar issue has been reported and presumably resolved - https://github.com/rabbitmq/rabbitmq-dotnet-client/pull/24

**Comment by michaelklishin** [comment]
@biiiipy thanks. So what would you recommend as a solution? Providing an easier way to force IPv4?

**Comment by michaelklishin** [comment]
Another idea: force IPv4 by default?

**Comment by biiiipy** [comment]
It should just fallback to IPV4, and looking at SocketFactory code, it kind of does that already. I'm not sure why I'm getting this error. I'll try do dig into this.

**Comment by michaelklishin** [comment]
@biiiipy thank you!

**Comment by biiiipy** [comment]
Sorry, this was a debugging side effect, closing.

**Comment by connect2sandeep** [comment]
getting an exception while trying to connect
Exception thrown: 'System.ArgumentException' in System.dll

Additional information: None of the discovered or specified addresses match the socket address family.

**Comment by jmbeach** [comment]
@biiiipy do you know how to fix this? I'm facing the same issue

**Comment by biiiipy** [comment]
@jmbeach sadly no, there could be a lot of reasons for this... Did you try my workaround mentioned on the 1st post?
Also, you could debug through Rabbit's code to see where the connection fails.
