### ISSUE TITLE
Publisher not throw exception immediately when connection forced close.

### ISSUE THREAD

**Issue by hoangvu88** [rabbitmq/rabbitmq-dotnet-client#127]
I wrote a test which publish messages to rabbitmq. While test is running, i use management plugin to force close it's connection. But exception only been threw after many successful loop. 
The brocker received 195,050 messages but the publisher announced it published 206941 messages.
Here are my code.

            ConnectionFactory factory = new ConnectionFactory();
            factory.UserName = "websosanh";
            factory.Password = "123456a@";
            factory.VirtualHost = "Test";
            factory.HostName = "172.22.0.177";

            var exchangeName = "TestExchange";
            var queueName = "TestQueue";
            var routingKey = "TestRouting";

            IConnection conn = factory.CreateConnection();
            IModel channel = conn.CreateModel();
            channel.ExchangeDeclare(exchangeName, ExchangeType.Direct);
            channel.QueueDeclare(queueName, true, false, false, null);
            channel.QueueBind(queueName, exchangeName, routingKey, null);
            var properties = channel.CreateBasicProperties();
            properties.DeliveryMode = 2;

            for (int i = 0; i < 500000; i++)
            {
                try
                {
                    channel.BasicPublish(exchangeName, routingKey, false, properties, System.Text.Encoding.ASCII.GetBytes("Message" + i));
                }
                catch (Exception exception)
                {
                    Logger.Error("Channel closed. i = " + i, exception);
                    break;
                }
            }
            if (channel.IsOpen)
                channel.Close();

Queues:
![queues](https://cloud.githubusercontent.com/assets/5976457/10507984/84f3d194-734e-11e5-84af-e74d6ab3eaf6.JPG)

Exception in log file: 
(c:\Users\vuhoang\Source\Repos\RabbitMQClient\Core.Drivers.RabbitMQTests\ProducerTests.cs:67) - Channel closed. i = 206941
RabbitMQ.Client.Exceptions.AlreadyClosedException: Already closed: The AMQP operation was interrupted: AMQP close-reason, initiated by Peer, code=320, text="CONNECTION_FORCED - Closed via management plugin", classId=0, methodId=0, cause=
   at RabbitMQ.Client.Impl.SessionBase.Transmit(Command cmd)
   at RabbitMQ.Client.Impl.ModelBase.ModelSend(MethodBase method, ContentHeaderBase header, Byte[] body)
   at RabbitMQ.Client.Framing.Impl.Model._Private_BasicPublish(String exchange, String routingKey, Boolean mandatory, Boolean immediate, IBasicProperties basicProperties, Byte[] body)
   at RabbitMQ.Client.Impl.ModelBase.BasicPublish(String exchange, String routingKey, Boolean mandatory, Boolean immediate, IBasicProperties basicProperties, Byte[] body)
   at RabbitMQ.Client.Impl.ModelBase.BasicPublish(String exchange, String routingKey, Boolean mandatory, IBasicProperties basicProperties, Byte[] body)

**Comment by michaelklishin** [comment]
It takes a moment for `connection.close` to be sent to the client, and even longer to detect TCP connection closure (which is a more realistic scenario than force-closing via rabbitmqctl).

Use a reasonably low [heartbeat](http://www.rabbitmq.com/heartbeats.html) interval (say, 5 seconds) and [publisher confirms](http://www.rabbitmq.com/confirms.html). That is the only way to ensure reliable delivery and detect connectivity issues. Also, please ask questions on rabbitmq-users.

**Comment by michaelklishin** [comment]
I guess a shorter way to explain this: there is no "immediately" in distributed systems (and your client and server effectively form one) and you need confirmations from the peer for reliable delivery. That's why heartbeats and publisher confirms exist in the protocol.

**Comment by hoangvu88** [comment]
@michaelklishin :+1: Thanks for you reply
