### ISSUE TITLE
Impossible to use a ulong as a header value

### ISSUE THREAD

**Issue by thepunkoff** [rabbitmq/rabbitmq-dotnet-client#1298]
Is there any particular reason why ulongs are forbidden as header values ([source](https://github.com/rabbitmq/rabbitmq-dotnet-client/blob/main/projects/RabbitMQ.Client/client/impl/WireFormatting.Write.cs#L152))? Shouldn't we support all primitive types for convenience?

**Comment by michaelklishin** [comment]
No reason other than: many other clients won't be able to support unsigned numerical types. But we can add support for them in this client.

**Comment by thepunkoff** [comment]
Yeah, but uints and ushorts are already supported right now, that's why I'm asking. It would be nice to have them all supported!

**Comment by michaelklishin** [comment]
By all means, please feel free to look into it and submit a PR. Thank you!

**Comment by thepunkoff** [comment]
Well I've posted a PR (https://github.com/rabbitmq/rabbitmq-dotnet-client/pull/1299)! But something's wrong with the CI build. I can't see the failure reason due to an endless loading screen. Could you please help?

**Comment by thepunkoff** [comment]
Closing as "won't do". Details: https://github.com/rabbitmq/rabbitmq-dotnet-client/pull/1299
