### ISSUE TITLE
Investigate the use of TaskCreationOptions.LongRunning

### ISSUE THREAD

**Issue by lukebakken** [rabbitmq/rabbitmq-dotnet-client#1318]
Reported here:

https://groups.google.com/g/rabbitmq-users/c/9lFwM_xF5cw

Relevant discussion:

https://github.com/rabbitmq/rabbitmq-dotnet-client/issues/959

**Comment by stebet** [comment]
It's not that simple. Task.Factory.StartNew does not support async methods which MainLoop will become eventually.

**Comment by d-jagoda** [comment]
I believe it was conditionally used before but was removed by commit 311ef63d6a47d7d488ced0e94134cb720b1fdfac

As for using async methods in Task.Factory.StartNew, it is possible to use them, you just have to unwrap the task get hold of the inner task no? Which is exactly what Task.Run with async methods to. So it would be no different from using Task.Run except for minor differences which can be changed via TaskCreationOptions.

`
            var task = Task.Factory.StartNew(async () =>
            {
                await Task.Delay(TimeSpan.FromSeconds(10));
            });

            await task.Unwrap();
            // Or
            // var inner = await task;
            // await inner;
`

**Comment by Zerpet** [comment]
> I figured there was a reason we're not using it.
> 
> @stebet for 6.x I'm assuming it's fine to make this change.

I'll be happy to keep this change for the 6.x branch, assuming it is not breaking change (as marked in #1321)

**Comment by lukebakken** [comment]
Fixed by #1321

**Comment by lukebakken** [comment]
@d-jagoda https://github.com/rabbitmq/rabbitmq-dotnet-client/releases/tag/v6.5.0
