### ISSUE TITLE
Queue Fails to Delete with Orphaned Binding

### ISSUE THREAD

**Issue by LeeWhite187** [rabbitmq/rabbitmq-dotnet-client#1376]
### Describe the bug

This bug is for v6.5.0 of the RabbitMQ.Client nuget package.
It's a queue binding registration problem that creates an exception on deletion of a queue.

The channel.QueueDelete method call in the .NET client library throws an exception with a message containing: 'NOT_FOUND - no exchange '.
This occurs if a previous add queue binding was attempted with an unknown exchange name.
The exception is erroneous, since the call is to delete a queue, and not an exchange.
So, that implies an orphaned reference, somewhere.... and the problem is not actually the queue delete call, directly.

It's actually that a previously executed channel.QueueBind method correctly fails with an exception for the missing exchange.
But is still allowed to register the binding (to a nonexistant exchange), before the throw.

And subsequently, when later, deleting a queue, the QueueDelete method call also throws an exception for the same missing exchange (and same exchange name).... because it discovers a binding for the missing exchange (that was allowed to be registered), even though no valid exchange existed (and the QueueBind call threw because of it).

This exception, on queue deletion, prevents the QueueDelete method logic from actually deleting the queue.
And, the queue has to be deleted via a REST call or through the management interface.

### Reproduction steps

1. Connect client to a RMQ cluster with a user context that has admin privileges.
2. Create a Guid string that will be the name of a queue to be created.
3. Create a Guid string that will represent an unknown exchange.
4. Create a Guid string that will be the binding routing key.
5. From the .NET client, create a queue with the Guid string from above.
6. From the management interface, verify the queue was created.
7. From the .NET client, create a queue binding using the queue name, exchange name, and routing key, created above.
8. This will throw an exception because the exchange is NOT_Found.
9. From the management interface, verify the queue binding is NOT present (though, it actually got registered before the throw).
10. Query the REST API for the queue binding, and verify that it is NOT present (though, it actually got registered before the throw).
11. From the .NET client, delete the queue by name.
12. Verify it throws an exception for a NOT_Found exchange, with the Guid string of the unknown exchange in the exception message.
13. From the management interface, verify the queue is still present, failing to be deleted.
14. From the REST API, verify the queue is still present, failing to be deleted.

### Expected behavior

The expected behavior is that:

The QueueBind method of the channel class must NOT register a binding or leave any dangling binding record when the given exchange name is not known, or the queue name is not known.

As well, the QueueDelete method of the channel must be intelligent enough to delete all bindings of the queue, regardless of exchange presence.
Also. The QueueDelete method should throw an exception for a not found queue, which it correctly does.
But, it should NOT throw an exception for a not found exchange, which is conceptually incorrect for a queue deletion.
It should gracefully cleanup any bindings without error.

**Comment by LeeWhite187** [comment]
I went through the effort, as a necessary workaround for the above issue, to create a REST client that performs the add/remove/exists for queue, exchange, and bindings.
I am able to correctly delete a queue via REST API, after an attempt to bind the queue to a missing exchange.
So, the RMQ service is behaving correctly.

Which means, there must be a bug in the .NET client that is causing it to throw an exchange for the NOT_Found exchange... when deleting a queue.

This is not a work stopping issue for me, since I merged in REST calls to perform the queue management activities (present on the channel class).

But, I expect this errant edge case could affect others.
Bug me if you need help isolating the problem.

Have a good day.

**Comment by LeeWhite187** [comment]
To note, I did try slowing down logic execution to determine if the errant exception is just an eventual consistency issue for an in-progress, asynchronous binding attempt.
But, pausing logic flow with a healthy sleep delay between test steps, did not prevent the error.

**Comment by lukebakken** [comment]
@LeeWhite187 would you be able to provide code to run with your reproduction steps?

**Comment by LeeWhite187** [comment]
Sure.
I've attached a VS project that demonstrates the problem:
[RMQ_QueueDeleteFailure_Test.zip](https://github.com/rabbitmq/rabbitmq-dotnet-client/files/13402436/RMQ_QueueDeleteFailure_Test.zip)

I thinned out the classes enough to readily follow execution, while preserving enough abstraction, in the unit test block, to visibly align with the "prose", above.
The unit test will assert failure at the Delete_Queue step, as this is the step that's expected to function properly, but does not.

No rush on fixing it. I built a REST client as workaround.

Bug me if questions, or if you need something else.
Hope this helps.

**Comment by lukebakken** [comment]
Thank you very much! I'm working on the version 7 release and one goal is to close as many outstanding issues as possible pre-release.

**Comment by LeeWhite187** [comment]
Anytime. Sorry for the delayed response, to getting you a test project to recreate the problem.

Bug me if you need anything.

**Comment by lukebakken** [comment]
@LeeWhite187 - the problem is in your `RMQ_Client.cs` code:

https://github.com/lukebakken/rabbitmq-dotnet-client-1376/blob/main/ClassesUnderTest/RMQ_Client.cs#L1285-L1291

Once there is an exception on a channel, you *must not use it anymore*, and must open a new channel.

Since you continue to use the same channel in your test scenario, you see the "stale" data.

Please feel free to reply if this does not seem to be the correct analysis.

**Comment by lukebakken** [comment]
Yes, a channel-level exception from RabbitMQ requires that you close the channel. RabbitMQ will close the channel on its end. In your test scenario, you can see that `IsOpen` is `false` on the `IModel` instance after the error.

Creating an "admin" channel is a good solution.

**Comment by LeeWhite187** [comment]
That’s interesting to know. My tests did not include any post checks, to confirm resources remained viable.
I’ll add that for my own sanity.

Thanks for the insight.
Good library.

**Comment by lukebakken** [comment]
Thank you. I really appreciate the effort you put into your issue description and for providing code.
