### ISSUE TITLE
If the connection gets blocked, IModel's Dispose method will block the thread 

### ISSUE THREAD

**Issue by bmihart** [rabbitmq/rabbitmq-dotnet-client#139]
Hi,

While trying to use RabbitMq Client Publisher Confirms we encountered an issue, in case the connection gets blocked at some point in time.
 
Please take a look at the following simple console application:

    class Program
    {
        static void Main(string[] args)
        {
            var connectionFactory = new ConnectionFactory
            {
                Uri = "amqp://test:test@192.168.56.101/PublishConfirm",
                AutomaticRecoveryEnabled = true
            };
 
            using(var connection = connectionFactory.CreateConnection())
            using(var channel = connection.CreateModel())
            {
                channel.ConfirmSelect();
                var properties = channel.CreateBasicProperties();
                properties.DeliveryMode = 2;
                channel.BasicPublish(string.Empty, "testQueue", true, false, properties, Encoding.UTF8.GetBytes("Hello world!"));
 
                bool timedOut;
                var publishConfirmed = channel.WaitForConfirms(TimeSpan.FromSeconds(5), out timedOut);
 
                if (timedOut)
                {
                    Console.WriteLine("Publish confirmations timed out");
                }
                else
                {
                    Console.WriteLine("Publish confirmation value: {0}", publishConfirmed);
                }
            }
 
            Console.WriteLine("Done");
            Console.ReadKey();
        }
    }
 
Before running this application try to starve RabbitMq broker of resources, for example by running this command "rabbitmqctl.bat set_vm_memory_high_watermark 0.01" (make sure that in rabbit administration tool the memory area becomes red).
If you run the program, you’ll see that "Publish confirmations timed out" message gets printed, but the application gets blocked and "Done" is never printed. If you debug the application in Visual Studio and hit Break (Ctrl + Alt + Break) you notice that the main thread is blocked in Dispose method of IModel interface waiting for a BlockingCell.Value.get. 
Instead of a using block I tried to call Dispose method in a try-catch-finally block or even tried to call Abort method of IModel interface, but the application behaviour remains unchanged.
If we receive a timeout we would like to be able to gracefully close the channel (instance of IModel) and take alternative actions, but this is not possible because our thread gets blocked in the Dispose (or Abort) method of IModel.

Thank you,
Bogdan Mihart

**Comment by michaelklishin** [comment]
RabbitMQ stops reading from the socket on publishing connections. It therefore cannot know if a channel was closed by the client. This is true for all clients and nobody has come up with a solution so far.
