### ISSUE TITLE
Support cancellation

### ISSUE THREAD

**Issue by lukebakken** [rabbitmq/rabbitmq-dotnet-client#1420]
Reference: [comment](https://github.com/rabbitmq/rabbitmq-dotnet-client/pull/1347#discussion_r1396392526)

@danielmarbach points out that the async API should support cancellation.

**Comment by lukebakken** [comment]
Notes:
* https://devblogs.microsoft.com/premier-developer/recommended-patterns-for-cancellationtoken
* https://learn.microsoft.com/en-us/dotnet/standard/threading/how-to-listen-for-cancellation-requests-by-polling
* https://learn.microsoft.com/en-us/dotnet/standard/threading/how-to-listen-for-cancellation-requests-that-have-wait-handles

**Comment by danielmarbach** [comment]
FYI since cooperative cancelation is up to the implementor to decide where and when cancelation can be triggered it might be OK to start adding the token to the public async APIs and then start implementing and further evolve it over time (example in minors)

**Comment by lukebakken** [comment]
#1535 added the last of the `CancellationToken` parameters to the public API's async methods.
