### ISSUE TITLE
Review async RPC continuations, await, and ConfigureAwait

### ISSUE THREAD

**Issue by lukebakken** [rabbitmq/rabbitmq-dotnet-client#1427]
cc @paulomorgado @danielmarbach 

Discussion about `.ConfigureAwait(false)` that prompted this issue:
https://github.com/rabbitmq/rabbitmq-dotnet-client/pull/1426#discussion_r1400909896

The current implementation of `AsyncRpcContinuation<T>` is such that the awaitable is configured in the class itself, here:

https://github.com/rabbitmq/rabbitmq-dotnet-client/blob/main/projects/RabbitMQ.Client/client/impl/AsyncRpcContinuations.cs#L72-L78

This means that `await k` does not use `.ConfigureAwait(false)`:

https://github.com/rabbitmq/rabbitmq-dotnet-client/blob/main/projects/RabbitMQ.Client/client/impl/ChannelBase.cs#L256

The original implementation of  `AsyncRpcContinuation<T>.GetAwaiter()` returned a `TaskAwaiter<T>`:

```
public TaskAwaiter<T> GetAwaiter()
{
    return _tcs.Task.GetAwaiter();
}
```

...however, even with the above code, `await k` does not allow `.ConfigureAwait(false)`:

<img width="444" alt="image" src="https://github.com/rabbitmq/rabbitmq-dotnet-client/assets/514926/140c3b03-c1c3-4f28-abb4-747c0f8bed1a">

So, my questions are:
* Is the [current implementation](https://github.com/rabbitmq/rabbitmq-dotnet-client/blob/main/projects/RabbitMQ.Client/client/impl/AsyncRpcContinuations.cs#L72-L78) the correct way to use `.ConfigureAwait(false)`?
* If not, what is?

**Comment by paulomorgado** [comment]
One thing you must have in mind is that `ConfigureAwait(_)` configures the `await` and not the taks,

It needs to be wherever the `await` is,

**Comment by lukebakken** [comment]
@paulomorgado Yes I realize that, but in this case, with the original implementation of `AsyncRpcContinuation<T>`, configuring the `await` _is not an option_, which I find surprising.

**Comment by paulomorgado** [comment]
`ConfigureAwait` is an instance method of the `Task` and `Task<TResult>` classes and `ValueTask` and `ValueTask<TResult>` structs.

If `k` is not one of them, it doesn't have that method.

Check out the [ConfigureAwait FAQ](https://devblogs.microsoft.com/dotnet/configureawait-faq/).

(I'm sorry, but I'm not on a device where I can check that).

**Comment by lukebakken** [comment]
OK, I have modified `AsyncRpcContinuation` to have a `WaitAsync()` method rather than `GetAwaiter()` in this commit, which resolves this issue:

https://github.com/rabbitmq/rabbitmq-dotnet-client/pull/1426/commits/26696efca87f22cfab9fde9b4083c5d6ee8393f9

**Comment by danielmarbach** [comment]
@lukebakken There was no issue, it was just that the previous version of the code didn't require `ConfigureAwait(false)` because it was already returning a correctly configured awaiter. A good analyzer would have caught that and not highlighted that you should add `ConfigureAwait(false)`. 

It is similar to `Task.Yield`. There, you cannot configure the context capturing.

**Comment by lukebakken** [comment]
Thanks for the clarification @danielmarbach. I thought the previous version was correct, but I think having an explicit `WaitAsync` may be a bit clearer.

**Comment by paulomorgado** [comment]
I think that should be left only for non-cancelable APIs. All other should already have a cancellation token and that one should be combined with a timeout cancellation token, when a timeout is required.
