### ISSUE TITLE
Should IModelExensions be named IModelExtensions (with a "t")?

### ISSUE THREAD

**Issue by China-Mr-zhong** [rabbitmq/rabbitmq-dotnet-client#1430]
### Describe the bug

ClassName：IModelExensions  Exensions The word is wrong

### Reproduction steps

1.
2.
3.
...

### Expected behavior

Correct should be Extensions

**Comment by lukebakken** [comment]
Thank you for noticing this. We can't change the name in the `6.x` release series since it would be a breaking change for cosmetic reasons.

In version `7.x` this static class is correctly called `IChannelExtensions`.
