### ISSUE TITLE
When using assembly binding redirect a connection error is shown

### ISSUE THREAD

**Issue by pabermod** [rabbitmq/rabbitmq-dotnet-client#1434]
### Describe the bug

When I use assembly binding redirection for System.Runtime.CompilerServices.Unsafe, if a new version of that library is used through a dependency update, and if it does not match the used version, a BrokerUnreachableException is thrown instantly when trying to connect:

> 
> Error connecting to host rabbitmq-ssl. RabbitMQ.Client.Exceptions.BrokerUnreachableException: None of the specified endpoints were reachable ---> System.IO.IOException: connection.start was never received, likely due to a network timeout
>    en RabbitMQ.Client.Framing.Impl.Connection.StartAndTune()
>    en RabbitMQ.Client.Framing.Impl.Connection.Open(Boolean insist)
>    en RabbitMQ.Client.Framing.Impl.Connection..ctor(IConnectionFactory factory, Boolean insist, IFrameHandler frameHandler, String clientProvidedName)
>    en RabbitMQ.Client.ConnectionFactory.CreateConnection(IEndpointResolver endpointResolver, String clientProvidedName)
>    --- Fin del seguimiento de la pila de la excepción interna ---

### Reproduction steps

Download the attached solution and start the project.

[RabbitMQRedirectAssembly.zip](https://github.com/rabbitmq/rabbitmq-dotnet-client/files/13548165/RabbitMQRedirectAssembly.zip)

The System.Runtime.CompilerServices.Unsafe dll is 5.0.0.0 version but in the redirect assembly is specified 6.0.0.0.

When connecting to rabbitmq there should be an exception that indicates that the dll was not found. but instead a BrokerUnreachable exception is shown

### Expected behavior

When connecting to rabbitmq there should be an exception that indicates that the dll was not found

**Comment by lukebakken** [comment]
I have added your code here and am investigating:

git@github.com:lukebakken/rabbitmq-dotnet-client-1434.git

**Comment by lukebakken** [comment]
@pabermod please take a look [here](https://github.com/rabbitmq/rabbitmq-dotnet-client/pull/1438#issuecomment-1839390982). Thanks!

**Comment by lukebakken** [comment]
Fixed by #1438

**Comment by lukebakken** [comment]
@pabermod just FYI, 6.8.0 has officially been released. Announcing it soon.
