### ISSUE TITLE
Only throw `RabbitMQ.Client`-specific exceptions.

### ISSUE THREAD

**Issue by paulomorgado** [rabbitmq/rabbitmq-dotnet-client#1439]
### Describe the bug

From [Using Standard Exception Types](https://learn.microsoft.com/en-us/dotnet/standard/design-guidelines/using-standard-exception-types):

> ❌ DO NOT throw [System.Exception](https://learn.microsoft.com/en-us/dotnet/api/system.exception) or [System.SystemException](https://learn.microsoft.com/en-us/dotnet/api/system.systemexception).

RabbitMQ code should return RabbitMQ exceptions. If there was another exception causing the one being thrown, it should be added as an `InnerException`.

### Reproduction steps

`ServiceBase.Notify` is throwing `System.Exception` at https://github.com/rabbitmq/rabbitmq-dotnet-client/blob/main/projects/RabbitMQ.Client/client/impl/SessionBase.cs#L128

### Expected behavior

a RabbitMQ-specific exception is thrown.

**Comment by lukebakken** [comment]
Thank you @paulomorgado for taking the time to open this issue with great details.

**Comment by lukebakken** [comment]
Exceptions thrown by this library could include the associated connection and channel as exception data to allow library users to take appropriate action. Thoughts? @paulomorgado

**Comment by paulomorgado** [comment]
All the information that can be provided is always helpful.

Exceptions have a [`Data` property](https://learn.microsoft.com/en-us/dotnet/api/system.exception.data) that can be used to add information.

But this is not very discoverable and people usually choose to add the data as custome exception properties.

If you are creating scenario specific exceptions, you can create properties for that.

But I wouldn't mind having them as data.

**Comment by lukebakken** [comment]
Closing! See [this comment](https://github.com/rabbitmq/rabbitmq-dotnet-client/issues/1440#issuecomment-2106273983).
