### ISSUE TITLE
Do not create exceptions just for logging

### ISSUE THREAD

**Issue by paulomorgado** [rabbitmq/rabbitmq-dotnet-client#1440]
### Describe the bug

Some exceptions are being created just for logging [here](https://github.com/rabbitmq/rabbitmq-dotnet-client/blob/main/projects/RabbitMQ.Client/client/impl/Connection.Receive.cs#L150) and [here](https://github.com/rabbitmq/rabbitmq-dotnet-client/blob/main/projects/RabbitMQ.Client/client/impl/Connection.Receive.cs#L155)

### Reproduction steps

Just log the error. No need for an exception.

But, if it's really needed, don't use `System.Exception`: see #1439 

### Expected behavior

No exception is created just for logging.

**Comment by lukebakken** [comment]
Thank you @paulomorgado!

**Comment by lukebakken** [comment]
I just did a search for `new.*Exception` within the `main` branch and it appears that this has been resolved over the course of working on version 7.
