### ISSUE TITLE
Consuming events not working on mono 4.2 under Linux 

### ISSUE THREAD

**Issue by acken** [rabbitmq/rabbitmq-dotnet-client#146]
When running a consumer using the .Net client running on Linux using mono 4.2 it can no longer consume events. There are no errors it is just not consuming events and the rabbit admin plugin shows 0 consumers on the given queue.

**Comment by michaelklishin** [comment]
It's not possible to suggest much with this much information. Please post to rabbitmq-users and provide a code example we can use to reproduce.

Mono has screwed up library developers who have dependencies compiled for .NET versions earlier than 4.5, which includes us. So we haven't had a chance to develop using Mono for a while now. We'd like to support it but there is no evidence in this that this is our issue => closing.

**Comment by michaelklishin** [comment]
Please include three more things:

 * RabbitMQ log files
 * .NET client version used
 * [A protocol capture with Wireshark](https://www.rabbitmq.com/amqp-wireshark.html) so that we can see what the client's sent, if anything.

**Comment by acken** [comment]
I just tested this using a docker a image and get an exception. When building a docker image from mono:latest it works as expected. When building an image from mono:4.2.1.102 I get an exception and rabbit says closing connection with handshake timeout. Somehow github does not accept my zip file so put it on ge.tt. It contains the exception, rabbit log and wireshark dump.

http://ge.tt/api/1/files/25uiLjT2/0/blob?download

**Comment by michaelklishin** [comment]
The exception comes from `RabbitMQ.Client.Impl.SocketFrameHandler.Connect`. An internet runtime object is being double-disposed. I doubt it is an issue with the client: we don't even have a socket to work with, so there is no chance the client is trying to dispose something.

**Comment by acken** [comment]
So the mono runtime is to blame?

**Comment by michaelklishin** [comment]
Yes, the standard library implementation. Especially if earlier Mono versions work correctly.

**Comment by acken** [comment]
Ok thanks. I'll report it to the mono team then.
