### ISSUE TITLE
Add net 6.0 so that conditional packages can be defined

### ISSUE THREAD

**Issue by thompson-tomo** [rabbitmq/rabbitmq-dotnet-client#1479]
### Is your feature request related to a problem? Please describe.

I want my dependencies to be bringing in only the bare minimum dependencies needed and to achieve this framework references should be used wherever possible

### Describe the solution you'd like

A dotnet 6 or net standard 2.1? TFM should be added to the project. The additional TFM will enable the System.Memory Dependency to have a condition placed on thr reference so that it is only added when needed.

### Describe alternatives you've considered

Accept additional dependencies

### Additional context

This is for v6 release branch

**Comment by lukebakken** [comment]
Feel free to open a PR to implement this. Otherwise, I will close it prior to the version 6.9.0 release, since this has not been requested before and does not seem to be a concern for most users of this library.

**Comment by thompson-tomo** [comment]
Thanks @lukebakken pr submitted.

**Comment by lukebakken** [comment]
Fixed by #1482
