### ISSUE TITLE
add suport for wasm

### ISSUE THREAD

**Issue by SongOfYouth** [rabbitmq/rabbitmq-dotnet-client#1518]
### Is your feature request related to a problem? Please describe.

rabbitmq-dotnet-client could not be used for wasm because of the dependance of `System.Net.Sockets` which is not supported on wasm.

### Describe the solution you'd like

as workaround, `System.Net.WebSockets` is included in .Net6, and it works on wasm.

**Comment by lukebakken** [comment]
Hello, thanks for using this library.

Someone in the community should provide a pull request for this feature, if they want it.

I'm going to close this issue and will re-open it if a pull request comes in.
