### ISSUE TITLE
Running a consumer app as a Windows Service

### ISSUE THREAD

**Issue by rtaborda** [rabbitmq/rabbitmq-dotnet-client#152]
Hi,

I have one simple console application that consumes messages from a queue and it works just fine, but if I try to run it wrapped in a Windows Service it just doesn't behave properly.
When the service starts the existing messages in the queue are consumed but the connection seems to be dropped immediately after, because the messages are not acknowledge and stay in the queue, and also because any further messages sent to the queue are not processed at all. In the RabbitMQ UI I can also see that the queue doesn't have any consumers.
If the same console app is run from a command window everything works fine, the messages are processed and acknowledge, and I can see the new consumer in the RabbitMQ UI.

Is this know a know issue? Are there any workarounds?

*Another post I found with the same issue, but sadly without a solution:*
https://groups.google.com/forum/#!msg/rabbitmq-users/l0GQ4w3sYEU/-LpIufk1EgAJ

**Comment by michaelklishin** [comment]
Sorry but I don't see how this can be caused by a client library such as this.

**Comment by michaelklishin** [comment]
Questions belong to rabbitmq-users.
