### ISSUE TITLE
AutorecoveringConnection doesn't use provided hostnames on init

### ISSUE THREAD

**Issue by khaale** [rabbitmq/rabbitmq-dotnet-client#153]
Hi RabbitMQ team,

Currently 3.6 .NET client has an issue with AutorecoveringConnection initialization - it always tries to connect to the host provided in connection factory, provided *hostnames* list is just ignored.

Looks like the issue caused by unused *hostname* at https://github.com/rabbitmq/rabbitmq-dotnet-client/blob/master/projects/client/RabbitMQ.Client/src/client/impl/AutorecoveringConnection.cs#L577
```csharp
        protected void Init(string hostname)
        {
            m_delegate = new Connection(m_factory, false, m_factory.CreateFrameHandler());
```

I suppose it should be used like 
```csharp

        protected void Init(string hostname)
        {
            m_delegate = new Connection(m_factory, false, m_factory.CreateFrameHandler(m_factory.Endpoint.CloneWithHostname(hostname)));

```

Regards, Alex K.

**Comment by michaelklishin** [comment]
Fixed directly in `stable`. @khaale I'm happy to provide a one-off build (a .dll) if you'd be interested in helping us test the change.

**Comment by khaale** [comment]
Thanks @michaelklishin ! I'd be happy to help with testing.

**Comment by michaelklishin** [comment]
@khaale can you shoot me an email (`michael` in the RabbitMQ domain)? I'll respond with a build from the tip of `stable`.
