### ISSUE TITLE
AutorecoveringConnection ignores ports from the hostname list

### ISSUE THREAD

**Issue by EGlaznev** [rabbitmq/rabbitmq-dotnet-client#157]
Given:
  new ConnectionFactory();
When:
  'AutomaticRecoveryEnabled' is set to true;
  and 'HostName' is not specified;
  and 'Port' is set to 5555;
  and 'hostnames' contains list of 'ABC:1234' and 'DEF:5678'
Then:
  ConnectionFactory.CreateConnection(IList<string> hostnames) do not use ports from strings and always tries to connect on port 555.

It's looks like a reason is here:
        public AmqpTcpEndpoint CloneWithHostname(string hostname)
        {
            return new AmqpTcpEndpoint(hostname, _port, Ssl);
        }

P.S. A previous version 3.6.0 contains this bug too, certainly.

**Comment by michaelklishin** [comment]
Since you understand the issue well, feel free to submit a PR against the stable branch.

**Comment by kjnilsson** [comment]
I've issued a PR for to allow ports to be parsed correctly

**Comment by michaelklishin** [comment]
A fix for this was reverted in #188, we will take a different approach.

**Comment by kjnilsson** [comment]
Just pushed a commit with a proposed api where we add an additional overload to CreateConnection that takes a list of AmqpTcpEndpoints. If this looks acceptable I will finish that approach.

https://github.com/rabbitmq/rabbitmq-dotnet-client/commit/29b8932c650fbe15a9defae75f4c79f8720302ed

**Comment by michaelklishin** [comment]
@kjnilsson that works.
