### ISSUE TITLE
AutorecoveringModel not autorecovering from channel exceptions

### ISSUE THREAD

**Issue by resnikb** [rabbitmq/rabbitmq-dotnet-client#159]
Hi,
It seems that AutorecoveringModel only recovers when the connection is broken and re-established. It does not attempt to autorecover if there was a channel exception that caused the closure. 

At the moment, I am using the following code to ensure recovery, but is there a better way?
```

var model = connection.CreateModel();
model.ModelShutdown += (sender, args) =>
{
    if (args.Initiator == ShutdownInitiator.Application)
        return;

    Task.Run(() => ((AutorecoveringModel)model).AutomaticallyRecover((AutorecoveringConnection)connection, null));
}; 

```

**Comment by michaelklishin** [comment]
Correct and recovering channels after exception was never in the scope for automatic recovery. Your approach seems fine.

**Comment by michaelklishin** [comment]
Note that your example doesn't handle topology recovery but I'm guessing that's fine, you just want to recover channels, and possibly consumers. You are on the right track.

**Comment by resnikb** [comment]
Correct, I'm fine with recreating topology. However, the `AutomaticallyRecover` feels a bit like an undocumented feature, and has an unused parameter - I wasn't sure whether and how it should be used by external code.

Thanks for such a quick response!
