### ISSUE TITLE
Nullable Reference Types

### ISSUE THREAD

**Issue by lechu445** [rabbitmq/rabbitmq-dotnet-client#1596]
### Is your feature request related to a problem? Please describe.

Let's add NRT annotations. There are many articles explaining what benefits it bring.

### Describe the solution you'd like

This change is possible to split into 2 changes:
- to mark public API with NRT (breaking change)
- add NRT to internal code

### Additional context

This would be a breaking change, as marking public API with NRT can cause warnings in users projects. If they have TreatWarningsAsErrors, this can cause their projects not built. Therefore, let's consider it as a breaking change.

**Comment by lukebakken** [comment]
Please feel free to provide a pull request to implement this.

Version 7 is slated to be released soon, so this will have to go into version 8.

**Comment by lukebakken** [comment]
@lechu445 please note that @bollhals has undertaken your request. I suggest you show your appreciation, because he has done a _LOT_ of work.

**Comment by lechu445** [comment]
Thanks @lukebakken for the update and thanks @bollhals for the PR. I will review your change to compare my current work with yours. Thanks a lot!
