### ISSUE TITLE
WinRT/Windows Store support

### ISSUE THREAD

**Issue by raffaine** [rabbitmq/rabbitmq-dotnet-client#16]
Guys,

I'm in some kind of trouble ... I don't know how to solve it. The problem is I'm building a Metro Style app with RabbitMQ.Client.Dll and when I try to instantiate a IBasicProperties or use BasicPublish the source stop compiling with the following error:
1>e:\Julio\Projetos\GitHub\RabbitMQ.Client.dll : error CS0011: The base class or interface 'System.ICloneable' in assembly 'mscorlib, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089' referenced by type 'RabbitMQ.Client.IContentHeader' could not be resolved

Read somewhere that this is because ICloneable doesn't exist anymore on WinRT.Should be useful to build full Win Store apps using RabbitMQ.

**Comment by michaelklishin** [comment]
Is this still relevant with master/`3.4.4`?

**Comment by ngbrown** [comment]
I wasn't part of this issue, but I had separately developed a WinRT branch and discussed it on the mailing list on [June 10, 2014](http://lists.rabbitmq.com/pipermail/rabbitmq-discuss/2014-June/036556.html).

The approach I had at the time wasn't fully integrated into the nuget packaging, so this effort really depends on #32.  I am planning on rebasing my work to the most recent codebase and would like to release have it part of the official release.

I need to know more about the CI environment that is used to build this library.  Supposedly, <http://www.appveyor.com/> (which is free for OSS projects and has nice integration with GitHub) can build Windows 8.1 Windows Store app packages on Windows Server 2012 R2, but I thought that a client SKU was needed.

**Comment by michaelklishin** [comment]
@ngbrown we use Windows 7 for building, as well as

 * VS 2013 Community edition
 * .NET 4.0 or 4.5
 * Cygwin (make and openssl are key for this particular repo)

the rest of the testing process currently depends on `rabbitmq-public-umbrella` but it isn't particularly sophisticated.

Can we add WinRT support without moving to Windows 8.1? (which we can do but we just finished moving to 7 and would need to ask for 8.1 licenses to be procured, worry about VM provisioning on 8.1, etc).

**Comment by ngbrown** [comment]
A WinRT library requires Windows 8.1 to build. It won't even load on Windows 7.  Now Windows 7 can compile a portable class library (PCL) but that [doesn't include Socket and TcpClient](http://stackoverflow.com/questions/24045075/why-cant-i-reference-system-net-sockets-in-a-portable-class-library-using-xamar).

The end result should look something like what [AutoMapper](https://github.com/AutoMapper/AutoMapper) does with building a PLC library and also building targeted libraries for each platform. Using the "bait-and-switch" technique, the targeted library with the actual implementation is selected by the tooling for the final application linking.  ([link](http://blog.xamarin.com/microsofts-pcl-reference-assemblies/) and [link](http://log.paulbetts.org/the-bait-and-switch-pcl-trick/)).

**Comment by michaelklishin** [comment]
@ngbrown I'd need to do some research on that but I'm guessing that the answer is "we can support WinRT and still build/run tests unrelated to it on Win 7 with some clever tricks". Is this correct?

**Comment by ngbrown** [comment]
There's no tricks that I know of to build the networking portion on Windows 7.  `StreamSocket` is only [on Windows 8 or Server 2012](https://msdn.microsoft.com/library/windows/apps/br226882).

There are some differences that I don't think you would want to paper over with a compatibility layer (which would still need compiled on Windows 8/2012, but maybe on another CI platform).  This is what the compatibility layer would need to take care of:

* It would need to handle the socket differences and could cover both `StreamSocket` and `TcpClient`.  The client support for SSL/TLS does not include the ability to use client certificates.
* Also AppDomain unloading is different, in that the Windows 8 application sends a [suspending event](https://msdn.microsoft.com/en-us/library/windows/apps/xaml/windows.ui.xaml.application.suspending.aspx), not a DomainUnload event.

**Comment by michaelklishin** [comment]
@ngbrown OK, so what are our options then? Drop Windows 7 support?

**Comment by ngbrown** [comment]
@michaelklishin no dropping of any support... Just adding.  Windows 8 is highly compatible in terms of what desktop applications it runs. For example, you could run your current build process as-is and get the same outputs.

I am suggesting using the [NuGet support for multiple framework versions and profiles](http://docs.nuget.org/Create/Enforced-Package-Conventions) to include additional dll's for new profiles.  For example, the AutoMapper OSS project I mentioned earlier has 11 separate targets in its [build script](https://github.com/AutoMapper/AutoMapper/blob/develop/default.ps1) that are combined into a single `.nuget` package.  Also check out the authors [blog post on this](http://lostechies.com/jimmybogard/2015/02/13/cross-platform-automapper-again/).

The differences mentioned above with `StreamSocket` and `TcpClient` are [limitations on the specific .Net profile](https://msdn.microsoft.com/en-us/library/br230302.aspx) that a Windows Store Application uses.  These are the new full-screen immersive apps and are now the 'Universal App' that also runs on Windows 8.1 Phone.  They are build for a newer Windows API, so require different  networking code from a library such as the RabbitMQ client.  Standard desktop apps wouldn't use that API, and would continue to use the existing framework and `TcpClient`.

By using the same files, and including [preprocessor directives](https://msdn.microsoft.com/en-us/library/4y6tbswk.aspx) like `#if NET45`, `#if MONO`, or `#if NETFX_CORE`, we can build outputs for additional platforms and framework versions.

**Comment by michaelklishin** [comment]
@ngbrown excellent, thank you for the detailed reply. We'll do what you suggest and now it should be much easier for you to help us ;)

**Comment by michaelklishin** [comment]
This is now in master. we still have to fix #82 and evaluate how we'd like to distribute the two versions but if all you need is a WinRT-compatible `.dll`, you can build and use one today. Huge thanks to @ngbrown for his enormous contribution!
