### ISSUE TITLE
createModel stays blocked

### ISSUE THREAD

**Issue by pdumais** [rabbitmq/rabbitmq-dotnet-client#160]
Using 3.2.1  and 3.6.1, calling createModel() sometimes never returns.

I was having a problem with my server VM, where I suspect that the rmq bus does not respond anymore due to some VM problem. But that is beyond the scope of this issue. 

The problem is that the client VM, when it calls createModel() during that issue seems to block indefintely. Should there be a timeout (exception thrown?) after a certain amount of time?

**Comment by michaelklishin** [comment]
Please use rabbitmq-users for questions. [There is a timeout](https://github.com/rabbitmq/rabbitmq-dotnet-client/issues/80), as well as [heartbeats](http://www.rabbitmq.com/heartbeats.html).
