### ISSUE TITLE
Issues with 7.0rc1 IAsyncBasicConsumer's method 

### ISSUE THREAD

**Issue by Tornhoof** [rabbitmq/rabbitmq-dotnet-client#1601]
### Describe the bug

The new IAsyncBasicConsumer interface has a method ``HandleBasicDeliver`` and a method parameter ``ReadOnlyBasicProperties`` , but with the modifier ``in``. You can't have ``in``, ``ref`` in async methods. So as soon as you implement the interface and actually have anything async to do, i.e. you add the async keyword, it won't compile anymore, with CS1988 (https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-messages/ref-modifiers-errors#reference-variable-restrictions).

https://github.com/rabbitmq/rabbitmq-dotnet-client/blob/2a5aed7823a7eb938443763d6319a12d24bfc462/projects/RabbitMQ.Client/client/api/IAsyncBasicConsumer.cs#L49-L55

``in`` basically makes only sense together with ``ref struct`` and specifically ``ref readonly struct``, atleast that's what I understand from all the discussions around https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/proposals/csharp-11.0/low-level-struct-improvements.

I highly recommend simply removing ``in`` this prior to the 7.0 release, as modifying it would be a breaking change and at the moment implementations would need to jump through loops to use it with async (async local method etc.).

In ``IBasicConsumer`` it's not there:
https://github.com/rabbitmq/rabbitmq-dotnet-client/blob/2a5aed7823a7eb938443763d6319a12d24bfc462/projects/RabbitMQ.Client/client/api/IBasicConsumer.cs#L92-L98

### Reproduction steps

See for example:
https://sharplab.io/#v2:EYLgxg9gTgpgtADwGwBYA0AXEBDAzgWwB8ABAJgEYBYAKGIAYACY8gVgG4biBmJ0hgYQYBvGgzFMexABxMkDALIBPeTAwALCABMAFAEsAdgwAqMXBgDKGKAFcwGBvkUA1bABtrMAJSjxQ8eJ8xAF9AhlDuBlhsTQh9V0UGMxs7Y1MLK1sMUJFqfxDqIKA===

### Expected behavior

-

**Comment by michaelklishin** [comment]
Thank you for providing all the details from the start!

**Comment by lukebakken** [comment]
Great, this will be easy to fix. Feel free to open a PR yourself if you'd like!

**Comment by Tornhoof** [comment]
will do.

**Comment by bollhals** [comment]
The problem with this is, `ReadOnlyBasicProperties` is a rather large struct, hence the `in` modifier was added back when it wasn't async yet to avoid copying the struct.

Now that the library moved to async, `in` is problematic as you've seen.
So the use of a large struct for these API's might actually be worse than creating a class to hold them.

**Comment by lukebakken** [comment]
@bollhals I'll open a PR to convert `ReadOnlyBasicProperties` to a class. It's unlikely that users will create instances of it over-and-over while publishing.
