### ISSUE TITLE
RabbitMQActivitySource.Deliver cannot be used by types that implement Consumer

### ISSUE THREAD

**Issue by Tornhoof** [rabbitmq/rabbitmq-dotnet-client#1621]
### Describe the bug

Currently ``RabbitMQActivitySource.Deliver`` is only called in the derived types ``AsyncEventingBasicConsumer`` and ``EventingBasicConsumer`` and  the method itself is marked as internal.

https://github.com/rabbitmq/rabbitmq-dotnet-client/blob/89d472d8995b815ae5a05b9d998853945c428b99/projects/RabbitMQ.Client/client/events/AsyncEventingBasicConsumer.cs#L99-L105

This means, if a dev is deriving from the base types ``DefaultBasicConsumer``  or ``AsyncDefaultBasicConsumer`` or implements the appropriate interfaces, the Deliver method can't be invoked.

All the other relevant ActivitySource methods are called from within ChannelBase, so these should be fine.

I think the easiest way forward is to make a public RabbitMQActivitySource.Deliver method with the args from the eventArgs:

Current:
https://github.com/rabbitmq/rabbitmq-dotnet-client/blob/89d472d8995b815ae5a05b9d998853945c428b99/projects/RabbitMQ.Client/client/impl/RabbitMQActivitySource.cs#L122-L142

Proposed change:

```csharp
        internal static Activity Deliver(BasicDeliverEventArgs deliverEventArgs)
        {
            return Deliver(deliverEventArgs.RoutingKey, deliverEventArgs.Exchange, deliverEventArgs.DeliveryTag,
                deliverEventArgs.BasicProperties, deliverEventArgs.Body.Length);
        }

        public static Activity Deliver(string routingKey, string exchange, ulong deliveryTag,
            in ReadOnlyBasicProperties readOnlyBasicProperties, int bodySize)
        {
            if (!s_subscriberSource.HasListeners())
            {
                return null;
            }

            // Extract the PropagationContext of the upstream parent from the message headers.
            Activity activity = s_subscriberSource.StartLinkedRabbitMQActivity(
                UseRoutingKeyAsOperationName ? $"{routingKey} deliver" : "deliver",
                ActivityKind.Consumer, ContextExtractor(readOnlyBasicProperties));
            if (activity != null && activity.IsAllDataRequested)
            {
                PopulateMessagingTags("deliver", routingKey, exchange,
                    deliveryTag, readOnlyBasicProperties, bodySize,
                    activity);
            }

            return activity;
        }
```

Then the dev can call it in their own implementation of ``HandleBasicDeliver``. I don't see any easy way to do it automatically, like for the other methods, that would be preferable.

### Reproduction steps

-

### Expected behavior

-

### Additional context

Maybe @stebet  has a better idea, he wrote the original PR.

**Comment by stebet** [comment]
I'll take a look :)

**Comment by lukebakken** [comment]
@stebet thank you!!!

**Comment by bollhals** [comment]
Wouldn't it be better to move it inside of the dispatcher rather than the BasicConsumer?

**Comment by lukebakken** [comment]
@bollhals would you mind expanding on your comment? I'm assuming that you mean `RabbitMQActivitySource.Deliver` should be called in these places:
* https://github.com/rabbitmq/rabbitmq-dotnet-client/blob/main/projects/RabbitMQ.Client/client/impl/ConsumerDispatching/AsyncConsumerDispatcher.cs#L29-L31
* https://github.com/rabbitmq/rabbitmq-dotnet-client/blob/main/projects/RabbitMQ.Client/client/impl/ConsumerDispatching/ConsumerDispatcher.cs#L31-L35

**Comment by bollhals** [comment]
Yes exactly. I wondered whether it would make more sense to do it at that level than in the consumer themselves.

**Comment by lukebakken** [comment]
@stebet @Tornhoof @bollhals -> https://github.com/rabbitmq/rabbitmq-dotnet-client/pull/1633

Let me know what you think!

**Comment by bollhals** [comment]
looks reasonable to me.

**Comment by Tornhoof** [comment]
Yeah, I agree, this looks quite neat.
