### ISSUE TITLE
NullReferenceException when setting null Uri into ConnectionFactory

### ISSUE THREAD

**Issue by lechu445** [rabbitmq/rabbitmq-dotnet-client#1622]
### Describe the bug

It is not clear if ConnectionFactory can have null Uri property. If ConnectionFactory is created via constructor, Uri property returns null. But, ConnectionFactory does not allow explicit set null Uri.

### Reproduction steps

Simple reproduction:
```c#
using RabbitMQ.Client;

var c = new ConnectionFactory();

Console.WriteLine(c.Uri == null); // prints True

c.Uri = null; // throws NullReferenceException
```

### Expected behavior

NullReferenceException is not thrown.

### Additional context

This issue was detected by Roslyn analyzer during work on https://github.com/rabbitmq/rabbitmq-dotnet-client/issues/1596.

**Comment by lechu445** [comment]
I don't fully understand the design choice to allow users to set and override Uri after ConnectionFactory is created. Maybe the design should be changed to leave only getter and move Uri setting logic into ConnectionFactory constructior? Then we are able to add null check for it.

Here is what I mean:
```c#
    public sealed class ConnectionFactory : ConnectionFactoryBase, IConnectionFactory
    {
        private Uri? _uri;

        public ConnectionFactory(Uri uri) // added parameter uri
        {
            if (uri is null) // added null check
            {
                throw new ArgumentNullException(nameof(uri));
            }
            SetUri(uri); // this is now called in constructor
            ClientProperties = new Dictionary<string, object>(DefaultClientProperties);
        }

        public Uri? Uri
        {
            get { return _uri; }
            // removed setter
        }
    }
```
This is the cleanest solution, but require breaking change in ConnectionFactory and IConnectionFactory.

**Comment by lukebakken** [comment]
@lechu445 please realize that this project's API is very, very old, so issues like this crop up.

Considering that you are the first person to notice or care about this behavior with regard to `ConnectionFactory.Uri` shows that it is low-priority to address.

I've marked this as a version 8 item so that better design choices can be made. Thanks.
