### ISSUE TITLE
Re-review use of `Task` vs `ValueTask` in API

### ISSUE THREAD

**Issue by lukebakken** [rabbitmq/rabbitmq-dotnet-client#1645]
See the discussion here: https://github.com/rabbitmq/rabbitmq-dotnet-client/pull/1642

cc @danielmarbach

**Comment by lukebakken** [comment]
@danielmarbach @stebet @paulomorgado @Hawxy

Re: `Task` vs `ValueTask` in the public API - my current inclination is to just use `Task` unless someone can come up with a concrete benchmark showing an appreciable performance benefit for `ValueTask`, or provide another compelling reason to use `ValueTask`.

As you are all aware, version 7 has been _years_ in the making. I am going to ship version 7 this month, no matter what 😸

**Comment by danielmarbach** [comment]
I definitely don't want to derail the release @lukebakken 

Just sharing thoughts and observations from our upgrade attempts. At the end of the day, if we leave things as is, that's also fine.

**Comment by lukebakken** [comment]
> Just sharing thoughts and observations from our upgrade attempts.

I'm all for making migrations from 6.x easier.

**Comment by danielmarbach** [comment]
Well one of the biggest pain points was that the order of some parameters changed and not the value task vs task 😜

**Comment by lukebakken** [comment]
> Well one of the biggest pain points was that the order of some parameters changed

I'm planning to update [the tutorials](https://github.com/rabbitmq/rabbitmq-tutorials/tree/main/dotnet) to use the latest RC before shipping version 7, so I'll probably make note of this, but if you'd like to mention which changes were most annoying that would be great. Maybe I can restore the parameter order in the API.

**Comment by danielmarbach** [comment]
@lukebakken the entire diff is visible here https://github.com/Particular/NServiceBus.RabbitMQ/pull/1446

**Comment by lukebakken** [comment]
Perfect, thanks!

**Comment by lukebakken** [comment]
@danielmarbach it looks like the `BasicPublishAsync` API was the biggest (maybe only?) offender, so I reverted the parameter order change in this commit: https://github.com/rabbitmq/rabbitmq-dotnet-client/pull/1664/commits/5abd91233704d27fb4ffc331ae9bdc5f1e1a55e0

**Comment by lukebakken** [comment]
Based on the comment by @Hawxy -

https://github.com/rabbitmq/rabbitmq-dotnet-client/issues/1413#issuecomment-2330757450

...I re-visited `IChannel`. Those methods that directly call `ModelSendAsync` without an RPC continuation will return `ValueTask`, while everything else returns `Task` or `Task<>`. Thanks everyone.
