### ISSUE TITLE
TunneledTcpClient and SQL 2014 CLR compatibility

### ISSUE THREAD

**Issue by osudude** [rabbitmq/rabbitmq-dotnet-client#167]
Tried upgrading from RabbitMQ.Client 3.5.x today to 3.6.1 for our SQL Clr SP that publishes to RabbitMQ.  Upon registering our assembly that depends on RabbitMQ.Client, SQL 2014 gave use the following error:

** CREATE ASSEMBLY failed because type "RabbitMQ.Client.TunneledTcpClient" in safe assembly "RabbitMQ.Client" has a finalizer. Finalizers are not allowed in safe assemblies. **

Does TunneledTcpClient necessarily need a finalizer?  I can try to register our assembly that depends on rabbitmq.client assembly as unsafe to see if I can get around the registration error.

May relate to [85](https://github.com/rabbitmq/rabbitmq-dotnet-client/pull/85)

See also [CLR Integration Programming Model Restrictions](https://msdn.microsoft.com/en-us/library/ms403273.aspx)

**Comment by michaelklishin** [comment]
It was introduced in https://github.com/rabbitmq/rabbitmq-dotnet-client/pull/115. If we can avoid having a finalizer, that's fine with me. Unfortunately neither of the features is particularly popular so I'm not sure what we should prefer.

**Comment by osudude** [comment]
Registering our SQL CLR assembly that depends on RabbitMQ.Client in unsafe mode seems to have worked.  It did require setting the database to trustworthy mode which is potentially a large security hole.

[Guidelines for using the TRUSTWORTHY database setting in SQL Server](https://support.microsoft.com/en-us/kb/2183687)

[SQL-Server-CLR-Integration-Part-Security](http://www.codeproject.com/Articles/17855/SQL-Server-CLR-Integration-Part-Security)

**Comment by kjnilsson** [comment]
I don't see why this class needs a finalizer. I can't see it holding on to any direct unmanaged resources (pointers, handles, etc) which is the only real reason to use finalizers. Will create a PR to remove it.

**Comment by michaelklishin** [comment]
Should be fixed in #174.
