### ISSUE TITLE
Allow DateTime for Headers in IBasicProperties

### ISSUE THREAD

**Issue by msschl** [rabbitmq/rabbitmq-dotnet-client#1691]
### Is your feature request related to a problem? Please describe.

Allow passing in DateTime as object into the Headers property of the IBasicProperties object.

See https://github.com/rabbitmq/rabbitmq-dotnet-client/blob/be1d1e38aa745d2fc5b989610dc2647dc6b79f2d/projects/RabbitMQ.Client/Impl/WireFormatting.Write.cs#L152

### Describe the solution you'd like

I think it needs to be implemented in https://github.com/rabbitmq/rabbitmq-dotnet-client/blob/be1d1e38aa745d2fc5b989610dc2647dc6b79f2d/projects/RabbitMQ.Client/Impl/WireFormatting.Write.cs#L152

**Comment by lukebakken** [comment]
The AMQP 0.9.1 protocol has no notion of date & time. You must convert to/from some other format in your application itself.
