### ISSUE TITLE
Single Active consumer

### ISSUE THREAD

**Issue by satishviswanathan** [rabbitmq/rabbitmq-dotnet-client#1723]
### Is your feature request related to a problem? Please describe.

We are using the RabbitMQ SAC feature and it works fine. I have a requirement where the client can have this ability to know if it's active or in waiting status.

![image](https://github.com/user-attachments/assets/3700f329-a84a-4618-96cc-c9c240835fce)

### Describe the solution you'd like

Can the AsyncDefaultBasicConsumer class have a status property through which the client can know if the client consumer is active or in waiting mode ?

**Comment by lukebakken** [comment]
The AMQP 0.9.1 protocol does not provide this information, so this library can't, either. Your best option is to query the HTTP API for this information, and this library facilitates those queries:

https://github.com/EasyNetQ/EasyNetQ.Management.Client

My _GUESS_ is that this field contains the information you're looking for:

https://github.com/EasyNetQ/EasyNetQ.Management.Client/blob/master/Source/EasyNetQ.Management.Client/Model/Consumer.cs#L11

**Comment by satishviswanathan** [comment]
@lukebakken Thank you for sharing your thoughts will use the HTTP api to query this info.
