### ISSUE TITLE
NullReferenceException when calling IConnection.CreateModel()

### ISSUE THREAD

**Issue by timoch** [rabbitmq/rabbitmq-dotnet-client#185]
In some rare cases, IConnection.CreateModel throws a NullReferenceException.
This happens when the connection closes between the call to ConnectionFactory.CreateConnection() and the call to IConnection.CreateModel()

See below: Initialise() attaches to Session.SessionShutdown. In the case described above, Session.SessionShutdown directly calls any handler it gets. As you can see, this.ConsumerDispatcher.Quiesce() is called immediately but this.ConsumerDispatcher is only set after the call to Initialize()

        public ModelBase(ISession session, ConsumerWorkService workService)
        {
            Initialise(session);
            ConsumerDispatcher = new ConcurrentConsumerDispatcher(this, workService);
        }

        protected void Initialise(ISession session)
        {
            CloseReason = null;
            NextPublishSeqNo = 0;
            Session = session;
            Session.CommandReceived = HandleCommand;
            Session.SessionShutdown += OnSessionShutdown;
        }

        public void OnSessionShutdown(object sender, ShutdownEventArgs reason)
        {
            this.ConsumerDispatcher.Quiesce();
            SetCloseReason(reason);
            OnModelShutdown(reason);
            BroadcastShutdownToConsumers(m_consumers, reason);
            this.ConsumerDispatcher.Shutdown(this);
        }

It feels like ConsumerDispatcher could simply be initialized before calling Initialize(). I don't know the exact impact though

**Comment by michaelklishin** [comment]
@timoch thank you for the investigation. Do you have a (basic, could be incomplete) test case we can use to reproduce?

**Comment by timoch** [comment]
Ok, here it is. There is a race condition between the connection AutoClose and the creation of models from multiple threads. I tried using a thread-static connection but it yields roughly the same result. Probably because the connection itself is managed by background threads owned by RabbitMQ.Client.

As a short term solution we will keep a model around. That should keep the connection up. 

    using System;
    using System.Threading;

    using RabbitMQ.Client;

    namespace ConsoleApplication2
    {
        class Program
        {
            private static IConnection connection;
            private static ConnectionFactory connectionFactory;

            static void Main(string[] args)
            {
                connectionFactory = new ConnectionFactory();
                connectionFactory.Uri = "amqp://itguard:itguard@broker.rabbitmq.dvl.fluxys.net:5672";
            
                var thread1 = new Thread(DoWork);
                thread1.Start(1);
                var thread2 = new Thread(DoWork);
                thread2.Start(2);
            }

            private static void DoWork(object id)
            {
                object lastConnection = null;
                while (true)
                {
                    try
                    {
                        var conn = EnsureConnection(id);
                        if (!object.ReferenceEquals(lastConnection, conn))
                        {
                            Console.WriteLine($"{id}: Connection switched");
                            lastConnection = conn;
                        }

                        var model = conn.CreateModel();
                        conn.AutoClose = true;
                        model.Close();
                    }
                    catch (NullReferenceException ex)
                    {
                        Console.WriteLine($"{id}: {ex}");
                    }
                    catch
                    {
                        Console.WriteLine($"{id}: ;");
                    }
                }
            }

            private static IConnection EnsureConnection(object id)
            {
                while (connection == null || !connection.IsOpen)
                {
                    connection = connectionFactory.CreateConnection();
                    connection.AutoClose = false;
                    connection.ConnectionShutdown += (sender, args) => { Console.WriteLine($"{id}: Connection shutdown"); };
                }

                return connection;
            }
        }
    }

**Comment by kjnilsson** [comment]
Hi @timoch - thanks for the investigation. I was able to use your test program to reproduce it on windows (but not on mono, strangely) but not after applying your proposed change. I also ran our complete test suite against it and it all passes ok. I've submitted a PR for this against the stable branch.

**Comment by timoch** [comment]
Hi @michaelklishin - the issue is marked as part of v3.6.3 but it looks like it didn't make it yet. At least, it is not fixed in v3.6.6. I could see the fix is included in the upcoming v3.7.0. Do you have a timeframe for v3.7.0 ?
Thanks

**Comment by michaelklishin** [comment]
It did make it into 3.6.3, see above. This client is now versioned independently from RabbitMQ except for 3.6.x. So 4.x releases are already out and 5.0 is in development.

**Comment by timoch** [comment]
I probably don't understand the tagging scheme you use. 

I can only observe that tag rabbitmq_3_6_6 does not contain commit https://github.com/rabbitmq/rabbitmq-dotnet-client/commit/166cf17f0c981cdf244392a7efd687b659a24b41 but rabbitmq_v3_7_0_milestone5 does. So do other tags for 4.x and 5.x versions.

**Comment by michaelklishin** [comment]
I changed the milestone to reflect reality. Just use a `4.x` version of the client.
