### ISSUE TITLE
New "Client Provided Name" feature not working -- connection_name undefined

### ISSUE THREAD

**Issue by bording** [rabbitmq/rabbitmq-dotnet-client#187]
While upgrading https://github.com/Particular/NServiceBus.RabbitMQ to use 3.6.2, I noticed that the new feature introduced in #164 appears to have a problem. 

Given the following code:
```csharp
static void Main(string[] args)
{
    var factory = new ConnectionFactory();

    using (var connection = factory.CreateConnection("ConnectionName"))
    {
        var name = connection.ClientProvidedName; //this is null;
        Console.ReadKey();
    }
}
```
Here is what I see when I look at the management UI:

![connectionlist](https://cloud.githubusercontent.com/assets/753669/15518788/7c6d7926-21cc-11e6-86bd-3700adb7bb45.PNG)

![connectiondetails](https://cloud.githubusercontent.com/assets/753669/15518791/7f6fb968-21cc-11e6-8afa-2961eb953f68.PNG)

I even tried manually setting the `connection_name` client property via `factory.ClientProperties["connection_name"] = "ConnectionName";` and the value still shows up as `undefined` in the management UI.

Looking at the changes from #164, I see that `connection_name` is overwritten [here](https://github.com/rabbitmq/rabbitmq-dotnet-client/blob/e8f0a3aca3ab16ca3f2537dbc78543c91ff58f92/projects/client/RabbitMQ.Client/src/client/impl/Connection.cs#L1280), so I suspect that the `ClientProvidedName` property must be null at that point for some reason.

**Comment by rossperry** [comment]
I am using .net client Nuget version 6.2.1
RabbitMQ 3.8.16 Erlang 24.0.2 and on the admin connection page I still see undefined instead of the clientProvidedName that I set.
            string conName = EnvHelper.GetStringOrDefault("SERVICE_NAME", "");
            if(conName == "")
            {
                string execPath = Assembly.GetEntryAssembly().Location;
                conName = Path.GetFileName(execPath);
            }

            _logger.Info($"Creating connection for {conName}");
            return factory.CreateConnection(conName);
Is this not working?
