### ISSUE TITLE
Content Header's Table (BasicProperties.Headers) handling of amqp's longstr

### ISSUE THREAD

**Issue by hammett** [rabbitmq/rabbitmq-dotnet-client#198]
Consider:

```
var props = model.CreateBasicProperties();
props.Headers = new Dictionary<string,object> { { "key", "some value" } };
```

The table is correctly serialized. When deserializing, though, the implementation of ReadFieldValue calls ReadLongstr which returns a byte array. The behavior is not properly reflexive on this one. Not sure it's intentional. 

A simple UTF8.GetString( ReadLongstr() ) would fix it. 

That said a lot of our existing code now expects the byte[], so the fix may cause some pain to existing users.

**Comment by kjnilsson** [comment]
Basic property headers are defined as an amqp table type. In the spec the table type contains both short and longstr types. However, rabbitmq does not quite follow the spec in that regards which means there is no ShortStr table type so in this case your string is interpreted as a longstr. 

see 3 Field Types in: https://www.rabbitmq.com/amqp-0-9-1-errata.html

**Comment by hammett** [comment]
That's fine. The issue is that the deserialization is turning it into a byte array. When add a string as an entry in a dictionary, it would be natural to expect an string on the other end.

**Comment by kjnilsson** [comment]
I agree but the problem is there is no on-spec way to communicate the encoding of a LongStr or if it even is meant to be a string at all. Any change here would be, as you noted above, a likely breaking change.

**Comment by michaelklishin** [comment]
Once we decouple this client's releases from RabbitMQ server, we can fix this in a `4.0.0` or something like that.

**Comment by kjnilsson** [comment]
I'm about to start work on this issue. It will have some API impact. It has the effect that header values can no longer be plain byte arrays. So any current usages of plain byte array header values will either be no longer be supported or not behave the same way on the wire. The client will assume that any field values of type `S` are UTF-8 encoded strings and convert them as such at the other end.

Sending byte arrays as header values can be worked around by wrapping the byte array in  the [BinaryTableValue](https://github.com/rabbitmq/rabbitmq-dotnet-client/blob/c165ffdab5cbf3cfb8ace73b3872bd3f24464225/projects/client/RabbitMQ.Client/src/client/api/BinaryTableValue.cs) class that uses the non-standard `x` field type.

The concern is that other clients may not behave the same way. The .NET client may no longer be used to publish messages to clients that expect a byte array header value with the `S` type. It may be that these clients are rare and it is no big deal.


The question is what to do when a user passes a plain byte array
1. We throw an exception advising the user to wrap it in a `BinaryTableValue`.
2. We implicitly wrap it in a `BinaryTableValue` and unwrap it at the other end. This means `BinaryTableValue` is effectively no longer part of the client API.
3. Leave the current functionality and hope that the consumer isn't another .NET client.

WDYT @michaelklishin @hammett ? I think I favour 2.

**Comment by michaelklishin** [comment]
Note that some languages don't have an equivalent to byte arrays. I'd check Java, Ruby and Python.

I am leaning towards option 1. Option 2 doesn't seem too bad but it depends on how other clients will react by default.

**Comment by hammett** [comment]
Taking into account that is ok to convert from byte[] to string and back, I think this would be just a normalization of a behavior. I'd add 

option 4 - plain byte[] are converted to strings. 

Then it would work with all other clients without any extra change.

**Comment by kjnilsson** [comment]
Round-tripping arbitrary binary data to utf8 and back is not a safe operation as this brief `fsi` session shows:

```
> Encoding.UTF8.GetString [|128uy|] |> Encoding.UTF8.GetBytes;;
val it : byte [] = [|239uy; 191uy; 189uy|]
```

Having looked at pika, bunny and the java client they all implement slightly different strategies. Pika appears to utf8 encode the header value data indiscriminately, bunny does not impose an encoding as far as I can tell and the java client has a similarly asymmetric api to the current .NET client in that it accepts string or byte arrays as input, does not impose an encoding on the transported data when it is passed as a byte array then returns a `LongString` type containing the binary data irrespective of how the header value was created. The `LongString` type contains convenience methods for doing the utf8 conversion if required.

It seems like header value interop between clients can be a tricky thing unless you restrict yourself to numbers and utf8 compatible strings. I am not sure what is gained by changing the current API in the .NET client here though. The asymmetry isn't great but it seems to me to be the option that stays closest to the spec and provides the most compatibility.

**Comment by hammett** [comment]
I dont remember saying UTF8 was a good idea, as it normalizes the stream. 

The bottom line issue is writing a string and retrieving a byte[]. This is understandable if you're familiar with the amqp type system, and how the information is lost (was a string or a byte[] to start with?) and maybe the design problem is exactly trying to bridge these two primitives in .net with a single primitive in amqp. 

IMHO the best solution is somewhat suggested by you: LongString. The amqp type is explicit in the api surface (as is Amqp Timestamp), and as long as it has explicit conversion operators, the programmer can cast to what she expects that to be interpreted.

**Comment by michaelklishin** [comment]
There is still no consensus about this issue, so I'm clearing its milestone.

**Comment by lukebakken** [comment]
#415 supersedes this issue.
