### ISSUE TITLE
Named parameter version of the API

### ISSUE THREAD

**Issue by OlsonDev** [rabbitmq/rabbitmq-dotnet-client#20]
This is just a generic request. I've noticed this client/API is very Boolean happy. I'd much rather see overloads which take in specific purpose enums.

I just put together a demo app and in reviewing the code I wrote yesterday, I'm having difficulty reading it. Compare what I have with what it could be.

What I have:
`model.QueueDeclare(queueName, true, false, false, null);`

What I could have:
`model.QueueDeclare(queue:queueName, durable:true, exclusive:false, autoDelete:false, arguments:null);`

What I'd like to have:
`model.QueueDeclare(queueName, Durability.Durable, Scope.Public, OnEmpty.DoNotDelete);`

The names of the enums are merely a suggestion -- if you can think of better names, go for it. I'd just like to see more overloads, default parameters, & enums.

Regarding default parameters, I'd even go so far as to say `model.QueueDeclare(queueName)` is acceptable so long as IntelliSense told me what all the defaults were.

**Comment by michaelklishin** [comment]
So, with .NET 4 (required in master), it is already possible to do something like

``` csharp
ch.QueueDeclare("", durable: false, exclusive: false, autoDelete: true, arguments: null)
```

This trades significant readability improvements for a tiny latency increase (for the I/O bound methods in our client). Looks like the only thing we should do is to update our tutorials to use named arguments and .NET guide to mention both ways of invoking methods.

Needless to say, I wish `javac` had this feature :)

**Comment by michaelklishin** [comment]
Will file a separate issue for the tutorials.
