### ISSUE TITLE
.Net Core support

### ISSUE THREAD

**Issue by wjdavis5** [rabbitmq/rabbitmq-dotnet-client#210]
Are there plans to port this library to .NET Core?

**Comment by michaelklishin** [comment]
#148, [mailing list announcement](https://groups.google.com/forum/#!searchin/rabbitmq-users/AppVeyor/rabbitmq-users/hyJLlXCbocY/IEWxno3oAwAJ).

**Comment by michaelklishin** [comment]
Please post questions to rabbitmq-users in the future. RabbitMQ uses GitHub issues for specific actionable items engineers can work on, not questions. Thank you.

**Comment by wjdavis5** [comment]
thank you
