### ISSUE TITLE
SSL Broken in 3.6.2

### ISSUE THREAD

**Issue by gwjames** [rabbitmq/rabbitmq-dotnet-client#212]
It appears 3.6.2 has broken SSL connections. If I specify to use SSL on a unique port, it is ignored and the connection tries to use port 5672.

If I revert back to 3.6.1, it works 100%.

**Comment by michaelklishin** [comment]
It doesn't have "broken SSL connections", it simply forces port to be 5671. See https://github.com/rabbitmq/rabbitmq-dotnet-client/issues/186. Use 3.6.1 or 3.6.3 M2.
