### ISSUE TITLE
Consider making ConnectionFactory.HostName a property

### ISSUE THREAD

**Issue by nkumars** [rabbitmq/rabbitmq-dotnet-client#217]
Hi,

The properties in RabbitMQ.Client.ConnectionFactory such as UserName and Password are actually set as properties (means it has {get;set;}) whereas for HostName does not exist, which actually forces us to use GetField method while the other two can be used with GetProperty. 

I dont know the purpose behind this, but I would suggest to have a consistent declaration, i.e., with {get;set;} or without.

Below is the screenshot that describes my explanation.

![fieldandpropertyissue](https://cloud.githubusercontent.com/assets/7982858/16585951/fb8b866e-42e0-11e6-856a-01d531f00159.png)

Regards,
Naveen

**Comment by kjnilsson** [comment]
Field -> Property is a breaking change as applications using .e.g `HostName` would need to be recompiled. I propose moving this to the 3.7 (v4.0.0) milestone and address it there.

**Comment by michaelklishin** [comment]
@kjnilsson fair enough.
