### ISSUE TITLE
Updating .Net Core branch and releasing a NuGet package

### ISSUE THREAD

**Issue by samirski** [rabbitmq/rabbitmq-dotnet-client#218]
If I'm not mistaken you were planning to update the .Net Core branch after the final release of .Net Core 1.0 and release a NuGet package for that. Since 1.0 is out, could you please release an official NuGet package for it?

**Comment by michaelklishin** [comment]
We release things when they are ready. There is a [NuGet feed of nightly builds](https://ci.appveyor.com/nuget/rabbitmq-dotnet-client-ci) but .NET Core is nowhere near maturity is neither our client on it. So there are no plans to produce a release in the next month or two.
