### ISSUE TITLE
'System.ObjectDisposedException' when closing/disposing connection

### ISSUE THREAD

**Issue by IAmShipy** [rabbitmq/rabbitmq-dotnet-client#220]
As discussed within the following Google groups thread:

[ObjectDisposed exception from C# RabbitMQ 3.5.4 client ](https://groups.google.com/forum/#!topic/rabbitmq-users/7zR-gQDU5pQ)

I'm also getting the same problem using RabbitMq.Client 3.6.3 with .Net framework 4.5.2, running within Visual Studio 2015.  The stack trace I'm getting is

```
System.ObjectDisposedException occurred
Message: Exception thrown: 'System.ObjectDisposedException' in mscorlib.dll
Additional information: Cannot access a disposed object.
   at System.Threading.TimerQueueTimer.Change(UInt32 dueTime, UInt32 period)
```

This bug was occurring within a larger application.  I originally thought it was some kind of multithreading problem caused by myself so to isolate the issue I've created a simple winform application and I still get the problem.

```c#
    public partial class Form1 : Form
    {
        public Form1()
        {
            InitializeComponent();
        }

        private void button1_Click(object sender, EventArgs e)
        {
            using (var producer = new Producer())
            {
                producer.Send("Test");
            }
        }
    }


    class Producer : IDisposable
    {
        private IConnection _connection;
        private IModel _model;

        public Producer()
        {
            ConnectionFactory connectionFactory = new ConnectionFactory()
            {
                HostName = "localhost",
                Port = 5672,
            };
            _connection = connectionFactory.CreateConnection();

            _model = _connection.CreateModel();

            _model.QueueDeclare("Queue:Testing", true, false, false, null);
        }

        public void Send(string message)
        {
            byte[] bytes = Encoding.UTF8.GetBytes(message);
            _model.BasicPublish(string.Empty, "Queue:Testing", CreateDefaultRequestProperties(_model), bytes);
        }

        private IBasicProperties CreateDefaultRequestProperties(IModel model)
        {
            var basicProperties = model.CreateBasicProperties();
            basicProperties.Persistent = true;
            basicProperties.ContentType = "application/json";
            basicProperties.ContentEncoding = "UTF-8";
            basicProperties.Priority = (byte)1;
            return basicProperties;
        }

        ~Producer()
        {
            Dispose(false);
        }

        public void Dispose(bool disposing)
        {
            if (disposing)
            {
                try
                {
                    _model?.Close();
                    _connection?.Close();                    
                }
                catch (ObjectDisposedException ignored){}
            }
        }

        public void Dispose()
        {
            Dispose(true);
            GC.SuppressFinalize(this);
        }
    }
```

It consistently happens when `_connection?.Close()` or `_connection?.Dispose()` is called. 

Any ideas what can be done to resolve this once and for all?

**Comment by kjnilsson** [comment]
Hi, Thanks for the report, I will try to replicate this using your example.

**Comment by IAmShipy** [comment]
Thank you.  To clarify, I will be ignoring the bug within my application hence the try..catch to ignore the ObjectDisposedException.  

But even so when running within VS2015, I still see the following error being output within the **Output** window (and it seems to be produced multiple times):

```
Exception thrown: 'System.ObjectDisposedException' in mscorlib.dll
Exception thrown: 'System.ObjectDisposedException' in mscorlib.dll
Exception thrown: 'System.ObjectDisposedException' in mscorlib.dll
Exception thrown: 'System.ObjectDisposedException' in mscorlib.dll
```

Also, if we turn on all **Common Language Runtime Exceptions** within **Debug>Windows>Exception Settings**, the debugging session stops when this bug occurs which is frustrating when trying to debug our code.

**Comment by michaelklishin** [comment]
`Connection.Dispose` is not what the client assumes you will use but good to know that `Connection.Close` can trigger it.

**Comment by kjnilsson** [comment]
Ok looks like I introduced a NullRef exception that can happen occasionally. Reopening until I have a fix for it.

**Comment by kjnilsson** [comment]
PR submitted that should reduce the chances of a null ref exception.
