### ISSUE TITLE
Please add support for .NET Standard (.NET Core)

### ISSUE THREAD

**Issue by niemyjski** [rabbitmq/rabbitmq-dotnet-client#221]
This would allow us to use this library xplat.

**Comment by bording** [comment]
FYI, they're already working on it. Take a look at the master branch, and https://github.com/rabbitmq/rabbitmq-dotnet-client/issues/218#issuecomment-231431425

**Comment by michaelklishin** [comment]
@niemyjski see #148.

@bording it's already done. There is a NuGet feed of nightly builds and .NET Core support has been announced on our mailing list. We don't have a timeline for a non-snapshot release as .NET Core is far from being mature and so is our client on it.

**Comment by niemyjski** [comment]
thanks for the heads up!
