### ISSUE TITLE
BrokerUnreachableException on Mono 4.2

### ISSUE THREAD

**Issue by mattzink** [rabbitmq/rabbitmq-dotnet-client#234]
It appears that the rabbit client, as of 3.6.4, started to use a method that's not implemented in Mono <= v4.2:

`RabbitMQ.Client.Exceptions.BrokerUnreachableException: None of the specified endpoints were reachable ---> System.MissingMethodException: Method 'IPAddress.MapToIPv6' not found.`

While this method has been implemented in Mono 4.4.2, it is still a breaking change for those of us stuck on Mono 4.2 as connecting to any rabbit server fails.

**Comment by mattzink** [comment]
Looks like the changes in https://github.com/rabbitmq/rabbitmq-dotnet-client/pull/224 are related. Unfortunately, since call binding is baked at compilation time, adding an extension method with the same name as an instance method has no effect if the client is compiled under .NET (so this doesn't help those of us that get the package via NuGet), and only helps when the instance method doesn't exist at compile time, as when compiled manually under Mono.

If the extension method name was changed to something that doesn't match the instance method name, then it would be unambiguous and would work on both Mono and Windows.

**Comment by michaelklishin** [comment]
Sorry but supporting old Mono versions is not a priority. Our team is very small and we need to spend our time wisely.
