### ISSUE TITLE
v4.0.0 - CreateConnection() within WebAPI Controller

### ISSUE THREAD

**Issue by infinutrition** [rabbitmq/rabbitmq-dotnet-client#239]
The following code hangs at CreateConnection() when placed inside of a WebAPI endpoint using v4.0.0 of RabbitMQ.Client.  Confirmed it works with v3.6.5.  Further confirmed that the exact same code works when called in Application_Start but not in Application_BeginRequest using v4.0.0.

Using latest ASP.NET WebAPI/OWIN and .NET 4.6.1.  

           var factory = new ConnectionFactory
            {
                HostName = "localhost",
                UserName = "XXX",
                Password = "YYY"
            };

            string queueName = "ZZZ";

            var args = new Dictionary<string, object>();
            args.Add("x-dead-letter-exchange", "TTT");
            args.Add("x-dead-letter-routing-key", queueName);
            string message = "Current time: " + DateTime.Now.ToLongTimeString();

            using (var connection = factory.CreateConnection())
            using (var channel = connection.CreateModel())
            {
                channel.QueueDeclare(queueName, true, false, false, args);

                var body = Encoding.UTF8.GetBytes(message);

                channel.BasicPublish(exchange: "",
                    routingKey: queueName,
                    basicProperties: null,
                    body: body);
            }

**Comment by michaelklishin** [comment]
Please post a [traffic capture](http://rabbitmq.com/amqp-wireshark.html) with both versions.

**Comment by kjnilsson** [comment]
I suspect we may have fallen foul of the async/await deadlock problem when using task schedulers other than the default one. I will perform some additional testing using winforms and/or web api to see if I can replicate it.

**Comment by kjnilsson** [comment]
@infinutrition there is now a release candidate for 4.0.1 available on nuget.org for you to try: https://www.nuget.org/packages/RabbitMQ.Client/4.0.1-rc1

**Comment by infinutrition** [comment]
@kjnilsson Initial tests show that the 4.0.1 RC1 works, thank you both for the quick action.

**Comment by michaelklishin** [comment]
@infinutrition thank you for reporting it and helping us verify.
