### ISSUE TITLE
EventingBasicConsumer race condition possibility

### ISSUE THREAD

**Issue by svet93** [rabbitmq/rabbitmq-dotnet-client#242]
I was just looking through the code of the EventingBasicConsumer and noticed that when the even is Received is raised, no temp copy is used to prevent race condition.  According to [this ](https://msdn.microsoft.com/en-us/library/w369ty8x.aspx) article you should have a temporary copy of the delegate in order to avoid the possibility of a race condition if the last subscriber unsubscribes immediately after the null check and before the event is raised.

Example from the link above:

```
protected virtual void OnRaiseCustomEvent(CustomEventArgs e)
{
      // Make a temporary copy of the event to avoid possibility of
      // a race condition if the last subscriber unsubscribes
     // immediately after the null check and before the event is raised.
     EventHandler<CustomEventArgs> handler = RaiseCustomEvent;

    // Event will be null if there are no subscribers
    if (handler != null)
    {
        // Format the string to send inside the CustomEventArgs parameter
        e.Message += String.Format(" at {0}", DateTime.Now.ToString());

        // Use the () operator to raise the event.
        handler(this, e);
    }
}
```

Also [this](https://codeblog.jonskeet.uk/2015/01/30/clean-event-handlers-invocation-with-c-6/) article could be useful to see cleaner ways of dealing with the issue.

**Comment by michaelklishin** [comment]
We already do something similar in a bunch of places. Makes sense to me.
