### ISSUE TITLE
Getting Visual Studio working properly in the master branch

### ISSUE THREAD

**Issue by bording** [rabbitmq/rabbitmq-dotnet-client#243]
While looking at the master branch, I see you've got project.json files set up to support a .NET Core build from the command line, but you don't seem to currently have anything set up to work with the projects in Visual Studio now (xprojs and a solution file that references everything).

Would you mind if I opened a PR that got all of that working? If that's OK, what do you want to do with the WinRT projects and the ServiceModel project? I believe it should be possible to maintain WinRT compatibility by adding an additional framework target of netstandard1.1. Likewise, I think the ServiceModel project could be updated to xproj/project.json and just target 451.

On the other hand, if you don't care about supporting either of those in the 4.x releases, I can't just remove them.

**Comment by kjnilsson** [comment]
Hi,

A PR would be welcome. I've been using VS code up to now. I would only include RabbitMQ.Client, Unit and the Apigen projects in the solution file for now. 

If I've understood it correctly, netstandard1.1 is missing a bunch of important APIs like socket support. Instead I think we need a separate target for some kind of [portable profile](https://github.com/dotnet/corefx/blob/master/Documentation/architecture/net-platform-standard.md#portable-profiles). I tried this but never got it working with the current toolset. Again if we can get something working here that would also be welcome.

**Comment by michaelklishin** [comment]
`ServiceModel` should go in master but if we can get 4.x to be WinRT-compatible, we should give it a shot.
