### ISSUE TITLE
Clarify the noAck parameter of BasicConsume

### ISSUE THREAD

**Issue by jeremyVignelles** [rabbitmq/rabbitmq-dotnet-client#255]
When following the tutorial, I came across this line:

> Message acknowledgments are turned on by default. In previous examples we explicitly turned them off by setting the noAck ("no manual acks") parameter to true. It's time to remove this flag and send a proper acknowledgment from the worker, once we're done with a task.

This really bugs me. Indeed, the `noAck` option was set to `true` on the first example, but this option enables the acknowledgment instead of disabling it.

When looking for the documentation, I found [the java equivalent to this function](https://www.rabbitmq.com/releases/rabbitmq-java-client/v3.1.1/rabbitmq-java-client-javadoc-3.1.1/com/rabbitmq/client/Channel.html#basicConsume%28java.lang.String,%20boolean,%20java.lang.String,%20boolean,%20boolean,%20java.util.Map,%20com.rabbitmq.client.Consumer%29), where the parameter is named `autoAck`
- The parameter should be named `autoAck`, to keep aligned with the Java client
- The default value should be set to `true`
- The documentation should be updated.

**Comment by michaelklishin** [comment]
We won't be changing the default value but it was renamed in at least Java and Ruby clients (Bunny), so it makes sense.

What documentation specifically needs updating?

**Comment by jeremyVignelles** [comment]
The documentations that are using the `BasicConsume` method, so basically each consumer source codes.
There is also the quoted paragraph that is taken from the C# tutorial, part II.

This name change is breaking for the users that followed the tutorial and used the named parameter explicitely, so I would suggest to make this change in the next major release.

**Comment by michaelklishin** [comment]
@jeremyVignelles can you please be more specific? Links to rabbitmq.com doc pages or GitHub source files would be sufficient ;)

**Comment by jeremyVignelles** [comment]
http://www.rabbitmq.com/tutorials/tutorial-one-dotnet.html
http://www.rabbitmq.com/tutorials/tutorial-two-dotnet.html
http://www.rabbitmq.com/tutorials/tutorial-three-dotnet.html
http://www.rabbitmq.com/tutorials/tutorial-four-dotnet.html
http://www.rabbitmq.com/tutorials/tutorial-five-dotnet.html
http://www.rabbitmq.com/tutorials/tutorial-six-dotnet.html

(look for "`BasicConsume(`")

+ http://www.rabbitmq.com/tutorials/tutorial-two-dotnet.html at the paragraph that is quoted in my first post. "Message acknowledgments are turned on by default[...]"

**Comment by maxima120** [comment]
> noAck option was set to true on the first example, but this option enables the acknowledgment instead of disabling it.

so if I had noAck = true in previous version, does this mean I keep it the same ? autoAck = true ?

**Comment by jeremyVignelles** [comment]
If this is just a rename, as this issue asked for, then yes, `noAck = true` translates to `autoAck = true`

**Comment by maxima120** [comment]
I am checking in into the production.. so id like to know for sure :)

**Comment by michaelklishin** [comment]
noAck means "no manual acknowledgements", so, automatic mode.

**Comment by InsOpDe** [comment]
I find `autoAck` more comprehensible than `noAck`, as `noAck` could also mean that messages should not / cannot be ack'ed.

**Comment by michaelklishin** [comment]
We have renamed this argument to "auto ack" in at least three other clients. We can do it for this client for 7.0, please submit pull requests.

**Comment by DumboJet** [comment]
FYI:
Your documentation seems to need an update.
[Here](https://www.rabbitmq.com/direct-reply-to.html) you still mention this as a `no-ack`!
Which is weird, since you can always do the `ack` manually...
