### ISSUE TITLE
NullReferenceException in HeartbeatReadTimerCallback crashing application

### ISSUE THREAD

**Issue by MichaelLogutov** [rabbitmq/rabbitmq-dotnet-client#257]
We just got another application crashed due to RabbitMQ library:

`Application: Scheduler.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.NullReferenceException
  at RabbitMQ.Client.Framing.Impl.Connection.HeartbeatReadTimerCallback(System.Object)
  at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
  at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
  at System.Threading.TimerQueueTimer.CallCallback()
  at System.Threading.TimerQueueTimer.Fire()
  at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
  at System.Threading.ThreadPoolWorkQueue.Dispatch()`

I think that all exceptions inside separate RabbitMQ library threads should not propagate exceptions in any cases. If connection is down and auto recovery is not completed or failed, then Publish and Get methods should throw exceptions.

Anyway - what should I do now to stop RabbitMQ library from crashing my application?
We're using RabbitMQ 3.6.5.0

**Comment by kjnilsson** [comment]
Hi, which version of the dotnet client are you using?

**Comment by kjnilsson** [comment]
Could you try the latest version of the client (currently 4.1.0)?

**Comment by MichaelLogutov** [comment]
Will do. Thanks.

**Comment by kjnilsson** [comment]
There may be a fix in [this](https://github.com/rabbitmq/rabbitmq-dotnet-client/commit/7b1f65cb545239235dbdd4aa9c9a9aed594cae22) commit.

**Comment by michaelklishin** [comment]
First of all, there is no such RabbitMQ version as `3.6.5.0`. What *.NET client library version* is used?

**Comment by MichaelLogutov** [comment]
https://www.nuget.org/packages/RabbitMQ.Client/3.6.5

**Comment by MichaelLogutov** [comment]
We've updated to 4.1.0 and got hit with the same crash this night:

`Application: Scheduler.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.NullReferenceException
   at RabbitMQ.Client.Framing.Impl.Connection.HeartbeatReadTimerCallback(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.TimerQueueTimer.CallCallback()
   at System.Threading.TimerQueueTimer.Fire()
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()`

**Comment by kjnilsson** [comment]
@MichaelLogutov ok, looks like there is still an issue somewhere. Can you give a bit more details on how it is being used? Some kind of minimal repro obviously would be fantastic :)

**Comment by MichaelLogutov** [comment]
We're creating connection when application start using IConnectionFactory.CreateConnection:
`var connection = this.connectionFactory.CreateConnection();
connection.AutoClose = false;`

And then we're using CreateChannel:
`
            var channel = connection.CreateModel();

            if (this.configuration.PublishConfirmTimeout > TimeSpan.Zero)
                channel.ConfirmSelect();

            return channel;
`

And Publish or BasicGet:
`
channel.BasicGet(queue: queueName, noAck: false)
`

The most curious thing is that this crash occurred in application that should not publish or receiving messages - and thus does not creates any channels. I could be wrong (it's really big solution and some part of it underneath can use queue to publish something) but maybe RabbitMQ.Client library spins some thread at any case?

**Comment by kjnilsson** [comment]
After looking at the code I could see one potential null ref scenario so have covered that in the linked PR.

**Comment by kjnilsson** [comment]
@MichaelLogutov if you want to test out the potential fix right away you could grab the latest package from AppVeyor (package feed: https://ci.appveyor.com/nuget/rabbitmq-dotnet-client-ci
). They are a bit confusingly versioned 4.0.0.x but do represent the latest master commits.

**Comment by michaelklishin** [comment]
We will re-trigger a build so that the version is a more sensible 4.1.0.x`.

**Comment by MichaelLogutov** [comment]
Thanks guys. Unfortunately I'm unable to install it.
I've added source:
`nuget sources add -Name rabbitmq -Source https://ci.appveyor.com/nuget/rabbitmq-dotnet-client-ci`

But I can't find the package:
```
C:\>nuget list -source rabbitmq
FAKE 4.25.5
NuGet.CommandLine 3.4.3
```

**Comment by kjnilsson** [comment]
You may need to enable listing of pre-releases.

**Comment by MichaelLogutov** [comment]
Yeah, I found it with "pre" flag but now I can't update it due to other packages referencing higher version than 4.0

**Comment by michaelklishin** [comment]
@MichaelLogutov we've bumped [AppVeyor minor version to 4.1.0](https://ci.appveyor.com/project/rabbitmq/rabbitmq-dotnet-client).

**Comment by kjnilsson** [comment]
Looks like the AppVeyor needs another tweak somewhere before it will version it correctly. Will take a look today.

**Comment by kjnilsson** [comment]
@MichaelLogutov you could try it now.

**Comment by michaelklishin** [comment]
[4.1.1-rc1](https://www.nuget.org/packages/RabbitMQ.Client/4.1.1-rc1) is now up on nuget.org.

**Comment by MichaelLogutov** [comment]
Thanks guys. I'm a bit overwhelmed with work on Monday. Will try it soon.

**Comment by MichaelLogutov** [comment]
Ok, we've updated yesterday all our tasks and for now it seems to work without crashes. But it was only one night.

**Comment by kjnilsson** [comment]
Thanks for testing. Let's leave it a couple of more days and see if the error re-occurs.

**Comment by tr00Hlodvig** [comment]
Have the same issue in rmq client version 3.6.5. Unfortunately I can't use 4.1.0 since we use .Net framework 4.5

**Comment by michaelklishin** [comment]
Please collect profiler data and traffic captures with both
versions and post them to the list.
Supporting .NET 4.5.0, 3.6.x client versions and QueuingBasicConsumer is not a priority for our small team so no promises but maybe it's something easy to dig out.

**Comment by michaelklishin** [comment]
Posted a comment here while thinking of a different thread. This change is small and possibly can be easily back ported for `3.6.6`.

**Comment by michaelklishin** [comment]
Back ported to `stable`, it will be in `3.6.6`.

**Comment by dove** [comment]
@michaelklishin  thanks for porting back to 3.6.6.  I can't upgrade until easynetq is ready for RabbitMQ 4.

**Comment by MatthewB2407** [comment]
@michaelklishin  

I was getting this error in 3.6.5.

If I'm not missing anything the fix was to upgrade to 3.6.6?

I've done this but getting the same error.

Can anyone help?

Thanks in advance

**Comment by dove** [comment]
@MatthewB2407 it did the trick for me.  maybe just double check you've got 3.6.6 and note any bindingredirects that might need to be updated.

**Comment by MatthewB2407** [comment]
@dove thanks for the response.

I'm very sure I've got 3.6.6 and just check any bindinredirects are correct.

Every time I deploy the RabbitMQ client onto our live server it crashes with the following:

Exception: System.NullReferenceException

Message: Object reference not set to an instance of an object.

StackTrace:    at RabbitMQ.Client.Framing.Impl.Connection.HeartbeatReadTimerCallback(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.TimerQueueTimer.CallCallback()
   at System.Threading.TimerQueueTimer.Fire()
   at System.Threading.TimerQueue.FireNextTimers()

**Comment by michaelklishin** [comment]
Team RabbitMQ does not use issues for questions or discussions or investigations. We don't have any information about how you deploy the client, what your environment is like, and so on. All we know is that this issue is a natural race condition and while without producing a TLA+ model of much of this client we cannot be 100% sure is no longer present, this iss is no longer being commonly reported by 3.6.6 or 4.x client users.

Please take this to rabbitmq-users and provide more details. Considering upgrading to `4.x` releases of this client, too, since `3.6.x` will soon be approaching the end of its development.
