### ISSUE TITLE
NuGet package not fully compatible with framework 4.5

### ISSUE THREAD

**Issue by Phoenix1271** [rabbitmq/rabbitmq-dotnet-client#262]
Packages for RabbitMQ.Client >= 4.0.0 are targeting .NET framework 4.5.1 which effectively breaks upgrade process for any project that references .NET 4.5 or .NET 4.5.2. Please fix this issue by setting target framework to 4.5 for next release.

**Comment by michaelklishin** [comment]
The intent was to target 4.5.1+, I believe.

**Comment by kjnilsson** [comment]
The version bump was explained in the [release announcement](https://groups.google.com/forum/#!searchin/rabbitmq-users/dotnet$204.0%7Csort:relevance/rabbitmq-users/hyJLlXCbocY/IEWxno3oAwAJ)

If you need 4.5 please use the 3.6.x releases. I don't see how it breaks 4.5.2 - 4.5.1 can be used with any higher version.
