### ISSUE TITLE
TcpClient/Socket objects disposed but still exist in memory

### ISSUE THREAD

**Issue by sungam3r** [rabbitmq/rabbitmq-dotnet-client#263]
Memory dump of our running app shows something like this:

![11](https://cloud.githubusercontent.com/assets/21261007/19237782/36461c3e-8f07-11e6-8d46-f3b2882a2f4a.PNG)

Both TcpClient and Socket objects have already been disposed, but still in memory referenced by TcpClientAdapter. TcpClientAdapter has private TcpClient / Socket field (depends of rabbitmq-dotnet-client version) which closed (disposed) in TcpClientAdapter.Close() method. We can consider this situation as memory leak with non-growing memory overhead.

![12](https://cloud.githubusercontent.com/assets/21261007/19238758/af033bc6-8f0b-11e6-9e21-01f6b73a6a51.PNG)

It's annoying to have those broken and unused objects (with all inner object trees, e.g. byte arrays or ManualResetEvents) in memory and in profiler reports. These objects prevent from investigation real memory leaks.

Please, consider to break reference to TcpClient / Socket in TcpClientAdapter after Close() call.
Maybe, it's better to break reference a bit higher in call stack, e.g. SocketFrameHandler class.

**Comment by kjnilsson** [comment]
We can certainly null the socket field in the Close method of `TcpClientAdapter`. What is the scenario where you are holding onto the Connection object after it has been closed?

**Comment by sungam3r** [comment]
We use EasyNetQ library and just call RabbitHutch.CreateBus and then Publish / Subscribe methods. App uses 6 RabbitAdvancedBus instances at the same time, serving 6 rpc-request and around 20-40 rpc-response queues.

**Comment by sungam3r** [comment]
Why do you think that the Connection object has been closed?

**Comment by kjnilsson** [comment]
If the socket and TcpClientAdaptor have already been disposed why keep the Connection instance around? IIRC EasyNetQ doesn't use the AutorecoveringConnection so not sure what the scenario is where the socket has been disposed but the Connection is still somehow in use.

**Comment by sungam3r** [comment]
Indeed, connection is closed (m_closed = true). But EasyNetQ really holds reference to Model object, which in turn holds reference to closed Connection.

**Comment by sungam3r** [comment]
![13](https://cloud.githubusercontent.com/assets/21261007/19270731/1c494586-8fca-11e6-91ff-6cd634a51c4e.png)

**Comment by kjnilsson** [comment]
May be worth getting onto the EasyNetQ maintainers and ask them to clean up after connection close.

**Comment by sungam3r** [comment]
May be, but it is good practice to break clearly known references to dead objects trees in own code. It protects from improper external use (as EasyNetQ does) and reduces memory footprint.

**Comment by michaelklishin** [comment]
We can do both ;)

**Comment by sungam3r** [comment]
Thank you! I will continue to investigate improper memory usage in EasyNetQ code.
