### ISSUE TITLE
RABBITMQ_LONG_RUNNING_TESTS is not set during CI

### ISSUE THREAD

**Issue by michaelklishin** [rabbitmq/rabbitmq-dotnet-client#276]
[Example build log](https://ci.rabbitmq.com/teams/main/pipelines/dotnet/jobs/test-rabbitmq-dotnet-client-pr/builds/49). So at least one test case is skipped.

**Comment by kjnilsson** [comment]
OK this has now been enabled in the dotnet concourse build as should be visible [here](https://ci.rabbitmq.com/teams/main/pipelines/dotnet/jobs/rabbitmq-dotnet-client/builds/67).
