### ISSUE TITLE
When compiled with NETFX_CORE, the enabled StreamSocket usage causes differing behavior when in an environment with a proxy enabled

### ISSUE THREAD

**Issue by CassOnMars** [rabbitmq/rabbitmq-dotnet-client#280]
In projects/client/RabbitMQ.Client/src/client/api/ConnectionFactoryBase.cs and many other places, added in commit 7c1a7d757dd62c184e8bbfd73288eccf465b4d05 (Added WinRT (Windows 8) compatible library, sharing code where possible.), the client now has support enabled for StreamSocket in .NET versions supporting the symbol NETFX_CORE. The problem with this is that StreamSocket by default transparently uses proxy settings defined in Internet Options, and does not provide a way to disable this, producing divergent behavior from environments where NETFX_CORE is not supported, and breaks environments where a proxy exists that upgraded the client from a version before this commit. See [here](https://social.msdn.microsoft.com/Forums/en-US/6b949fc2-db42-428a-84c3-3e0e37210ec5/why-does-streamsocketconnectasync-set-up-two-tcp-connections-when-proxy-is-configured-in-system?forum=winappswithnativecode) for discussion on this.

**Comment by kjnilsson** [comment]
do you suggest we expose a way to set `StreamSocketControl.SerializeConnectionAttempts`?

**Comment by michaelklishin** [comment]
@kjnilsson was this addressed by https://github.com/rabbitmq/rabbitmq-dotnet-client/commit/44544ba97c591ad1ecb78954e238c69fbe9e844f or they aren't related?

**Comment by kjnilsson** [comment]
I _think_ this is unrelated and specific to winrt.

**Comment by kjnilsson** [comment]
@drheart do you suggest we expose a way to set `StreamSocketControl.SerializeConnectionAttempts`?

**Comment by lukebakken** [comment]
`NETFX_CORE` no longer exists as a define, so I'll assume this issue no longer applies.
