### ISSUE TITLE
Issue on removing connection while closing Application.

### ISSUE THREAD

**Issue by PritamUpadhyay** [rabbitmq/rabbitmq-dotnet-client#29]
I am using .NET RabbitMQ Client library. I want to develop a messaging system. For this, I have implemented all necessary methods of RabbitMQ. Moreover I have to develope dispose() for removing connection from RabbitMQ as connection is not removed automatically. I am calling this method in FormClosing() event so this method will be triggered when user closes the application by clicking on close button and by the logic connection will be removed. Up to this, all code is working perfectly.
 
The problem is,
Calling a dispose() to remove connection explicitly is bad practice so i don’t want to use dispose(). I'm not able to remove any connection at the time of closing the application without triggering dispose(). Connection remains into RabbitMQ.
 
Question:
 
How to remove this connection from RabbitMQ without calling dispose() explicitly?

**Comment by michaelklishin** [comment]
This repository is currently a mirror. Please post questions to rabbitmq-users.
