### ISSUE TITLE
Error connecting over SSL

### ISSUE THREAD

**Issue by jondunning** [rabbitmq/rabbitmq-dotnet-client#30]
Hi,

Ive been trying to connect to my rabbitmq broker using SSL but I keep getting the following exception;

"A call to SSPI failed"

    var connectionFactory = new ConnectionFactory()
                {
                    HostName = {hostname},
                    Port = 5671,
                    UserName = "guest",
                    Password = "guest",
                    AuthMechanisms = new AuthMechanismFactory[] {new ExternalMechanismFactory()},
                    Ssl = new SslOption
                    {
                        Enabled = true,
                        ServerName = {hostname},
                        Version = SslProtocols.Tls12,
                        AcceptablePolicyErrors = SslPolicyErrors.RemoteCertificateNameMismatch |
                                                 SslPolicyErrors.RemoteCertificateChainErrors,
                    },
                };                

                using (IConnection conn = connectionFactory.CreateConnection())
                {
                   .....
                }

Ive found this;

http://lists.rabbitmq.com/pipermail/rabbitmq-discuss/2013-November/031709.html

Not sure what the correct approach is to get this working. Ive written the same code in Java and it connects to my broker fine. My colleague has also posted this on stackoverflow.

Can anyone point me in the right location? 

Thanks,

Jon

**Comment by michaelklishin** [comment]
This repository is currently a mirror. The same issue is [already reported](https://groups.google.com/forum/#!topic/rabbitmq-users/MUC7-ObGBKc) to rabbitmq-users.

**Comment by michaelklishin** [comment]
We had to revert this change (#44, #45) because it does more harm than good. I've noticed that you use external authentication without client certificate. Is this intentional? This makes little sense to me.

I've filed a new issue to investigate an alternative solution: #46.

**Comment by michaelklishin** [comment]
Added a test in cb2b6d22ca5f64204902c24557adf02aa85c8be6. Closing #46.
