### ISSUE TITLE
Update remote procedure call (RPC) tutorial to work without deprecated QueueingBasicConsumer

### ISSUE THREAD

**Issue by mattqs** [rabbitmq/rabbitmq-dotnet-client#300]
QueueingBasicConsumer has been deprecated, but remote procedure call (RPC) tutorial https://www.rabbitmq.com/tutorials/tutorial-six-dotnet.html is still using QueueingBasicConsumer.

  Could the existing tutorial be updated? Or is there another remote procedure call (RPC) tutorial that shows how to do this without QueueingBasicConsumer? 

  I could try to come up with something myself, but I'm not an expert in rabbitmq and don't want to waste a great deal of time or effort in creating something that already exists.

**Comment by michaelklishin** [comment]
This belongs to https://github.com/rabbitmq/rabbitmq-tutorials/issues/112.

**Comment by michaelklishin** [comment]
@mattqs it can but no promises on when that might happen.

**Comment by mattqs** [comment]
The tutorials code https://github.com/rabbitmq/rabbitmq-tutorials/blob/master/dotnet/RPCServer/RPCServer.cs already uses `EventingBasicConsumer` . It is only the wordpress text that is showing the deprecated code.

**Comment by michaelklishin** [comment]
What Wordpress text?

**Comment by mattqs** [comment]
The document that can be found at
https://github.com/rabbitmq/rabbitmq-website/blob/live/site/tutorials/tutorial-six-dotnet.md

**Comment by michaelklishin** [comment]
It does not use Wordpress but OK, I will sync it up.
