### ISSUE TITLE
Implement TCP back pressure for consumer deliveries

### ISSUE THREAD

**Issue by or150** [rabbitmq/rabbitmq-dotnet-client#301]
Whenever a IBasicConsumer handles the messages too slowly and cannot keep up with delivery rate, the client's work pool starts getting filled with messages and may consume a lot of memory under heavy load.

A simple repro of the problem:
```csharp
using RabbitMQ.Client;
using RabbitMQ.Client.Events;

namespace RabbitMqBug
{
    class Program
    {
        static void Main(string[] args)
        {
            var factory = new ConnectionFactory()
            {
                HostName = "localhost",
                WorkPoolCapacity = 0
            };

            var connection = factory.CreateConnection();
            var model = connection.CreateModel();
            var consumer = new EventingBasicConsumer(model);
            consumer.Received += (s, e) =>
            {
                while (true)
                {

                }
            };
            model.QueueDeclare("TEST");
            model.BasicConsume(consumer, "TEST", true);

            model.ExchangeDeclare("TEST", ExchangeType.Direct);
            model.QueueBind("TEST", "TEST", "TEST");
            while (true)
            {
                model.BasicPublish("TEST", "TEST", body: new byte[100]);
            }
        }
    }
}
```

**Comment by michaelklishin** [comment]
This is not a memory leak but rather the classic producer-consumer problem where producer outpaces consumer. This was addressed in Java client in https://github.com/rabbitmq/rabbitmq-java-client/issues/19 and a similar solution might work for this client.

There is a "workaround": use [manual acknowledgements](http://www.rabbitmq.com/confirms.html) and a suitable channel QoS prefetch.

**Comment by michaelklishin** [comment]
As @bording points out in #302, it's going to be tough to solve this and keep the improvements from #253 around, so perhaps the answer should be "use manual acknowledgements."

We can also make it possible to provide a a custom consumer work pool implementation.

**Comment by kjnilsson** [comment]
As it is fairly risky to make a change in the current client we will try to address this issue in the planned new client.

**Comment by thyams** [comment]
I just wanted to chime in since it's been awhile since the last message. micro tweaking the prefetch count and manual acknowledge greatly helped it preventing any performance.  Keeping the consumer utilization between 95-99% (monitored at the HTTP API) and not 100% made all the difference in the world with a looped publisher.

The one thing I would add is to publish many in bat hes with await Task.Delay(Rand.Next(0,2)); instead of a plain foreach payload, publish.

This was

**Comment by lukebakken** [comment]
Reading the comments it appears that workarounds exist using the existing client.
