### ISSUE TITLE
Support ArraySegment bodies in BasicPublish

### ISSUE THREAD

**Issue by Astomat** [rabbitmq/rabbitmq-dotnet-client#303]
Hello,
It will be very helpful to have the ability to receive ArraySegment<byte> body in BasicPublish method.
I have many cases in which memory needs to copied in order to build the proper body byte array instead of just defining a segment in byte array buffers.
Another posibility is to accecpt offset and length in addition to body byte array.

Thanks,
Astomat

**Comment by michaelklishin** [comment]
@kjnilsson sounds like a new override we can safely introduce? thoughts?

**Comment by kjnilsson** [comment]
Sounds like a good idea. There may be a few changes to make for this but definitely worth investigating.

**Comment by stebet** [comment]
It would be smart to also allow using Memory<byte>. To utilize memory pooling/recycling efficiently another one using [IMemoryOwner ](https://docs.microsoft.com/en-us/dotnet/api/system.buffers.imemoryowner-1)(supported in the System.Memory NuGet packages for .NET Framework) making it possible to often avoid memory copies (almost entirely when pipelines are introduced) when publishing.

**Comment by lukebakken** [comment]
I think it's safe to assume that #706 and other improvements in version `7.0.0` will address this issue.
