### ISSUE TITLE
ConnectionFactory does not support HA active/passive scenario

### ISSUE THREAD

**Issue by alfein** [rabbitmq/rabbitmq-dotnet-client#305]
When using ConnectionFactory with multiple endpoints in a HA active/passive scenario I specify several AmqpTcpEndpoint instances with one for every broker host in the cluster.  One of then is MASTER and others are REPLICAs.

Client randomly chooses an endpoint to use.  When it picks a replica - connection fails at startup - it will not try others.

PS.  I am running a QPID server, not Rabbit, but AMQP should be a standard thing, I think.

**Comment by michaelklishin** [comment]
[Yes, it does](https://github.com/rabbitmq/rabbitmq-dotnet-client/blob/master/projects/client/RabbitMQ.Client/src/client/api/IConnectionFactory.cs#L116) support multiple endpoints but connects only to one node at a time. There are no plans to change this.

**Comment by michaelklishin** [comment]
Initial connection failures are not retried because they are trivial to handle and re-try. Automatic connection recovery will try all hosts until one of them is reachable. This is by design.

There are no master and replicate nodes in RabbitMQ. Queues have a master and zero or more mirrors but all nodes are identical.

**Comment by michaelklishin** [comment]
@alfein and it's quite trivial to catch the exception and retry. Things work the way you want during connection recovery, which happens concurrently to application activity and thus can be considered "unsupervised."

**Comment by alfein** [comment]
Agree -  I did it, but need your help making it clearner  - more encapsulated.

**Comment by alfein** [comment]
Помогите пожалуйста

**Comment by kjnilsson** [comment]
@alfein Ideally I'd like not to expose any more state. The client _should_ try other endpoints after an initial failed attempt as demonstrated by [this](https://github.com/rabbitmq/rabbitmq-dotnet-client/blob/master/projects/client/Unit/src/unit/TestConnectionFactory.cs#L203) test. 

Can you supply a bit more info on the actual issue? What exception is thrown for the attempt at connecting to a mirror? Which version of the RabbitMQ client are you using? How does QPid work when you attempt to connect to a replica? Does the connection succeed then QPid shuts the connection or is there simply nothing listening on the port?

**Comment by alfein** [comment]
@kjnilsson, the TCP connection succeeds but QPID broker closes it after because virtual host is not reachable.

**Comment by kjnilsson** [comment]
Does the broker write anything to the connection before closing it?

**Comment by alfein** [comment]
Yes. Need to get back to you with details I am not at the pc at the moment.

**Comment by alfein** [comment]
Before I get to you can you change your unit test to point to localhost but with a different port?  If you are running a rabbit server locally during unit tests perhaps an http admin port?  DNS resolution failure may be ok but a deeper connection failure may not.

**Comment by kjnilsson** [comment]
The current code works with any connection failure at the point of connection. It (probably) won't handle the scenario where the TCP connection first succeeds but the broker then closes it. It would be useful to see a tcpdump/wireshark capture here to see exactly what the QPid broker does when you try to connect to a replica.

**Comment by alfein** [comment]
iIRC. The exception happens inside GetReply method of some protocol handler.  It's raised as an invalidoperationexception and wrapped inside BrokerNotReachableException before getting rethrown

**Comment by kjnilsson** [comment]
Right. Earlier than I thought. What version of the client are you using?

**Comment by alfein** [comment]
5.0.0-r2. Needed to set the addressfamily on the AmqpTcpEndpoint

**Comment by kjnilsson** [comment]
A wireshark capture and the full exception stack trace would be very useful for me to continue investigations.

**Comment by alfein** [comment]
After about a hour - in transit now.

**Comment by alfein** [comment]
OK Exception message:
The AMQP operation was interrupted: AMQP close-reason, initiated by Peer, code=320, text="Virtual host 'host1' is not active", classId=10, methodId=40, cause=

   at RabbitMQ.Client.Impl.SimpleBlockingRpcContinuation.GetReply(TimeSpan timeout)
   at RabbitMQ.Client.Impl.ModelBase.ConnectionOpen(String virtualHost, String capabilities, Boolean insist)
   at RabbitMQ.Client.Framing.Impl.AutorecoveringConnection.Init(IFrameHandler fh)


RabbitMQ.Client.Exceptions.BrokerUnreachableException: None of the specified endpoints were reachable ---> RabbitMQ.Client.Exceptions.OperationInterruptedException: The AMQP operation was interrupted: AMQP close-reason, initiated by Peer, code=320, text="Virtual host 'host1' is not active", classId=10, methodId=40, cause=
   at RabbitMQ.Client.Impl.SimpleBlockingRpcContinuation.GetReply(TimeSpan timeout)
   at RabbitMQ.Client.Impl.ModelBase.ConnectionOpen(String virtualHost, String capabilities, Boolean insist)
   at RabbitMQ.Client.Framing.Impl.AutorecoveringConnection.Init(IFrameHandler fh)
   at RabbitMQ.Client.ConnectionFactory.CreateConnection(IEndpointResolver endpointResolver, String clientProvidedName)
   --- End of inner exception stack trace ---
   at RabbitMQ.Client.ConnectionFactory.CreateConnection(IEndpointResolver endpointResolver, String clientProvidedName)


//Endpoints
  var endpoints = new List<AmqpTcpEndpoint>()
            {
                new  AmqpTcpEndpoint()
                {
                     AddressFamily = AddressFamily.InterNetwork,
                     HostName =  "our-host2", //faking host name, which is a valid hostname originally
                     Port = 5671,
                     Ssl = new SslOption()
                    {
                        Enabled = true,
                        ServerName = "cname-on-cert",
                        Version = System.Security.Authentication.SslProtocols.Tls12
                    },
                },
                new  AmqpTcpEndpoint()
                {
                     AddressFamily = AddressFamily.InterNetwork,
                     HostName =  "our-host1", //faking host name, which is a valid hostname originally
                     Port = 5671,
                     Ssl = new SslOption()
                    {
                        Enabled = true,
                        ServerName = "cname-on-cert",
                        Version = System.Security.Authentication.SslProtocols.Tls12
                    },
                }

**Comment by michaelklishin** [comment]
So the server does send a `connection.close`. This is very different semantically from a TCP connection failure. Recovering from server-sent `connection.close` unconditionally is a bad idea: that's how you get zombie clients that just wouldn't die even if you force disconnect them.
Some clients have a setting that lets you opt-in and recover from `connection.close` but none do this during initial connection.

I'm not sure what "virtual host is not active" means exactly in Qpid but either it's a vhost permission problem or something Qpid-specific. In the former case it makes little sense to retry as it's a misconfiguration. In the latter case I'm not sure how much time we'd like to invest into supporting Qpid-specific errors.

**Comment by alfein** [comment]
The virtual host is not active is a message that you get from QPID when virtual node you are connected to is setup as a replica - not MASTER. Replica nodes cannot accept connections.  The broker accepts the TCP connection, but after the client requests a certain virtual host - the broker sends the message and disconnects.

It's OK if you don't want to take the risk of complexity and support this on your end.  Please make some private members as protected and let me take the risk of this on initialization. 

Thanks

**Comment by michaelklishin** [comment]
Right, which is not an error or scenario the AMQP 0-9-1 spec mentions.

@kjnilsson I think making a few methods overridable but not public is fine. Would you agree to that?

**Comment by kjnilsson** [comment]
Ok let me have a think how to best approach it. @alfein how did you envisage handling it if the requested methods where made virtual/protected? 

One approach may be to implement a custom `IEndpointResolver` that always returns the endpoints in the order they were provided (Given three nodes [A, B, C] it first returns A, then B then C). Then you could wrap your call to `CreateConnection` in some code that catches the exception and for each attempt shuffles the endpoint list such that the first attempt is given [A, B, C] and tries A. If this attempt fails you pass the endpoints in order [B, C, A], then [C, A, B].

It is a bit of a work-around but I think it could work relatively nicely. You could also leave the default randomly selected `IEndpointResolver` in place and just retry until it finds an appropriate node.

**Comment by alfein** [comment]
@kjnilsson 

1. Make Init a virtual method - let me override it
2. Allow me to set "endpoints" field of AutorecoveringConnection from derived class
3. allow me to call Init(IFrameHandler) method in AutorecoveringConnection from derived class
3. inside my ConnectionFactory.Init() override, I would create a class that derives from AutorecoveringConnection  
4. My AutorecoveringConnection  class would have a method to set the "endpoints" field and do a foreach on the endpoints 

Poor man's version of the new InitTryAll method

   Exception lastEx = null;
            foreach(var fh in endpoints.All().Select(m_factory.CreateFrameHandler))
            {
                try
                {
                    init(fh);
                    return;
                }
                catch(Exception ex)
                {
                    if (ex.InnerException == null)
                    {
                        lastEx = ex;
                    }
                    else
                    {
                        lastEx = ex.InnerException;
                    }
                }
            }
            throw lastEx;

**Comment by kjnilsson** [comment]
That sounds a lot more complicated that what I suggested above. Any particular reason you can't just wrap the call to `CreateConnection` as I suggested above?

**Comment by michaelklishin** [comment]
The goal of encapsulation is a noble and useful one until it's not. Sorry but we are dealing with something that's not a RabbitMQ problem, something that's not mentioned in the spec, and something that would not improve encapsulation of this client. It's a bit difficult to justify non-trivial internal changes that would only benefit one particular application.

**Comment by alfein** [comment]
@kjnilsson, @michaelklishin 

OK.

**Comment by alfein** [comment]
@kjnilsson, your solution worked well and is elegant too. 

Thank you.

**Comment by kjnilsson** [comment]
Glad to hear it. Good luck.
