### ISSUE TITLE
TLS Issues with dotnet core on Debian

### ISSUE THREAD

**Issue by dbason** [rabbitmq/rabbitmq-dotnet-client#306]
Hi,

We are currently using the dotnetcore docker image (which is based on Debian) and trying to connect to a broker with TLS.  We have installed the CA into the docker image as part of the build:
```
COPY ca.crt /usr/local/share/ca-certificates/ca.crt
RUN update-ca-certificates
```

And confirmed that we can connect on TLS to the RabbitMQ management console from inside the container (using curl) however when we try to connect with the AMQP client we get errors:
```
2017-02-02T00:05:53.588444400Z =ERROR REPORT==== 2-Feb-2017::00:05:53 ===
2017-02-02T00:05:53.588459700Z SSL: certify: ssl_connection.erl:456:Fatal error: handshake failure
```

Has anyone else had similar experience on dotnetcore on Linux?

**Comment by dbason** [comment]
It's also worth pointing out that from the Linux container openssl s_client connections work, and connections to the broker work from the Windows client, and from a different nodejs client.  The issue seems to be that CA list isn't getting picked up in Linux.

**Comment by dbason** [comment]
Closing this because the mailing list seems a better place for it

**Comment by michaelklishin** [comment]
@dbason thank you for moving it to rabbitmq-users. FTR, here's [the thread](https://groups.google.com/forum/#!topic/rabbitmq-users/a5HIyM1VPY4). The conclusion so far is that it's a problem with .NET Core on Linux, as other clients on Linux and .NET Core clients on Windows can successfully connect. Also, disabling peer verification makes the problem go away.
