### ISSUE TITLE
Best way to close a Connection object shared across threads

### ISSUE THREAD

**Issue by aaron-horst** [rabbitmq/rabbitmq-dotnet-client#31]
I have a .net console that delivers a high volume of messages to RabbitMQ that shares a Connection object across all threads.  What are the suggested practices for closing the connection at the end of execution?  We notice the console will not exit until the connection is explicitly closed.  Setting AutoClose = true after channel creation tears down at inconsistent points so perhaps we are missing an additional setting.

**Comment by michaelklishin** [comment]
This repository is a mirror. Please post questions to rabbitmq-users.

**Comment by PritamUpadhyay** [comment]
Are you implementing using(){ } block?
e.g
 using (IConnection connection = connectionFactory.CreateConnection())
{
                    using (IModel model = connection.CreateModel())
                    {
                       IBasicProperties basicProperties = model.CreateBasicProperties();
                       basicProperties.Headers = new Dictionary<string, object>();
                       basicProperties.Headers.Add("CC", routingkey);
                       basicProperties.Headers.Add("APP_KEY", ExchangeName);
                        byte[] Message = new byte[MessageSize];
                        while (true)
                        {
                            model.BasicPublish(ExchangeName,routingkey,basicProperties, Message);
                        }
                    }
}
