### ISSUE TITLE
Lower .NET Standard to 1.4

### ISSUE THREAD

**Issue by alexdrl** [rabbitmq/rabbitmq-dotnet-client#311]
Hello, we need to reference to this library for some .NET Standard 1.4 library. We target 1.4 for making seamless the migration to .NET Standard 2.0.

I have cloned the repo locaaly in VS 2017 and lowered the .NET Standard from 1.5 to 1.4. The unique compilation errors are located in SocketFrameHandler.cs with the use of BufferedStream. With this BufferedStream removed and accesing only the netstream variable I can build the library to .NET Standard 1.4. I am going to test the library if it works, but to my knowledge this should be no problem.

Can someone verify if this change is valid? Maybe I could submit a pull request when the project system of the library is updated to VS 2017... :smile:

**Comment by michaelklishin** [comment]
`SocketFrameHandler` should be functional without buffering but it will be less efficient, potentially significantly so.

Sorry but we aren't interested in supporting older .NET Standard versions. .NET Core and .NET Standard are still far from being mature and the only way for those who were adventurous enough to adopt it is forward.

**Comment by alexdrl** [comment]
Obviously I understand your case... but maybe the generated NuGet package could target 1.4 (without BufferedStream) and 1.5 (with BufferedStream), and resolve the differences with conditional compilation.

If I understand it correctly, with .NET Standard 1.4 we could target this library with no modifications from full .NET and UWP (WinRT)

Anyways, thanks to OSS :smile: I will be able to modifiy this library to my needs, only changing the necessary lines of code and knowing the consequences...

**Comment by michaelklishin** [comment]
Regular .NET 4.5.2+ is supported by this client. WinRT used to be supported but we are not actively working on it.

**Comment by adamralph** [comment]
> We target 1.4 for making seamless the migration to .NET Standard 2.0.

At one time, MS did say that .NET Standard 2.0 would be breaking with respect to .NET Standard 1.5 and 1.6, but they back-tracked on this and decided to make .NET Standard 2.0 non-breaking instead.

**Comment by michaelklishin** [comment]
@adamralph thank you for chiming in!

**Comment by alexdrl** [comment]
@adamralph Wow, we did not know that. Thank you!
