### ISSUE TITLE
Consider moving ConnectionFactory.SetUri to an exetension method on IConnectionFactory

### ISSUE THREAD

**Issue by paulomorgado** [rabbitmq/rabbitmq-dotnet-client#312]
If [`SetUri`](https://github.com/rabbitmq/rabbitmq-dotnet-client/blob/master/projects/client/RabbitMQ.Client/src/client/api/ConnectionFactory.cs#L516) was an extension method on `IConnectionFactory`, it would be easier to test code by having a dependency on `IConnectionFactory` instead of `ConnectionFactory`.

**Comment by michaelklishin** [comment]
@paulj please submit a PR against master. I don't have any objections to doing this for 5.0. @kjnilsson you?

**Comment by kjnilsson** [comment]
We can make SetUri and extension property as the methods/properties it would need to operation are marked as Obsolete (e.g. `ConnectionFactory.Uri`). We could instead add it to `IConnectionFactory` instead which should help with testing.
