### ISSUE TITLE
ExchangeBind problem impacts more versions than initial testing revealed

### ISSUE THREAD

**Issue by bording** [rabbitmq/rabbitmq-dotnet-client#317]
So it looks like the problem I found in #314 is more widespread than my initial testing led me to believe.

In the master branch, `AutomaticRecoveryEnabled` is `true` by default, and I forgot to manually set that to true when testing. 😦

Revised repro:

```csharp
var factory = new ConnectionFactory();
factory.AutomaticRecoveryEnabled = true;

var connection = factory.CreateConnection();
var channel = connection.CreateModel();

channel.ExchangeDeclare("test1", ExchangeType.Fanout);
channel.ExchangeDeclare("test2", ExchangeType.Fanout);

channel.ExchangeBind("test1", "test2", "");
channel.ExchangeBind("test1", "test2", ""); //this throws
```

Here is the result of my testing:
```
3.6.6: works
3.6.7: broken
3.6.8: broken

4.1.1: works
4.1.2: broken

5.0.0-pre3: broken
5.0.0-pre4: works
```

So this bug is currently still a problem for 3.6.7, 3.6.8, and 4.1.2.

**Comment by kjnilsson** [comment]
Thanks for finding this. . I will cherrypick the fix into stable and 4.x.

**Comment by michaelklishin** [comment]
We should release a `4.1.3` then.

**Comment by adamralph** [comment]
And a 3.6.9?

**Comment by michaelklishin** [comment]
oh, and perhaps cherry-pick to 3.6.x

**Comment by kjnilsson** [comment]
Working onit.

**Comment by kjnilsson** [comment]
4.1.3 is up: https://www.nuget.org/packages/RabbitMQ.Client/4.1.3

**Comment by adamralph** [comment]
Thanks @kjnilsson - I'll smoke test it.

**Comment by adamralph** [comment]
@kjnilsson I'm happy to report that 4.1.3 seems OK, with respect to NServiceBus.RabbitMQ.

I'll keep an eye out for 3.6.9.

**Comment by adamralph** [comment]
@michaelklishin @kjnilsson I'm happy to report that 3.6.9 seems OK, with respect to NServiceBus.RabbitMQ.

**Comment by kjnilsson** [comment]
@adamralph good to hear. Thanks for reporting back.
