### ISSUE TITLE
Consider expanding IChannelFactory with method from ChannelFactory

### ISSUE THREAD

**Issue by pardahlman** [rabbitmq/rabbitmq-dotnet-client#324]
The `ChannelFactory` has a [very handy method](https://github.com/rabbitmq/rabbitmq-dotnet-client/blob/master/projects/client/RabbitMQ.Client/src/client/api/ConnectionFactory.cs#L422) for creating a connection where each hosts is declared with a port (and `SslOptions`):

```csharp
factory.CreateConnection(new List<AmqpTcpEndpoint>
{
	new AmqpTcpEndpoint
	{
		HostName = "server1",
		Port = 4672
	},
	new AmqpTcpEndpoint
	{
		HostName = "server2",
		Port = 4673
	},
	new AmqpTcpEndpoint
	{
		HostName = "server3",
		Port = 4674
	}
});
```
This method is not part of the `IConnectionFactory` interface. My dilemma is that I want to use the interface so that I can mock the calls in my unit tests but I also have the ability to specify port for each host. Is there any chance you could add this method to the interface?

Cheers!

**Comment by michaelklishin** [comment]
@pardahlman we can for `5.0` (which is not too far off). Please submit a PR :)

**Comment by pardahlman** [comment]
Allright, I'm on it 👌
