### ISSUE TITLE
Build.bat fails for multiple reasons

### ISSUE THREAD

**Issue by develorem** [rabbitmq/rabbitmq-dotnet-client#326]
The build.bat file no longer seems to work on Windows
The first problem it encounters is that there are now multiple SLN files in the root and it doesn't know which one to pick when running the 'dotnet restore'
Modifying it to choose one gets past the restore but the next line in the batch file (the dotnet run Apigen call) fails with an exception of Access Denied; looks like just specifying the the csproj manually fixes that as well. 

After fixing these two problems, my bat file works as expected and everything compiles.
Fixing the second problem is easy, just change to this line:
dotnet run -p .\projects\client\Apigen\Apigen.csproj --apiName:AMQP_0_9_1 .\docs\specs\amqp0-9-1.stripped.xml .\gensrc\autogenerated-api-0-9-1.cs

Fixing the first problem is harder, you probably need a build.bat and a buildRT.bat ? And then update the build instructions accordingly.

**Comment by michaelklishin** [comment]
@develorem feel free to submit a PR against the `4.x` branch.

**Comment by kjnilsson** [comment]
@develorem Thanks for reporting this. We missed to test this when we moved to the new new dotnet core projects system. 
The reason there are two solution files is that RT doesn't work on non-windows so I think it is appropriate to point `build.bat` to `RabbitMQDotNetClientWithRT.sln` and leave `build.sh` using `RabbitMQDotNetClient.sln`

**Comment by develorem** [comment]
Looks like on the 4.x branch there's only one SLN file, but it won't build for different reasons it seems. 
error MSB4057: The target "_GenerateRestoreGraphProjectEntry" does not exist in the project.
In fact, if I switch back to master and run the build.bat using the RT sln file, I get the same error. 

So I've submitted a PR for an update to build.bat that points to the non-RT sln file, and updates the csproj, and it's created against master since the update to 4.x won't make a difference to getting it to build.
https://github.com/rabbitmq/rabbitmq-dotnet-client/pull/327
And yet, the build fails. Apparently the appveyor setup doesn't handle the batch file change. 
Something so simple... will continue to investigate later.

**Comment by kjnilsson** [comment]
@develorem ok so it sounds like there are other issues around RT, perhaps you require some additional dependencies. It isn't super important for us to support RT in 5.x. Also appveyor hasn't been updated to support the new .NET core dependencies yet. I will test your change as is and if it works then we'll merge it as is.

**Comment by develorem** [comment]
Thanks. I'm running a clean install of VS2017 Community Edition on Windows 7.  Truthfully I only installed VS17 to get the "dotnet" command line tool used in your build configs (but I'm happy to use it since I have it now!). Perhaps its a version issue with "dotnet"? Not sure, I'm kinda new to Core and RT. Let me know if there's anything else I can do to help.

**Comment by michaelklishin** [comment]
@develorem .NET Core had breaking changes relatively recently. We've switched our build toolchain to support the [most recent release](https://www.microsoft.com/net/core) only.

**Comment by adamralph** [comment]
Has #327 fixed this?
