### ISSUE TITLE
ConnectionFactory <Summary> comment indicates non-existant property .Uri

### ISSUE THREAD

**Issue by develorem** [rabbitmq/rabbitmq-dotnet-client#328]
The Summary comments for the RabbitMQ.Client.ConnectionFactory class indicate a ConnectionFactory has a property Uri with the following comment:
`    ///     factory.Uri = "amqp://localhost";`
I note instead a new method:  SetUri(string)
The comments should be updated to reflect this. 
Will submit a PR in a moment.

**Comment by develorem** [comment]
PR: https://github.com/rabbitmq/rabbitmq-dotnet-client/pull/329
base is master, or should I change it to 4.x ?

**Comment by michaelklishin** [comment]
@develorem I will cherry pick. Thank you.

**Comment by michaelklishin** [comment]
I'm curious why we don't use a `Uri` property. It's something that looks like an oversight if you consider [the entire ConnectionFactory interface](https://github.com/rabbitmq/rabbitmq-dotnet-client/blob/master/projects/client/RabbitMQ.Client/src/client/api/IConnectionFactory.cs).

**Comment by michaelklishin** [comment]
@kjnilsson @develorem @bording @danielmarbach how would you feel about deprecating `IConnectionFactory#SetUri` and introducing a `Uri` property in `5.0`? Is it worth considering or should I just rein in my naming OCD? :)

**Comment by kjnilsson** [comment]
@michaelklishin set `Uri` and `uri` properties were actually removed in 5.x and decprecated in 4.x. That said I don't mind if we turn SetUri into a property again. I agree it would be more consistent. I know why we removed `uri` but can't recall why `Uri` also was removed and replaced.

**Comment by michaelklishin** [comment]
@kjnilsson OK, then I suggest that we don't do anything more in this area for a while 😆 .

**Comment by kjnilsson** [comment]
I think the reason was that `SetUri` could have an overload that took a `string` just like I think `uri` used to do but it seems that overload was never implemented (or missed by anyone).

**Comment by develorem** [comment]
Not sure how closely you work with EasyNetQ project, but I know they reference the uri property:
https://github.com/EasyNetQ/EasyNetQ/blob/develop/Source/EasyNetQ/IConnectionFactory.cs#L41
Easy change though and that's the only place that needs updating to work with latest ver of RabbitMQ.Client
I do think that in some cases external source will want to pull the full URI out of the connection class (for their own logging purposes or whatever)

**Comment by michaelklishin** [comment]
EasyNetQ maintainers upgrade some time after this client is released. Now that this client is no longer tied to RabbitMQ releases, we try to follow a reasonably semantic versioning scheme (that's why we are already approaching 5.0 :)), which should make upgrades more predictable for dependent projects.

According to https://github.com/rabbitmq/rabbitmq-dotnet-client/commit/7c6c2598e6bba2e46e530bfaf5343dba00dec639, `uri` and `Uri` were settable only.

**Comment by danielmarbach** [comment]
Like already discussed with the method approach it is easier to have multiple overloads of the same method which is a plus for the method. If that is not desired I see no reason why not make it a property with get and set. Setter only properties are a bit awkward in my point of view. Or what would be the reason to not exposed it readable once set?

**Comment by michaelklishin** [comment]
@danielmarbach I see no reason. We can reintroduce `Uri` the property with both. Not sure if `SetUri` should be left in place :/

**Comment by kjnilsson** [comment]
As far as I'm concerned `SetUri` can go in favour of `Uri`. Seems no one missed not having a setter that just takes a string.

**Comment by adamralph** [comment]
Is it valid to have the properties mutable after construction? If not, I question the validity of all the properties of the interface. If these are write-once properties, it may make more sense for the API to look like this:

```csharp
public interface IConnectionFactory
{
    public IConnection CreateConnection();
}

// convenience class for implementations to optionally inherit from
public abstract class ConnectionFactoryBase : IConnectionFactory
{
    // some arguments could be optional if appropriate
    public ConnectionFactoryBase(Uri uri, ...) { ... }

    // read only
    protected Uri Uri { get; }
    
    public abstract IConnection CreateConnection();
}
```

**Comment by kjnilsson** [comment]
@adamralph I totally agree with you. The `IConnectionFactory` interface has evolved over a long time and isn't particularly consistent or even particularly easy to reason about as is, however I'm reluctant to make too many breaking changes given every single user of the client uses it.
