### ISSUE TITLE
Downgrade platform target to netstandard1.2

### ISSUE THREAD

**Issue by gzak** [rabbitmq/rabbitmq-dotnet-client#334]
Gernally speaking, I think library projects should target the _oldest_ possible framework/platform version possible, to maximize compatibility. I noticed that this library supports .NET Framework 4.5.1, but only .NET Standard 1.5. The equivalent version for standard that supports 4.5.1 is 1.2, rather than 1.5.

Is there any particular reason this library needs to target 1.5 _and_ 4.5.1 explicitly? I believe just targeting 1.2 will automatically cover 4.5.1.

**Comment by michaelklishin** [comment]
Sorry, with .NET Core moving fast and being far from mature yet it'd be counterproductive. Maybe in a couple of years when the dust settles down.

**Comment by michaelklishin** [comment]
This client was adapted to support .NET Core because the community demanded it but dropping "regular" .NET was not an option either. It will eventually require 4.6.x and a new client for just .NET Core will be developed from scratch.

**Comment by kjnilsson** [comment]
A lot of dependencies, such as sockets isn't available in 1.2. 1.5 was the lowest netstandard version we were able to target without removing use of required APIs. We _may_ be able to target 1.4 with only a few `IFDEF`s but that is probably as low as we can practically go.

**Comment by gzak** [comment]
Got it, that makes sense.
