### ISSUE TITLE
Requesting an update to the dev tools listing for NServiceBus

### ISSUE THREAD

**Issue by adamralph** [rabbitmq/rabbitmq-dotnet-client#343]
I know this is the wrong place to raise this, but I'm hoping that, in closing this issue, you'll be able to point me in the right direction. Apologies for raising this here, but I don't know where else to ask.

In https://www.rabbitmq.com/devtools.html, there's a listing for NServiceBus, which, in comparison with the other listings, is worded strangely, ".NET NServiceBus client" and doesn't have a description next to it.

We'd like to suggest an improvement to this listing. What's the best way to do that?

Many thanks!

**Comment by kjnilsson** [comment]
Hi Adam,

I agree the wording is strange.

How about a PR or issue to: https://github.com/rabbitmq/rabbitmq-website ?

Cheers
Karl

**Comment by adamralph** [comment]
That looks like the ideal place, thanks. 😄 

I had no idea the website was OSS. That's great.

**Comment by adamralph** [comment]
Raised https://github.com/rabbitmq/rabbitmq-website/pull/420
