### ISSUE TITLE
AutorecoveringConnection using foreground thread

### ISSUE THREAD

**Issue by cruikshj** [rabbitmq/rabbitmq-dotnet-client#348]
When setting the `AutomaticRecoveryEnabled` option, a foreground thread is created to periodically recover a connection.  It spends most of its life sleeping.  This seems like it should be a background thread such that an application can close normally without specifically closing that thread.  I understand that disposing the factory will clean up this thread but it still seems like this specific thread shouldn't stop a program from closing.  I can also understand other connection threads forcing the disposal as discussed [here](https://github.com/rabbitmq/rabbitmq-dotnet-client/pull/21), just not necessarily this one.

I think the change would be to configure the following task with the `LongRunning` hint.

https://github.com/rabbitmq/rabbitmq-dotnet-client/blob/master/projects/client/RabbitMQ.Client/src/client/impl/AutorecoveringConnection.cs#L398

This is not a high priority, as I can ensure in all code paths that the factory is disposed.  Just seemed odd when I ran into it.

**Comment by michaelklishin** [comment]
@cruikshj please submit a PR with the proposed change?

@kjnilsson @danielmarbach does this sound reasonable to you?

**Comment by cruikshj** [comment]
Whoops.  I had the wrong thread in my sights.  I had gotten turned around with different behavior coming from a dotnet core application and a full .net application.  The thread that was holding up my application was actually the main loop thread in the connection class (but only in full .NET).  Makes sense after digging in the code a bit.  Looks like the long running task is used for core applications but not for full .NET.  

Anyway, I was able to resolve the issue by setting the `UseBackgroundThreadsForIO` setting in the full .NET application. 

Sorry for wasting your time.
