### ISSUE TITLE
Wrong DLL version (0.0.0.0) on .NET client (5.0.1) 

### ISSUE THREAD

**Issue by Gsantomaggio** [rabbitmq/rabbitmq-dotnet-client#359]
With the client 5.0.1 the dll version is `0.0.0.0`

I have seen the problem checking the management UI.

Tab "Connection", column "Client", as:
![screen shot 2017-10-03 at 10 17 17](https://user-images.githubusercontent.com/386987/31115939-81ac62c8-a824-11e7-9384-d5285f0170e2.png)

RabbitMQ version `3.6.11`

**Comment by kjnilsson** [comment]
Confirmed [bug](https://github.com/rabbitmq/rabbitmq-dotnet-client/blob/master/projects/client/RabbitMQ.Client/src/client/impl/Connection.cs#L358)
