### ISSUE TITLE
Revamp code generator

### ISSUE THREAD

**Issue by michaelklishin** [rabbitmq/rabbitmq-dotnet-client#36]
We've been avoiding tweaking code generator much in recent years because it's fairly hard to make non-trivial changes. As a result it is much harder to refactor the rest of the library because we depend on the existing `ModelBase` hierarchy and responsibility scope heavily.

Now that we require .NET 4.0, we can investigate [Expression Trees](https://msdn.microsoft.com/en-us/library/bb397951.aspx). The idea of using F# has came up a few times in the past (for [templating](http://blog.sigmaukraine.com/generating-csharp-code-using-fsharp/), implementing `ModelBase` in F# and relying e.g. on [Code Quotations](https://msdn.microsoft.com/en-us/library/dd233212.aspx) will likely suffer from the law of diminishing returns in our case).

Specific points of improvements we should aim for:
- Make it easier to make changes to `ModelBase`
- Split generator `ModelBase` into smaller parts
- Make generated code better suited for future API and implementation changes, e.g. in #16 and #20.

Since the code generation artefacts are not exposed to end users, we can make breaking changes there but preserving .NET and Mono compatibility is a must.

**Comment by YulerB** [comment]
Is the idea to use T4?

**Comment by YulerB** [comment]
Or something like this:

client	.ConfigureHosts(Expression<Func<IEnumerable<EndPoint>> host)

	.GetCluster(Expression<Func<string>> host)
	.GetLocalCluster()

	.Heartbeat(Expression<Func<int>> expfi)
	.VirtualHost(Expression<Func<string>> vHost)
	
	.AuthenticatePlain(Expression<Func<NetworkCredential>> cred)
	.AuthenticateCertificate(Expression<Func<X509Certificate2>> cert)			
	
	.SetAutomaticFailover(Expression<Func<bool>> automatic)
	.RecoverTopology(Expression<Func<bool>> recover)
	.DirectExchange(Expression<Func<string>> exchange)
	
	.AutoDeleteQueue(Expression<Func<string>> queue)
	.DurableQueue(Expression<Func<string>> queue)
	
	.SetDeadLetter(Expression<Func<string>> exchange, Expression<Func<string>> queue)
	.SetQualityOfService(Expression<Func<int>> expfi)
	
	.Publish(Message message)

	.ConsumeAsync(Func<Task, Message> consumer)
	.Consume(Action<Message> consumer);

**Comment by lukebakken** [comment]
Labeled for net-gen client and closing.
