### ISSUE TITLE
Memory Thrashing

### ISSUE THREAD

**Issue by YulerB** [rabbitmq/rabbitmq-dotnet-client#361]
Allot of memory is allocated and destroyed of different byte lengths.
This has impact on the CPU and on memory fragmentation, leading to higher latency.
I have 2 recomendations, 
1. use socket methods using SocketAsyncEventArgs
2. pool the byte[] that are being allocated.

**Comment by YulerB** [comment]
This ties in with issue #303, as ArraySegment<byte> may be part of the solution.

**Comment by lechu445** [comment]
Why this issue was closed?

**Comment by lukebakken** [comment]
#706 may address this.
