### ISSUE TITLE
Unique identifier for channel?

### ISSUE THREAD

**Issue by pardahlman** [rabbitmq/rabbitmq-dotnet-client#362]
Hello,

At times, I want a way to uniquely identify channels. The `IModel` interface has the property `ChannelNumber`, a number that is unique _per connection_. This is not a deterministic way to identify channels since it (theoretically) is possible to have multiple connections in the same application.

Do you think it would be possible or make sense to introduce some sort of globally unique identifier for channels? If not for the current client, then perhaps for the re-write?

When debugging my code, I see that the instances of channel has reference to a Session that in turn has reference to the connection which has an Id (`Guid`). The combination of connection id and channel number should suffice for a key.

Cheers!

**Comment by michaelklishin** [comment]
@pardahlman if you need a globally (per process) unique channel ID you can use channel object's hash code or a hash code of the [connection, channel number] pair. What worries me about this approach is that

1. No other client has anything like this and it wasn't requested
2. Session is an implementation detail
3. Session ID will change after connection recovery

So none of them are necessarily reliable enough as OS process-wide unique identifiers.

**Comment by pardahlman** [comment]
Hi @michaelklishin - thanks for getting back to me 👍. Using the hash code was my first idea, too. However, the same actual channel to the broker is represented with different object instances - for example I noticed it in the `BasicAcks` event delegates. Here's a small unit test that fails

```csharp
[Fact]
public async Task Compare_Channel_Number_And_Hash_Code()
{
  using (var connection = new ConnectionFactory().CreateConnection())
  using (var channel = connection.CreateModel())
  {
    var basicAckSender = new TaskCompletionSource<IModel>();
    channel.ConfirmSelect();
    channel.BasicAcks += (sender, args) =>
    {
      basicAckSender.TrySetResult(sender as IModel);
    };
    channel.BasicPublish(string.Empty, string.Empty, null, new byte[0]);
    await basicAckSender.Task;
    Assert.Equal(basicAckSender.Task.Result.ChannelNumber, channel.ChannelNumber); // ok
    Assert.Equal(basicAckSender.Task.Result.GetHashCode(), channel.GetHashCode()); // fails
  }
}
```

**Comment by michaelklishin** [comment]
Doesn't the snippet compare a channel hash code with something else? Unless you perform connection recovery, I don't see how `channel` above can become a different object in its `using` block.

Channels are identified as a connection name + channel ID in the HTTP API. Connection name includes client port and will change when connection recovery happens. For pretty much all intents and purposes, this is sufficient.

I don't think we will be adding a unique ID for channels because even if "natural keys" and hash code (?!) are not stable enough, we might as well let the application developer decide how to deal with it.

**Comment by michaelklishin** [comment]
@pardahlman IIRC you have a pooling library, so I'll assume this is for that project. Take a look at how Spring AMQP does connection and channel pooling (caching). I can't guarantee they do the same thing you have in mind but Java client doesn't have any global channel IDs just like this client doesn't.

**Comment by pardahlman** [comment]
It is not strictly necessary, and I have a way around this. It comes with a cost of complexity and stack-allocation, as the callback methods needs to reference the channel from outside the scope instead of using `sender` (which to the best of my knowledge is a representation of the same channel). Anyways, it was just a thought 😉.

Cheers!
