### ISSUE TITLE
Get error while looping ExchangeDeclare

### ISSUE THREAD

**Issue by goyzhang** [rabbitmq/rabbitmq-dotnet-client#369]
I'm using RabbitMQ Client in a windows service. As documented, the `ExchangeDeclare` should be idempotent and has no effect if the exchange is already in place. Howerver, I got `timeout `and `"Pipelining of requests forbidden"` error running following testing codes:
```
            IModel channel;
            var factory = new ConnectionFactory()
            {
                HostName = "192.168.1.70",
                UserName = "rabbitmq",
                Password = "rabbitmq",
                RequestedHeartbeat = 40,
                AutomaticRecoveryEnabled = true,
                NetworkRecoveryInterval = TimeSpan.FromSeconds(15)
            };
            var Conn = factory.CreateConnection();
            channel = Conn.CreateModel();
            while (true)
            {
                Console.WriteLine("try \n");
                Thread.Sleep(1000);
                try
                {
                    channel.ExchangeDeclare("woohoo", "direct"); //error
                    var message = "data";
                    var body = Encoding.UTF8.GetBytes(message);
                    channel.BasicPublish(exchange: "woohoo",
                                                    routingKey: "info",
                                                    basicProperties: null,
                                                    body: body);
                    Console.Write("done\n");
                }
                catch(Exception ex)
                {
                    Console.WriteLine(ex.Message);
                }                  
            }
```
It published for the first loop. But in the second loop it throws `Timeout` error then the followings get `System.NotSupported "Pipelining of requests forbidden"` Error.This is tested in a single-thread program. If I change it to `ExchangeDeclareNoWait`, everything goes well. 
Am I doing something wrong? I did the same before but no such errors. The client version is 5.0.1(under windows 10 .NET 4.6.1) and the server is RabbitMQ 3.6.6.

**Comment by goyzhang** [comment]
It turns out another guy overwhelmed the server and the storage was full, which I didn't think of.. If you declare once, it still runs without error.

**Comment by lukebakken** [comment]
> It turns out another guy overwhelmed the server and the storage was full

You will get errors in this case. The client appears to be working as expected.
