### ISSUE TITLE
Unclear errors on server SSL certificate validation failure

### ISSUE THREAD

**Issue by SilverC** [rabbitmq/rabbitmq-dotnet-client#370]
When a server SSL certificate validation failure occurs the error message given by the C# client is that none of the specified nodes were reachable which is misleading and makes diagnosing difficult. I'm not sure if this is a ASP.NET Core verbosity issue or a issue with where the exception is caught in the client. I'm using a self signed CA. That CA is not in the trusted certificate store which on a Mac environment is the Apple Keychain and on Linux is the openssl trusted root store for ASP.NET Core 2.0. 

* RabbitMQ version - 3.6.9
* Erlang version - 19.3
* RabbitMQ.Client version - 5.0.1
* ASP.NET Core version - 2.0.0

 ```
_rabbitConnectionFactory = new ConnectionFactory
            {
                HostName = "hostname",
                Port = 5671,
                AutomaticRecoveryEnabled = true,
                TopologyRecoveryEnabled = true,
                UserName = "username",
                Password = "password"
                RequestedConnectionTimeout = 15000,
                Ssl = new SslOption
                {
                    Enabled = true,
                    ServerName = "hostname",
                    CertPath = Path.Combine(env.ContentRootPath, "certpath/cert.p12"),
                    CertPassphrase = "secretpassphrase",
                    Version = SslProtocols.Tls12
                }
            };
_connection = _rabbitConnectionFactory.CreateConnection();
```

**Comment by michaelklishin** [comment]
RabbitMQ or client libraries do not implement TLS. As far as this client is concerned, it failed to connect. There *is* additional information in the underlying exception stack trace plus server logs.

**Comment by SilverC** [comment]
Failing to connect and none of the specified nodes being reachable have different meanings. The destination being unreachable implies a path to the remote node was not found. That's clearly not the case here so the exception is still ambiguous at best. 

The server logs just say the client disconnected not why because it was the client who decided to disconnect based on the fact it was unable to validated the remote node's certificate. 

After some digging I see the error in the stack trace so that's at least helpful.

**Comment by michaelklishin** [comment]
@SilverC I'm not aware of a single message that can cover dozens of different ways in which connection can fail. That's why what we have is generic. I somewhat doubt there can be a significantly better generic message but if you have a suggestion, let us know.

The issue here is not so much with the exception but with the fact that the only way to really find out the details is to look at the nested exceptions, which some tools can cut and most developers don't bother with.

**Comment by SilverC** [comment]
I agree that proper logging would bubble up the issue much better. In my case I was catching the exception and logging it but the logging framework wasn't logging the nested exception all the way to the ssl validation failure. It was actually stopping just short in the stacktrace unfortunately. 

In my, admittedly, pedantic opinion the exception should read something like "Failed to connect to remote server" if this is going to be a generic exception for every type of connection failure. The current one implies a certain failure type instead of being as vague as it probably should be given the scope of failures it covers. Something more generic would have prompted me to investigate additional areas more readily rather than looking immediately in the wrong place because the exception suggested I couldn't even reach the server which wasn't accurate. 

Just my two cents and I understand you guys probably have more pressing issues to resolve.
