### ISSUE TITLE
Consider Supporting Reactive Extensions

### ISSUE THREAD

**Issue by RehanSaeed** [rabbitmq/rabbitmq-dotnet-client#378]
I wrote the following code to turn the `Recieved` event from a consumer into an `IObservable<T>` and threw in custom acknowledgements into the mix too. This allows you to use Linq and the power of Reactive Extensions to do some interesting things with this sort of time series data.

This issue is just a suggestion of either building this into the next version (I notice you are considering a rewrite with the aim of modernizing the API surface) or providing some extension methods in a separate package.

```
Recieve<Foo>("Exchange", "RoutingKey")
    .Where(x => x.Value.Bar == 5)
    .Subscribe(x =>
    {
        using (x)
        {
            Console.WriteLine(x);
        }
    });

public IObservable<DisposableValue<T>> Recieve<T>(string exchangeName, string routingKey)
{
    if (exchangeName == null)
    {
        throw new ArgumentNullException(nameof(exchangeName));
    }

    if (routingKey == null)
    {
        throw new ArgumentNullException(nameof(routingKey));
    }

    var queueName = this.model.QueueDeclare().QueueName;
    this.model.QueueBind(queueName, exchangeName, routingKey);

    using (var subscription = new Subscription(model, queueName, false))
    {
        var consumer = new EventingBasicConsumer(this.model);

        var observable = Observable
            .FromEventPattern<BasicDeliverEventArgs>(
                x => consumer.Received += x,
                x => consumer.Received -= x)
            .Select(x => new DisposableValue<T>(
                Deserialize<T>(x.EventArgs.Body),
                () => this.model.BasicAck(x.EventArgs.DeliveryTag, false)));

        this.model.BasicConsume(queueName, false, consumer);

        return observable;
    }
}

public class DisposableValue<T> : IDisposable
{
    private readonly Action disposeAction;

    public DisposableValue(T value, Action disposeAction)
    {
        this.disposeAction = this.disposeAction ??
            throw new ArgumentNullException(nameof(DisposableValue<T>.disposeAction));
        this.Value = value;
    }

    public T Value { get; }

    public void Dispose() => this.disposeAction();
}
```

**Comment by pardahlman** [comment]
Hello @RehanSaeed, nice work! Do you mind a few follow up questions?

* The way I read your code, there is no way to `baskic.nack` or `basic.reject` a received message. Any ideas how this would be supported?
* It looks like the implementation is hard wired to a particular serialization mechanism (whatever is happening in `Deserialize`). How would different types of serialization types be supported?
* The message gets acked by the fact that you have a `using` statement in the Subscribe callback. It feels like a big risk (and perhaps likely?) that people will miss to dispose the object and thereby pile up received but unacked messages?

IMHO, Rx support for consuming messages would be super nice. But in order to be truly useful it needs to support more scenarios than "the happy flow". Also, the fact that the example code performs serialization, implicitly acks the messages and only exposes the message body to the user makes me think that it is more high level than the goal of this client.

**Comment by RehanSaeed** [comment]
- Regarding serialization, in my example I am creating an `IObservable<T>` but there is nothing stopping you from returning an `IObservable<BasicDeliverEventArgs>` instead. The consumer of the `IObservable` would then be responsible for deserialization like so:

```
observable.Select(x => Deserialize(x.EventArgs.Body));
```

- On your first point about `nack` or `reject`, instead of returning `IObservable<BasicDeliverEventArgs>` as in my first example, you could return a different object with `Nack` and `Reject` methods on it. In my opinion, you should still consider keeping a separate happy path method above with automatic acknowledgement built in because that's what most people would use (my assumption).

- On your third point about the `using` statement, this is where my RabbitMQ knowledge runs out. I've used some code from examples I've seen. In fact, the `subscription` variable is not used and I'm not entirely sure if I need it. I will be revisiting my code soon and will investigate then.

I think you could still use Rx and support all of your requirements above. The only question is whether you want to take a dependency on `System.Reactive`.

**Comment by rwkarg** [comment]
We have an internal library that takes a different approach and exposes queues as ISourceBlock<AmqpMessage> and points to exchanges with ITargetBlock<AmqpMessage>
where AmqpMessage is basically a BasicDeliverEventArgs with a channel/model held internally so it can expose .Ack() and .Nack(bool) methods. AmqpSourceBlock (implementation of the ISourceBlock<AmqpMessage>) also allows adding/removing bindings.
Publishing is a simple .Post to the TargetBlock.
Consuming is linking an ActionBlock<AmqpMessage> to the ISourceBlock (which will default to serial processing unless you opt in to parallelism when you create the ActionBlock)

This is intended to be the 80% common use case and it practice is basically all of our internal use cases (we do Eventing, RPC, Streaming Responses, Chat).

It also does things like using a single Connection for all SourceBlocks (consuming) and a single Connection for all TargetBlocks (publishing) to keep socket usage down but separate publishers and consumers for better flow control handling. Also handled reconnects and re-declaring exchanges/queues/consumers from before the base library had that functionality.

That said, it's happily existed for several years on top of the various versions of the .NET SDK and I never really felt like we've been missing anything by it not being in the base library.

Perhaps these two implementations (Dataflow/Rx) should exists as separate contrib packages on top of the base client?

**Comment by michaelklishin** [comment]
@rwkarg many contributors to this client would agree with that: external libraries is a better idea (because they can make more mistakes/evolve quicker/ship more frequently).

**Comment by lukebakken** [comment]
Closing, please see [this comment](https://github.com/rabbitmq/rabbitmq-dotnet-client/issues/378#issuecomment-365777996).
