### ISSUE TITLE
Topology recovery stalls when it runs into a declaration failure

### ISSUE THREAD

**Issue by dbuchko** [rabbitmq/rabbitmq-dotnet-client#379]
During an Azure maintenance patch for the Meltdown and Spectre security vulnerabilities to the servers hosting an HA RabbitMQ cluster on Pivotal Cloud Foundry, a simple .NET queue listener [client application](https://github.com/dbuchko/Listener/tree/28e29a625664ff180ffd4f26fd80cca8890f8f1f) failed to recover it's connection when the autorecovery mode was left at the default enabled value of `true`.   The root cause as indicated in the attached [log file](https://github.com/rabbitmq/rabbitmq-dotnet-client/files/1607934/listener.log) appears to be in the topology recovery code, where re-declaration of the durable queue is throwing an exception because the home node of the queue is not available.  Once the exception was thrown at 1-4-2018 0:17:37, the client application hangs and must be manually restarted, which is done at 1-4-2018 14:18:28..

.NET RabbitMQ Client Version:  5.0.1
RabbitMQ PCF service tile version:  1.9.11

**Comment by michaelklishin** [comment]
This behaviour is expected. Use transient or mirrored queues if that's not what you want, then the queue master will be moved to a different node.

**Comment by lukebakken** [comment]
@michaelklishin I think we can address this case in the .NET client - make it a little smarter in the topology re-declaration. Also, the issue of the client hanging indefinitely is a problem.

**Comment by michaelklishin** [comment]
We've considered this before with other clients. The list f options is not too long: fail topology recovery, ignore and continue or retry N times. The option we effectively have today in other clients is the first one.

The behaviour of queue declaration in this case can be controlled via the queue durability property, which is by design.

**Comment by lukebakken** [comment]
See #383, too

**Comment by lukebakken** [comment]
Please see dbuchko/Listener#1 for example code that appears to address this.

**Comment by TiwariRajiv** [comment]
@lukebakken facing this issue. Could you please share if there has been any good solution for this issue lately.
Using Java rabbitmq client version : 5.14.2
