### ISSUE TITLE
RabbitMq: Error while creating a connection

### ISSUE THREAD

**Issue by PavanKakumani** [rabbitmq/rabbitmq-dotnet-client#381]
Facing an error randomly while creating a connection

Connection.CreateModel();

Initially i thought it is related to Network issue, but not sure about the Root cause of this issue.
Could someone help to resolve the issue?

Application written in : .Net 
Class Library using :  RabbitMQ.Client.dll  Version : 3.6.1.0.

**Comment by lukebakken** [comment]
Hello - please post a message to the [`rabbitmq-users`](https://groups.google.com/forum/#!forum/rabbitmq-users) mailing list. The RabbitMQ team does not use GitHub issues for discussion or problem analysis.

When you post your message to the mailing list, please include complete error details and stack traces. If there are entries in the RabbitMQ server log that correspond, include those as well.

Thank you.

**Comment by michaelklishin** [comment]
Consider providing the entire stack trace and server logs when you post this to the mailing list. Also consider upgrading from the 3.6.x version of the client: there are several 4.x and 5.x releases available.
