### ISSUE TITLE
Incorrect read timeout during start and tune

### ISSUE THREAD

**Issue by Fresa** [rabbitmq/rabbitmq-dotnet-client#385]
https://github.com/rabbitmq/rabbitmq-dotnet-client/blob/c698ba41d859bca3e3bb91e7d5075ec85f1f9136/projects/client/RabbitMQ.Client/src/client/impl/Connection.cs#L1284

Should probably have been `TotalMilliseconds `instead of `Milliseconds`. Default is 10 seconds which will translate into 0 milliseconds in the current implementation which will set the socket to have an infinite receive timeout.

**Comment by michaelklishin** [comment]
This seems reasonable. Please submit a PR?

**Comment by lukebakken** [comment]
Looks like that's not the only place:

```
$ git grep '\.Milliseconds'
projects/client/RabbitMQ.Client/src/client/impl/Connection.cs:1021:                _heartbeatWriteTimer = new Timer(HeartbeatWriteTimerCallback, null, 200, m_heartbeatTimeSpan.Milliseconds);
projects/client/RabbitMQ.Client/src/client/impl/Connection.cs:1022:                _heartbeatReadTimer = new Timer(HeartbeatReadTimerCallback, null, 200, m_heartbeatTimeSpan.Milliseconds);
projects/client/RabbitMQ.Client/src/client/impl/Connection.cs:1284:            m_frameHandler.ReadTimeout = m_factory.HandshakeContinuationTimeout.Milliseconds;
```
