### ISSUE TITLE
Allow IP version to be specified in connection factory

### ISSUE THREAD

**Issue by DanFTRX** [rabbitmq/rabbitmq-dotnet-client#395]
In the majority of ConnectionFactory.CreateConnection() overloads, the AmqpTcpEndpoint's generated does not specify an AddressFamily
[Code for Reference A](https://github.com/rabbitmq/rabbitmq-dotnet-client/blob/bf2a79965299fa9b12a3f7938e6b6ef8ed1dfc42/projects/client/RabbitMQ.Client/src/client/api/ConnectionFactory.cs#L281)
[Code for Reference B](https://github.com/rabbitmq/rabbitmq-dotnet-client/blob/bf2a79965299fa9b12a3f7938e6b6ef8ed1dfc42/projects/client/RabbitMQ.Client/src/client/api/ConnectionFactory.cs#L430)

The connection factory will then attempt to connect using both IPv6 and IPv4(whichever succeeds first in that order) because it is not specified.
[Code for Reference](https://github.com/rabbitmq/rabbitmq-dotnet-client/blob/bf2a79965299fa9b12a3f7938e6b6ef8ed1dfc42/projects/client/RabbitMQ.Client/src/client/impl/SocketFrameHandler.cs#L87)

(ShouldTryIPv6 returns true when the OS supports IPv6 and the endpoint does not specify a IPv4)
[Code for Reference](https://github.com/rabbitmq/rabbitmq-dotnet-client/blob/bf2a79965299fa9b12a3f7938e6b6ef8ed1dfc42/projects/client/RabbitMQ.Client/src/client/impl/SocketFrameHandler.cs#L243)

It will then throw an exception if no IPv6 addresses are resolved from the DNS endpoint
[Code for Reference](https://github.com/rabbitmq/rabbitmq-dotnet-client/blob/bf2a79965299fa9b12a3f7938e6b6ef8ed1dfc42/projects/client/RabbitMQ.Client/src/client/impl/TcpClientAdapter.cs#L32)

Although connections are still made once the IPv4 attempt is made, this behavior makes debugging very difficult in an application that makes frequent RabbitMQ connections, as it will constantly be breakpointing the debugger.

 It would be nice to be able to specify IPv4 explicitly on the ConnectionFactory.

**Comment by lukebakken** [comment]
We would be happy to review a pull request that implements this. Please include tests. Thanks!

**Comment by bobledeveloppeur** [comment]
Sorry, i had no time to make pretty merge request
but fixed it with this code on my implementation
```csharp
private static IConnectionFactory GetConnectionFactory()
{
        return new ConnectionFactory()
        {
                EndpointResolverFactory = SetEndpointAsInterNetworkBeforeGetDefaultResolver,
        };
}
private static IEndpointResolver SetEndpointAsInterNetworkBeforeGetDefaultResolver(IEnumerable<AmqpTcpEndpoint> endpoints)
{
        foreach(var endpoint in endpoints)
                endpoint.AddressFamily = System.Net.Sockets.AddressFamily.InterNetwork;
        return new DefaultEndpointResolver(endpoints);
}
```

**Comment by tylerohlsen** [comment]
This was brought up again in issue #481.  I'd be willing to contribute with a PR if we can agree on an approach @lukebakken and/or @michaelklishin.  

What do you think about my suggestion for [a statically settable default for AddressFamily](https://github.com/rabbitmq/rabbitmq-dotnet-client/issues/481#issuecomment-514334402)?

**Comment by michaelklishin** [comment]
@tylerohlsen a way to force use of a certain IP family makes sense to me. Please submit a PR?

**Comment by tylerohlsen** [comment]
Ok. Can do. 

Could I also take a crack at making some of the other default values in the library as settable properties as well (keeping binary backwards compatibility)?

Or should I stick to just address family for now?

**Comment by michaelklishin** [comment]
@tylerohlsen you are welcome to do that in follow-up PRs. Note that the community expects adherence to the strictest semantic version interpretation, which means some things can only go into 6.0. But we would definitely consider your PRs and ideas :) Thank you!

**Comment by michaelklishin** [comment]
@tylerohlsen our clients use the second option, with a "preference settings". I find it hard to justify a dependency on `Microsoft.AspNetCore.WebUtilities` for this library, too.

**Comment by kjnilsson** [comment]
Wouldn't the minimal change be to provide an `DefaultAddressFamily` instance method on ConnectionFactory and have this value set on every `AmqpTcpEndpoint` instance created by the ConnectionFactory?

**Comment by tylerohlsen** [comment]
The `AmqpTcpEndpoint` is not always constructed by the connection factory.  There's parse methods and clones and dynamic creation from the _Endpoint_ getter in the connection factory (which is not cached, it's created on every call to the getter).  

So I don't think that's the minimal change.

**Comment by tylerohlsen** [comment]
I think the minimal change would be [here](https://github.com/rabbitmq/rabbitmq-dotnet-client/compare/master...tylerohlsen:tohlsen/defaultAddressFamily).  Is that more acceptable?

**Comment by kjnilsson** [comment]
@tylerohlsen would it be more discoverable if `DefaultAddressFamily` was exposed on the `ConnectionFactory`?

**Comment by tylerohlsen** [comment]
@kjnilsson That's debatable.  Since this is a static property for an instance property on AmqpTcpEndpoint, I could see it as discoverable there.  There are other static Default* properties on ConnectionFactory, so it would be consistent next to the others and a connection factory does seem like an appropriate place.  But the other Default* static properties are only for instance properties on ConnectionFactory itself.  

¯\\\_(ツ)\_/¯  I'm game for wherever you think.

**Comment by tylerohlsen** [comment]
@michaelklishin or @kjnilsson final thoughts on putting the property on `AmqpTcpEndpoint` or `ConnectionFactory`?  And how about which branch to merge to?

**Comment by michaelklishin** [comment]
I'm leaning slightly towards `ConnectionFactory` as I believe it's unlikely that anyone would prefer to use different settings for different endpoints. @lukebakken?

**Comment by lukebakken** [comment]
`ConnectionFactory` holds several other defaults so that seems reasonable.

**Comment by tylerohlsen** [comment]
Can-do.  And the branch?

**Comment by michaelklishin** [comment]
@tylerohlsen please submit a PR against `master` if this is what you're asking. This library's user community expects the strictest possible Semantic Versioning interpretation when it comes to API changes, so let's start with `master` (future 6.0) and see if we can backport this change without causing an outrage :)

**Comment by kjnilsson** [comment]
PR merged - closing.
