### ISSUE TITLE
System.NotSupportedException: Pipelining of requests forbidden

### ISSUE THREAD

**Issue by mmikirtumov** [rabbitmq/rabbitmq-dotnet-client#396]
Hi,

I have the following issue.

In my local machine RabbitMQ works fine with no issue.
Local Version is 3.7.0, Erlang 20.1.

But when I try to use other (using network) version of RabbitMQ it sends me the following exception
Version 3.6.14 Erlang 18.3

`System.NotSupportedException: Pipelining of requests forbidden at RabbitMQ.Client.Impl.RpcContinuationQueue.Enqueue(IRpcContinuation k) at RabbitMQ.Client.Impl.ModelBase.Enqueue(IRpcContinuation k) at RabbitMQ.Client.Impl.ModelBase.ModelRpc(MethodBase method, ContentHeaderBase header, Byte[] body) at RabbitMQ.Client.Framing.Impl.Model._Private_ExchangeDeclare(String exchange, String type, Boolean passive, Boolean durable, Boolean autoDelete, Boolean internal, Boolean nowait, IDictionary`2 arguments) at RabbitMQ.Client.Impl.ModelBase.ExchangeDeclare(String exchange, String type, Boolean durable, Boolean autoDelete, IDictionary`2 arguments) at EasyNetQ.RabbitAdvancedBus.<>c__DisplayClass33_0.<ExchangeDeclareAsync>b__1(IModel x) at EasyNetQ.Producer.ClientCommandDispatcherSingleton.<>c__DisplayClass8_0.<InvokeAsync>b__0(IModel x) at EasyNetQ.Producer.ClientCommandDispatcherSingleton.<>c__DisplayClass7_0`1.<InvokeAsync>b__1(IModel channel) at EasyNetQ.Producer.PersistentChannel.InvokeChannelAction(Action`1 channelAction) at EasyNetQ.Producer.ClientCommandDispatcherSingleton.<>c__DisplayClass7_0`1.<InvokeAsync>b__0() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at EasyNetQ.RabbitAdvancedBus.<ExchangeDeclareAsync>d__33.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at EasyNetQ.Producer.PublishExchangeDeclareStrategy.<DeclareExchangeAsync>d__4.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at EasyNetQ.RabbitBus.<PublishAsync>d__13`1.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at WOF.Bus.Infrastructure.EasyNetQBusAdapter.<PublishAsync>d__6`1.MoveNext()'`

**Comment by lukebakken** [comment]
Hello and thank you for using RabbitMQ.

Most likely, this issue is due to a bug in `EasyNetQ`. The `Pipelining of requests forbidden` error is mentioned [here](https://www.rabbitmq.com/dotnet-api-guide.html#model-sharing) and can be found [using this google search](https://goo.gl/oncTWk). If you can reproduce this error without using `EasyNetQ`, please provide code to do so and re-open this issue. Thanks!
