### ISSUE TITLE
Remove RabbitMQ.Client.MessagePatterns

### ISSUE THREAD

**Issue by michaelklishin** [rabbitmq/rabbitmq-dotnet-client#407]
`RabbitMQ.Client.MessagePatterns` are akin to the examples we had in the Java client except that it was never clearly communicated. Some of them are examples, others make a very specific workflow a bit more convenient without doing a great job at error handling.

The patterns have been kept afloat for a while, through the .NET Core migration and so on in the last 2-3 years. They cause sporadic test failures (e.g. see #406) and require maintenance work at no real benefit.

@kjnilsson and I agreed to deprecate them in 5.1.0 and remove them in a future release.

**Comment by lukebakken** [comment]
Confirmed removed in `master`, also see #514
