### ISSUE TITLE
EventingBasicConsumer Strange Behavior After Server Restart

### ISSUE THREAD

**Issue by busyscout** [rabbitmq/rabbitmq-dotnet-client#410]
Imagine, we have 8 messages in queue - strings 1 to 8. 
They are pushed to queue using this code which was taken from dotnet tutorial:
```csharp
static void Main(string[] args)
{
	var factory = new ConnectionFactory()
	{
		HostName = "localhost"
	};
	using (var connection = factory.CreateConnection())
	{
		using (var channel = connection.CreateModel())
		{
			channel.QueueDeclare(queue: "task_queue",
			 durable: true,
			 exclusive: false,
			 autoDelete: false,
			 arguments: null);

			var properties = channel.CreateBasicProperties();
			properties.Persistent = true;
			for(var i = 1;i<=8;i++)
			{
				var message = i.ToString();
				var body = Encoding.UTF8.GetBytes(message);
				channel.BasicPublish(exchange: "",
					 routingKey: "task_queue",
					 mandatory: true,
					 basicProperties: properties,
					 body: body);

				Console.WriteLine(" [x] Sent {0}", message);
			}
		}
	}

	Console.WriteLine("Finished");
	Console.ReadLine();
}
```
I have a very simple consumer app, that handles these messages:
```cs
class Program
{
	static void Main(string[] args)
	{
		var factory = new ConnectionFactory() { HostName = "localhost" };
		using (var connection = factory.CreateConnection())
		{
			using (var channel = connection.CreateModel())
			{
				ProcessChannel(channel);
				Console.WriteLine(" Press [enter] to exit.");
				Console.ReadLine();
			}
		}
	}

	static void ProcessChannel(IModel channel)
	{
		channel.QueueDeclare(queue: "task_queue",
				durable: true,
				exclusive: false,
				autoDelete: false,
				arguments: null);

		var consumer = new EventingBasicConsumer(channel);
		consumer.ConsumerCancelled += (s, a) =>
		 {
			 Console.WriteLine("ConsumerCancelled");
		 };
		consumer.Received += (model, ea) =>
		{
			try
			{
				var body = ea.Body;
				var message = Encoding.UTF8.GetString(body);
				Console.WriteLine($" [{DateTime.Now:HH:mm:ss}] Received {message}");
				Thread.Sleep(TimeSpan.FromMinutes(2));
				//Restart RabbitMQ server here
				Console.WriteLine($" [{DateTime.Now:HH:mm:ss}] Done {message}");
				Console.WriteLine($" Delivery tag is {ea.DeliveryTag}");
				channel.BasicAck(deliveryTag: ea.DeliveryTag, multiple: false);
			}
			catch(Exception exc)
			{
				Console.WriteLine($"Error while handle message - {exc}");
			}
		};
		channel.BasicConsume(queue: "task_queue",
							 autoAck: false,
							 consumer: consumer);
	}
}
```
This code is taken mostly from dotnet tutorial.
So, each message processing time is 2 minutes.
If everything works messages are processed one after one with total processing time of 16 minutes.
If I comment sleep code and run my consumer app I will get this expected output:
```
Press [enter] to exit.
 [19:41:22] Received 1
 [19:41:22] Done 1
 Delivery tag is 1
 [19:41:22] Received 2
 [19:41:22] Done 2
 Delivery tag is 2
 [19:41:22] Received 3
 [19:41:22] Done 3
 Delivery tag is 3
 [19:41:22] Received 4
 [19:41:22] Done 4
 Delivery tag is 4
 [19:41:22] Received 5
 [19:41:22] Done 5
 Delivery tag is 5
 [19:41:22] Received 6
 [19:41:22] Done 6
 Delivery tag is 6
 [19:41:22] Received 7
 [19:41:22] Done 7
 Delivery tag is 7
 [19:41:22] Received 8
 [19:41:22] Done 8
 Delivery tag is 8
```
But if my server is restarted after first message was received but before it was ack-ed I got a very strange behavior:
```
[19:51:34] Received 1
ConsumerCancelled <-- RabbitMQ service was restarted
 [19:52:43] Received 1 <-- RabbitMQ service started. 2nd handler started?
 [19:53:34] Done 1 <-- 1st handler
 Delivery tag is 1 <-- 1st handler. No effect on ack
 [19:53:34] Received 2 <-- 1st handler still working !??
 [19:54:43] Done 1 <-- 2nd handler
 Delivery tag is 9 <-- 2nd handler. Ack is successful. Message removed from queue
 [19:54:43] Received 2 <-- 2nd handler
 [19:55:34] Done 2 <-- 1st handler still working ...
 Delivery tag is 2<-- 1st handler acks second message with no effect at all
 [19:55:34] Received 3 <-- 1st handler received third message, same message soon will be received by 2nd handler
 [19:56:43] Done 2
 Delivery tag is 10
 [19:56:43] Received 3
```
So after restart we have 2 channels - old and new. Both receive same messages.
For each message we now have 2 `Received` events. The ack of first event does nothing - the message stays in queue, no exception is thrown. Only second event ack works. It is a very strange behavior.
I couldn't find any examples or articles to describe this behavior. Is it expected one? How to deal with it?

I am using latest version of RabbitMQ (3.7.4) on Windows with latest version of Erlang (20.3) and latest versions of .net core client (RabbitMQ.Client 5.1.0-rc1).

**Comment by michaelklishin** [comment]
Thank you for your time.

Team RabbitMQ uses GitHub issues for specific actionable items engineers can work on. GitHub issues are not used for questions, investigations, root cause analysis, discussions of potential issues, etc (as defined by this team).

We get at least a dozen of questions through various venues every single day, often light on details.
At that rate GitHub issues can very quickly turn into a something impossible to navigate and make sense of even for our team. Because GitHub is a tool our team uses heavily nearly every day, the signal/noise ratio of issues is something we care about a lot.

Please post this to [rabbitmq-users](https://groups.google.com/forum/#!forum/rabbitmq-users).

Thank you.

**Comment by michaelklishin** [comment]
When RabbitMQ restarts there's a very good chance [there will be redeliveries](http://www.rabbitmq.com/confirms.html#automatic-requeueing) due to automatic requeueing.
