### ISSUE TITLE
Sending C# class as message in cross-assembly

### ISSUE THREAD

**Issue by amitrajiitj** [rabbitmq/rabbitmq-dotnet-client#412]
I have been using a class as Dto to transfer data from publisher to queue from one application and deserialize the message to the class in the subscriber in other application. However, in doing so there is an exception occuring named Assembly reference for original Dto class is not found. Please suggest a way to transfer message through dto across applications.

**Comment by lukebakken** [comment]
Hello! This is a basic C#/.NET programming question and not related to RabbitMQ directly. Questions like these should be posted to StackOverflow or other C#/.NET community help forums.

"Assembly reference for original Dto class is not found" means that the `.dll` file containing your DTO class is not present for use by all of your applications.
