### ISSUE TITLE
RabbitMQ cross platform access issue

### ISSUE THREAD

**Issue by AshishShukla16** [rabbitmq/rabbitmq-dotnet-client#413]
Hi team,
We were working on rabbitMQ and using the C# client, publisher and subscriber components are designed and managed by two different team working on different solutions.

Team 1 designing the publisher sends message of **Type A** by converting it to byte array.
Team 2 designing the subscriber receives the byte data published by team A and need to convert it to **Type A** for further processing.

So in this scenario, do both teams needs to work on shared "Type A" because if both team maintain the same message type at their end then it does not work.

Does there any possibility to use **JSON** type message structure to store in RabbitMQ so both the system can use it for cross platform. I searched over the internet and find the RabbitMQ server only stores the bytes.

Also our one of the publisher client is built on **Java** so how to communication with that as it's using the Java client and manage message payload type at it's own end?

Warm Regards
Ashish Shukla

**Comment by lukebakken** [comment]
RabbitMQ is not aware of the contents of a message and considers a message to be a set of bytes. This means that you are free to serialize your data in any way you would like. You can set [message attributes](https://www.rabbitmq.com/tutorials/amqp-concepts.html#messages) to indicate the content type and content encoding of the message, and consumers would then use that information to deserialize the message body appropriately.

Note that RabbitMQ does **not** care what any of the message attributes are and will always treat a message as a byte blob.

**Comment by lukebakken** [comment]
If you have further questions, please do not use GitHub issue. Post your questions to the [`rabbitmq-users`](https://groups.google.com/forum/#!forum/rabbitmq-users) mailing list. Thank you!

**Comment by adamralph** [comment]
@AshishShukla16 as @lukebakken indicates, this is a higher level concern than the queueing system itself. You may want to look at something like NServiceBus, which provides [samples for integration with third party systems](https://docs.particular.net/nservicebus/messaging/third-party-integration), which may be running on different platforms.

Full disclosure: I work for Particular Software, the makers of NServiceBus. If you'd like to discuss your problem with us in more detail, you're welcome to raise an issue in our [discussion forum](https://discuss.particular.net/) or chat with one of our developers at https://particular.net/ (see "Chat with one of our devs" in the bottom right corner).
