### ISSUE TITLE
The Write method cannot be called when another write operation is pending

### ISSUE THREAD

**Issue by neil-119** [rabbitmq/rabbitmq-dotnet-client#417]
* RabbitMQ version: 3.7.4
* Erlang version: 20.2.3
* Client library version: 5.1.0-rc1 (.NET Core)
* Windows Server 2016

We are getting these random write errors (sporadic) in an ASP.NET Core web app. Retrying the request after several seconds succeeds, but not sure why they're happening in the first place. We create a different connection per thread and create new models in each method that uses that connection. We also tried sharing a single long-lived connection but creating new models in each thread / method to no avail.

Message and StackTrace: System.NotSupportedException:  The Write method cannot be called when another write operation is pending.
   at System.Net.Security.SslStreamInternal.ProcessWrite(Byte[] buffer, Int32 offset, Int32 count, LazyAsyncResult asyncResult)
   at System.Net.Security.SslStream.Write(Byte[] buffer, Int32 offset, Int32 count)
   at RabbitMQ.Client.Impl.SessionBase.Transmit(Command cmd)
   at RabbitMQ.Client.Impl.ModelBase.ModelRpc(MethodBase method, ContentHeaderBase header, Byte[] body)
   at RabbitMQ.Client.Framing.Impl.Model._Private_ChannelOpen(String outOfBand)
   at RabbitMQ.Client.Framing.Impl.AutorecoveringConnection.CreateNonRecoveringModel()
   at RabbitMQ.Client.Framing.Impl.AutorecoveringConnection.CreateModel()

**Comment by wjdavis5** [comment]
As mentioned here as well:

https://groups.google.com/forum/#!topic/rabbitmq-users/HgXZe1DgOhw

**Comment by michaelklishin** [comment]
@wjdavis5 provided some code in the rabbitmq-users thread, we'll give it a shot.

**Comment by kjnilsson** [comment]
At some point the `Transmit` call was moved outside a lock here:

https://github.com/rabbitmq/rabbitmq-dotnet-client/blob/27468916d6682211e68bf871a7463db438c0ba43/projects/client/RabbitMQ.Client/src/client/impl/SessionBase.cs#L199-L201

I don't fully understand how it now is handled in the `SocketFrameHandler`. @YulerB any ideas?

**Comment by michaelklishin** [comment]
Yes, I had feeling this may be a side effect of #354, too.

**Comment by kjnilsson** [comment]
We may just need a granular lock around the socket write operation:

https://github.com/rabbitmq/rabbitmq-dotnet-client/blob/27468916d6682211e68bf871a7463db438c0ba43/projects/client/RabbitMQ.Client/src/client/impl/SocketFrameHandler.cs#L238

**Comment by YulerB** [comment]
The SSLStream class doesn't follow the Liskov substitution principle.

The writes  and reads must only be done on a single thread.

The NetworkStream doesn't have the same issue.

The solution is to probably buffer the data to send, and process the full contents of the buffer onto the SSLStream, rather than locking the write.

If you plan to add a lock, only lock when using the SSLStream.

**Comment by kjnilsson** [comment]
I think we need to lock over both.

From the MSDN docs:

"Read and write operations can be performed simultaneously on an instance of the NetworkStream class without the need for synchronization. As long as there is one unique thread for the write operations and one unique thread for the read operations, there will be no cross-interference between read and write threads and no synchronization is required."

**Comment by michaelklishin** [comment]
A fine grained lock is what other clients (usually) use.

**Comment by kjnilsson** [comment]
I see Brian's point though - the docs probably state what they state due to the SslStream quirks. For a non-ssl socket the send method on the socket is safe to be called from multiple threads so shouldn't need locking - why locking is required for SSL I'm not sure.

Almost all `Stream` APIs suffer from LSP violations. It's why subtype polymorphism is so very hard to get right in practise.

**Comment by YulerB** [comment]
The source for NetworkStream doesn't raise NotSupportedException when Writing, only the SSLStream. 

The [_SSLStream](https://referencesource.microsoft.com/#System/net/System/Net/SecureProtocols/_SslState.cs,babe8a79b74013e9) writes encrypted streams using StartWrite, FinishWrite mechanics.  Instead of synchronizing the resource during these writes, they have left that to the caller 👎.

**Comment by kjnilsson** [comment]
@YulerB they have yes but if anything it is NetworkStream that is the exception as it supports writes from multiple threads which is contrary to the documentation! :)

I think the solution to this will be to take a fine grained lock around the write _if_ we are using ssl. I'll draft something up.

**Comment by kjnilsson** [comment]
Just issued a PR with a potential fix. Not sure if anyone is able to verify using sources only. I can see if we're able to generate PR packages still.

**Comment by wjdavis5** [comment]
Is there a build I can test?

**Comment by michaelklishin** [comment]
@wjdavis5 would a .dll file suffice? We can easily build and upload one.

**Comment by kjnilsson** [comment]
I've fixed our PR packages so the latest one should have this change. See: https://www.myget.org/feed/rabbitmq/package/nuget/RabbitMQ.Client

**Comment by kjnilsson** [comment]
correction this is the package to use for the PR: https://www.myget.org/feed/rabbitmq/package/nuget/RabbitMQ.Client/5.0.0-546ea94b

**Comment by wjdavis5** [comment]
Initial runs are looking good

**Comment by michaelklishin** [comment]
When diagnosing concurrency hazards maximum message rates are not necessary. Having a test that's been running for many hours is what you need.

**Comment by neil-119** [comment]
We've been running the PR version for several hours now in our dev environment, and the write error appears to have been resolved. Waiting for the PR to be merged into the master branch before we push it to production.

**Comment by michaelklishin** [comment]
We should finish QA'ing this soon. Thanks for the report, @neil-119.

**Comment by neil-119** [comment]
Hello, we've been running this for 5 days now in dev, and we haven't seen any more of these exceptions. I am not sure if it is related, but we are seeing the following exception every now and then however:

RabbitMQ.Client.Exceptions.AlreadyClosedException: Already closed: The AMQP operation was interrupted: AMQP close-reason, initiated by Peer, code=320, text="CONNECTION_FORCED - broker forced connection closure with reason 'shutdown'", classId=0, methodId=0, cause=
   at RabbitMQ.Client.Framing.Impl.Connection.EnsureIsOpen()
   at RabbitMQ.Client.Framing.Impl.AutorecoveringConnection.CreateModel()

**Comment by michaelklishin** [comment]
@neil-119 that is an attempt to do something on a connection that's been closed because RabbitMQ node was asked to shut down. Not related in any way.

**Comment by neil-119** [comment]
I thought so. Thanks for confirming.

**Comment by MikeZarlenga** [comment]
Has it been determined that using 2 connections, one for consuming and one for publishing, will make this problem go away?  Or is that speculation?

And what version of the .NET Client should have this problem fixed? From the exchanges above, it sounds like this was probably addressed in a 4.n release but I just stumbled across this very error with the 5.1.0-rc1 .NET Client DLL.

Best regards.

RESPONDER | 05:25:57.611 | Error | [Received] Exception: The Write method cannot be called when another write operation is pending.
RESPONDER | 05:25:57.617 | Informational | [Received] StackTrace:    at System.Net.Security._SslStream.ProcessWrite(Byte[] buffer, Int32 offset, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStream.Write(Byte[] buffer, Int32 offset, Int32 count)
   at System.IO.BinaryWriter.Write(Byte[] buffer)
   at RabbitMQ.Client.Impl.SocketFrameHandler.WriteFrameSet(IList`1 frames)
   at RabbitMQ.Client.Impl.Command.TransmitAsFrameSet(Int32 channelNumber, Connection connection)
   at RabbitMQ.Client.Impl.Command.Transmit(Int32 channelNumber, Connection connection)
   at RabbitMQ.Client.Impl.SessionBase.Transmit(Command cmd)
   at RabbitMQ.Client.Impl.ModelBase.ModelSend(MethodBase method, ContentHeaderBase header, Byte[] body)
   at RabbitMQ.Client.Framing.Impl.Model._Private_BasicPublish(String exchange, String routingKey, Boolean mandatory, IBasicProperties basicProperties, Byte[] body)
   at RabbitMQ.Client.Impl.ModelBase.BasicPublish(String exchange, String routingKey, Boolean mandatory, IBasicProperties basicProperties, Byte[] body)
   at RabbitMQ.Client.Impl.AutorecoveringModel.BasicPublish(String exchange, String routingKey, Boolean mandatory, IBasicProperties basicProperties, Byte[] body)
   at RabbitMQ.Client.IModelExensions.BasicPublish(IModel model, String exchange, String routingKey, IBasicProperties basicProperties, Byte[] body)
   at UnitTests.Responder.Received(Object consumer, BasicDeliverEventArgs args) in E:\TFS\EZPay\9.7\972\dev\EGS\EFT\source\Libraries\EZLinkLib\UnitTests\AmqpComms\Responder.cs:line 135

**Comment by michaelklishin** [comment]
This is not a discussion venue. There's a [rabbitmq-users post](https://groups.google.com/d/msg/rabbitmq-users/HgXZe1DgOhw/iUqlIlSGAwAJ) that provides a summary. Several people reported that #418 provides sufficient synchronisation for TLS socket streams.

**Comment by michaelklishin** [comment]
#418 is available in `5.1.0-rc.3`, not any earlier version and not in 4.x. I don't think 4.x is affected since certain networking code changes that lifted synchronisation (with sufficient changes for *regular* streams) were never adopted there.
