### ISSUE TITLE
Logging methods throw exceptions when used in .NET Framework 4.6.1 project

### ISSUE THREAD

**Issue by JonGinty** [rabbitmq/rabbitmq-dotnet-client#419]
Hello,

Apologies in advance if this is a known issue, I did try to trawl the documentation for anything similar.

We are using the latest RabbitMQ.Client NuGet package (v 5.0.1) in our .NET Framework 4.6.1 project. any call to any of the RabbitMQ event source logging methods (ESLog.Info, ESLog.Error etc.) causes a FileNotFound exception to be raised.

After further investigation, the cause appears to be that the dll in the NuGet package was build using the net451 configuration. I was able to mitigate this within our application by cloning the RabbitMQ.Client source and re-building under net461 configuration, and then manually referencing this dll instead of using the NuGet package.

The exact error message is "Could not load file or assembly 'Microsoft.Diagnostics.Tracing.EventSource, Version=1.1.28.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.". 

The source code actually appears to handle this situation correctly when built for the correct configuration. 
(RabbitMqClientEventSource.cs)
```c#
    using System;
#if NET451
    using Microsoft.Diagnostics.Tracing;
#else
    using System.Diagnostics.Tracing;
#endif
```
The version built for the NuGet package appears to be using the Microsoft.Diagnostics.Tracing version of EventSource which does not appear to be present in the .NET Framework 4.6.1

I believe this to be the same issue  #373 which I believe was mis-diagnosed as a missing log file.

Also, I should add that although this sounds like a relatively minor issue, many of the calls to these log methods seem to happen within threads managed by the RabbitMQ.Client and as such are not easily catchable from within our code. We initially encountered this issue because any loggable event that occurred within the client (in our case, an incorrect password) would cause this exception to be thrown and would cause our entire application to exit due to an unhandled exception.

Anyway, thanks for your time, do with this information as you wish, and let me know if you want any more details.

Regards
Jon Ginty

**Comment by michaelklishin** [comment]
We produce two separate versions, one for .NET Standard 1.5 and another for .NET framework 4.5.1. The latter does include a `Microsoft.Diagnostics.Tracing` dependency.

Looks like there's a bunch of `Tracing.X` packages published to NuGet [these days](https://www.nuget.org/packages?q=Microsoft.Diagnostics.Tracing).

**Comment by kjnilsson** [comment]
@JonGinty did you install the client using NuGet? if so it should pull down the required dependencies and reference them.

**Comment by michaelklishin** [comment]
A way to reproduce (e.g. a small public GitHub repo and platform details) would be great. Otherwise this is mailing list material.

**Comment by JonGinty** [comment]
@kjnilsson Yeah, I installed the client to my project using NuGet
@michaelklishin I'll try set up a minimum repro ASAP although it's unlikely I'll have the time to do this today / tomorrow

**Comment by bording** [comment]
@JonGinty Something about your scenario doesn't add up. If you're using .NET Framework 4.6.1, then that means you'll be referencing the `net451` version of RabbitMQ.Client.dll, and that means you'll have a package dependency on Microsoft.Diagnostics.Tracing.EventSource.Redist as well.

That means in your bin folder, you will have both RabbitMQ.Client.dll and Microsoft.Diagnostics.Tracing.EventSource.dll, so you shouldn't be getting the "Could not load file or assembly" error.

**Comment by JonGinty** [comment]
@bording @michaelklishin @kjnilsson 
OK, so I discovered after trying to build a repro project that this is actually an issue with OUR build process rather than anything to do with your project or NuGet. Long and short of it was that the Microsoft.Diagnostics.Tracing.EventSource.Redist was not copied to our output.

Sincerest apologies for wasting your time with this, and thanks for all of the quick responses.
Jon

**Comment by wjdavis5** [comment]
@JonGinty  - I'm seeing this same thing right now. How did you resolve it?

**Comment by JonGinty** [comment]
@wjdavis5 this issue was caused by the Microsoft.Diagnostics.Tracing dll not being present in the bin folder of the running application. Just make sure that the Microsoft.Diagnostics.Tracing dll is definitely there and that should fix it.
Otherwise you could manually add a reference to the Microsoft.Diagnostics.Tracing redist package in NuGet for your project but if you installed RabbitMQ.Client from NuGet then you definitely shouldn't need to and that'd probably indicate something else was the problem.
Hope this helps.
Jon

**Comment by wjdavis5** [comment]
Thank you @JonGinty !

**Comment by yekanchi** [comment]
I got this error on .net framework 4.8
