### ISSUE TITLE
QueueingBasicConsumer does not AutoRecover

### ISSUE THREAD

**Issue by jag919** [rabbitmq/rabbitmq-dotnet-client#42]
With AutomaticRecoveryEnabled, a QueueingBasicConsumer does not resume when a connection is reestablished, because the OnCancel call closes the queue.  Nothing in the recovery reopens it.  I worked around by creating my own consumer that does not close the queue on cancel.

**Comment by michaelklishin** [comment]
Queueing consumers are not recovered. It is non-trivial to do given how it works. Subclass the default consumer.

**Comment by jag919** [comment]
I would suggest adding a comment in the code or documentation to this effect then.

**Comment by michaelklishin** [comment]
Yes, we should definitely mention this in the guide. Thank you.
