### ISSUE TITLE
Is any idea support RabbitMQ AsyncClient?

### ISSUE THREAD

**Issue by caozhiyuan** [rabbitmq/rabbitmq-dotnet-client#422]
i develop a noblocking async client。

https://github.com/caozhiyuan/RabbitMQ.AsyncClient

**Comment by michaelklishin** [comment]
I'm not sure what this is about but our team does not use GitHub issues for discussions or announcements. Please announce your client on the mailing list and provide a bit of background what the motivation, design goals and so on.
