### ISSUE TITLE
Add .NET Standard 2.0 support in addition to 1.5

### ISSUE THREAD

**Issue by JBaltika** [rabbitmq/rabbitmq-dotnet-client#428]
Hi,

Would it possible to update the nuspec for .netStandard2.0 target. Thanks.

J.B

**Comment by michaelklishin** [comment]
It’s not a matter of updating the spec file. It’s a matter of cutting support for earlier .NET Standard versions. We will consider it but no offer no ETA promises.

**Comment by kjnilsson** [comment]
We may have to do a bit of ci work to get the release pipeline building ok but adding another target should be fine. I wonder if the latest tooling will be able to build `net451` on linux without jumping through all the massive number of hoops we currently are.

**Comment by adamralph** [comment]
AFAIK the only way to build `net451` on Linux is to use Mono. After all, that's the only .NET Framework implementation outside Windows.

**Comment by adamralph** [comment]
@bording thats great to hear. IIRC I saw something about that on Twitter recently too.

I guess it's orthogonal to this issue though. Should this issue be reopened? I think it's reasonable to regard this issue as simply *adding* a netstandard 2.0 target, where https://github.com/rabbitmq/rabbitmq-dotnet-client/issues/429 is something else.

**Comment by michaelklishin** [comment]
New target was added in #435.
