### ISSUE TITLE
Require/exclusively target .NET Standard 2.0

### ISSUE THREAD

**Issue by michaelklishin** [rabbitmq/rabbitmq-dotnet-client#429]
This is a placeholder issue for when we would like to drop support for .NET Standard < 2.0. References #428.

**Comment by bording** [comment]
Another option to consider would be to add an additional target to the mix:

`<TargetFrameworks>net451;netstandard1.5;netstandard2.0</TargetFrameworks>`

**Comment by michaelklishin** [comment]
@bording thank you. Are there any potential downsides? If not, may I ask you to submit a PR? ❤️

**Comment by bording** [comment]
I can't really think of a downside, other than the NuGet package size gets larger since you're shippping 3 assemblies instead of 2! 😄 

Adding `netstandard2.0` now also means you can still decide to drop the other frameworks in a new major later on if you want.

I'll see what I can do about a PR.

**Comment by lukebakken** [comment]
Resolved by #690.
