### ISSUE TITLE
RecoverQueue deletes recorded bindings before they can be recovered

### ISSUE THREAD

**Issue by jag919** [rabbitmq/rabbitmq-dotnet-client#43]
AutorecoveringConnection calls RecoverQueues, which in turn calls DeleteRecordedQueue(oldName).   This function executes m_recordedBindings.RemoveWhere(b => name.Equals(b.Destination)); The next call to RecoverBindings does nothing, since the bindings were removed for the old queue name.

**Comment by michaelklishin** [comment]
FTR, we've fixed this in the Java client before.

**Comment by michaelklishin** [comment]
Relevant Java client change: https://github.com/rabbitmq/rabbitmq-java-client/commit/0c0f2bff36a85b8a5c8c499cce24e95a0ae707a8.

**Comment by dumbbell** [comment]
Since 3.4.0.
