### ISSUE TITLE
ConnectionShutdown with low RequestedHeartbeat and invoking BasicAck from separate thread

### ISSUE THREAD

**Issue by dimzon** [rabbitmq/rabbitmq-dotnet-client#431]
I'm using Rabbit 3.7.7 Erlang 21.0.1 Rabbit.Client 5.1.0 (latest NuGet version) .NET Framework 4.7.2

```
using System;
using System.Threading;
using RabbitMQ.Client;
using RabbitMQ.Client.Exceptions;

namespace ConsoleAppMqCrashDemo
{
    class Program
    {
        static ConnectionFactory GetConnectionFactory()
        {
            return new ConnectionFactory
            {
                RequestedHeartbeat = 1, // removing RequestedHeartbeat solve problem too
                RequestedConnectionTimeout = 5,
                NetworkRecoveryInterval = TimeSpan.FromSeconds(3),
                AutomaticRecoveryEnabled = false
            };
        }

        class MyConsumer: DefaultBasicConsumer
        {
            public MyConsumer(IModel model) : base(model)
            {
            }

            private readonly object _sync = new object();
            public override void HandleBasicDeliver(
                string consumerTag,
                ulong deliveryTag,
                bool redelivered,
                string exchange,
                string routingKey,
                IBasicProperties properties,
                byte[] body
            )
            {
                var model = this.Model;
                WaitCallback wcb = state =>
                {
                    Console.Write(" " + Thread.CurrentThread.ManagedThreadId);
                    Thread.Sleep(6666);

                    try
                    {
                            lock (_sync)
                            {
                                model.BasicAck(deliveryTag, false);
                            }
                        }
                        catch (AlreadyClosedException e)
                        {
                            Console.Write(" ! ");
                        }

                };
                // invoking wcb directly instead tread pool solve problem
                ThreadPool.QueueUserWorkItem(wcb, null);
            }
        }

        static void Main(string[] args)
        {
            var sender = new Action(() =>
            {
                using (var cn = GetConnectionFactory().CreateConnection())
                using (var m = cn.CreateModel())
                {

                    m.QueueDeclare("test.queue_123", false, false, false);
                    for (;;)
                    {
                            m.BasicPublish("", "test.queue_123", false, m.CreateBasicProperties(), new byte[] { 0});
                        Thread.Sleep(100);
                    }
                }
            });
            sender.BeginInvoke(null, null);
            Thread.Sleep(100);
            var reciever = new Action(() =>
            {
                using (var cn = GetConnectionFactory().CreateConnection())
                using (var m = cn.CreateModel())
                {
                    cn.ConnectionShutdown += (o, eventArgs) => Console.WriteLine(eventArgs.Cause);
                    m.BasicQos(0, 2000, false);
                    m.BasicConsume("test.queue_123", false, new MyConsumer(m));
                    Thread.Sleep(5000000);
                }
            });
            reciever.BeginInvoke(null, null);
            Thread.Sleep(5000000);
        }
    }
}
```
I'm trying to get as reliable RabbitMQ connection as possible so I use minimal Heatbeat to detect network issues. I'm trying to run "jobs" into ThreadPool which means BasicAck from pooled thread. I'm using ' lock (_sync)' construction to avoid concurrent thread access to IModel. Unfortunally I'm getting **ConnectionShutdown** event for reciever with Cause
``` 
System.IO.IOException: Не удается прочитать данные из транспортного соединения: Удаленный хост принудительно разорвал существующее подключение. ---> System.Net.Sockets.SocketException: Удаленный хост принудительно разорвал существующее подключение
   в System.Net.Sockets.Socket.Receive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags)
   в System.Net.Sockets.NetworkStream.Read(Byte[] buffer, Int32 offset, Int32 size)
   --- Конец трассировки внутреннего стека исключений ---
   в RabbitMQ.Client.Impl.InboundFrame.ReadFrom(NetworkBinaryReader reader)
   в RabbitMQ.Client.Impl.SocketFrameHandler.ReadFrame()
   в RabbitMQ.Client.Framing.Impl.Connection.MainLoopIteration()
   в RabbitMQ.Client.Framing.Impl.Connection.MainLoop()
```

Both removing Heartbeat **OR** removing multi-treading approach make this event to disappear. Does it mean I need multiple connections (since consumer code works in single connection-associated background thread) to make multi-threaded processing while keeping low heartbeat value?

**Comment by michaelklishin** [comment]
See server logs. Almost certainly you have a case of incorrect framing on the wire due to concurrent access. There are discussions similar to this in rabbitmq-users archives.

**Comment by dimzon** [comment]
I does not see a reason to close this issue. Provide a proper syncronization primitive in client api so i can lock(something) to avoid concurrent access.

**Comment by michaelklishin** [comment]
Thank you for your time.

Team RabbitMQ uses GitHub issues for specific actionable items engineers can work on. This assumes that we have a certain amount of information to work with.

Getting all the details necessary to reproduce an issue, make a conclusion or even form a hypothesis about what's happening can take a fair amount of time. Our team is multiple orders of magnitude smaller than the RabbitMQ community. Please help others help you by providing a way to reproduce the behavior you're
observing and sharing as much relevant information as possible [on the list](https://groups.google.com/forum/#!forum/rabbitmq-users):

 * Server, client library and plugin (if applicable) versions used
 * Server logs
 * A code example or terminal transcript that can be used to reproduce
 * **Full** exception stack traces (not a single line message)
 * `rabbitmqctl status` (and, if possible, `rabbitmqctl environment` output)
 * Other relevant things about the environment and workload, e.g. OS/systemd logs, [a traffic capture](https://www.rabbitmq.com/amqp-wireshark.html), deployment tool logs, etc

Feel free to edit out hostnames and other potentially sensitive information.

When/if we have a complete enough understanding of what's going on, a recommendation will be provided or a new issues with more context will be filed.

Thank you.

**Comment by michaelklishin** [comment]
It's not unreasonable for a library to not support concurrent access in some or all cases.
Concurrency primitives and "an object to lock" are already available in .NET proper.

Most importantly, there isn't enough details to tell what specifically requires synchronisation. Our team is several orders of magnitude smaller than the community and the proof of an issue in the client is on the reporter.

On a possibly unrelated note, heartbeat values of 1 second are 5 times lower than the recommended minimum and will result in false positives. Which might exactly be why the remote host closes the connection but you haven't posted any logs to prove that hypothesis.

**Comment by kjnilsson** [comment]
Since 5.1 I think it should be safe to use models from other threads as it now locks on rpc methods as well as pre buffer full frames. I agree with Micahel. This is most likely something to do with the very low heartbeat value.
