### ISSUE TITLE
Consider making internal types sealed and internal

### ISSUE THREAD

**Issue by paulomorgado** [rabbitmq/rabbitmq-dotnet-client#446]
I think there are types that should be made `sealed` and `internal`. They don't seem to be meant for instantiation outside of the library.

**Comment by michaelklishin** [comment]
Do you have at least a partial list of such types?

**Comment by paulomorgado** [comment]
I'm not that familiar with the whole code base yet but classes implementing `IConnection` and `IModel` don't seem to be intended for direct instantiation. `ConectionFactory` creates instances of types implementing `IConnection`. Instances implementing `IConnection` create instances of types implementing `IModel`. If these types are not intended to be directly instantiated or extended they should be sealed and internal.

I've been thinking of opening this issue for a while be [this tweet](https://twitter.com/terrajobst/status/1037426506543190016) reminded me that it was overdue.

**Comment by lukebakken** [comment]
This will be implemented by #714 . PR #739 did a lot of it but @bording indicated more work is to be done.
