### ISSUE TITLE
Consider removing unnecessary bitwise and operations

### ISSUE THREAD

**Issue by paulomorgado** [rabbitmq/rabbitmq-dotnet-client#449]
These bitwise and operations are redundant:

* [Write((byte)((i & 0xFF00) >> 8));](https://github.com/rabbitmq/rabbitmq-dotnet-client/blob/master/projects/client/RabbitMQ.Client/src/util/NetworkBinaryWriter.cs#L96)
* [Write((byte)(i & 0x00FF));](https://github.com/rabbitmq/rabbitmq-dotnet-client/blob/master/projects/client/RabbitMQ.Client/src/util/NetworkBinaryWriter.cs#L97)
* [Write((byte)((i & 0xFF00) >> 8));](https://github.com/rabbitmq/rabbitmq-dotnet-client/blob/master/projects/client/RabbitMQ.Client/src/util/NetworkBinaryWriter.cs#L105)
* [Write((byte)(i & 0x00FF));](https://github.com/rabbitmq/rabbitmq-dotnet-client/blob/master/projects/client/RabbitMQ.Client/src/util/NetworkBinaryWriter.cs#L106)
* [Write((byte)((i & 0xFF000000) >> 24));](https://github.com/rabbitmq/rabbitmq-dotnet-client/blob/master/projects/client/RabbitMQ.Client/src/util/NetworkBinaryWriter.cs#L114)
* [Write((byte)((i & 0x00FF0000) >> 16));](https://github.com/rabbitmq/rabbitmq-dotnet-client/blob/master/projects/client/RabbitMQ.Client/src/util/NetworkBinaryWriter.cs#L115)
* [Write((byte)((i & 0x0000FF00) >> 8));](https://github.com/rabbitmq/rabbitmq-dotnet-client/blob/master/projects/client/RabbitMQ.Client/src/util/NetworkBinaryWriter.cs#L116)
* [Write((byte)(i & 0x000000FF));](https://github.com/rabbitmq/rabbitmq-dotnet-client/blob/master/projects/client/RabbitMQ.Client/src/util/NetworkBinaryWriter.cs#L117)
* [Write((byte)((i & 0xFF000000) >> 24));](https://github.com/rabbitmq/rabbitmq-dotnet-client/blob/master/projects/client/RabbitMQ.Client/src/util/NetworkBinaryWriter.cs#L126)
* [Write((byte)((i & 0x00FF0000) >> 16));](https://github.com/rabbitmq/rabbitmq-dotnet-client/blob/master/projects/client/RabbitMQ.Client/src/util/NetworkBinaryWriter.cs#L126)
* [Write((byte)((i & 0x0000FF00) >> 8));](https://github.com/rabbitmq/rabbitmq-dotnet-client/blob/master/projects/client/RabbitMQ.Client/src/util/NetworkBinaryWriter.cs#L127)
* [Write((byte)(i & 0x000000FF));](https://github.com/rabbitmq/rabbitmq-dotnet-client/blob/master/projects/client/RabbitMQ.Client/src/util/NetworkBinaryWriter.cs#L128)
* [(short)(((i & 0xFF00) >> 8) | ((i & 0x00FF) << 8))](https://github.com/rabbitmq/rabbitmq-dotnet-client/blob/master/projects/client/RabbitMQ.Client/src/util/NetworkBinaryReader.cs#L114-L115)
* [(int)(((i & 0xFF000000) >> 24) | ((i & 0x00FF0000) >> 8) | ((i & 0x0000FF00) << 8) | ((i & 0x000000FF) << 24))](https://github.com/rabbitmq/rabbitmq-dotnet-client/blob/master/projects/client/RabbitMQ.Client/src/util/NetworkBinaryReader.cs#L136-L143)
* [(long)(((i & 0xFF00000000000000) >> 56) | ((i & 0x00FF000000000000) >> 40) | ((i & 0x0000FF0000000000) >> 24) | ((i & 0x000000FF00000000) >> 8) | ((i & 0x00000000FF000000) << 8) | ((i & 0x0000000000FF0000) << 24) | ((i & 0x000000000000FF00) << 40) | ((i & 0x00000000000000FF) << 56))](https://github.com/rabbitmq/rabbitmq-dotnet-client/blob/master/projects/client/RabbitMQ.Client/src/util/NetworkBinaryReader.cs#L136-L143)
* [(ushort)(((i & 0xFF00) >> 8) | ((i & 0x00FF) << 8))](https://github.com/rabbitmq/rabbitmq-dotnet-client/blob/master/projects/client/RabbitMQ.Client/src/util/NetworkBinaryReader.cs#L167-L168)
* [(uint)(((i & 0xFF000000) >> 24) | ((i & 0x00FF0000) >> 8) | ((i & 0x0000FF00) << 8) | ((i & 0x000000FF) << 24))](https://github.com/rabbitmq/rabbitmq-dotnet-client/blob/master/projects/client/RabbitMQ.Client/src/util/NetworkBinaryReader.cs#L177-L180)
* [(ulong)(((i & 0xFF00000000000000) >> 56) | ((i & 0x00FF000000000000) >> 40) | ((i & 0x0000FF0000000000) >> 24) | ((i & 0x000000FF00000000) >> 8) | ((i & 0x00000000FF000000) << 8) | ((i & 0x0000000000FF0000) << 24) | ((i & 0x000000000000FF00) << 40) | ((i & 0x00000000000000FF) << 56))](https://github.com/rabbitmq/rabbitmq-dotnet-client/blob/master/projects/client/RabbitMQ.Client/src/util/NetworkBinaryReader.cs#L189-L196)

**Comment by lukebakken** [comment]
We should investigate using the code from [this project](https://github.com/jamesqo/Be.IO) with the appropriate fixes and accreditation.

**Comment by lukebakken** [comment]
Also see https://github.com/dotnet/corefx/issues/31265

**Comment by stebet** [comment]
I actually have an implementation that's easily usable for a proper cross-platform fix, that I used in the pipelines implementation here: https://github.com/rabbitmq/rabbitmq-dotnet-client/pull/706

It utilizes functionality from [System.Memory](https://www.nuget.org/packages/System.Memory/) (which has targets for the needed TFMs) and would be compatible with .NET Core moving forward.

**Comment by lukebakken** [comment]
@stebet what do you think about adding those changes for the `6.0` release? It sounds reasonable to me.

**Comment by stebet** [comment]
Should be doable. That library will also enable memory pooling and is well compatible with .NET Framework targets (used in StackExchange.Redis and Google.Protobuf for example).

Would also make sense to then split the big Pipeline PR into separate PRs, one for memory pooling and another for the actual pipeline integration.

**Comment by lukebakken** [comment]
> Would also make sense to then split the big Pipeline PR into separate PRs, one for memory pooling and another for the actual pipeline integration.

Smaller PRs are great... there's a chance I can understand them 😄
