### ISSUE TITLE
ConnectionFactory Protocol property is ignored

### ISSUE THREAD

**Issue by paulomorgado** [rabbitmq/rabbitmq-dotnet-client#453]
The value of the `Protocol` property of `ConnectionFactory` ([src/client/api/ConnectionFactory.cs#L233](https://github.com/rabbitmq/rabbitmq-dotnet-client/blob/master/projects/client/RabbitMQ.Client/src/client/api/ConnectionFactory.cs#L233)) is ignored.

If it's really not to be used, it should be decorated with the [Obsolete](https://docs.microsoft.com/en-us/dotnet/api/system.obsoleteattribute).

On the other hand, being able to plug a protocol might be nice for testing / faking scenarios.

**Comment by lukebakken** [comment]
Nope!

**Comment by kjnilsson** [comment]
It can go. 👍

**Comment by paulomorgado** [comment]
I still think the whole thing is missing some test friendly infrastructure. Something equivalent to the [test web server](https://docs.microsoft.com/en-us/aspnet/core/test/integration-tests).

A test protocol could be one way. Couldn't it?

**Comment by paulomorgado** [comment]
@kjnilsson, "it can go" means removing it?

**Comment by paulomorgado** [comment]
Totally agree! @kjnilsson

**Comment by paulomorgado** [comment]
Done! #456
