### ISSUE TITLE
Consider closing ConnectionFactory for derivation or open it consistently

### ISSUE THREAD

**Issue by paulomorgado** [rabbitmq/rabbitmq-dotnet-client#455]
The `CreateConnection` method of [`ConnectionFactory`](https://github.com/rabbitmq/rabbitmq-dotnet-client/blob/master/projects/client/RabbitMQ.Client/src/client/api/ConnectionFactory.cs) for creating a default connection (no arguments) is `virtual`.

However, the other overloads are not virtual. Any class that tries to extend `ConnectionFactory` will always be incomplete.

**Comment by kjnilsson** [comment]
If there is no reason for a property being virtual then it shouldn't.

**Comment by paulomorgado** [comment]
Than being said, why is `CreateConnection()` virtual and the other overloads not?

**Comment by bording** [comment]
Why would an end user ever need to override this class? Given that we're talking 6.0 breaking changes, I think taking a hard look at every public class and considering making them `sealed` is a decent idea.

**Comment by paulomorgado** [comment]
Here's why: https://github.com/Parametric/RabbitMQ.Fakes

Totally agree with making it sealed. And make `CreateFrameHandler` and `CreateFrameHandlerForHostname` not public.

And make `Connection` `internal`.

**Comment by warrenvdm79** [comment]
If we have some functionality which uses RabbitMQ and we want to test that functionality, we used the above mentioned Fakes project. https://github.com/Parametric/RabbitMQ.Fakes

Based on @paulomorgado comment, I take it there is some "bad blood". Not sure why, and I am not sure why someone would be so against a Fake framework to help with Unit Testing code. 

Considering it is now sealed in 6.0, what would you suggest as an alternative to Unit Testing functionality which depends on RabbitMQ.

**Comment by michaelklishin** [comment]
There is no "bad blood" but there's always friction around how much of the API is public and how much can be mocked out. Mocks are not very popular on the RabbitMQ team. Sometimes they are useful but nearly all tests we use for RabbitMQ itself, for example, are integration or property-based. So it simply wasn't a priority to keep API elements that mocking needs public.

I'd say the alternative now is to not use mocks. Note that consumers can be tested in relative isolation. I don't see much value in testing publishers with mocks. I'd rather invest time in integration and resiliency tests using something like Toxiproxy.

This client and some other suites use Docker files to make dependency setup (RabbitMQ nodes, an LDAP server, things of that kind) easier. If that was your excuse to going with mocks, perhaps that approach would be viable?
