### ISSUE TITLE
Concurrency issue with BasicPublish() on separate channels

### ISSUE THREAD

**Issue by TravisWilkins** [rabbitmq/rabbitmq-dotnet-client#457]
RabbitMQ version: 3.7.7 running on windows server 2012 R2
Erlang version: 21.0.1
.Net Client version: 5.1.0 targeting .net framework 4.6.2

RabbitMQ log of event:
2018-09-14 09:32:28.399 [info] <0.9336.1> accepting AMQP connection <0.9336.1> ([::1]:59933 -> [::1]:5672)
2018-09-14 09:32:28.491 [info] <0.9336.1> connection <0.9336.1> ([::1]:59933 -> [::1]:5672): user 'guest' authenticated and granted access to vhost '/'
2018-09-14 09:32:28.540 [error] <0.9336.1> Error on AMQP connection <0.9336.1> ([::1]:59933 -> [::1]:5672, vhost: '/', user: 'guest', state: running), channel 3:
 operation none caused a connection exception frame_error: "type 3, first 16 octets = <<0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0>>: {invalid_frame_end_marker,\n                                                                0}"
2018-09-14 09:32:31.553 [warning] <0.9336.1> closing AMQP connection <0.9336.1> ([::1]:59933 -> [::1]:5672):
fatal_frame_error

I am trying a rather simple test to make the same RPC pattern call on two different threads with two different channels. The payload is largish at about 1MB. If I shrink the payload smaller the issue goes away (or is at least harder to trigger). The publish calls will fail in the example about 80-90% of the time. If I use debug points which end up separating out the calls in time the issue will not occur which leads me to believe there is a concurrency issue here.

Code example:
static void Main(string[] args)
        {
            string exchange = "testExchange";
            try
            {
                using (RabbitProxy rp = new RabbitProxy())
                {
                    rp.Initialize();
                    Task<byte[]> t1 = Task.Run(() => rp.Rpc(exchange, new byte[999999]));
                    Task<byte[]> t2 = Task.Run(() => rp.Rpc(exchange, new byte[999999]));
                   
                    Task.WaitAll(t1, t2);
                }
            }
            catch (Exception e)
            {
            }
        }

public class RabbitProxy : IDisposable
    {
        private class RpcReplyData
        {
            public SemaphoreSlim ReceivedSignal { get; set; }
            public byte[] Data { get; set; }
        }

        private class PublishMessage
        {
            public string Exchange { get; set; }
            public string RoutingKey { get; set; } = String.Empty;
            public byte[] Data { get; set; }
            public IBasicProperties Props { get; set; }
            public RpcReplyData Reply { get; set; }
            public Guid Id { get; set; }
        }

        private readonly TimeSpan _timeOut = new TimeSpan(0, 0, 30);
        private const string ReplyToQueue = "amq.rabbitmq.reply-to";
        private const string Server = "localhost";
        private readonly ConcurrentDictionary<Guid, RpcReplyData> _rpcReplies = new ConcurrentDictionary<Guid, RpcReplyData>();
        private readonly ConcurrentDictionary<int, IModel> _threadIdToChannel = new ConcurrentDictionary<int, IModel>();
        private readonly ConnectionFactory _factory = new ConnectionFactory {HostName = Server};
        private IConnection _connection;

        public bool IsOpen => _connection.IsOpen && GetChannel(Thread.CurrentThread.ManagedThreadId).IsOpen;

        public async Task<byte[]> Rpc(string exchange, byte[] argument)
        {
            SemaphoreSlim receivedSignal = new SemaphoreSlim(0, 1);
            Guid id = Guid.NewGuid();
            RpcReplyData reply = new RpcReplyData {ReceivedSignal = receivedSignal};

            var channel = GetChannel(Thread.CurrentThread.ManagedThreadId);
            Console.WriteLine("ThreadId {0}", Thread.CurrentThread.ManagedThreadId);
            var props = channel.CreateBasicProperties();
            props.Timestamp = new AmqpTimestamp(DateTimeOffset.UtcNow.ToUnixTimeSeconds());
            props.CorrelationId =id.ToString();
            props.ReplyTo = ReplyToQueue;
            var message = new PublishMessage { Exchange = exchange, Data = argument, Props = props, Id = id, Reply = reply };
            
            Console.WriteLine("Channel Number: {0} ", channel.ChannelNumber);
            channel.BasicPublish(message.Exchange, message.RoutingKey, message.Props, message.Data);
            _rpcReplies.TryAdd(message.Id, message.Reply);

            Console.WriteLine("Channel Number: {0} - still going", channel.ChannelNumber);
            await receivedSignal.WaitAsync(_timeOut);
            Console.WriteLine("Channel Number: {0} - get a result", channel.ChannelNumber);
            return reply.Data;
        }

        private IModel GetChannel(int threadId)
        {
            IModel channel;
            _threadIdToChannel.TryGetValue(threadId, out channel);
            if (channel != null)
            {
                return channel;
            }

            channel = _connection.CreateModel();
            _threadIdToChannel.TryAdd(threadId, channel);
            var replyToConsumer = new EventingBasicConsumer(channel);
            replyToConsumer.Received += (model, ea) =>
            {
                Guid id;
                bool isGuid = Guid.TryParse(ea.BasicProperties.CorrelationId, out id);
                RpcReplyData reply;

                if (isGuid && _rpcReplies.TryRemove(id, out reply))
                {
                    reply.Data = ea.Body;
                    reply.ReceivedSignal.Release();
                }
            };

            channel.BasicConsume(ReplyToQueue, true, replyToConsumer);
            return channel;
        }

        public void Initialize()
        {
            Dispose();
            _connection = _factory.CreateConnection();
            var channel = GetChannel(Thread.CurrentThread.ManagedThreadId);
            channel.ExchangeDeclare("testExchange", "fanout");
            _connection.CallbackException += _connection_CallbackException;
            _connection.ConnectionShutdown += _connection_ConnectionShutdown;
            //channel.QueueDeclare(queue: "hello",
            //    durable: false,
            //    exclusive: false,
            //    autoDelete: false,
            //    arguments: null);
            //channel.QueueDeclare(queue: "testReply",
            //    durable: false,
            //    exclusive: false,
            //    autoDelete: false,
            //    arguments: null);
        }

        private void _connection_ConnectionShutdown(object sender, ShutdownEventArgs e)
        {
            throw new NotImplementedException();
        }

        private void _connection_CallbackException(object sender, CallbackExceptionEventArgs e)
        {
            throw new NotImplementedException();
        }

        public void Dispose()
        {
            _connection?.Abort();

            _connection?.Dispose();
            foreach (var channel in _threadIdToChannel.Values)
            {
                channel?.Dispose();
            }

            _threadIdToChannel.Clear();
        }
    }

**Comment by michaelklishin** [comment]
Thank you for your time.

Team RabbitMQ uses GitHub issues for specific actionable items engineers can work on. GitHub issues are not used for questions, investigations, root cause analysis, discussions of potential issues, etc (as defined by this team).

We get at least a dozen of questions through various venues every single day, often light on details.
At that rate GitHub issues can very quickly turn into a something impossible to navigate and make sense of even for our team. Because GitHub is a tool our team uses heavily nearly every day, the signal/noise ratio of issues is something we care about a lot.

Please post this to [rabbitmq-users](https://groups.google.com/forum/#!forum/rabbitmq-users).

Thank you.
