### ISSUE TITLE
Don't fail when no client certificates are provided

### ISSUE THREAD

**Issue by michaelklishin** [rabbitmq/rabbitmq-dotnet-client#46]
Our original solution in 36efc0085d7300cadb164469bc8ceada6d301624 makes it impossible to provide other TLS options and no certificates (see #44, #45).

We should check for null `X509CertificateCollection`s and use a blank one.

**Comment by michaelklishin** [comment]
cb2b6d22ca5f64204902c24557adf02aa85c8be6 suggests that not providing a client certificate is possible without any further changes.

**Comment by dumbbell** [comment]
Since 3.5.0.
