### ISSUE TITLE
SSL connections hangs

### ISSUE THREAD

**Issue by TiagoJVO** [rabbitmq/rabbitmq-dotnet-client#462]
Environment details:
* RabbitMQ 3.7.7
* Erlang 20.3
* RabbitMQ.Client 5.0.0
* Windows 10 x64

It looks like sometimes connections hang forever when there is a miss configuration for RaabitMQ SSL, for instance a problem on reading SSL certificate. Here is the stack trace where connections get hanged:
`mscorlib.dll!System.Threading.ManualResetEventSlim.Wait(int millisecondsTimeout, System.Threading.CancellationToken cancellationToken)	Unknown
mscorlib.dll!System.Threading.Tasks.Task.SpinThenBlockingWait(int millisecondsTimeout, System.Threading.CancellationToken cancellationToken)	Unknown
mscorlib.dll!System.Threading.Tasks.Task.InternalWait(int millisecondsTimeout, System.Threading.CancellationToken cancellationToken)	Unknown
mscorlib.dll!System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task task)	Unknown
RabbitMQ.Client.dll!RabbitMQ.Client.SslHelper.TcpUpgrade(System.IO.Stream tcpStream, RabbitMQ.Client.SslOption sslOption)	Unknown
RabbitMQ.Client.dll!RabbitMQ.Client.Impl.SocketFrameHandler.SocketFrameHandler(RabbitMQ.Client.AmqpTcpEndpoint endpoint, System.Func<System.Net.Sockets.AddressFamily, RabbitMQ.Client.ITcpClient> socketFactory, int connectionTimeout, int readTimeout, int writeTimeout)	Unknown
RabbitMQ.Client.dll!RabbitMQ.Client.ConnectionFactory.CreateFrameHandler(RabbitMQ.Client.AmqpTcpEndpoint endpoint)	Unknown
RabbitMQ.Client.dll!RabbitMQ.Client.EndpointResolverExtensions.SelectOne<System.__Canon>(RabbitMQ.Client.IEndpointResolver resolver, System.Func<RabbitMQ.Client.AmqpTcpEndpoint, System.__Canon> selector)	Unknown
RabbitMQ.Client.dll!RabbitMQ.Client.Framing.Impl.AutorecoveringConnection.Init(RabbitMQ.Client.IEndpointResolver endpoints)	Unknown
RabbitMQ.Client.dll!RabbitMQ.Client.ConnectionFactory.CreateConnection(RabbitMQ.Client.IEndpointResolver endpointResolver, string clientProvidedName)	Unknown
Project.Plugin.RabbitMQ.dll!Project.Plugin.RabbitMQ.RabbitMQPubSub.CreateConnection() Line 290	C#
Project.Plugin.RabbitMQ.dll!Project.Plugin.RabbitMQ.LazyInitializer<RabbitMQ.Client.IConnection>.Value.get() Line 129	C#
Project.Plugin.RabbitMQ.dll!Project.Plugin.RabbitMQ.RabbitMQPubSub.IsAvailable(out System.Exception ex) Line 251	C#
Project.Plugin.RabbitMQ.dll!Project.Plugin.RabbitMQ.RabbitMQPubSub.IsAvailable() Line 245	C#`

And here you have my `CreateConnection` configurations:
`
ConnectionFactory factory = new ConnectionFactory {
	AutomaticRecoveryEnabled = true,
	TopologyRecoveryEnabled = true,
	NetworkRecoveryInterval = TimeSpan.FromSeconds(1),
	RequestedConnectionTimeout = 15000,
	HostName = "somehost",
	Port = 5671,
	UserName = "myUser",
	Password = "myPassword",
	VirtualHost = "myHost",
};
factory.Ssl.Enabled = true;
factory.Ssl.ServerName = "somehost";
factory.Ssl.Version =
	System.Security.Authentication.SslProtocols.Tls
	| System.Security.Authentication.SslProtocols.Tls11
	| System.Security.Authentication.SslProtocols.Tls12;
return factory.CreateConnection();
`

I saw several posts where people report this problem, and they always get help to overcome their configuration problem, but that it's not what I am trying to archive here, I need to know that there is a problem on the configuration pragmatically, for instance with a timeout on that `CreateConnection`.
I already saw a bug report and a fix proposal from 2014 ([here](https://lists.rabbitmq.com/pipermail/rabbitmq-discuss/2014-February/033861.html)). Is it possible to have a fix for this, or at least a workarround?

Cheers,
Tiago Oliveira

**Comment by michaelklishin** [comment]
Thank you for your time.

Team RabbitMQ uses GitHub issues for specific actionable items engineers can work on. GitHub issues are not used for questions, investigations, root cause analysis, discussions of potential issues, etc (as defined by this team).

We get at least a dozen of questions through various venues every single day, often light on details.
At that rate GitHub issues can very quickly turn into a something impossible to navigate and make sense of even for our team. Because GitHub is a tool our team uses heavily nearly every day, the signal/noise ratio of issues is something we care about a lot.

Please post this to [rabbitmq-users](https://groups.google.com/forum/#!forum/rabbitmq-users).

Thank you.

**Comment by michaelklishin** [comment]
I'm not sure if you mean "programmaticlaly" or "pragmatically" but what you are observing with malformed certificates has been tracked down to an Erlang's TLS implementation bug first reported as https://github.com/ninenines/ranch/issues/196 and then https://bugs.erlang.org/browse/ERL-664. There is no way for a client to know.

RabbitMQ 3.7.8 will do a couple more checks early on boot and we have ideas for further improvements in mind but RabbitMQ does not and will not implement TLS, so if a TLS loads something from disk on demand — and in Erlang it does — we cannot guarantee or know if a TLS connection then stops making progress.

RabbitMQ client connections have a couple of timeouts: for initial TCP connection and for AMQP 0-9-1 handshake. RabbitMQ server has a TLS handshake timeout, too. As always with timeouts, they can naturally happen from time to time, and low values (e.g. < 5s) can lead to false positives.

**Comment by TiagoJVO** [comment]
Ok, we'll wait for Erlang 21.1 version. Thanks!
