### ISSUE TITLE
Make implementation internal

### ISSUE THREAD

**Issue by paulomorgado** [rabbitmq/rabbitmq-dotnet-client#466]
As an exercise, I made almost every implementation detail internal: https://github.com/paulomorgado/rabbitmq-dotnet-client/tree/internal

There's surely room for improvement. But I think it's a good start.

**Comment by michaelklishin** [comment]
@paulomorgado so what's the scope of this issue? Please submit a PR if you intend your experiment to be considered as is?

**Comment by paulomorgado** [comment]
I first thought of it as conversation starter.

I'll do some more work on it and submit a PR.
