### ISSUE TITLE
No Way to Determine What Queue a Message Came From

### ISSUE THREAD

**Issue by rnunley** [rabbitmq/rabbitmq-dotnet-client#467]
On the IModel or IFullModel, it would be useful to have a property that has the bound queue name so when we're creating an arbitrator singleton for many queues with a callback method per queue, we can determine which callback to call without leaking the RabbitMQ event delegate. 

As it is currently, neither the sender nor event params of the EventingBasicConsumer->Received delegate tell us what queue the message originated from.

**Comment by lukebakken** [comment]
Hello! Thanks for using RabbitMQ.

I recommend using a closure for the `Received` callback that captures the queue's name. There are probably other methods to accomplish this as well. If I am mis-understanding your requirement and how C# language features can't solve them, please reply to the mailing list ([link](https://groups.google.com/forum/#!forum/rabbitmq-users)) with a complete project demonstrating your issue in a repository and I'll check it out.

**Comment by dsidirop** [comment]
> I recommend using a closure for the Received callback that captures the queue's name.

I am not sure I understand the solution proposed here: If we bind to multiple queues while having one subscription-callback attached to the underlying channel how can we tell from which queue we picked the message from?

Sorry if I am missing something.

**Comment by lukebakken** [comment]
You would have to use multiple callbacks, each capturing the queue's name.

**Comment by michaelklishin** [comment]
Alternatively you can use different explicitly provided consumer tags (one per queue name?) which must be unique on a single channel. Consumer tag is available in delivery metadata.
