### ISSUE TITLE
Make IQueueingBasicConsumer and ISubscription public

### ISSUE THREAD

**Issue by abellix** [rabbitmq/rabbitmq-dotnet-client#47]
I am trying to have some cases covered by tests, some of the interfaces I need to mock are made internal in the solution (e.g. I would like to mock IQueueingBasicConsumer). 
Is there any reason for interfaces like IQueueingBasicConsumer, ISubscription not being exposed?

**Comment by michaelklishin** [comment]
Not a lot of people asked to date. What interfaces do you want to implement?

**Comment by abellix** [comment]
those two would be enough for the moment

**Comment by dumbbell** [comment]
Commits fixing this issue were cherry-picked to `stable`.
