### ISSUE TITLE
Consider adding an API approval test

### ISSUE THREAD

**Issue by bording** [rabbitmq/rabbitmq-dotnet-client#470]
With all of the other changes going on into this upcoming 6.0 release, one thing I think would be a good idea would be to add a test that clearly shows what the public API surface of the library is.

This sort of test would let you see changes to the public types as they are made, making it much easier to detect breaking changes.

If this sounds like something you'd be okay with adding, I can submit a PR.

**Comment by kjnilsson** [comment]
@bording sounds like a great idea.

**Comment by michaelklishin** [comment]
Don't existing integration test mostly serve that purpose already? I mean, I haven't seen your PR yet but what kind of test would go beyond what 100s of existing tests already cover?

**Comment by bording** [comment]
@michaelklishin Here's an example of what I'm talking about: https://github.com/Particular/NServiceBus/blob/develop/src/NServiceBus.Core.Tests/ApprovalFiles/APIApprovals.ApproveNServiceBus.netstandard.approved.txt

That file is generated as part of a test, so if anything changes the public API surface, the test will fail and leave you with a file that you can diff to see what has changed.

At that point you either realize you shouldn't make the proposed change, or you update the approved file to allow it, and the test passed again.

**Comment by michaelklishin** [comment]
What interfaces should be covered with such tests? Connection factory, connection and channel? Consumers, too?

**Comment by bording** [comment]
I the idea is that every public member of every public type will end up in the file since any change there would be externally visible.

That's why it's so important to internalize all the implementation, and only have the actual API surface public.

**Comment by kjnilsson** [comment]
Closing as done.
