### ISSUE TITLE
Do not default to IP.v4 - assert it's IP.v4

### ISSUE THREAD

**Issue by paulomorgado** [rabbitmq/rabbitmq-dotnet-client#481]
This [code](https://github.com/rabbitmq/rabbitmq-dotnet-client/blob/master/projects/client/RabbitMQ.Client/src/client/impl/SocketFrameHandler.cs#L101) assumes that, if it's not `AddressFamily.InterNetworkV6`, then it must be `AddressFamily.InterNetwork`.

It should make sure it is one or the other.

**Comment by tylerohlsen** [comment]
A potential fix / workaround would be to allow for a statically settable default for the [AddressFamily](https://github.com/rabbitmq/rabbitmq-dotnet-client/blob/v5.1.0/projects/client/RabbitMQ.Client/src/client/api/AmqpTcpEndpoint.cs#L177).  Then either `ConnectUsingIPv6` or `ConnectUsingIPv4` would be executed and not both.  

This can be done today by using one of the ConnectionFactory.CreateConnection overloads that takes in a list of AmqpTcpEndpoint where you can set the AddressFamily before passing it to CreateConnection.  But in my case, I do not control the code that calls to CreateConnection.  

Thoughts?

**Comment by michaelklishin** [comment]
@tylerohlsen a way to force use of a certain IP family makes sense to me. Please submit a PR?

**Comment by lukebakken** [comment]
Fixed by #651
