### ISSUE TITLE
Consider making IAsyncConnectionFactory public

### ISSUE THREAD

**Issue by paulomorgado** [rabbitmq/rabbitmq-dotnet-client#482]
While the API for creating asynchronous connections is not the best approach, it is what we have and it's impossible to rely on interfaces only to create asynchronous connections.

This would be immediately solved if `IAsyncConnectionFactory` was public.

**Comment by michaelklishin** [comment]
At this point I think it makes a lot of sense. @kjnilsson @lukebakken  WDYT?
