### ISSUE TITLE
Consumer async It does not work asynchronous .netCore

### ISSUE THREAD

**Issue by radupopConnatix** [rabbitmq/rabbitmq-dotnet-client#485]
Rabbitmq server version rabbitmq-server-3.7.8
Erlang: OTP 21.0
Os: Windows 10 Pro

Let's say I have a channel that it accepts maximum 10 items. Then I want to have work done in the received to be run asynchronous. 
My first sample of code was: 
`var factory = new ConnectionFactory() { HostName = "localhost"};
            using(var connection = factory.CreateConnection())
            using(var channel = connection.CreateModel())
            {
                channel.QueueDeclare(queue: "hello");

                var consumer = new  EventingBasicConsumer(channel);
                consumer.Received += (model, ea) =>
                {
                    var body = ea.Body;
                    var message = Encoding.UTF8.GetString(body);
                    channel.BasicAck(ea.DeliveryTag, false);
                    Console.WriteLine(" [x] Received {0}", message);
                    Thread.Sleep(1000); //simulate delay
                };
                channel.BasicQos(0, 10, false);
                channel.BasicConsume("hello", false, consumer);
            }`
I have seen that it takes it in sequence waiting 1 second.

After looking on the web I have upgrade the solution to
`var factory = new ConnectionFactory() { HostName = "localhost", DispatchConsumersAsync = true};
            using(var connection = factory.CreateConnection())
            using(var channel = connection.CreateModel())
            {
                channel.QueueDeclare(queue: "hello");

                var consumer = new  AsyncEventingBasicConsumer(channel);
                consumer.Received += async (model, ea) =>
                {
                    var body = ea.Body;
                    var message = Encoding.UTF8.GetString(body);
                    channel.BasicAck(ea.DeliveryTag, false);
                    Console.WriteLine(" [x] Received {0}", message);
                    await Task.Delay(1000); // simulate delay
                };
                channel.BasicQos(0, 10, false);
                channel.BasicConsume("hello", false, consumer);
            }`

I have expected to see let's say 10 message pop up on the console, but instead I have got the same behavior as in the first synchronous approach, waiting 1 second between messages.

When I put a break point inside the delegate I could see that it wait to the delegate to finish before another message is process.

Is this he desired behavior? If yes, what is the differences between sync and async versions?

**Comment by michaelklishin** [comment]
Thank you for your time.

Team RabbitMQ uses GitHub issues for specific actionable items engineers can work on. GitHub issues are not used for questions, investigations, root cause analysis, discussions of potential issues, etc (as defined by this team).

We get at least a dozen of questions through various venues every single day, often light on details.
At that rate GitHub issues can very quickly turn into a something impossible to navigate and make sense of even for our team. Because GitHub is a tool our team uses heavily nearly every day, the signal/noise ratio of issues is something we care about a lot.

Please post this to [rabbitmq-users](https://groups.google.com/forum/#!forum/rabbitmq-users).

Thank you.

**Comment by michaelklishin** [comment]
See [QoS and acknowledgement mode documentation](https://rabbitmq.com/confirms.html). The difference is in the implementation of consumer operation dispatch. The rest is dictated by the protocol and not client library or consumer implementation details.
