### ISSUE TITLE
IModel.Dispose() hangs after consuming with IBasicConsumer.HandleBasicDeliver()

### ISSUE THREAD

**Issue by GarrettDavis** [rabbitmq/rabbitmq-dotnet-client#49]
Starting with version 3.5 of .NET client, I'm seeing an issue with disposing models after consuming on that channel.  Dispose() will hang indefinitely.  There was nothing wrong with the connection when this happened.  Everything was running smoothly.  I have an application that may frequently create and dispose channels on which we consume messages.  In the mean time I have reverted to 3.4.3 so my application works.

Thanks

**Comment by michaelklishin** [comment]
Please use `IModel#Close` instead of `Dispose`. There is a bug about re-working `Dispose` already. If `Close` also hangs, please take a thread dump and file a new issue.

Thank you.
