### ISSUE TITLE
Make DefaultBasicConsumer.m_consumerCanceled private

### ISSUE THREAD

**Issue by canton7** [rabbitmq/rabbitmq-dotnet-client#493]
In master, `DefaultBasicConsumer` has the public field `m_consumerCanceled`. [See here](https://github.com/rabbitmq/rabbitmq-dotnet-client/blob/d9a33838c60a2b87fe013017fdcaa98404cece64/projects/client/RabbitMQ.Client/src/client/api/DefaultBasicConsumer.cs#L58).

Is this intentional? It's very rare to want to expose the backing delegate for an event directly. Anyone can run `someConsumer.m_consumerCanceled = null` and remove all subscribers to the `ConsumerCanceled` event.

(The logic used to raise the ConsumerCanceled event is also very unusual - it's normally sufficient to raise the event in the usual way, rather than looping through its invocation list)

**Comment by michaelklishin** [comment]
I believe this is covered by #445, so no separate issue is really necessary.
