### ISSUE TITLE
Feature: Add certificate revocation list validation property to improve security

### ISSUE THREAD

**Issue by SeekToDestroy** [rabbitmq/rabbitmq-dotnet-client#499]
Simple feature to add.
Add a property to the ssl configuration for ValidateCRL or EnforceCRLValidation.
Use this property in the SSLStream. AuthenticateAsClientAsync call instead of FALSE as it is now.

Also, why call the async method with getawaiter().getresult() instead of just calling the synchronous version?.
GetResult() is really normally only called by the .NET library itself.

Its all a simple change and that will improve security.

**Comment by kjnilsson** [comment]
This sounds like a reasonable feature to add. Would you like to provide a pull request for this simple change?

The reason the Async version is used is that the synchronous version was not available in .NET core 1.0

**Comment by michaelklishin** [comment]
@SeekToDestroy since you have specific ideas about improvement, please submit a PR.

**Comment by michaelklishin** [comment]
@kjnilsson @bording  I believe per [the kind of] SemVer [we've been practicing] it's appropriate to ship #500 in a minor version release, WDYT?

**Comment by michaelklishin** [comment]
Addressed by @SeekToDestroy in #500. Thank you.

**Comment by bording** [comment]
@michaelklishin Taking a quick look at the PR, it does seem like it should be okay for that to be in a new minor.
