### ISSUE TITLE
Cannot parse “client_properties” header.

### ISSUE THREAD

**Issue by forlayo** [rabbitmq/rabbitmq-dotnet-client#504]
I'm listening for connection changes through events pluging ("amq.rabbitmq.event", "connection.#").

It works properly so I'm adding at java side two additional parameters as clientproperties, to get the identity of the user that connects or disconnect.

However at c# side I can only access these properties as a list of byte[], and not sure on how to convert it to a Dictionary or so..

If I print all entries

```
if (args.BasicProperties.Headers.TryGetValue("client_properties", out object value))
            {
                var items = value as List<object>;
                foreach(var item in items)
                {
                    Console.WriteLine($"{item.GetType().ToString()}");
                    var bytes = item as byte[];
                    result.Add(Encoding.UTF8.GetString(bytes));
                }
            }
```
I can see this:
```
{<<"platform">>,longstr,<<"Java">>}
{<<"capabilities">>,table,[{<<"connection.blocked">>,bool,true},{<<"basic.nack">>,bool,true},{<<"exchange_exchange_bindings">>,bool,true},{<<"authentication_failure_close">>,bool,true},{<<"publisher_confirms">>,bool,true},{<<"consumer_cancel_notify">>,bool,true}]}
{<<"groupId">>,longstr,<<"1e6e935f0d4d9ec446d67dadc85cbafd10d1a095">>}
{<<"information">>,longstr,<<"Licensed under the MPL. See http://www.rabbitmq.com/">>}
{<<"version">>,longstr,<<"4.8.1">>}
{<<"copyright">>,longstr,<<"Copyright (c) 2007-2018 Pivotal Software, Inc.">>}
{<<"product">>,longstr,<<"RabbitMQ">>}
```
What kind of object format is and how can I parse this?:
`{<<id>>,type,<<value>>}`

I've posted same question on stackoverflow -> https://stackoverflow.com/questions/53836624/rabbitmq-parsing-client-properties-header-from-c-sharp

**Comment by michaelklishin** [comment]
Thank you for your time.

Team RabbitMQ uses GitHub issues for specific actionable items engineers can work on. GitHub issues are not used for questions, investigations, root cause analysis, discussions of potential issues, etc (as defined by this team).

We get at least a dozen of questions through various venues every single day, often light on details.
At that rate GitHub issues can very quickly turn into a something impossible to navigate and make sense of even for our team. Because GitHub is a tool our team uses heavily nearly every day, the signal/noise ratio of issues is something we care about a lot.

Please post this to [rabbitmq-users](https://groups.google.com/forum/#!forum/rabbitmq-users).

Thank you.

**Comment by michaelklishin** [comment]
Thank you for your time.

Team RabbitMQ uses GitHub issues for specific actionable items engineers can work on. This assumes that we have a certain amount of information to work with.

Getting all the details necessary to reproduce an issue, make a conclusion or even form a hypothesis about what's happening can take a fair amount of time. Our team is multiple orders of magnitude smaller than the RabbitMQ community. Please help others help you by providing a way to reproduce the behavior you're
observing and sharing as much relevant information as possible [on the list](https://groups.google.com/forum/#!forum/rabbitmq-users):

 * Server, client library and plugin (if applicable) versions used
 * Server logs
 * A code example or terminal transcript that can be used to reproduce
 * **Full** exception stack traces (not a single line message)
 * `rabbitmqctl status` (and, if possible, `rabbitmqctl environment` output)
 * Other relevant things about the environment and workload, e.g. OS/systemd logs, [a traffic capture](https://www.rabbitmq.com/amqp-wireshark.html), deployment tool logs, etc

Feel free to edit out hostnames and other potentially sensitive information.

When/if we have a complete enough understanding of what's going on, a recommendation will be provided or a new issues with more context will be filed.

Thank you.

**Comment by michaelklishin** [comment]
Please provide a set of steps to reproduce (we don't even know what .NET client version is used here). I'm not sure why that particular table would not be parsed by the client but if we have evidence of that, it should be addressed.
