### ISSUE TITLE
Any plans for support for aspnet5 and aspnetcore5 ?

### ISSUE THREAD

**Issue by StefH** [rabbitmq/rabbitmq-dotnet-client#51]
Any plans for support for aspnet5 and aspnetcore5 ?

**Comment by michaelklishin** [comment]
How is ASP.NET relevant to this project? Do you mean .NET 5, perhaps? It likely should work without any modifications.

**Comment by michaelklishin** [comment]
It's a good idea to post questions to [rabbitmq-users](https://groups.google.com/forum/#!forum/rabbitmq-users).

**Comment by StefH** [comment]
Indeed, I was referring to vNext : http://www.asp.net/vnext/overview/aspnet-vnext/aspnet-5-overview

**Comment by michaelklishin** [comment]
We'll assess compatibility with it as soon as it is out.
