### ISSUE TITLE
Mark all RabbitMQ.Client.MessagePatterns as obsolete

### ISSUE THREAD

**Issue by michaelklishin** [rabbitmq/rabbitmq-dotnet-client#514]
`Subscription` specifically has been deprecated since at least 3.4 where we had both a modern consumer operation dispatcher which prevents consumers from blocking I/O activity and automatic connection recovery which `Subscription` interferes with basically by design. However, it was never properly deprecated and removed from the docs.

See [this rabbitmq-users thread](https://groups.google.com/forum/#!topic/rabbitmq-users/PVaJzqa_qeg) for background.

[168224294]

**Comment by michaelklishin** [comment]
@bording @kjnilsson @lukebakken  FYI.

**Comment by lukebakken** [comment]
Confirmed marked as `Obsolete` in `5.x` branch.
