### ISSUE TITLE
Consider removing implementations for unused events in Connection

### ISSUE THREAD

**Issue by antiduh** [rabbitmq/rabbitmq-dotnet-client#515]
Split from #512 .

The `Connection` class exposes events that it never fires - `RecoverySucceeded` and `ConnectionRecoveryError`. It seems these events are defined in `Connection` because they're part of the `IConnection` interface, which seems to define these events on behalf of `AutorecoveringConnection`.

As an example, here are all of the callsites to the `RecoverySucceeded` event and its backing field:

```
        public event EventHandler<EventArgs> RecoverySucceeded
        {
            add
            {
                lock (m_eventLock)
                {
                    m_recoverySucceeded += value;
                }
            }
            remove
            {
                lock (m_eventLock)
                {
                    m_recoverySucceeded -= value;
                }
            }
        }


        private void Dispose(bool disposing)
        {
           ...
                    m_recoverySucceeded = null;
           ...
         }
```

Since the events are never fired from within `Connection`, but they need to be implemented by `Connection` to meet the `IConnection` interface, the events should be replaced with empty add-remove handlers, and all backing fields should be removed.

```
        public event EventHandler<EventArgs> RecoverySucceeded
        {
            add { }
            remove { }
        }

        public event EventHandler<ConnectionRecoveryErrorEventArgs> ConnectionRecoveryError
        {
            add { }
            remove {}
        }
```

**Comment by michaelklishin** [comment]
We can consider extracting an `IAutorecoverableConnection`, it sounds like a natural thing to do to me.

**Comment by antiduh** [comment]
That was an option I was thinking of, but I didn't want to overstep my bounds; I was aiming for fixes that are low-impact / non-breaking, but I'm ok with separating the concerns into different interfaces.

**Comment by michaelklishin** [comment]
@antiduh that's fine and appreciated. Larger changes can always follow later.

**Comment by michaelklishin** [comment]
We will undo this in https://github.com/rabbitmq/rabbitmq-dotnet-client/issues/940 for `7.0`. Using empty handlers and providing `IConnection` users a way to register recovery events makes more sense. Casting to `IAutorecoveringConnection` is not intuitive at all.
