### ISSUE TITLE
MapMessageBuilder.GetContentBody() throws NullReferenceException

### ISSUE THREAD

**Issue by BrentSouza** [rabbitmq/rabbitmq-dotnet-client#53]
Looks like the Body is being set to null before actually writing the contents.

```c#
public override byte[] GetContentBody()
{
	this.Body = null;
	MapWireFormatting.WriteMap(base.Writer, this.Body);
	return base.GetContentBody();
}
```

**Comment by michaelklishin** [comment]
That indeed looks wrong. Was changed in 795a718c1973f418ce7f6adac866ae587b03a4db. Feel free to submit a PR that undoes the damage :)

**Comment by michaelklishin** [comment]
@BrentSouza see #55. You can [build the library from source](https://github.com/rabbitmq/rabbitmq-dotnet-client/blob/master/RUNNING_TESTS.md#building) and give it a try.

**Comment by dumbbell** [comment]
Since RabbitMQ 3.5.0.
