### ISSUE TITLE
Use named arguments in C# tutorials

### ISSUE THREAD

**Issue by michaelklishin** [rabbitmq/rabbitmq-dotnet-client#56]
See https://github.com/rabbitmq/rabbitmq-dotnet-client/issues/20. It's already possible in C# as we require .NET 4.0 now, so we should update the tutorials.

**Comment by mfloryan** [comment]
Shouldn't this be an issue on https://github.com/rabbitmq/rabbitmq-tutorials ?

**Comment by michaelklishin** [comment]
This issue grew out of something filed in this repo. We can move it.

**Comment by michaelklishin** [comment]
Thank you. I'll close this when we update rabbitmq-website to match.

**Comment by Pliner** [comment]
As I see now, I forgot to update cs files from dotnet folder... :(

**Comment by Pliner** [comment]
Done!

**Comment by Pliner** [comment]
@michaelklishin If you want I could update website too, but actually site has a bit different version of .cs in comparison to dotnet-visual-studio folder. Should I replace site versions to dotnet-visual-studio folder?

**Comment by michaelklishin** [comment]
I'd rather adapt the tutorials for now. There will be more code changes coming, so we'll have a way to compare the two and pick a version we like more.

**Comment by michaelklishin** [comment]
This is done.
