### ISSUE TITLE
Connection handle leak

### ISSUE THREAD

**Issue by michaelklishin** [rabbitmq/rabbitmq-dotnet-client#58]
See [this thread](https://groups.google.com/d/msg/rabbitmq-users/VGK5zVMUJmU/8_3KdrqRP88J). The report includes a test case which looks reasonable.

**Comment by michaelklishin** [comment]
First attempt at reproducing this: unsuccessful.

``` csharp
using NUnit.Framework;
using RabbitMQ.Client.Exceptions;
using System;
using System.Diagnostics;
using System.Threading;

namespace RabbitMQ.Client.Unit
{
    [TestFixture]
    public class TestConnectionChurnHandleLeak : IntegrationFixture
    {
        [Test]
        public void TestHandleLeak()
        {
            var cf = new ConnectionFactory();
            var me = Process.GetCurrentProcess();
            Console.WriteLine("{0} handles before the test...", me.HandleCount);
            for (var i = 0; i < 1000; i++)
            {
                using (var conn = cf.CreateConnection())
                {
                }
            }
            Thread.Sleep(TimeSpan.FromSeconds(5));
            Console.WriteLine("{0} handles after the test...", me.HandleCount);
        }
    }
}
```

Output:

````
580 handles before the test...
580 handles after the test..
```

**Comment by michaelklishin** [comment]
Leaving this open to see if we can gather more details.

**Comment by chrhlnd** [comment]
Possibly a tangent. I've noticed the Heartbeat timers not getting cleaned up while debugging on my project. Had a use case where a connection would get setup and torn down as needed. My timers kept growing forever though causing various reference to exist in the vm forever.

Connection.cs

~95

        private Timer _heartbeatReadTimer;
        private Timer _heartbeatWriteTimer;

Don't seem to have disposes.

**Comment by michaelklishin** [comment]
@chrhlnd yup, that seems to be the case, thank you!

**Comment by michaelklishin** [comment]
@chrhlnd please try with master (a nightly build will be available tomorrow). Thank you for pointing this out.

**Comment by michaelklishin** [comment]
I've cherry-picked this to `stable`.

**Comment by mikebridge** [comment]
I can confirm that the nightly build of the 3.5.2 prerelease fixes a memory leak which is leaving several objects in memory, including RabbitMQ.Client.Framing.Impl.Connection.  Is there any timeline on an official update to nuget?

**Comment by michaelklishin** [comment]
3.5.2 is scheduled for the first decade of May.

**Comment by mikebridge** [comment]
Any thoughts about the possibility creating a beta release on nuget?  This seems like a pretty serious defect---I assume it will affect anyone who tries to use it.

I've been trying all night to hack a working version from the nightly builds but the transient dependencies with strong naming is killing me. :(

**Comment by mikebridge** [comment]
Finally got it working with 3.4.0.

**Comment by michaelklishin** [comment]
@mikebridge yes, you can use a earlier version of the client. Client and server versions don't have to be in lock step.

**Comment by mikebridge** [comment]
@michaelklishin Good to know, thanks!  Memory is still stable after 9 hours, so the switch to 3.4.0 seems to have fixed it for the time being.

**Comment by michaelklishin** [comment]
Also, unless you configure the server to enable TLS, provide certificates and key, etc, you will see 5 failures saying that broker on port 5671 is not reachable. Don't worry about it.

**Comment by acquleo** [comment]
hi @michaelklishin,
from my point of view the test must be changed in that way:

            var cf = new ConnectionFactory();
            var me = Process.GetCurrentProcess();
            Console.WriteLine("{0} handles before the test...", me.HandleCount);
            //do job
            me = Process.GetCurrentProcess(); //update process information
            Console.WriteLine("{0} handles after the test...", me.HandleCount);

After that modification I can see a real handle leak.

**Comment by michaelklishin** [comment]
@acquleo this is an equally simplistic test. You need to run it for a long time and then wait for minutes to make sure all connections are closed.

I'm not sure what a "real" handle leak is. Feel free to profile what objects may still be leaked. There are a few days to try to get a better version into 3.5.2.

**Comment by acquleo** [comment]
@michaelklishin with 100 cycles the handle count change from ~200 to ~800.
244 handles before the test...
822 handles after the test...
Do you mean that they will be destroyed after some time?

**Comment by acquleo** [comment]
@michaelklishin what I tried to said is that the code on the unit test is not only simplistic but wrong because it read the handle count only the first time.
On the second Console.WriteLine it display the same variable with the same value of the first WriteLine.

 var me = Process.GetCurrentProcess(); 
Console.WriteLine("{0} handles before the test...", me.HandleCount);
//do job
Console.WriteLine("{0} handles after the test...", me.HandleCount); //Handle count not updated

**Comment by michaelklishin** [comment]
@acquleo I have no reason to not believe you but the docs do not suggest that `GetCurrentProcess` returns an immutable snapshot. Again, feel free to take a look into it: memory profiler should quickly tell us what it it may be. Yes, TCP connections are not always released immediately by the OS.

**Comment by acquleo** [comment]
@michaelklishin I was testing the official binary dll, but the leak it doesn't happen with the compiled library from source code... so it will be fixed with 3.5.2.
Thanks

**Comment by michaelklishin** [comment]
@acquleo thank you for confirming!

**Comment by dumbbell** [comment]
Since RabbitMQ 3.5.0.
