### ISSUE TITLE
Heartbeat causing connection issues

### ISSUE THREAD

**Issue by tellybrown** [rabbitmq/rabbitmq-dotnet-client#637]
This is on the publisher side.  My client sends just fine but after about 15-30 seconds the Heartbeat triggers and causes my application to essentially hang for 60 seconds.  Then the exception occurs and puts my connection into a failed state and the same exception occurs when I attempt to use it.  It seems like the library is trying to send the heartbeat but times out because I am sending maybe too fast or somehow blocking the heartbeat from sending/receiving.

The only code that is somewhat new is the GetProperties().  Before I was sending a null for the properties.

```
        public async Task RunAsync(CancellationToken cancellationToken)
        {
            try
            {
                using (var conn = new SqlConnection(""))
                {
                    await conn.OpenAsync();
                    while (!cancellationToken.IsCancellationRequested)
                    {
                        using (SqlTransaction tran = conn.BeginTransaction())
                        {
                            var eventData = await Read(conn, tran);
                            if (eventData == null)
                            {
                                break;
                            }
                            //Do some work
                            await _queue.SendAsync(topic, eventData);
                            tran.Commit();
                        }
                    }
                }
                await Task.Delay(Setting.Sleep);
            }
            catch (Exception ex)
            {
                await _logClient.WriteExceptionAsync(ex);
            }
        }
```

I am wrapping the BasicPublish in a Task.Run

```
        public async Task SendAsync(string topic, T t)
        {
            await Task.Run(() =>
            {
                var body = GetMessage(t);
                _Channel.BasicPublish(_Exchange, topic, GetBasicProperties(), body);
            });
        }
        protected internal IBasicProperties GetBasicProperties()
        {
            var ret = _Channel.CreateBasicProperties();
            ret.DeliveryMode = 2;
            return ret;
        }
```

```

1) Exception Information
*********************************************
Exception Type: RabbitMQ.Client.Exceptions.AlreadyClosedException
ShutdownReason: AMQP close-reason, initiated by Library, code=0, text="End of stream", classId=0, methodId=0, cause=System.IO.IOException: Unable to write data to the transport connection: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond. ---> System.Net.Sockets.SocketException: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond
   at System.Net.Sockets.NetworkStream.Write(Byte[] buffer, Int32 offset, Int32 size)
   --- End of inner exception stack trace ---
   at System.Net.Sockets.NetworkStream.Write(Byte[] buffer, Int32 offset, Int32 size)
   at RabbitMQ.Client.Impl.SocketFrameHandler.Write(Byte[] buffer)
   at RabbitMQ.Client.Framing.Impl.Connection.HeartbeatWriteTimerCallback(Object state)
Message: Already closed: The AMQP operation was interrupted: AMQP close-reason, initiated by Library, code=0, text="End of stream", classId=0, methodId=0, cause=System.IO.IOException: Unable to write data to the transport connection: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond. ---> System.Net.Sockets.SocketException: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond
   at System.Net.Sockets.NetworkStream.Write(Byte[] buffer, Int32 offset, Int32 size)
   --- End of inner exception stack trace ---
   at System.Net.Sockets.NetworkStream.Write(Byte[] buffer, Int32 offset, Int32 size)
   at RabbitMQ.Client.Impl.SocketFrameHandler.Write(Byte[] buffer)
   at RabbitMQ.Client.Framing.Impl.Connection.HeartbeatWriteTimerCallback(Object state)
Data: 0 data values
TargetSite: Void Transmit(RabbitMQ.Client.Impl.Command)
HelpLink: NULL
Source: RabbitMQ.Client
HResult: -2146233088

StackTrace Information
*********************************************
   at RabbitMQ.Client.Impl.SessionBase.Transmit(Command cmd)
   at RabbitMQ.Client.Impl.ModelBase.BasicPublish(String exchange, String routingKey, Boolean mandatory, IBasicProperties basicProperties, Byte[] body)
   at abc.Lib.Messaging.Client.TopicQueue`1.<>c__DisplayClass3_0.<SendAsync>b__0()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
--- End of stack trace from previous location where exception was thrown ---
   at abc.Lib.Messaging.Client.TopicQueue`1.SendAsync(String topic, T t)
   at abc.Job.DbEvent.Service.DbEventJob.RunAsync(CancellationToken cancellationToken) in E:\@\B\4\159\s\job\dbevent\service\DbEventJob.cs:line 75

```

**Comment by michaelklishin** [comment]
Thank you for your time.

Team RabbitMQ uses GitHub issues for specific actionable items engineers can work on. This assumes that we have a certain amount of information to work with.

Getting all the details necessary to reproduce an issue, make a conclusion or even form a hypothesis about what's happening can take a fair amount of time. Our team is multiple orders of magnitude smaller than the RabbitMQ community. Please help others help you by providing a way to reproduce the behavior you're
observing and sharing as much relevant information as possible [on the list](https://groups.google.com/forum/#!forum/rabbitmq-users):

 * Server, client library and plugin (if applicable) versions used
 * Server logs
 * A code example or terminal transcript that can be used to reproduce
 * **Full** exception stack traces (not a single line message)
 * `rabbitmqctl status` (and, if possible, `rabbitmqctl environment` output)
 * Other relevant things about the environment and workload, e.g. OS/systemd logs, [a traffic capture](https://www.rabbitmq.com/amqp-wireshark.html), deployment tool logs, etc

Feel free to edit out hostnames and other potentially sensitive information.

When/if we have a complete enough understanding of what's going on, a recommendation will be provided or a new issues with more context will be filed.

Thank you.

**Comment by michaelklishin** [comment]
There isn't much we can suggest with the amount of information provided. Any activity on a connection counts for a heartbeat, so even if heartbeat frames are not sent on time it should not matter for the broker.

Please help others help you by collecting and sharing relevant information. We really don't like to guess on this team.

All connection lifecycle events, including closure of connections for any reason (including missed heartbeats), are [logged by RabbitMQ](https://www.rabbitmq.com/logging.html#logged-events). A [traffic capture](https://www.rabbitmq.com/amqp-wireshark.html) would provide a lot of relevant information.
Lastly, RabbitMQ and .NET client versions would be very useful to know.

Please start a rabbitmq-users thread once you collect more relevant information.

**Comment by michaelklishin** [comment]
Also potentially relevant: [alarm events](https://www.rabbitmq.com/alarms.html) are logged and will prevent all client-side socket writes from progressing soon after triggering. Looking out for those in RabbitMQ logs is a good idea.

According to the stack trace the channel was closed by the library (so, not server or explicitly in application code). This could be the [heartbeat write callback](https://github.com/rabbitmq/rabbitmq-dotnet-client/blob/5.x/projects/client/RabbitMQ.Client/src/client/impl/Connection.cs#L1131) which does something other clients don't.

**Comment by michaelklishin** [comment]
Filed #638 for a hypothesis that seems plausible from inspecting the code.
