### ISSUE TITLE
Heartbeat frame write failures should not close connection

### ISSUE THREAD

**Issue by michaelklishin** [rabbitmq/rabbitmq-dotnet-client#638]
There is only so much information in #637 but while inspecting the stack trace, I've noticed that in this client, a [failed heartbeat write closes the connection](https://github.com/rabbitmq/rabbitmq-dotnet-client/blob/5.x/projects/client/RabbitMQ.Client/src/client/impl/Connection.cs#L1131). The code also doesn't account for other activity on the connection.

As a result, on a very busy connection or a connection that managed to trigger a resource alarm or transient flow control for a long enough period, it is feasible to see a heartbeat write failure.

Other clients don't close connections this aggressively. For example, Java client [does not](https://github.com/rabbitmq/rabbitmq-java-client/blob/master/src/main/java/com/rabbitmq/client/impl/HeartbeatSender.java) and, in fact, wouldn't even send heartbeat frames if there was recent activity on a connection.

**Comment by tellybrown** [comment]
What information do you need?  I can easily reproduce this just by having a hard loop sending to a topic exchange.  I was wrong about the times as I was looking at VS timers.  It is around 60 seconds before it starts to block.

**Comment by michaelklishin** [comment]
Server log files.

**Comment by tellybrown** [comment]
Attached are the two logs i see.

[crash.log](https://github.com/rabbitmq/rabbitmq-dotnet-client/files/3087074/crash.log)
[server.log](https://github.com/rabbitmq/rabbitmq-dotnet-client/files/3087075/server.log)

**Comment by michaelklishin** [comment]
There is evidence of [abruptly closed TCP connections]():

```
2019-04-16 16:39:47.671 [warning] <0.24945.13> closing AMQP connection <0.24945.13> (192.168.82.128:12951 -> 172.26.176.11:5672):
client unexpectedly closed TCP connection
2019-04-16 16:39:47.702 [warning] <0.24949.13> closing AMQP connection <0.24949.13> (192.168.82.128:12952 -> 172.26.176.11:5672):
client unexpectedly closed TCP connection
```

and mass connections/disconnects. Abrupt connection closures in this case seem to confirm the hypothesis in this issue because `Connection#HeartbeatWriteTimerCallback` closes TCP connection
without sending a `connection.close`.

There is also evidence of this node [running out of file descriptors](https://www.rabbitmq.com/networking.html#open-file-handle-limit) (see [Connection monitoring](https://www.rabbitmq.com/connections.html#monitoring) as well):

```
** {badarg,[{erlang,port_command,[#Port<0.875290>,[]],[{file,"erlang.erl"},{line,3136}]},{os,cmd,2,[{file,"os.erl"}
```

which is not related to this issue but is something operators must pay close attention to.

**Comment by michaelklishin** [comment]
#639 contains a proposed change that will avoid closing connections on a heartbeat frame write. [Test suite instructions](https://github.com/rabbitmq/rabbitmq-dotnet-client/blob/master/RUNNING_TESTS.md#building) explain how to build the client from source in case you'd like to compare.

**Comment by michaelklishin** [comment]
#639 is included into [5.1.1-rc1](https://www.nuget.org/packages/RabbitMQ.Client/5.1.1-rc1), please give it a shot.

**Comment by tellybrown** [comment]
That doesn't seem to have fixed it.  Same error

**Comment by michaelklishin** [comment]
Then I don't have enough information to form another hypothesis. Please collect as much information as possible (ideally a way to reproduce) and start a mailing list thread.
