### ISSUE TITLE
need to use queue as temp db

### ISSUE THREAD

**Issue by NakWarsi** [rabbitmq/rabbitmq-dotnet-client#641]
hello All,
my requirement is a bit different, obviously what I am looking for would violate the property of a queue but I am just seeking for an option.
I want to store the data in the queue for some period of time. I mean, I don't want to delete the message from the queue even when I read the message.
obviously, in that situation, I will have an issue with reading the message so I was thinking to apply priority for all the message coming in the queue and read them accordingly and delete the message periodically.
is this possible?
guide me...
thanks

**Comment by kjnilsson** [comment]
This is mailing list material. Please use the rabbitmq-users email group for discussion items. We use GitHub issues for actual actionable work items.
