### ISSUE TITLE
Model.cs file not found

### ISSUE THREAD

**Issue by armanpetrosyan23** [rabbitmq/rabbitmq-dotnet-client#642]
Hi, I canot build your C# client application, Can`t find Model.cs file
Please answer me,

**Comment by lukebakken** [comment]
The RabbitMQ team does not use GitHub to troubleshoot. In addition, there is not enough information here to assist you.

Please ask this on the [mailing list](https://groups.google.com/forum/#!forum/rabbitmq-users).

Provide information on what you are trying to do, what you expect to see, what you _are_ seeing, and what commands you are running.

**Comment by michaelklishin** [comment]
The file is produced by a code generator. See [Running Tests](https://github.com/rabbitmq/rabbitmq-dotnet-client/blob/master/RUNNING_TESTS.md#building) on how to build the client from source.
