### ISSUE TITLE
Actual connection timeout may vary significantly due to the use of TimeoutAfter in ConnectOrFail

### ISSUE THREAD

**Issue by FrancescoBonizzi** [rabbitmq/rabbitmq-dotnet-client#648]
- RabbitMq client: 5.1.0
- Microsoft.Diagnostics.Tracing.EventSource.Redist: 1.1.28

**The problem from the outside**
When calling `connectionFactory.CreateConnection();` with a specified `RequestedConnectionTimeout` you see different behaviours:
1. If you set as HostName "google.com" it breaks near the timeout you suggested (even if it lasts a bit longer). It seems that in case a host exists and refuses the connection, the timeout is respected.
2. If you set as HostName something that does not exists, like "abcdefghtest", the break occurs **later than the specified timeout, and usually it doubles it**.
3. If you set as HostName an endpoint that exists and there is a rabbitmq server listening, but you specified wrong the hostname, it does answer in ~20/~30 seconds, **without respecting at all the timeout you suggested**.

**Steps to reproduce behaviour 1**
Create a new Windows Console Application with .NET framework 4.5.2 and install those Nuget packages:

- RabbitMq client: 5.1.0
- Microsoft.Diagnostics.Tracing.EventSource.Redist: 1.1.28

```
static void Main(string[] args)
{
	var requestedConnectionTimeout = TimeSpan.FromSeconds(3);

	var connectionFactory = new ConnectionFactory()
	{
		HostName = "google.com",
		UserName = "test",
		Password = "test",
		Port = 5672,
		RequestedConnectionTimeout = (int)requestedConnectionTimeout.TotalMilliseconds,
	};

	var timer = Stopwatch.StartNew();

	try
	{
		var connection = connectionFactory.CreateConnection();
		Console.WriteLine("Connected");
	}
	catch(Exception ex)
	{
		Console.ForegroundColor = ConsoleColor.Red;
		Console.WriteLine(ex.ToString());
		Console.ForegroundColor = ConsoleColor.White;
	}
	finally
	{
		timer.Stop();
		Console.ForegroundColor = ConsoleColor.Yellow;
		Console.WriteLine();
		Console.WriteLine($"Timeout: {requestedConnectionTimeout.TotalMilliseconds}ms");
		Console.WriteLine($"Real elapsed: {timer.ElapsedMilliseconds}ms");
		Console.ForegroundColor = ConsoleColor.White;
	}

	Console.WriteLine();
	Console.WriteLine("Test end");
	Console.Read();
}
```

Run the application.
In this case you will see that the innermost exception is of type `System.TimeoutException` and the ouput will be, more or less:
- The exception in red
- "Timeout: 3000ms" (in yellow)
- "Real elapsed: 3128ms" (in yellow, a similar value)

**Steps to reproduce behaviour 2**
Same as behaviour 1, but with `HostName = "abcdefghtest",`.
The output will be, more or less:
- The exception in red, sometimes `System.TimeoutException`, sometimes `SockeException`
- "Timeout: 3000ms" (in yellow)
- "Real elapsed: 6092ms" (in yellow, a similar value)

In this case I may have a reason: because in the library code you call `ConnectOrFail` two times, one to try to connect with IPV6 (without rethrowing the exception) and one to connect with IPV4. Both fails so maybe this doubles the timeout you notice.

**Steps to reproduce behaviour 3**
Have a local RabbitMQ server running. In my case I did this with Docker on Windows 10 with Linux containers: `docker run -d --hostname testhost -p 15672:15672 --name testrabbit4 rabbitmq:3-management`. In this case, my docker IP is 172.17.0.2.

Then, same as behaviour 1, but with `HostName = "172.17.0.2",`.
The output will be, more or less:
- The exception in red, sometimes `System.Net.Sockets.SocketException`:
- "Timeout: 3000ms" (in yellow)
- "Real elapsed: 21069ms" (in yellow, a similar value)

The timeout is really later than expected.

In my opinion the problem is in the internal extension `TimeoutAfter`. This "technique" won't work if the caller doesn't change thread. If the whole code works on the same thread, `Task.Delay` never get called so the client timeout is never involved.

I reproduced the issue like this:

**Working TimeoutAfter demonstration**

```
static void Main(string[] args)
{
	TimeoutAfter(Test(), 500).GetAwaiter().GetResult();
	Console.WriteLine("Test end");
	Console.Read();
}

public static async Task Test()
{
	Console.WriteLine("Task start");
	await Task.Delay(4000);
	Console.WriteLine("Task stop");
}

public static async Task TimeoutAfter(Task task, int millisecondsTimeout)
{
	object obj = task;
	Task task2 = await Task.WhenAny(new Task[]
	{
		task,
		Task.Delay(millisecondsTimeout)
	}).ConfigureAwait(false);
	if (obj == task2)
	{
		obj = null;
		await task;
		return;
	}
	Console.WriteLine("TIMEOUT!");
}
```

You will see the correct sequence of output, because my Test mehods lasts 4000ms and I set the timeout to 500ms: 
- Task start
- TIMEOUT!
- Test end
- Task stop

**Unexpected behaviour TimeoutAfter demonstration**
```
static void Main(string[] args)
{
	var s = Stopwatch.StartNew();
	TimeoutAfter(WhatCausesTheUnexpectedBehaviour(), 500).GetAwaiter().GetResult();
	s.Stop();
	Console.WriteLine($"{s.ElapsedMilliseconds}ms");
	Console.WriteLine("WhatCausesTheUnexpectedBehaviour end");
   
	Console.Read();
}

public static Task WhatCausesTheUnexpectedBehaviour()
{
	Console.WriteLine("Task start");
	Thread.Sleep(4_000);
	Console.WriteLine("Task stop");
	return Task.FromResult(false);
}

public static async Task TimeoutAfter(Task task, int millisecondsTimeout)
{
	object obj = task;
	Task task2 = await Task.WhenAny(new Task[]
	{
		task,
		Task.Delay(millisecondsTimeout)
	}).ConfigureAwait(false);
	if (obj == task2)
	{
		obj = null;
		await task;
		return;
	}
	Console.WriteLine("TIMEOUT!");
}
```

In this case you will see:
- Task start
- Task stop
- 4017ms
- WhatCausesTheUnexpectedBehaviour end

The timeout isn't fired. Why? If you debug into it, you will see that "WhatCausesTheUnexpectedBehaviour" locks the whole thread so "TimeoutAfter" is being called after the first method execution.

I think this is the same happening into RabbitMQ client library when using TimeoutAfter extension, in particular here:

```
private void ConnectOrFail(ITcpClient socket, AmqpTcpEndpoint endpoint, int timeout)
{
	try
	{
		socket.ConnectAsync(endpoint.HostName, endpoint.Port).TimeoutAfter(timeout).ConfigureAwait(false).GetAwaiter().GetResult();
	}
	catch (ArgumentException inner)
	{
		throw new ConnectFailureException("Connection failed", inner);
	}
	catch (SocketException inner2)
	{
		throw new ConnectFailureException("Connection failed", inner2);
	}
	catch (NotSupportedException inner3)
	{
		throw new ConnectFailureException("Connection failed", inner3);
	}
	catch (TimeoutException inner4)
	{
		throw new ConnectFailureException("Connection failed", inner4);
	}
}

```
Hope everything is clear and not out of place.

**Comment by michaelklishin** [comment]
Thank you for the detailed analysis. Any client connection involves at least two operations that have a very good chance of timing out:

 * Hostname resolution
 * Actual connection

So the following piece of code from the `SocketFrameHandler`

``` csharp
socket.ConnectAsync(endpoint.HostName, endpoint.Port)
                      .TimeoutAfter(timeout)
                      .ConfigureAwait(false)
                      // this ensures exceptions aren't wrapped in an AggregateException
                      .GetAwaiter()
                      .GetResult();
```

not only depends on the `TimeoutAfter(timeout)` behaviour in this context but also on the interpretation of the timeout by the library used, such as its treatment of hostname resolution.

I'd welcome specific suggestions as to what we can do in the above snippet to make the behaviour more predictable but it will never be precise because, as stated above, a single timeout does not represent the range of possible scenarios.

**Comment by FrancescoBonizzi** [comment]
I'm going to make some tests and propose a solution. Thanks a lot!

**Comment by FrancescoBonizzi** [comment]
In my opinion the solution could be calling `ConnectAsync` with `Task.Run`:
`Task.Run(() => socket.ConnectAsync(endpoint.HostName, endpoint.Port)).TimeoutAfter(timeout).ConfigureAwait(false).GetAwaiter().GetResult();
`

I attached a very simple sample in which you can see the three cases:
1. Awaiting the Task that won't block the thread
2. Your specific case where the Task blocks the timeout thread
3. The solution

[TimeoutAfterTest.zip](https://github.com/rabbitmq/rabbitmq-dotnet-client/files/3551459/TimeoutAfterTest.zip)

**Comment by michaelklishin** [comment]
@FrancescoBonizzi that seems like a small enough change. Can you please submit a pull request so that we can QA it? Thank you 🙏.

**Comment by FrancescoBonizzi** [comment]
Of course!
