### ISSUE TITLE
EventingBasicConsumer.Received won't keep running in windows service

### ISSUE THREAD

**Issue by howardhee** [rabbitmq/rabbitmq-dotnet-client#663]
I am created a windows service to consume the delay message by using Rabbit MQ, but I realized the connection wont keep connect, it's running for first time only. I have to added a while loop to make sure consumer is keep running. 

```
          using (var connection = factory.CreateConnection())
          {
                using (var channel = connection.CreateModel())
                {
                    string name = channel.QueueDeclare().QueueName;
                    channel.QueueBind(queue: name, exchange: "delay_mq_exchange", routingKey: "delay_mq_routingKey");

                    var consumer = new EventingBasicConsumer(channel);

                    consumer.Received += (model, ea) =>
                    {
                        var message = Encoding.UTF8.GetString(ea.Body);

                        // continue code
                    };

                    channel.BasicConsume(queue: name,
                                         autoAck: true,
                                         consumer: consumer);

                    //while (true)  //have to add while loop to make sure keep running
                    //{
                    //}
                }
            }
```

But when i am using obsolete method - "QueueingBasicConsumer", it's working fine and keep running.

```
          using (var connection = factory.CreateConnection())
          {
                using (var channel = connection.CreateModel())
                {
                    string name = channel.QueueDeclare().QueueName;
                    channel.QueueBind(queue: name, exchange: "delay_mq_exchange", routingKey: "delay_mq_routingKey");

                    var consumer = new QueueingBasicConsumer(channel);
                    channel.BasicConsume(name, false, consumer);

                    while (true)
                    {
                        var ea = consumer.Queue.Dequeue();
                        var body = ea.Body;

                        var message = Encoding.UTF8.GetString(body);

                        channel.BasicAck(ea.DeliveryTag, false);
                    }
                }
            }
```

**Comment by michaelklishin** [comment]
Thank you for your time.

Team RabbitMQ uses GitHub issues for specific actionable items engineers can work on. GitHub issues are not used for questions, investigations, root cause analysis, discussions of potential issues, etc (as defined by this team).

We get at least a dozen of questions through various venues every single day, often light on details.
At that rate GitHub issues can very quickly turn into a something impossible to navigate and make sense of even for our team. Because GitHub is a tool our team uses heavily nearly every day, the signal/noise ratio of issues is something we care about a lot.

Please post this to [rabbitmq-users](https://groups.google.com/forum/#!forum/rabbitmq-users).

Thank you.

**Comment by michaelklishin** [comment]
`QueueingBasicConsumer` operates using a forever running loop, which keeps at least one thread (often the main one) alive at all times. With "non-blocking" consumer implementations it's up to you to find an appropriate way to keep the application running. In some languages an endless loop with sleeps is a common approach. `ManualResetEvent`s is at least one [alternative available even in ancient versions of .NET](https://stackoverflow.com/questions/2586612/how-to-keep-a-net-console-app-running).

**Comment by howardhee** [comment]
Thanks for your answer

**Comment by lukebakken** [comment]
I strongly suggest using a project like [TopShelf](https://topshelf.readthedocs.io/en/latest/index.html) to develop your Windows service.
