### ISSUE TITLE
Support the connection.update-secret extension used with OAuth 2

### ISSUE THREAD

**Issue by tyb-dev** [rabbitmq/rabbitmq-dotnet-client#672]
Feature request:
Support connection.update-secret in RabbitMQ.Client. 

Background:
The AMQP 0-9-1 reference guide at https://www.rabbitmq.com/amqp-0-9-1-reference.html defines a method connection.update-secret. This method is intended to be used with authorization plugins like rabbitmq_auth_backend_oauth2. This plugin allows establishing a connection with a token rather than a password. Such tokens usually have an expiry timestamp and connections become unusable after this point. Using the method connection.update-secret, it is possible to supply a new token that has not yet expired without having to re-establish the connection. It would also allow updating permissions at this point. The plugin ships with RabbitMQ 3.8 and therefore it makes sense to support it within RabbitMQ.Client. Without this feature, we can not make use of this plug-in.

**Comment by michaelklishin** [comment]
You are right except that JWT tokens can be used but they have really long expiration periods, which is not great.

**Comment by lukebakken** [comment]
Resolved by #674
