### ISSUE TITLE
Upgrade Microsoft.NET.Test.Sdk

### ISSUE THREAD

**Issue by michaelklishin** [rabbitmq/rabbitmq-dotnet-client#673]
Upgrading `Microsoft.NET.Test.Sdk` to `16.4.0` leads `./run-test.sh` to not actually run any tests. Something has changed around test discovery if I had to guess. We need to investigate this
and stay reasonably up-to-date.

**Comment by bording** [comment]
There's a good chance that will be solved by also updating NUnit3TestAdapter to the latest version as well. Test discovery is an interaction between both packages.

**Comment by michaelklishin** [comment]
Unfortunately the following combination of dependencies still exhibits this behavior (no tests are actually run):

``` xml
<ItemGroup>
    <PackageReference Include="ApprovalTests" Version="4.4.0" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="16.4.0" />
    <PackageReference Include="NUnit" Version="3.12.0" />
    <PackageReference Include="NUnit3TestAdapter" Version="3.15.1" />
    <!--<PackageReference Include="PublicApiGenerator" Version="8.1.0" />-->
    <PackageReference Include="Mono.Cecil" Version="0.10.3" />
  </ItemGroup>
```

**Comment by bording** [comment]
Hmm, weird. I'll try and take a quick look at what the problem is then.

**Comment by michaelklishin** [comment]
@bording thank you very much 🙏

**Comment by bording** [comment]
@michaelklishin See #675
