### ISSUE TITLE
Change in 5.1 synchronisation behavior when connection is shared between threads

### ISSUE THREAD

**Issue by poloBBQ** [rabbitmq/rabbitmq-dotnet-client#681]
I encountered what may possibly be the same issue explained in #457 but am unable to reopen that one.

The error shown is the following

> RabbitMQ.Client.Exceptions.AlreadyClosedException: Already closed: The AMQP operation was interrupted: AMQP close-reason, initiated by Peer, code=501, text='FRAME_ERROR - type 3, first 16 octets = <<"{\r\n\t\"lookupKey\":">>: {invalid_frame_end_marker,
                                                        102}', classId=0, methodId=0
  at RabbitMQ.Client.Framing.Impl.Connection.EnsureIsOpen () [0x00013] in <f61cf0f6a90940e784dab21d07bae87d>:0
  at RabbitMQ.Client.Framing.Impl.AutorecoveringConnection.EnsureIsOpen () [0x00000] in <f61cf0f6a90940e784dab21d07bae87d>:0
  at RabbitMQ.Client.Framing.Impl.AutorecoveringConnection.CreateModel () [0x00000] in <f61cf0f6a90940e784dab21d07bae87d>:0

I built a similar example to the one @TravisWilkins posted on their issue plus simplifying it and following @michaelklishin's advice of creating a new connection per thread. Here is the code:

```csharp
class Program
{
	private static ConnectionFactory factory = new ConnectionFactory();
	private static byte[] data;

	private static int loops;
	private static int sleepMs;
	private static int threads;

	static void Main(string[] args)
	{
		if (args.Length != 4)
		{
			Console.WriteLine("Usage: .exe loops sleepMs threads payloadFile");
			Environment.Exit(-1);
		}

		loops = int.Parse(args[0]);
		sleepMs = int.Parse(args[1]);
		threads = int.Parse(args[2]);
		data = File.ReadAllBytes(args[3]);

		// initialize factory here

		for (int i = 0; i < threads; i++)
		{
			Console.WriteLine("Start WriteMessage");
			Thread t = new Thread(new ThreadStart(WriteDirectMessage));
			t.Start();
		}

		System.Threading.Thread.Sleep((int)(loops * 1.2f * sleepMs));
		Console.WriteLine("Finished");
	}

	private static void WriteDirectMessage()
	{
		Console.WriteLine("On WriteDirectMessage");

		IConnection connection = factory.CreateConnection(); ;

		IModel channel = null;
		try
		{
			for (int i = 0; i < loops; i++)
			{
				try
				{
					channel = connection.CreateModel();

					IBasicProperties props;
					props = channel.CreateBasicProperties();
					props.Persistent = true;

					channel.ExchangeDeclare(exchange: "exch", type: "direct", durable: true, autoDelete: false, arguments: null);

					channel.BasicPublish(exchange: "exch",
											routingKey: "myQueue",
											basicProperties: props,
											body: data);

					Thread.Sleep(sleepMs);
				}
				finally
				{
					if (channel != null)
					{
						try
						{
							channel.Close();
							channel.Dispose();
						}
						catch { }
					}
				}
			}

		}
		catch (Exception ex)
		{
			var msg = ex.ToString();
			Console.WriteLine(msg);
		}
	}
}
```

I'm not too sure of the parameters needed to reliably reproduce it, as sometimes with lower threads, loops or small payload the code works just fine. I've run the sample with the values 100 for loops, 50 for sleepMs and 100 for number of threads. Plus, the payload has a size of 153,661 bytes.

Running the same code with v5.0.1 of the RabbitMQ.Client works flawlessly, while using 5.1.0 or 5.1.2 cause the aforementioned issue.

As mentioned in the original issue, it doesn't seem to happen when the sample is run on every machine, even while keeping Rabbit server the same.

I'm also attaching a pcap capture taken while running the sample and reproducing the issue, in case it helps [capture.zip](https://github.com/rabbitmq/rabbitmq-dotnet-client/files/4019528/capture.zip)

**Comment by michaelklishin** [comment]
It does not matter if you "keep RabbitMQ the same" since all that matters in this workload is connection-level synchronisation in this client.

Thanks for the data. We have to release 6.0 first but sharing a connection between threads is something we have supported for as long as I remember, so this workload seems reasonable.

**Comment by michaelklishin** [comment]
Very likely that that this is the effect of the relaxed locking in #350 #354. @poloBBQ FYI given that this is not a commonly reported issue and using a connection per thread is straightforward enough we may conclude that this is the "new" desired behavior.

**Comment by michaelklishin** [comment]
@poloBBQ you say that this cannot be reproduced on every machine. So what settings do reproduce it and what is the difference between said machines? Can you share logs from a node running at debug log level when the exception occurs?

**Comment by michaelklishin** [comment]
After inspecting the dump I am convinced this is an effect of #350 and #354. There's "frame overlap" on the wire which confuses not only RabbitMQ protocol parser but also Wireshark.

We need more information about what the difference is between the machines (and test run values) that trigger this behavior vs. those that do not.

Things such as:

 * Operating system
 * .NET version used
 * Local vs. remote RabbitMQ node connection (loopback code paths can be drastically different in the kernel)
 * TCP and .NET settings that can affect socket write behavior

In the dump the "unparseable" event begins after the first multi-frame method, `basic.publish`. @poloBBQ does the issue still occur if you modify the test to NOT publish and thus avoid sending multi-frame methods?

**Comment by michaelklishin** [comment]
#354 does include [a similar test that performs publishing](https://github.com/rabbitmq/rabbitmq-dotnet-client/pull/354/files#diff-3db021ace1d576bfc1902e120052cefbR175) on a shared channel but not on a shared connection. This means that it does not attempt concurrent writes of multi-framed methods (publishing a message sends a `basic.publish` plus a "content metadata" frame plus zero or more message payload frames) but this test does.

**Comment by lukebakken** [comment]
@poloBBQ - I want to confirm that the code you provided is what reproduces the `FRAME_ERROR` error. I have taken your code and cleaned it up [here](https://github.com/rabbitmq/rabbitmq-dotnet-client/blob/rabbitmq-dotnet-client-681/projects/GH-681/Program.cs) so that the program uses connections and channels correctly.

Can you use my code in your environment and reproduce the problem? I am using the arguments `100 50 100 D:\randomfile.txt` in my testing and do not see the error. `randomfile.txt` is a random text file of `153661` bytes. I am running RabbitMQ 3.8.2 on another server in my environment.

I will continue to try to reproduce with a few more different arguments, but given how I'm using a connection-per-thread without any channel or connection sharing among threads I don't see how a `FRAME_ERROR` could happen.

**Comment by bording** [comment]
@lukebakken Using a connection per thread has never been a requirement in the past, only ensuring `IModel` instances themselves aren't used on multiple threads simultaneously.

Does the code provided here repro a problem if you use a single connection? If it does, then I think that needs to be treated as a bug because that's an undesirable change in behavior for sure.

As an additional bit of anecdotal evidence for this being a problem, I have been seeing some customers reporting invalid frame error problems that would seem to be related to this.

**Comment by michaelklishin** [comment]
See #350 and #354. That change was promised to be safe without locking.

**Comment by bording** [comment]
@michaelklishin Based on https://github.com/rabbitmq/rabbitmq-dotnet-client/issues/681#issuecomment-570658245 it sounds like a test case was missed for those changes?

**Comment by michaelklishin** [comment]
There isn't a practical test case that can prove safety. We should add one to make sure it's not something easily reproducible. The OP suggested that not every machine reproduces the issue. We are waiting for details about the difference between those environments.

If someone is familiar with .NET streams enough to spot the issue, we'd definitelly appreciate help.

FWIW it is not a commonly reported issue and 5.1.x has been around for a while.

**Comment by bording** [comment]
> FWIW it is not a commonly reported issue and 5.1.x has been around for a while.

I haven't seen a lot of reports either, but I have had a few customers have problems, so there does seem to be some rare error state the client can get into. I've not been able to track down any reliable repro yet.

**Comment by lukebakken** [comment]
@bording - the issue report here is confusing. Why submit code that doesn't reproduce the problem? That is what I would like @poloBBQ to clarify.

My next step is to share the connection among threads which I suspect is what @poloBBQ meant to submit in the code sample.

**Comment by lukebakken** [comment]
@bording @poloBBQ unfortunately, still not luck reproducing with [this code](https://github.com/rabbitmq/rabbitmq-dotnet-client/blob/rabbitmq-dotnet-client-681/projects/GH-681/Program.cs). I've changed it to use a shared connection, and have tried different arguments for thread count, loops, sleep as well as different file sizes.

I'm using Windows 10 Pro, .NET 4.7.2 for the test app and am running RabbitMQ 3.8.2 / Erlang 22.2.1 on FreeBSD on a low-powered home server (Intel i3 / 8GiB RAM) / spinning 2TB disks ZFS).

**Comment by poloBBQ** [comment]
Firstly, I am sorry but I mixed up two different past occurrences I found searching for the issue and thought you had already seen a link I had not posted before: [this](https://groups.google.com/forum/#!searchin/rabbitmq-users/invalid_frame_end_marker|sort:date/rabbitmq-users/jsAPwsKGxw0/lXSn3suuAgAJ) is from rabbitmq-users and seems to also be the same problem.

@lukebakken your linked code still causes the issue, I'll use your code (shared connection) for the following tests unless you tell me otherwise

I've also attached the log from the node when the exception happens: [rabbit.log](https://github.com/rabbitmq/rabbitmq-dotnet-client/files/4029771/rabbit.log)

To add information
* RabbitMQ  3.7.16, Erlang/OTP 22 [erts-10.4.4]
* The machine running the client code that fails is a CentOS release 6.7 (Final) through Mono JIT compiler version 5.18.1.0 (I don't have a Windows Server machine to test in the same conditions as the linked post)
* .NET Framework 4.5.2
* The connection is remote in all cases

**Comment by michaelklishin** [comment]
@poloBBQ let's focus on reproducing this in the latest .NET Core and on Windows. If this is something Mono JIT/4.5.2-specific we won't be reintroducing locking.

**Comment by poloBBQ** [comment]
Just tried building it for .NET Core 3.1 and running on a CentOS Linux release 7.4.1708 machine and it is still present. I can't provide a way to repro it on Win as it doesn't seem to happen for me (even with bigger payloads). But I believe this, plus the other two instances of people with similar diagnoses should be good enough to prove it is not mono-specific.

**Comment by michaelklishin** [comment]
@poloBBQ and if you reintroduce a lock on socket writes?

**Comment by lukebakken** [comment]
@poloBBQ could you please answer [my original question](https://github.com/rabbitmq/rabbitmq-dotnet-client/issues/681#issuecomment-571221017)? Does the code you posted [here](https://github.com/rabbitmq/rabbitmq-dotnet-client/issues/681#issue-545037478) reproduce the issue in your environment? That code uses a connection per-thread so I have no idea how it could cause the framing issue.

**Comment by poloBBQ** [comment]
@lukebakken I opened the ticket with the mentioned code. Yes, it does reproduce the issue.

@michaelklishin Re-added locks in just SocketFrameHandler shown in [this diff](https://github.com/rabbitmq/rabbitmq-dotnet-client/pull/350/files) and, I don't really know what it means, but does indeed fix the issue.

**Comment by michaelklishin** [comment]
@poloBBQ does this PR address the issue? https://github.com/rabbitmq/rabbitmq-dotnet-client/pull/682

**Comment by poloBBQ** [comment]
@michaelklishin Just tested it and it does address the issue, thank you all!

**Comment by michaelklishin** [comment]
We extended what we already do for TLS streams to all socket activity in #683. It's unfortunate that the lock contention reduction in #350, #354 has to be rolled back but the net stream concurrency guarantees seem to be too vague to rely on.

@poloBBQ feel free to try master for one last confirmation. This will become 6.0 which will require .NET 4.5.2 and has fairly minor breaking API changes.
