### ISSUE TITLE
Add .editorconfig to unify coding style in the project and reformat code to spec.

### ISSUE THREAD

**Issue by stebet** [rabbitmq/rabbitmq-dotnet-client#689]
I suggest adding a [.editorconfig](https://docs.microsoft.com/en-us/visualstudio/ide/create-portable-custom-editor-options?view=vs-2019) file to the project to unify the coding style. A good baseline would be to simply copy the [.editorconfig](https://github.com/dotnet/runtime/blob/master/.editorconfig) that is used by Microsoft for .NET Core development, to keep things similar.

**Comment by lukebakken** [comment]
Resolved by #692
