### ISSUE TITLE
Reduce allocations by using pooled memory and recycling memory streams

### ISSUE THREAD

**Issue by stebet** [rabbitmq/rabbitmq-dotnet-client#694]
The RabbitMQ client currently allocates a lot of unnecessary memory and has a lot of GC overhead.

I'm currently working on a PR to reduce the allocations being made, and will probably introduce some *Async overloads as well as they help reduce lock contention.

Here is the current progress I have made with a test app that opens two connections. One connection bulk publishes 50000 messages in 100 message batches containing just an 4-byte integer as payload. The other connection receives those messages so it's mostly just measureing the frame serialize/deserialize overhead.

Before: 
![image](https://user-images.githubusercontent.com/661658/72981150-038aa380-3dd4-11ea-8376-6fffed35477f.png)

After:
![image](https://user-images.githubusercontent.com/661658/72981169-0d140b80-3dd4-11ea-858f-22bef83b56ef.png)

I'll follow up this issue with discussions and link the PR once it's ready for review.

**Comment by stebet** [comment]
Some explanations:
The **before** uses the current NuGet release of the RabbitMQ.Client library.
The **after** uses code based on the latest master branch which is the 6.0 release.

**Comment by michaelklishin** [comment]
So a 25% reduction with this specific run. Looks promising!

**Comment by lechu445** [comment]
ralated to https://github.com/rabbitmq/rabbitmq-dotnet-client/pull/452

**Comment by stebet** [comment]
I have got System.IO.Pipelines working on the socket connection as well, will push the PR soon for review and testing. Improvements are quite impressive, will add details and screenshots later :)

**Comment by stebet** [comment]
So here's where I'm at. Similar scenario as above, one sender, one receiver. Bulk Send 50000 messages in 500x100 message batches, but now with a 512 byte, 4kb and 16kb payloads.

# Before
## 512 byte payload
![image](https://user-images.githubusercontent.com/661658/73113528-55cee000-3f0c-11ea-8383-d93fd3166512.png)

## 4kb payload
![image](https://user-images.githubusercontent.com/661658/73113574-7f880700-3f0c-11ea-9dde-4b09983f7e97.png)

## 16kb payload
![image](https://user-images.githubusercontent.com/661658/73113615-afcfa580-3f0c-11ea-8c67-ec33bb0b37a2.png)

# After (using pooled arrays, recyclable memorystreams and System.IO.Pipelines)
## 512 byte payload
![image](https://user-images.githubusercontent.com/661658/73113695-2ff60b00-3f0d-11ea-90a3-7e1eba0a0f7d.png)

## 4kb payload
![image](https://user-images.githubusercontent.com/661658/73113718-5caa2280-3f0d-11ea-8b05-cdf1022ce584.png)

## 16kb payload
![image](https://user-images.githubusercontent.com/661658/73113777-a5fa7200-3f0d-11ea-811b-711c185d43a1.png)

**Comment by stebet** [comment]
More progress :)

## 512 byte payloads
![image](https://user-images.githubusercontent.com/661658/73376464-650bb000-42b5-11ea-9dd9-c6d2e711d35b.png)

## 4kb payloads
![image](https://user-images.githubusercontent.com/661658/73376845-fe3ac680-42b5-11ea-8cfc-eabea4160c0a.png)

## 16kb payloads
![image](https://user-images.githubusercontent.com/661658/73376963-33dfaf80-42b6-11ea-9905-8077e78f1a00.png)

**To summarize:**
512 byte payloads are down from 556mb to 238mb (57% reduction)
4kb payloads are down from 1.96gb to 411mb (79% reduction)
16kb payloads are down from 7.14gb to 1.00 gb (86% reduction)

**What's left**
To finish up the PR I need to get all the tests to run which will require a little refactoring around catching the exceptions/errors that happen now that the Pipelines are taking care of reading and writing the sockets, as they are  little harder to reach and parse. Once that's ready, I'll submit the PR for further work and discussions on what APIs (if any) might need to change.

**Comment by michaelklishin** [comment]
@stebet impressive 💪

**Comment by lukebakken** [comment]
This will be addressed by either #706 or #707

**Comment by lukebakken** [comment]
#1445 appears to be the "final word" on this issue. Closing.
