### ISSUE TITLE
Support source linking

### ISSUE THREAD

**Issue by lukebakken** [rabbitmq/rabbitmq-dotnet-client#697]
Supercedes #484 

https://docs.microsoft.com/en-us/dotnet/standard/library-guidance/sourcelink

**Comment by PureKrome** [comment]
Hi @lukebakken - I have a PR _basically_ ready for this. I just need to check how the package is created into a NuGet package and published to NuGet.org.

I can [see that AppVeyor is used ](https://github.com/rabbitmq/rabbitmq-dotnet-client/blob/master/appveyor.yml) for CI/CD. But I can't see where the `dotnet pack` is handled and any nuget deployment.

Are there any docs or can you link to any files in the repo, please?

**Comment by lukebakken** [comment]
The packaging is handled by our internal CI process which is not public. Please open your PR and we can work on it together. Thank you.

**Comment by lukebakken** [comment]
This is the shell script that is run on Debian 10 to produce a final release:

```sh
#!/bin/sh
set -ex

# redirect all output to standard output stream
exec 2>&1

dotnet --version

readonly script_dir="$(cd "$(dirname "$0")" && pwd)"
readonly src_dir="$(cd "$script_dir/../../../rabbitmq_dotnet_client" && pwd)"
readonly version="$(cat "$src_dir/../version/version")"
readonly major="$(echo "$version" | cut -d . -f1)"
readonly assembly_info_file="$src_dir/projects/client/RabbitMQ.Client/src/client/properties/AssemblyInfo.cs"
readonly project_file="$src_dir/projects/client/RabbitMQ.Client/RabbitMQ.Client.csproj"

# update informational/product version
sed -i'' 's/AssemblyInformationalVersion("[^"]*")/AssemblyInformationalVersion("'"$version"'")/g' "$assembly_info_file"

# update only the major version number for the assembly version
sed -i'' 's/AssemblyVersion("[^.]*\.0\.0")/AssemblyVersion("'"$major"'.0.0")/g' "$assembly_info_file"

# update the VersionPrefix field which becomes the package version during dotnet pack
sed -i'' 's/<VersionPrefix>[^<]*<\/VersionPrefix>/<VersionPrefix>'"$version"'<\/VersionPrefix>/g' "$project_file"

cd "$src_dir"

# create snk file to be used for assmebly strong naming
echo "$DOTNET_SNK_DATA" | base64 --decode > rabbit.snk

# perform main build
./build.sh

# build the client using the special SignedRelease target
# this assumes that the signing key (rabbit.snk) has been copied or generated to
# the root of the project directory
dotnet build ./projects/client/RabbitMQ.Client --configuration SignedRelease

# the build only delay signs the assemblies so we need to manually apply the private key
sn -R ./projects/client/RabbitMQ.Client/bin/SignedRelease/netstandard2.0/RabbitMQ.Client.dll rabbit.snk
sn -R ./projects/client/RabbitMQ.Client/bin/SignedRelease/net461/RabbitMQ.Client.dll rabbit.snk

# pack without re-building to ensure we include the strongnamed dlls
dotnet pack ./projects/client/RabbitMQ.Client --no-build --configuration SignedRelease

#push the package
dotnet nuget push -k "$NUGET_API_KEY" -s https://www.nuget.org/api/v2/package \
    ./projects/client/RabbitMQ.Client/bin/SignedRelease/RabbitMQ.Client.*.nupkg
```

**Comment by lukebakken** [comment]
@PureKrome the following `Vagrantfile` will set up a VM exactly like our CI build image: 
[Vagrantfile.txt](https://github.com/rabbitmq/rabbitmq-dotnet-client/files/4136939/Vagrantfile.txt)

**Comment by bording** [comment]
A PR to add this should pretty much only need to consist of adding the following package reference:
```
<PackageReference Include="Microsoft.SourceLink.GitHub" Version="1.0.0" PrivateAssets="All" />
```
And adding the following properties:
```
<PublishRepositoryUrl>true</PublishRepositoryUrl>
<EmbedUntrackedSources>true</EmbedUntrackedSources>
```

**Comment by PureKrome** [comment]
Cheers - the previous script has most of what I need to figure out. Before I create a PR ( i was going to create a DRAFT PR but couldnt' figure out how to do that), the [change is in this commit](https://github.com/PureKrome/rabbitmq-dotnet-client/commit/9c56b9c0cf2263ad2ad36883f9c6cfae893bd5d7).

So when I get a chance today, at lunch, I'll report back with more info for you.

It's all good - I've done this before so hopefull this will help.

**Comment by PureKrome** [comment]
@bording yeah. check my commit in the above post (we posted _at the same time_!!!!!! )

**Comment by bording** [comment]
I actively dislike separate symbol packages, and much prefer to just have the pdb included in the NuGet package. That's easily accomplished by adding the following:
```
<AllowedOutputExtensionsInPackageBuildOutputFolder>$(AllowedOutputExtensionsInPackageBuildOutputFolder);.pdb</AllowedOutputExtensionsInPackageBuildOutputFolder>
```

**Comment by PureKrome** [comment]
@lukebakken make a call, mate. I have my PR ready to go, now that I have all the info.(including the extra steps needed in the CI script).

My PR [follows the documentation with their suggestions](https://github.com/dotnet/sourcelink/blob/master/README.md#using-source-link-in-net-projects). 

If you want mine, I'll PR. If you want @bording then i'll move along. I'm not going to get into a personal debate about opinions. 🍻

**Comment by michaelklishin** [comment]
@PureKrome even if we don't end up going with your PR, it would still contribute meaningfully as you'd share your findings and we'd have a point of reference. If you feel like finishing your work, please submit it. Thank you for contributing!

**Comment by lukebakken** [comment]
@PureKrome please open your pull request. Thank you.

**Comment by PureKrome** [comment]
No probs @michaelklishin and @lukebakken - PR with extra info, incoming.
