### ISSUE TITLE
Always strongly name / sign library

### ISSUE THREAD

**Issue by lukebakken** [rabbitmq/rabbitmq-dotnet-client#745]
Currently we keep `rabbit.snk` secret and only use it during release builds. There's no good reason to keep this data secret, so we should do the following:

* Import `rabbit.snk` into this repository
* Remove the `SignedRelease` build target
* Modify this project's build to sign all builds
* Modify internal CI scripts to not use the secret key

That's probably not a comprehensive list at this point.

Thanks to @bording for pointing out the current "really weird" process [here](https://github.com/rabbitmq/rabbitmq-dotnet-client/issues/741#issuecomment-592912332) 😄

**Comment by bording** [comment]
> Modify this project's build to sign the DLL for Release builds

Strong naming is for assembly identity, so you should always do it, not just for Release builds.
