### ISSUE TITLE
Why are there "paket" artifacts in this repository?

### ISSUE THREAD

**Issue by lukebakken** [rabbitmq/rabbitmq-dotnet-client#747]
@michaelklishin @kjnilsson I see that `paket.lock` was updated relatively recently. Is there something I need to do for the upcoming `5.2.0` and `6.0.0` releases?

**Comment by michaelklishin** [comment]
When we switched to Paket .NET Core was very immature and its tooling was both rapidly changing and outright buggy. Today we can probably rely on .NET Core build tools entirely, even though I like Paket a lot.

**Comment by michaelklishin** [comment]
@kjnilsson can/should we drop Paket and go all in, given that by 7.0 we would support .NET Core exclusively? @bording WDYT?

**Comment by bording** [comment]
On `master` at least, I don't think paket is being used at all, so I think the remaining bits are entirely vestigial and can be removed.

**Comment by lukebakken** [comment]
Thanks everyone. It seems like Paket is something that a consumer of this library may want to use but that having Paket files as part of this library aren't necessary. I'll remove from `master` and will open a separate PR to remove from `5.x`
