### ISSUE TITLE
Prerelease NuGet packages sort incorrectly

### ISSUE THREAD

**Issue by rwkarg** [rabbitmq/rabbitmq-dotnet-client#755]
Pre-release package `6.0.0-pre10` is newer than `6.0.0-pre9` but on nuget.org the sorting places the `pre10` package between `pre1` and `pre2`

This is because of how version precedence works with SemVer 2.0: https://semver.org/#spec-item-11

In the future, adding a dot between `pre` and `<prerelease_number>` would correctly numerically sort by prerelease_number instead of lexicographical as it is done now. Ex. `6.0.0-pre.10`

Unfortuantely, there are already existing packages with the existing naming scheme.

This will get "fixed" once there is an `-rc.<number>` prerelease package (since 'r' sorts after 'p') but there should still be a dot between `-rc` and `<number>`. As such, no action needs to be taken on the existing packages (indeed, nothing can be done as they're already published) but future package naming should follow a pattern that will properly sort.

**Comment by rwkarg** [comment]
This could just get closed out. Mainly wanted to have documentation of the issue and a solution for how to name packages moving forward.

**Comment by michaelklishin** [comment]
Our team does not maintain nuget.org.

**Comment by bording** [comment]
@michaelklishin It's not related to nuget.org specifically, but how the  SemVer spec says you should treat versions. 

@rwkarg's suggestion to make the package versions SemVer-compliant is a reasonable quest, and something you could change.

**Comment by michaelklishin** [comment]
Moved to #756 with a more specific description.

**Comment by lukebakken** [comment]
Thanks for bringing this to our attention.

**Comment by lukebakken** [comment]
Well, turns out we've always been removing the dot after `pre` or `rc`, probably to deal with the fact that old versions of NuGet required it - https://docs.microsoft.com/en-us/nuget/concepts/package-versioning
