### ISSUE TITLE
Adjust pre-release version naming pattern

### ISSUE THREAD

**Issue by michaelklishin** [rabbitmq/rabbitmq-dotnet-client#756]
Originally reported by @rwkarg in #755. NuGet would sort versions correctly if pre-release versions used `6.0.0-pre.{n}` instead of `6.0.0-pre{n}` as their naming pattern.

This affects RCs as well as other types of preview releases, e.g. `6.0.0-rc1` should become `6.0.0-rc.1`.

**Comment by lukebakken** [comment]
Interesting, we've always removed the dot from `pre.XX`: [code](https://github.com/rabbitmq/rabbitmq-ci/blob/16d8369ea485c749389e54eaeb05c6f2215e7650/dotnet/master/pre-rabbitmq-dotnet-client.sh#L13).

There must have been an old requirement to do that.

**Comment by lukebakken** [comment]
Fixed by https://github.com/rabbitmq/rabbitmq-ci/commit/caed04fe74f3b23bf303939695dd0fdc62d4c146

**Comment by bording** [comment]
> There must have been an old requirement to do that.

Yes, NuGet at one point did not understand SemVer 2.0 versions, so the only real way to deal with the sorting problem was to pad out things with a lot of extra zeros.

But, you can just use a proper 2.0 version now, so that seems like the best way to handle it now.
