### ISSUE TITLE
Log what TLS version(s) is enabled on the system

### ISSUE THREAD

**Issue by michaelklishin** [rabbitmq/rabbitmq-dotnet-client#765]
See #764 for the background. It would be great to have additional debug logging that would log what TLS version a connection will use and what is enabled on the system to the extent we can observe it (e.g. using https://docs.microsoft.com/en-us/dotnet/api/system.net.servicepointmanager?view=netframework-4.8).

**Comment by lukebakken** [comment]
This may not be possible with .NET core, but I will investigate prior to releasing version 7.

**Comment by lukebakken** [comment]
After re-reading #765 (whew!) my conclusion is that we don't need to implement #765 as the affected .NET Framework and .NET Core versions are no longer supported, or, if someone hits that issue (unlikely, given the PR associated with it), they can find a workaround.

**Comment by michaelklishin** [comment]
Fair enough.
