### ISSUE TITLE
AssemblyVersion isn't being updated correctly

### ISSUE THREAD

**Issue by bording** [rabbitmq/rabbitmq-dotnet-client#768]
While looking at the 6.0 package that was posted in https://github.com/rabbitmq/rabbitmq-dotnet-client/issues/764#issuecomment-602800870, I was able to confirm something I thought might be a problem.

The `AssemblyVersion` of the assemblies is not being updated. Its still stuck at `4.0.0.0`:

![image](https://user-images.githubusercontent.com/753669/77358076-98037a80-6d1f-11ea-9f5d-4704ea887780.png)

I don't really understand how the versions are being inserted into the project through your CI, but whatever it's doing is missing `AssemblyVersion`.

This is important to update since it's part of the assembly identity, and you definitely should increment it for a new major / when there are breaking changes.

**Comment by bording** [comment]
Hmm, is the CI even doing anything anymore? I know at one point there was some sort of tokenized pre-compile insert, and you can still see remnants of it. Perhaps that's no longer being done, and we just need to clean up the project to let it version things properly now?

**Comment by michaelklishin** [comment]
@bording if there's a standard approach to this in modern .NET, now would be the time to try to adopt it.

**Comment by lukebakken** [comment]
We are not using this file anywhere -

https://github.com/rabbitmq/rabbitmq-dotnet-client/blob/master/projects/client/RabbitMQ.Client/src/tokenized/AssemblyInfo.cs.in

I will delete it and figure out why `AssemblyVersion` is stuck.

**Comment by lukebakken** [comment]
@bording I'm fixing `AssemblyVersion` as it is checked in, but note that our CI does set that value:

https://www.myget.org/feed/rabbitmq/package/nuget/RabbitMQ.Client/6.0.0-pr-56b16ba6

Our CI build does not explicitly set `AssemblyFileVersion` at this time.

I forget, is it `AssemblyVersion` that stays at the latest major version, and `AssemblyFileVersion` that increments for `6.0.1`, `6.0.2`, `6.1.0`, etc or is it the other way around?

**Comment by bording** [comment]
@lukebakken I just checked a package from the MyGet feed, and it has the same problem as the one posted that I looked at earlier:

![image](https://user-images.githubusercontent.com/753669/77368680-23d2d200-6d33-11ea-933a-076147e213c4.png)

When you say " our CI does set that value:" what specifically are you referring to that your CI does? It's not clear to me what what it would be doing to create a version that is different from what you'd get building locally in VS.

> Our CI build does not explicitly set `AssemblyFileVersion` at this time.

And yet that one does seem to be picking up a value that is correct.

> I forget, is it AssemblyVersion that stays at the latest major version, and AssemblyFileVersion that increments for 6.0.1, 6.0.2, 6.1.0, etc or is it the other way around?

The only version number that actually matters for assembly identity and loading is `AssemblyVersion`. All the others are basically for display purposes.

**Comment by bording** [comment]
Could you share what your CI system is doing with the versions behind the scenes?

**Comment by bording** [comment]
> @bording if there's a standard approach to this in modern .NET, now would be the time to try to adopt it.

@michaelklishin Instead of having versions hardcoded, I'd recommend moving to one of the commit-based versioning tools. They do tend to require some changes to how you manage aspects of the repo (branching, deploying, etc).

There are 3 that I'm aware of and involved with to various degrees:

1. MinVer
2. GitVersion
3. Nerdbank.GitVersioning

**Comment by lukebakken** [comment]
Sorry @bording , I was using the explorer "Properties" to check the version rather than a better tool.

Here is the script that produces a final release of this library: 
[final-rabbitmq-dotnet-client.sh.txt](https://github.com/rabbitmq/rabbitmq-dotnet-client/files/4372518/final-rabbitmq-dotnet-client.sh.txt)

**Comment by lukebakken** [comment]
This is what is contained in the files read at the beginning of the scripts:

```
~\development\rabbitmq\rabbitmq-ci [version-dotnet-master ≡]> cat .\pre_version
6.0.0-pre.10
~\development\rabbitmq\rabbitmq-ci [version-dotnet-master ≡]> cat .\version
6.0.0-rc.1
```

**Comment by lukebakken** [comment]
So once #770 is committed, at least the hard-coded `AssemblyVersion` will be correct for PR builds.

**Comment by lukebakken** [comment]
MinVer looks like a good solution, thanks for the suggestion.

**Comment by bording** [comment]
> This is what is contained in the files read at the beginning of the scripts:

I don't understand what that is showing me. How does that get into the actual versions baked into the assemblies?

**Comment by lukebakken** [comment]
These lines edit the `AssemblyInfo.cs` and `csproj` file in-place on the CI server with version information, prior to the `dotnet build` and packing steps:

```
# update informational/product version
sed -i'' 's/AssemblyInformationalVersion("[^"]*")/AssemblyInformationalVersion("'"$version"'")/g' "$assembly_info_file"

# update only the major version number for the assembly version
sed -i'' 's/AssemblyVersion("[^.]*\.0\.0")/AssemblyVersion("'"$major"'.0.0")/g' "$assembly_info_file"

# update the VersionPrefix field which becomes the package version during dotnet pack
sed -i'' 's/<VersionPrefix>[^<]*<\/VersionPrefix>/<VersionPrefix>'"$version"'<\/VersionPrefix>/g' "$project_file"
```

Based on what you said earlier, we need to be setting `AssemblyVersion` to more than just the major version. I think moving to MinVer will solve our issues.

**Comment by lukebakken** [comment]
You see version `4.0.0` in the myget packages because the build script for PRs doesn't modify the versions. I'll address that as well. Thanks for noticing the very out-of-date `AssemblyVersion` value.

**Comment by bording** [comment]
> Based on what you said earlier, we need to be setting AssemblyVersion to more than just the major version

No, that's actually a good practice for AssemblyVersion when you're following SemVer and strong naming, because it's part of the assembly identity. Adding minor and patch versions means the assembly would require binding redirects more often for no real benefit. 

When you've made a breaking change, then you want the assembly identity to update a well, which is why `major.0.0.0` is a good way to go.

> I think moving to MinVer will solve our issues.

Yes, this moves versioning into the repo and gets it out of a CI script, so :+1: to that.

**Comment by lukebakken** [comment]
OK, to summarize for the version `6` series:

* `AssemblyVersion` always remains at `6.0.0.0`
* `AssemblyFileVersion` has the full version (like `6.1.3.0`)
* The MyGet / NuGet packages also have the full version (like `6.1.3.0`)
* What do you recommend for `AssemblyInformationalVersion`?

**Comment by bording** [comment]
> AssemblyVersion always remains at `6.0.0.0`

👍 
> AssemblyFileVersion has the full version (like `6.1.3.0`)

👍 

> The MyGet / NuGet packages also have the full version (like `6.1.3.0`)

This one would actually be a 3-part number, so `6.1.3`

> What do you recommend for AssemblyInformationalVersion?

This can really be anything. It's pretty common to see a full SemVer 2.0 version with metadata that includes things like commit hash and branch name.

To give an example, if I build the NServiceBus RabbitMQ transport master branch right now, I get the following:

```
AssemblyVersion: 5.0.0.0
AssemblyFileVersion: 5.2.0.0
Package version: 5.2.0-alpha.67
AssemblyInformationalVersion: 5.2.0-alpha.67+Branch.master.Sha.c3a3daf2e1c0d0a98bd65978d2d7a6ad0aaa48ab.c3a3daf2e1c0d0a98bd65978d2d7a6ad0aaa48ab
```

We're currently getting the commit hash in there twice because GitVersion is including it, and then Source Link is appending it again. That's something I need to look into fixing!

And if you view the details of the assembly in Windows, you see the following:
![image](https://user-images.githubusercontent.com/753669/77454719-4adee180-6dcf-11ea-920f-cf07dc78b4e6.png)

You can see that AssemblyFileVersion is displayed as "File version" and AssemblyInformationalVersion is displayed as "Product version". 

AssemblyVersion is not displayed at all.

**Comment by lukebakken** [comment]
@bording hot off the presses:

https://www.nuget.org/packages/RabbitMQ.Client/6.0.0-pre.11

https://www.nuget.org/packages/RabbitMQ.Client/5.2.0-rc.2

**Comment by bording** [comment]
It might be worth unlisting the older 6.0 preview packakges on nuget.org:
![image](https://user-images.githubusercontent.com/753669/77807474-5136bd00-705e-11ea-8102-d25751d724f9.png)

Shouldn't be a problem going forward, but old version format is currently sorting higher.

**Comment by bording** [comment]
Also, and I know this is unrelated to this issue, do you have a larger version of the icon for the packge? Something 64x64 would be ideal:

The current one is way too small:

![image](https://user-images.githubusercontent.com/753669/77807573-a2df4780-705e-11ea-80b9-11ac3caea3aa.png)

**Comment by lukebakken** [comment]
Aha! I was wondering where that `icon.png` file was used. I just thought it was in explorer. I'll get a 64x64 one in the next pre-release.

**Comment by lukebakken** [comment]
Listing is updated on NuGet.org

**Comment by lukebakken** [comment]
OK new image added and it's almost right ... I just fixed the transparent background. Next version will have it. Thanks for noticing @bording and have a great weekend.

**Comment by lukebakken** [comment]
*Finally* got the transparency right -

https://www.nuget.org/packages/RabbitMQ.Client/6.0.0-pre.14

Thank you to the GIMP - https://github.com/GNOME/gimp
