### ISSUE TITLE
Pull Request myget packages should have a better name

### ISSUE THREAD

**Issue by lukebakken** [rabbitmq/rabbitmq-dotnet-client#769]
See [this comment](https://github.com/rabbitmq/rabbitmq-dotnet-client/issues/764#issuecomment-602879981)

**Comment by michaelklishin** [comment]
Ideally there should be a way to have them sorted chronologically, which I don't think is the case at the moment.

**Comment by lukebakken** [comment]
This is a good start:

https://www.myget.org/feed/rabbitmq/package/nuget/RabbitMQ.Client/6.0.0-pre.10.31+782

Version metadata is the pull request number. The number `31` is the number of commits since the latest tag (the ["height"](https://github.com/adamralph/minver#how-it-works)).

Fixed by https://github.com/rabbitmq/rabbitmq-ci/commit/dcfdf8dc6c0e50da3c54aee5b70d54a1713590bf
