### ISSUE TITLE
Broken Link to ChangeLog.md from README.md

### ISSUE THREAD

**Issue by HermannGruber** [rabbitmq/rabbitmq-dotnet-client#778]
In [README.md](https://github.com/rabbitmq/rabbitmq-dotnet-client/blob/5.x/README.md) the link to the changelog is broken.

**Comment by michaelklishin** [comment]
This is open-source software so you are welcome to contribute by submitting a pull request.

**Comment by HermannGruber** [comment]
Thanks for the encouragement! Next time I'll go ahead and do a PR :-)
