### ISSUE TITLE
6.0 change log

### ISSUE THREAD

**Issue by michaelklishin** [rabbitmq/rabbitmq-dotnet-client#793]
6.0 has enough substantial changes that we should produce a detailed changelog, even if most of them ended up being backward-compatible.

**Comment by lukebakken** [comment]
Sounds good, I'll go through [the milestone](https://github.com/rabbitmq/rabbitmq-dotnet-client/milestone/41?closed=1) and will pick out changes that users will find interesting.

**Comment by michaelklishin** [comment]
To be more specific, I find RabbitMQ's own change log to be reasonably specific. This client's own change log is typically very terse with single line change descriptions.

`System.Memory` data types and their implicit conversions are worth mentioning even if they are mostly a boring implementation detail.

It would be great to have some final memory and throughput comparisons done, the likes of what @stebet and @Anarh2404 have provided with their PRs.
