### ISSUE TITLE
Solution configurations always use "Debug"

### ISSUE THREAD

**Issue by lukebakken** [rabbitmq/rabbitmq-dotnet-client#797]
I noticed that no matter what build configuration is used, the output is always `bin\Debug\X` where `X` is the target framework.

I had to run a build with `detailed` output to be sure that this command actually used the `Release` configuration:

```
dotnet build .\RabbitMQDotNetClient.sln --configuration Release --verbosity detailed
```

Output: [build-out.txt](https://github.com/rabbitmq/rabbitmq-dotnet-client/files/4411023/build-out.txt)

This isn't the end of the world it's just ... odd.

**Comment by lukebakken** [comment]
Setting the `OutputPath` property the "usual way" in the `csproj` files via VS doesn't have an effect. I'm kind of mystified.

**Comment by bording** [comment]
@lukebakken This is actually a big problem because that means you're never building Release mode assemblies. Debug assemblies don't have any optimizations enabled.

I see what the problem is though:

```
	GlobalSection(ProjectConfigurationPlatforms) = postSolution
		{8C554257-5ECC-45DB-873D-560BFBB74EC8}.Debug|Any CPU.ActiveCfg = Debug|Any CPU
		{8C554257-5ECC-45DB-873D-560BFBB74EC8}.Debug|Any CPU.Build.0 = Debug|Any CPU
		{8C554257-5ECC-45DB-873D-560BFBB74EC8}.Release|Any CPU.ActiveCfg = Debug|Any CPU
		{8C554257-5ECC-45DB-873D-560BFBB74EC8}.Release|Any CPU.Build.0 = Debug|Any CPU
		{B8FAC024-CC03-4067-9FFC-02846FB8AE48}.Debug|Any CPU.ActiveCfg = Debug|Any CPU
		{B8FAC024-CC03-4067-9FFC-02846FB8AE48}.Debug|Any CPU.Build.0 = Debug|Any CPU
		{B8FAC024-CC03-4067-9FFC-02846FB8AE48}.Release|Any CPU.ActiveCfg = Debug|Any CPU
		{B8FAC024-CC03-4067-9FFC-02846FB8AE48}.Release|Any CPU.Build.0 = Debug|Any CPU
		{B416DDB7-5E3E-4A20-B5A9-C6E518E203A2}.Debug|Any CPU.ActiveCfg = Debug|Any CPU
		{B416DDB7-5E3E-4A20-B5A9-C6E518E203A2}.Debug|Any CPU.Build.0 = Debug|Any CPU
		{B416DDB7-5E3E-4A20-B5A9-C6E518E203A2}.Release|Any CPU.ActiveCfg = Debug|Any CPU
		{B416DDB7-5E3E-4A20-B5A9-C6E518E203A2}.Release|Any CPU.Build.0 = Debug|Any CPU
```

In the solution file, the Release mode configurations are defined as using Debug for some reason.

**Comment by lukebakken** [comment]
Alright, I missed that! Let me fix it.

**Comment by bording** [comment]
@lukebakken It looks like there is a similar problem on the `5.x` branch. Looking at the solution file, I can see that there are still a lot of project-level entries, but the solution-level entries for them have been removed. There's just `Debug` and `Release` now, and those project-level entries have some problems.

**Comment by lukebakken** [comment]
Thanks, I'll file an issue for `5.x`. I was going to check in the morning :-)
