### ISSUE TITLE
UNEXPECTED_FRAME during multithreaded message publishing

### ISSUE THREAD

**Issue by Anarh2404** [rabbitmq/rabbitmq-dotnet-client#800]
Master branch
`Message: 
    RabbitMQ.Client.Exceptions.AlreadyClosedException : Already closed: The AMQP operation was interrupted: AMQP close-reason, initiated by Peer, code=505, text='UNEXPECTED_FRAME - expected content header for class 60, got non content header frame instead', classId=60, methodId=40`

Link to the test in my branch https://github.com/Anarh2404/rabbitmq-dotnet-client/blob/unexpected-frame-repro/projects/Unit/TestFloodPublishing.cs#L89

In branch 5.x the test passes

**Comment by michaelklishin** [comment]
You are sharing a channel for concurrent publishing, which this or any other RabbitMQ client our team maintains has never supported. Client API guide should mention this as a no-no.

**Comment by michaelklishin** [comment]
[Sharing Channels Between Threads](https://www.rabbitmq.com/dotnet-api-guide.html#model-sharing) is the section I was referring to.

**Comment by michaelklishin** [comment]
https://github.com/rabbitmq/rabbitmq-dotnet-client/issues/681 is also relevant here. That issue covers publishing on a shared *connection* and https://github.com/Anarh2404/rabbitmq-dotnet-client/blob/unexpected-frame-repro/projects/Unit/TestFloodPublishing.cs#L127 does it on a shared *channel* (`IModel`).

**Comment by ttutko** [comment]
We just hit his same issue after upgrading to RabbitMQ.Client 6.0.0 from 5.1.0. We were using async tasks to perform some work and then publish a message to an exchange. However, we were using a singleton IModel instance. The options as we saw it in the short term were to either create Hundreds of IModel instances in the span of a few seconds or add locking on the IModel instance around the call to BasicPublish. 

@michaelklishin I thought I saw in another issue somewhere that the locking commits that caused this to break were rolled back? Is that accurate and should that be in 6.0.0 or a future release? Also, the TestFloodPublishing test that you linked to in your comment above does not seem to do anything with sharing IModel across threads despite the comments/title saying it does. Unless I am missing something, all of the IModel usage is on a single thread in the test. You would need to spin off multiple Tasks and then `Task.WhenAll()` them to reproduce the error. Can the docs/samples be updated to show the recommended way to perform BasicPublish within asynchronous tasks?

**Comment by stebet** [comment]
A good workaround is to use System.Threading.Channels if possible, or a ConcurrentQueue to buffer your messages from multiple threads. That way you can have a single reader task reading asynchronously from the Channel/Queue and send the messages on a dedicated channel. You can then increase the number of readers if you find your buffers filling up to keep up with the publishing.

**Comment by lukebakken** [comment]
@ttutko you are correct, `IModel` instances can't be shared across threads, and has never been supported by this library.

**Comment by ttutko** [comment]
I get that it might not have been the intention but it always worked before up through at least 5.1.0. The referenced test mentioned by @michaelklishin in https://github.com/rabbitmq/rabbitmq-dotnet-client/issues/800#issuecomment-608515505 has a test called `TestMultithreadFloodPublishing()` but the test does nothing multi-threaded.

Is creating IModel relatively expensive? Trying to determine if it's better to synchronize `BasicPublish()` calls with a `lock(channel) { }` pattern (this is what we did so far and has resolved the issue) or just create a new IModel instance every time.

@stebet has a good possibility too so I will have to consider that. Thanks.

**Comment by michaelklishin** [comment]
Opening a channel is a network round trip. Expensive enough to ruin throughput if you [open a new one per message](https://www.rabbitmq.com/channels.html#lifecycle).
