### ISSUE TITLE
Enable Deterministic Builds for packaged releases

### ISSUE THREAD

**Issue by stebet** [rabbitmq/rabbitmq-dotnet-client#805]
[Deterministic builds](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-options/deterministic-compiler-option) should be enabled for NuGet releases to both enable source linking and to verify that the code has indded been built with the referenced sources.

There is an excellent guide on how to enable this by @clairernovotny here: https://github.com/clairernovotny/DeterministicBuilds

**Comment by lukebakken** [comment]
Thanks, this looks relatively easy to do for `6.0.0`.
