### ISSUE TITLE
Support connection lists and host selection strategies

### ISSUE THREAD

**Issue by btecu** [rabbitmq/rabbitmq-dotnet-client#81]
I think it would be very useful to have a thin wrapper. For instance, the Java client supports creating a connection factory providing an array of addresses (ip and port). I read something about auto-healing although I don't remember seeing it documented and so I'm not sure if it's fully supported.

Specifically, I would like to be able to provide multiple servers and the client should take care of the rest. What happens if the current server goes down? Switch to another server. Perhaps have options for how many attempts before giving up, how to pick the next server...

**Comment by michaelklishin** [comment]
Automatic connection recovery [is provided in the .NET client](http://www.rabbitmq.com/dotnet-api-guide.html). The only thing it is missing is a way to specify a list of hosts.

**Comment by Pliner** [comment]
Very good news :+1:  

It seems to be the last step in .Net client before migrating to its recovery mechanism in EasyNetQ!

**Comment by michaelklishin** [comment]
Excellent. I'm fairly happy with how this is shaping up.

**Comment by scratch-net** [comment]
@Pliner 
Does it mean that EasyNetQ will use the built in recovery mechanism instead of its own?
