### ISSUE TITLE
Symbol packages aren't being published to nuget.org

### ISSUE THREAD

**Issue by bording** [rabbitmq/rabbitmq-dotnet-client#817]
While I don't particularly care for symbol packages, the .snupkg files should be uploaded to nuget.org as well, and I see that hasn't been done yet for the newly released packages.

**Comment by lukebakken** [comment]
Output from the release process indicates they should have been uploaded:

```
+ dotnet nuget push -k c03a8981-5c48-42a5-8171-5c99b409f04c -s https://www.nuget.org/api/v2/package ./packages/RabbitMQ.Client.6.0.0.nupkg
Pushing RabbitMQ.Client.6.0.0.nupkg to 'https://www.nuget.org/api/v2/package'...
  PUT https://www.nuget.org/api/v2/package/
  Created https://www.nuget.org/api/v2/package/ 955ms
Your package was pushed.
+ set +u
+ set -- ./packages/RabbitMQ.Client.6.0.0.snupkg
+ [ -f ./packages/RabbitMQ.Client.6.0.0.snupkg ]
+ dotnet nuget push -k c03a8981-5c48-42a5-8171-5c99b409f04c -s https://www.nuget.org/api/v2/package ./packages/RabbitMQ.Client.6.0.0.snupkg
```

**Comment by lukebakken** [comment]
I don't see the success message, however. Hm.

**Comment by bording** [comment]
Hmm, if they actually made it to nuget.org, there should be a separate symbols download link on the page for the package.

**Comment by bording** [comment]
Oh, I'm pretty sure there's a separate url you're supposed to push the symbol packages to.

**Comment by bording** [comment]
Yeah, looks like you've got the older v2 urls hardcoded, so you'd need a different symbol url.

However, if you change everything to `https://api.nuget.org/v3/index.json` instead, I think it just works.

**Comment by lukebakken** [comment]
That's a weird upload URL. Thanks

**Comment by lukebakken** [comment]
@bording thank you for noticing this. I have updated our CI scripts to use the correct URL for NuGet and MyGet.

Symbols for 6.0 are indexed, and 5.2 are in-process right now.
