### ISSUE TITLE
NullReferenceException on AutorecoveringModel.IsClosed

### ISSUE THREAD

**Issue by ig-sinicyn** [rabbitmq/rabbitmq-dotnet-client#829]
RabbitMQ.Client 6.0.0, RabbitMQ.Client.Impl.AutorecoveringModel:

```
        public bool IsClosed
        {
            get { return _delegate.IsClosed; }
        }
```
The getter throws null reference for disposed entities. Reason [is here](https://github.com/rabbitmq/rabbitmq-dotnet-client/blob/eb48e2dcff49b704fb2be95abc4628a662149a53/projects/RabbitMQ.Client/client/impl/AutorecoveringModel.cs#L368):
```
        private void Dispose(bool disposing)
        {
            if (disposing)
            {
               ...
                _delegate = null;
            }
        }
```

**Comment by lukebakken** [comment]
This should be a simple fix, please submit a pull request with a test. Thank you.

**Comment by bording** [comment]
The question is, what is the correct behavior? If the object is disposed, should that return `true` or `false`?

Or should it throw [ObjectDisposedException](https://docs.microsoft.com/en-us/dotnet/api/system.objectdisposedexception)?

**Comment by ig-sinicyn** [comment]
I'd prefer following behavior:
1. For members that are used to check for connection availability/health - do not throw.
As far as I can see there are only two properties that should not throw:
IsOpen (returns false if disposed);
IsClosed (returns true if disposed). 
2. For all other members: throw ObjectDisposedException.

**Comment by ig-sinicyn** [comment]
@lukebakken I'm quite busy this week so the issue is up for grabs:)

**Comment by michaelklishin** [comment]
It would be slightly more user-friendly if `IsOpen` and `IsClosed` continued acting like predicates and did not throw when the underlying non-recovering connection is disposed of.

**Comment by stebet** [comment]
Yep. Throwing in Property Getters is considered bad practice.

**Comment by lukebakken** [comment]
I'm getting this today.
