### ISSUE TITLE
The implementation of the AsyncEventingBasicConsumer is not safe when there are multiple handlers attached

### ISSUE THREAD

**Issue by quixoticaxis** [rabbitmq/rabbitmq-dotnet-client#838]
The invocations of the events in [`AsyncEventingBasicConsumer`](https://github.com/rabbitmq/rabbitmq-dotnet-client/blob/4e5a405c879129d8bcb4ab1b6a387c26a9967947/projects/RabbitMQ.Client/client/events/AsyncEventingBasicConsumer.cs) are not safe when there are multiple handlers attached in a sense that they only await the handler that had been attached last.
For example, the `Received` event is invoked like this:
```csharp
await (Shutdown?.Invoke(this, reason) ?? Task.CompletedTask).ConfigureAwait(false);
```
This invocation is starting the handlers one by one, and, as soon as one returns a `Task`, it moves to the next one. When it  reaches the last handler, it grabs its resulting task and awaits only this single `Task` (or `Task.CompletedTask` if the last handler happens to return `null`). I suppose this is not intended.

If the idea is to await all of the handlers (and, considering the remarks that state that "Handlers must copy or fully use delivery body before returning", it is), something along the lines of
```csharp
var received = Received;
await Task.WhenAll(received.GetInvocationList()
    .Select(handler => handler.DynamicInvoke(
        this,
        new BasicDeliverEventArgs(
            consumerTag,
            deliveryTag,
            redelivered,
            exchange,
            routingKey,
            properties,
            body)) as Task
        ?? Task.CompletedTask))
        .ConfigureAwait(false);
```
may fix the issue.

P.s. I've initially asked the question in the [mailing lists](https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!topic/rabbitmq-users/bxUujWAxwPg), but I guess it's more comfortable to discuss the code on github.

**Comment by lukebakken** [comment]
I _think_ I understand what is being asked here. This project is open-source and we would welcome a pull request that implements a solution with a test that demonstrates the problem with the current implementation. Thank you.

**Comment by bording** [comment]
While I'm not sure why you'd want multiple handlers attached to the the events, you are correct that the the way the are being invoked right now prevents that from working properly.

I wouldn't to see LINQ introduced into this code path, though, so a foreach loop over the `GetInvocationList` results probably makes more sense.

**Comment by bording** [comment]
Microsoft does have an MIT licensed `InvokeAsync` extension method that could potentially be used as inspiration, but I'll leave it to @lukebakken to determine if there are any licensing considerations around that.

**Comment by stebet** [comment]
Good catch!
