### ISSUE TITLE
WaitForConfirmsOrDie closes channel and connection - how to recover?

### ISSUE THREAD

**Issue by arabelaa** [rabbitmq/rabbitmq-dotnet-client#853]
I am using rabbitmq (rabbitmq:3.7.17) inside docker container in an environment with a lot of network hiccups. 

I configured a timeout of 10 seconds when calling WaitForConfirmsOrDie but this is not enough. It fails quite often because of network issues.

I noticed that in case this fails the channel closes and the connection also.
```

2020-05-26 13:35:47.962 [error] <0.2959.0> Error on AMQP connection <0.2959.0> (172.28.0.7:37475 -> 172.28.0.3:5672, vhost: '/', user: 'guest', state: running), channel 4:
 operation basic.publish caused a connection exception channel_error: "expected 'channel.open'"
2020-05-26 13:35:59.959 [info] <0.2959.0> closing AMQP connection <0.2959.0> (172.28.0.7:37475 -> 172.28.0.3:5672, vhost: '/', user: 'guest')
```
I would like to recover from this situations. 

I have the following setup

   ```
public AmqpClient this[string topic] => _topicDictionary.GetOrAdd(topic, CreateAmqpClient);
   // AmqpClient is just a wrapper around IModel and EventingBasicConsumer

        private AmqpClient CreateAmqpClient(string topic)
        {
            var model = _connection.CreateModel();
            model.ModelShutdown += (sender, args) =>
            {
                if (args.Initiator != ShutdownInitiator.Application ||
                    args.ReplyText != "Timed out waiting for acks") return;

                _topicDictionary.Remove(topic, out _);
                _logger.LogWarning("Publish to topic {topic} timed out waiting for acks.", topic);
            };
            return new AmqpClient(model, topic, _messageHandlingOptions);
        }
```

I have a dictionary <topic, channel>. When an model.ShutDown is triggered by ModelBase WaitForConfirmsOrDie
```
    public void WaitForConfirmsOrDie(TimeSpan timeout)
    {
      bool timedOut;
      if (!this.WaitForConfirms(timeout, out timedOut))
      {
        this.Close(new ShutdownEventArgs(ShutdownInitiator.Application, (ushort) 200, "Nacks Received", (object) new IOException("nack received")), false);
        throw new IOException("Nacks Received");
      }
      if (timedOut)
      {
        **this.Close(new ShutdownEventArgs(ShutdownInitiator.Application, (ushort) 200, "Timed out waiting for acks", (object) new IOException("timed out waiting for acks")), false);**
        throw new IOException("Timed out waiting for acks");
      }
    }
```
I remove the model from the dictionary so the next publish will create the channel again. 
The problem with this approach is that I have hanging connections (not all the time) and my consumers are unable to process the messages from the queue (I am using `EventingBasicConsumer `- push approach) - I am obliged to kill the hanging connections for the consumers to be able to process messages.
I believe this will work in 80-90% of the time (if the broker confirms in max 10 sec), but not 100% and I need reliability. Btw I am using the default setup for the `Connection ` creation (so autorecovery enabled, `RequestedHeartbeat `60 sec)

So this approach is not ok. 
Is there another way to recover? Any hints, advises are appreciated. Thanks!

**Comment by michaelklishin** [comment]
Thank you for your time.

Team RabbitMQ uses GitHub issues for specific actionable items engineers can work on. GitHub issues are not used for questions, investigations, root cause analysis, discussions of potential issues, etc (as defined by this team).

We get at least a dozen of questions through various venues every single day, often light on details.
At that rate GitHub issues can very quickly turn into a something impossible to navigate and make sense of even for our team. Because GitHub is a tool our team uses heavily nearly every day, the signal/noise ratio of issues is something we care about a lot.

Please post this to [rabbitmq-users](https://groups.google.com/forum/#!forum/rabbitmq-users).

Thank you.
