### ISSUE TITLE
Re-visit PR #855

### ISSUE THREAD

**Issue by lukebakken** [rabbitmq/rabbitmq-dotnet-client#859]
#855 

See this comment by @danielmarbach -

https://github.com/rabbitmq/rabbitmq-dotnet-client/pull/855#issuecomment-637456360

**Comment by lukebakken** [comment]
Fixed by #863

**Comment by danielmarbach** [comment]
@lukebakken I'm very confused now. Maybe you can help me. I looked at https://github.com/rabbitmq/rabbitmq-dotnet-client/blob/6.x/projects/RabbitMQ.Client/client/impl/Work.cs#L19 on the 6.x branch and it still has the yield in there

**Comment by lukebakken** [comment]
I must have forgotten to back port this.
