### ISSUE TITLE
Connection close hangs forever if closed for second time

### ISSUE THREAD

**Issue by SubasishMohapatra** [rabbitmq/rabbitmq-dotnet-client#872]
I am using RabbitMQ .Net Client 6.0.0 in our application. I am using a wrapper class to encapsulate my queue Channel and Connection object. I reuse this object by calling a clean method which basically closes, disposes and sets Connection and Channel objects to null. The first time I do it it works fine.
However the second time when I recreate the wrapper instance and try to call connection.Close() manually, it hangs forever. On hovering on it, it shows as "auto-recovering". But if I don't call Close(), just call dispose and set it to null it works fine.
Whats the recommended way to clean up the existing connection including the channels?

```
public void Clear()
{
          _connection?.Close();
            Channel?.Close();
            Channel?.Dispose();
            _connection?.Dispose();
            Channel = null;
            _connection = null;
}
```

**Comment by michaelklishin** [comment]
@SubasishMohapatra can you inspect the threads and their state when your app is in that state, please?

**Comment by SubasishMohapatra** [comment]
Ohh yesss..that was the cause...The creation of channels and closing was happening on different threads.
Thanks for the hint.

**Comment by RomanGorgol** [comment]
We have faced similar problem. Sometimes connection.Close() hangs. But I can't understand why threads are matter? Is it necessary to create and close channel on the same thread?

RabbitMQ .Net Client 3.2.4
Rabbit 3.7.7

**Comment by lukebakken** [comment]
@RomanGorgol - please upgrade to the latest client. Version 3.X is no longer supported and is very old.
