### ISSUE TITLE
Immediate call to GetAllQueue API after DeleteQueue API returns me the deleted queue as well

### ISSUE THREAD

**Issue by SubasishMohapatra** [rabbitmq/rabbitmq-dotnet-client#873]
I see a problem when I call Get All Queues API immediately after Delete API.
The GetAllQueues API still returns me the deleted queue and I have to wait a while to reflect the right results(excluding the deleted one)

var deletionTask = httpClient.DeleteAsync(string.Format(CultureInfo.InvariantCulture, "/api/queues/{0}/{1}", virtualHost, queueName));
var queueResult = httpClient.GetAsync(string.Format(CultureInfo.InvariantCulture, "api/queues/{0}", virtualHost)).Result;

Whats the remedy here?

**Comment by michaelklishin** [comment]
This client has nothing to do with the HTTP API client you use. Connections, channels and queues emit stats periodically so closure or deletion events are observable after a certain delay.

**Comment by sungam3r** [comment]
@SubasishMohapatra Did you **await** `deletionTask` ?

**Comment by michaelklishin** [comment]
The client used in this issue is the HTTP API client, most likely the one provided by EasyNetQ. This is an AMQP 0-9-1 client.
