### ISSUE TITLE
Message header of type byte[]

### ISSUE THREAD

**Issue by BenBorn** [rabbitmq/rabbitmq-dotnet-client#879]
We have a Byte-array in the amqp-header if I use the code:
`result.BasicProperties.Headers.TryGetValue("key", out object value);`
the value has the type: `BinaryTableValue`. But this type is internal. So how can I now get the byte[] content?

**Comment by michaelklishin** [comment]
This is not intentional. We should make this value public and move it to the public part of the API, `RabbitMQ.Client`. Feel free to submit a PR that does it. In the meantime, you can use string values instead.

**Comment by lukebakken** [comment]
Fixed by #880
