### ISSUE TITLE
Compatibility with Visual Studio 2019 Community 

### ISSUE THREAD

**Issue by lukebakken** [rabbitmq/rabbitmq-dotnet-client#885]
@bording @stebet @danielmarbach  I'm hoping you can assist me with this one.

I haven't tried to open the `RabbitMQDotNetClient.sln` file in VS2019 for a couple weeks but now when I open the `.sln` file I get prompted to migrate the projects. After migration, the `.cs` files are no longer listed under the projects and of course it doesn't build. Building from the command line works as expected.

![vs2019-where-the-heck-is-everything](https://user-images.githubusercontent.com/514926/86156161-5fabcf00-baba-11ea-90ac-00d1be1dc19e.png)

I completely removed VS2019 and re-installed, then used the "Visual Studio Installer" to ensure that every .NET and .NET Core related feature is enabled. I am using chocolatey to install VS2019, here are the relevant versions -

```
visualstudio-installer 2.0.1
visualstudio2019community 16.6.1.0
```

I have used "Import and Export Settings" to reset all settings to defaults.

This isn't a show-stopper as I frequently work on this project using `vim`, but it's annoying and I can't seem to figure this out. Here is the compressed upgrade log: 
[UpgradeLog.zip](https://github.com/rabbitmq/rabbitmq-dotnet-client/files/4853415/UpgradeLog.zip)

I also committed the small number of changes after the upgrade in this branch: https://github.com/rabbitmq/rabbitmq-dotnet-client/tree/lrb-migrated-vs2019

Configuration exported from "Visual Studio Installer" - 
[vsconfig.txt](https://github.com/rabbitmq/rabbitmq-dotnet-client/files/4853460/vsconfig.txt)

Any assistance is very much appreciated, thanks.

**Comment by bollhals** [comment]
I use VS 2019 exclusively but no upgrade was required of any project in the solution...

**Comment by lukebakken** [comment]
@bollhals I was using VS2019 day-to-day leading up to the 6.0 and 6.1 releases without issue. Then, an upgrade screwed everything up. I may re-try uninstalling everything again and then re-installing without using chocolatey.

**Comment by bording** [comment]
> I may re-try uninstalling everything again and then re-installing without using chocolatey.

That's what I suggest. I'm able to open the solution on `master` without any sort of upgrade prompts.

**Comment by lukebakken** [comment]
Great, thanks @bording. Are you using VS2019 community edition? Does the list of selected components in vsconfig.txt make sense to you?

**Comment by Keboo** [comment]
The issue is you need to install the .NET Core workload from the Visual Studio installer.

**Comment by bording** [comment]
> Are you using VS2019 community edition?

No, I'm using Professional, but that shouldn't make a difference.

>  Does the list of selected components in vsconfig.txt make sense to you?

You do seem to be missing some items compared to what I have installed. As @Keboo mentioned, you do need the . NET Core workload installed.

Here's a picture of what my installer looks like:
![image](https://user-images.githubusercontent.com/753669/86169527-c4c9e980-bae7-11ea-84e3-1ae74c11b930.png)

**Comment by lukebakken** [comment]
Great! Thanks. This is the first I've heard of the ".NET Core Workload".

**Comment by lukebakken** [comment]
Thanks a lot everyone. I uninstalled everything development related and only installed VS2019 community (still via chocolatey) with the suggested ".NET desktop development" workload rather than individual packages. It's back to working again. Now I just need ViEmu and I'll be set.
