### ISSUE TITLE
Consider restricting the ability push commits to branches without a PR first

### ISSUE THREAD

**Issue by bording** [rabbitmq/rabbitmq-dotnet-client#889]
I'd like to suggest that branch protection settings be enabled so that all changes to the "permanent" branches (master and the version branches) be done via PR only, removing the ability for commits to be pushed branches directly.

The reason I think this would a be a good change is that it helps improve visibility of all the code changes being made. Since I watch this repo, I get notifications for all PRs, but when a commit is pushed to a branch, skipping a PR, no notification is raised.

Using the PR process would give all external contributors a chance to inspect and comment on all changes made.

**Comment by michaelklishin** [comment]
We rarely push directly, usually it’s tiny documentation or test updates. Pushes to topic branches are effectively all backports. We can try it. Similar restrictions in other RabbitMQ projects have not always been well received.

**Comment by lukebakken** [comment]
Here is what I have set for the `master`, `6.x` and `5.x` branches: [branch-protection-rules.pdf](https://github.com/rabbitmq/rabbitmq-dotnet-client/files/4881240/branch-protection-rules.pdf)

**Comment by michaelklishin** [comment]
I have started doing all backports via a separate PR. It’s not really annoying as I expected it to be. Let’s see how these two changes go.
