### ISSUE TITLE
Subscription.Close() hangs if queue is deleted underneath it

### ISSUE THREAD

**Issue by cjbhaines** [rabbitmq/rabbitmq-dotnet-client#89]
Hi,

I'm in the process of trying to upgrade from 3.1.1 to 3.5.2. We have some integration tests in our libraries which wrap the RabbitMQ.Client and test for deleting a queue from underneath the consumer and handle recreating it which fail with the 3.5.2. 

In 3.1.1 Subscription.Next would return true but have a null delivery which is a sign for us to restart our consumer loop because it's not in a good state, closing the subscription would then throw a NullReferenceException which we would catch and re-declare the queue. 

In 3.5.2 with all auto recovery options disabled when I delete the queue the Subscription returns a null delivery as with 3.1.1 but then Subscription.Close hangs indefinitely.

I have uploaded a project which reliably reproduces this issue which you can download from my OneDrive account here: https://onedrive.live.com/redir?resid=bb18e69b948ef2cb!10413&authkey=!AGQfekistaojCsg&ithint=file%2czip

Follow the instructions from the console apps. Tested against server versions: 3.3.5, 3.4.1, 3.5.2.

Would appreciate any help on this because I can't spot any smoking guns in the RabbitMQ.Client code.

Thanks,
Chris

**Comment by michaelklishin** [comment]
Anything in the RabbitMQ logs around the time?

**Comment by cjbhaines** [comment]
Just this:

=INFO REPORT==== 18-May-2015::17:25:04 ===
accepting AMQP connection <0.433.0> ([::1]:53796 -> [::1]:5672)

=WARNING REPORT==== 18-May-2015::17:25:06 ===
closing AMQP connection <0.433.0> ([::1]:53796 -> [::1]:5672):
connection_closed_abruptly

**Comment by michaelklishin** [comment]
@cjbhaines so the change in behaviour seems to be since 3.3.x, am I understanding correctly? I'll look into this once I'm back from being on the road next week.

**Comment by cjbhaines** [comment]
I suspect this is a client side issue as 3.1.1 works with all server versions I have tested, and from looking at the release notes the .NET client changes started from 3.2.0. I will look at testing every version up from there to see when it starts deadlocking itself.

**Comment by cjbhaines** [comment]
I can reproduce this from 3.2.0 onwards.

**Comment by michaelklishin** [comment]
May have to do with bug `25716`, which is about making `queue.delete` idempotent.

**Comment by michaelklishin** [comment]
Thanks for bisecting it!

**Comment by michaelklishin** [comment]
This may be due to a behaviour change of `queue.delete` in bug `25716`: the method is now idempotent. Consumer cancellation notifications should not be affected, though.

**Comment by cjbhaines** [comment]
No worries, thanks for looking into this! It's worth noting the queue delete uses a different channel. In other scenarios I have tried I have even used a different connection.

**Comment by michaelklishin** [comment]
Fixed by #93.

**Comment by cjbhaines** [comment]
Fix looks good, thanks!
