### ISSUE TITLE
Regression / change in behavior in version 6.1

### ISSUE THREAD

**Issue by lukebakken** [rabbitmq/rabbitmq-dotnet-client#891]
A couple users have reported issues when upgrading from 6.0 to 6.1:

* Heartbeat timeouts in "high throughput" scenario - https://groups.google.com/d/topic/rabbitmq-users/IPjq9-rccBI/discussion
* AMQP handshake timeout on connect - https://groups.google.com/d/topic/rabbitmq-users/0XCwaOlAX38/discussion

Could either of these be due to insufficient threads available in the thread pool upon startup?

**Comment by stebet** [comment]
Would be interesting to see. Have they tried 6.1.1 to see if that fixes any of the issues?

**Comment by lukebakken** [comment]
I will ask, good point.

**Comment by lukebakken** [comment]
`6.1.1` became `6.2.0` which I haven't released yet. I will release an RC today after finishing up #868 

https://github.com/rabbitmq/rabbitmq-dotnet-client/milestone/49

**Comment by lukebakken** [comment]
https://www.nuget.org/packages/RabbitMQ.Client/6.2.0-rc.1

:crossed_fingers:

**Comment by bollhals** [comment]
Hmm there is one thing that could be influenced in high throughput cases, never thought of it this way but I think it would be theoretically possible.

We've changed internally when you want to send a command from directly sending it on the socket to the internal channel that then has one writer attached that basically just writes it out to the socket.
Now in scenarios where you'd such a high load (or slow server) that you fill the channel queue so full that the heartbeat frame gets not sent out in time, you'll eventually end up in a timeout. (Assuming the server only resets the heartbeat on heartbeat frames )

I've once saw it when I was debugging a modified flooding publish test (sending from multiple threads a few million messages in total through one connection) that the queue backlog can go quite high :) Not sure though whether this could be the source of the issue for the first link. 

For the 2nd I don't know, not enough information yet to figure out something, but from what's written the timeout occurs on connect? That sounds strange for a heartbeat or I am missing something here.

**Comment by lukebakken** [comment]
RabbitMQ resets the heartbeat timeout on any socket activity, sending or receiving, not just heartbeat frames.

**Comment by bollhals** [comment]
> RabbitMQ resets the heartbeat timeout on any socket activity, sending or receiving, not just heartbeat frames.

Excellent, that means my theory is completely incorrect :) 
But that would mean that nothing was received at all on a high throughput scenario? 🤔

**Comment by lukebakken** [comment]
We don't know enough to say. I asked for some code and more details.

**Comment by lukebakken** [comment]
Closing due to lack of response from the initial reporters :man_shrugging:
