### ISSUE TITLE
System.Memory and assembly version conflict

### ISSUE THREAD

**Issue by lukebakken** [rabbitmq/rabbitmq-dotnet-client#894]
In [this `rabbitmq-users` message](https://groups.google.com/d/topic/rabbitmq-users/3-elYifTCDE/discussion) the user shows that there is an issue with `System.Memory`, and also reported the problem [here](https://forums.autodesk.com/t5/revit-api-forum/rabbitmq-connect-to-external-application-from-revit/td-p/9595221#M48064).

It turns out they are using the RabbitMQ .NET client in an environment that has a different version of `System.Memory.dll` present. I believe this is the scenario that @bording pointed out in [this comment](https://github.com/rabbitmq/rabbitmq-dotnet-client/pull/729#issuecomment-591631100).

At this point there's not much we can do but what should my guidance be in this scenario if it comes up again?

**Comment by stebet** [comment]
Binding Redirects in the web.config or app.config should take care of these:
https://docs.microsoft.com/en-us/dotnet/framework/configure-apps/redirect-assembly-versions

**Comment by lukebakken** [comment]
Great, thank you.

**Comment by michaelklishin** [comment]
Added a short [doc section](https://www.rabbitmq.com/dotnet-api-guide.html?skip_cache=1#dependencies) (CDN propagation will take some time)
