### ISSUE TITLE
Async methods not available on .NET 4 or 4.5

### ISSUE THREAD

**Issue by tommy-carlier** [rabbitmq/rabbitmq-dotnet-client#91]
The asynchronous methods (e.g. *SharedQueue.DequeueAsync*) are not available in .NET 4 or 4.5, even though the source code indicates that these methods should be available (#if NETFX_CORE || NET4).

I suspect that the NET4 conditional symbol is not set correctly.

In some places, #if NETFX_CORE is checked without including NET4, even though it should.

It might be a good idea to introduce a conditional symbol ASYNC_SUPPORTED and use that instead of "NETFX_CORE || NET4" in places where asynchronous functionality is used, and then define this symbol in the .NET 4/4.5 and WinRT projects.

**Comment by michaelklishin** [comment]
WinRT is still a work in progress. Feel free to look into things that should be done differently and submit a PR :)

**Comment by michaelklishin** [comment]
@tommy-carlier if we'd like to get this into 3.6.0, now is the time to look into a PR. There's only a week or so weeks left till 3.6.0 enters feature freeze for such changes.

**Comment by warrenrumak** [comment]
For what it's worth, Microsoft no longer supports .NET 4.0 and 4.5 with security updates or fixes.  It might be okay to let this item go.

https://blogs.msdn.microsoft.com/dotnet/2015/12/09/support-ending-for-the-net-framework-4-4-5-and-4-5-1/

**Comment by michaelklishin** [comment]
Thank you.

We will develop a new client for .NET Core from scratch. This client then will transition to maintenance mode only for a year or two until the new one (as well as .NET Core) matures.

**Comment by michaelklishin** [comment]
This client is in maintenance mode now and uses .NET Core tooling in master, which we couldn't get to build the WinRT version :( Closing this as it's not entirely clear if we can support WinRT in the future. .NET Core eclipses it and will be what master in this client and a new client (see #148) will target.
