### ISSUE TITLE
OnRecovery Event

### ISSUE THREAD

**Issue by BarShavit** [rabbitmq/rabbitmq-dotnet-client#939]
Hello

It will be nice to have an event inside the connection which fires when a connection recovery happened.
We can use it to manage publish confirms & etc.

Thank you!

**Comment by michaelklishin** [comment]
[There already is](https://github.com/rabbitmq/rabbitmq-dotnet-client/blob/275b4ebcc6f00df414612703ea0c3e367f233c26/projects/RabbitMQ.Client/client/impl/AutorecoveringConnection.cs#L84).
