### ISSUE TITLE
Time out exception on CreateModel in high volume scenario

### ISSUE THREAD

**Issue by pedrofernandesfilho** [rabbitmq/rabbitmq-dotnet-client#945]
**Problem**

I'm getting "The operation has timed out" exception on `CreateModel()` in a high volume queuing scenario.

**Details**

In a ASPNET Core API, the Controller Action call `SendMessage` method of `ProducerMessage` class.
Doing 60 simultaneous requests 3 times with an interval of 1 second, the error occurs in the third time.

**Code**

```
    public class ProducerMessage<T>
    {
        private readonly ObjectPool<IModel> channelPool;

        public ProducerMessage(ObjectPool<IModel> channelPool) => this.channelPool = channelPool;

        public Task SendMessage(T message, string exchange, string routingKey = "", bool persistent = false)
        {
            var channel = channelPool.Get();
            var propertie = channel.CreateBasicProperties();
            propertie.Persistent = persistent;
            channelPool.Return(channel);
            return SendMessage(message, exchange, routingKey, propertie);
        }

        public Task SendMessage(T message, string exchange, string routingKey = "", IBasicProperties? properties = null)
        {
            var channel = channelPool.Get();

            try
            {
                var jsonEmBytes = JsonSerializer.SerializeToUtf8Bytes(message);

                AddUuidIfNecessary(channel, ref properties);

                channel.BasicPublish(exchange: exchange,
                    routingKey: routingKey,
                    basicProperties: properties,
                    body: cifrada);

                return Task.CompletedTask;
            }
            finally
            {
                channelPool.Return(channel);
            }
        }

        private static void AddUuidIfNecessary(IModel channel, ref IBasicProperties? properties)
        {
            properties ??= channel.CreateBasicProperties();
            properties.Headers ??= new Dictionary<string, object>();
            if (!properties.Headers.ContainsKey("UUID"))
                properties.Headers.Add("UUID", Guid.NewGuid().ToString());
        }
    }
```

```
            services.AddSingleton(CreateConnection);
            services.AddSingleton(CreateObjectPool);
```

```
        private static IConnection CreateConnection(IServiceProvider serviceProvider)
        {
            try
            {
                var options = serviceProvider.GetRequiredService<IOptions<RabbitMQOptions>>();

                if (options.Value.ConnectionString == null)
                    throw new ArgumentException("connection string.");

                var factory = new ConnectionFactory()
                {
                    Uri = new Uri(options.Value.ConnectionString),
                    AutomaticRecoveryEnabled = true,
                    DispatchConsumersAsync = true
                };

                return factory.CreateConnection(options.Value.HostNames.ToList());
            }
            catch (BrokerUnreachableException ex)
            {
                throw new Exception("connect RabbitMQ server error", ex);
            }
        }

        private static ObjectPool<IModel> CreateObjectPool(IServiceProvider serviceProvider)
        {
            var producerOptions = serviceProvider.GetRequiredService<IOptions<ProducerOptions>>();
            var connection = serviceProvider.GetRequiredService<IConnection>();
            var policy = new RabbitModelPooledObjectPolicy(connection);
            var provider = new DefaultObjectPoolProvider { MaximumRetained = producerOptions.Value.MaximumChannelInPool };
            return provider.Create(policy);
        }
```

How I can resolve this?

**Comment by michaelklishin** [comment]
There isn't a whole lot of information to work with, I'm afraid. A timeout can happen in the client or be reported by the RabbitMQ node. A full stack trace and [server logs](https://www.rabbitmq.com/logging.html) would clarify this. In fact, it is not clear what method throws the exception. We do not guess in this community.

Then there is `RabbitModelPooledObjectPolicy` which is not shown. I googled for it and found [a forum post](https://www.c-sharpcorner.com/article/publishing-rabbitmq-message-in-asp-net-core/) and a couple of posts that refer to it.
It's something that is critically important to know what this pool does. It can be that its size is insufficient for the rate.

Finally, 60 messages a second is not a rate that ever needs any kind of tuning for. 60 `channel.open`/`channel.open-ok` roundtrips a second is *a lot* more expensive and [not how channels are supposed to be used](https://www.rabbitmq.com/channels.html#monitoring). So my guess is that the pooling mechanism actually doesn't do what it promises. To compare, try the same workload with a single channel, then repeat with your code and observe the [channel churn rate](https://www.rabbitmq.com/channels.html#high-channel-churn) the node reports.

**Comment by pedrofernandesfilho** [comment]
Thank you for the informations.
And I'm sorry for the lack of information. I put some more.

I understood that to support 60 simultaneous publish of messages, it is indicated that the pool has this amount (or approximately) of channels. Makes sense?

**Comment by michaelklishin** [comment]
That's my best guess given that we don't know where the timeout originates (the pool or the server-side of the connection due to high channel churn).

**Comment by pedrofernandesfilho** [comment]
How I do to know where the timeout comes from?

**Comment by michaelklishin** [comment]
@pedrofernandesfilho see my recommendations below. Start with server logs and channel churn metrics. They were mentioned because they are highly relevant.
