### ISSUE TITLE
unintelligible text or data missing using 6.2.1

### ISSUE THREAD

**Issue by liugt34** [rabbitmq/rabbitmq-dotnet-client#960]
with the client version of 5.2.0, it works well
when i upgrade it to 6.2.1,  i meet this problem 

the code is next
```
5.2.0:   await Consumer.Notice(list.Select(o => (o.Body, o.DeliveryTag)).ToList());
6.2.1:   await Consumer.Notice(list.Select(o => (o.Body.ToArray(), o.DeliveryTag)).ToList());    //use Span
```
the data is next
{
    "data": {
        "sourceId": null,
        "registerNo": "1",
        "safeLoad": null,
        "obliquity": null,
        "dirAngle": null,
        "status": 0,
        "message": null,
        "idCard": null,
        "driverName": null,
        "powerStatus": 0,
        "tiltX": 1.67,
        "tiltY": 1.67,
        "alarmCode": null,
        "craneId": 3,
        "fall": null,
        "height": 11,
        "range": 12.4,
        "rotation": 89.9,
        "load": 0,
        "weightPercent": 0,
        "windSpeed": 1.9,
        "tiltAngle": 1.67,
        "torque": null,
        "torquePercent": 0,
        "serialNo": "9090171",
        "fakeNo": "35020610030003",
        "recordTime": "2020-10-23T19:25:40",
        "creationTime": "2020-10-23T19:25:42.0069589+08:00",
        "isDeleted": false,
        "id": "bee64853-7741-4350-ada1-2b52846eac81"
    },
    "success": true,
    "code": 0,
    "origin": null,
    "deviceMediator": null
}
**iator ":null}  //this place  the right word is "mediator", but less "med" letter**

![image](https://user-images.githubusercontent.com/8056013/97129890-f0e63600-177a-11eb-8246-19e29c0122b6.png)

**Comment by michaelklishin** [comment]
Thank you for your time.

Team RabbitMQ uses GitHub issues for specific actionable items engineers can work on. This assumes that we have a certain amount of information to work with.

Getting all the details necessary to reproduce an issue, make a conclusion or even form a hypothesis about what's happening can take a fair amount of time. Our team is multiple orders of magnitude smaller than the RabbitMQ community. Please help others help you by providing a way to reproduce the behavior you're
observing and sharing as much relevant information as possible [on the list](https://groups.google.com/forum/#!forum/rabbitmq-users):

 * Server, client library and plugin (if applicable) versions used
 * Server logs
 * A code example or terminal transcript that can be used to reproduce
 * **Full** exception stack traces (not a single line message)
 * `rabbitmqctl status` (and, if possible, `rabbitmqctl environment` output)
 * Other relevant things about the environment and workload, e.g. OS/systemd logs, [a traffic capture](https://www.rabbitmq.com/amqp-wireshark.html), deployment tool logs, etc

Feel free to edit out hostnames and other potentially sensitive information.

When/if we have a complete enough understanding of what's going on, a recommendation will be provided or a new issues with more context will be filed.

Thank you.

**Comment by michaelklishin** [comment]
We need an executable way to reproduce. There can be too many factors that affect the logged value, in particular how the consumer is implemented. See [Consumer Memory Safety](https://www.rabbitmq.com/dotnet-api-guide.html#consuming-memory-safety) which are new requirements in `6.x`.

**Comment by stebet** [comment]
It really looks like this is a case of the consumers not copying the event buffers for further processing. If you copy the contents of the event body, does that run correctly?

**Comment by liugt34** [comment]
> It really looks like this is a case of the consumers not copying the event buffers for further processing. If you copy the contents of the event body, does that run correctly?

sorry, because the project is out of time ,we have to rollback to 5.2.0, next period we will review this problem ，an try to solve it!
