### ISSUE TITLE
One application with 3 consumer - not running em parallel

### ISSUE THREAD

**Issue by pabloandrei** [rabbitmq/rabbitmq-dotnet-client#961]
Hello guys, I have a question that I researched previously and I didn't find a solution.
I have an application, which should process 3 or more requests and parallel, using RabbitMq.

For this, I created 3 "consumer", according to the code below:

```
private void StartBasicConsume()
        {
            _logger.LogTrace("Starting RabbitMQ basic consume");

            if (_consumerChannel != null)
            {
                var consumer01 = new AsyncEventingBasicConsumer(_consumerChannel);
                consumer01.Received += Consumer_Received;
                _consumerChannel.BasicConsume(
                    _queueName,
                    false,
                    consumer01);

                var consumer02 = new AsyncEventingBasicConsumer(_consumerChannel);
                consumer02.Received += Consumer_Received;
                _consumerChannel.BasicConsume(
                    _queueName,
                    false,
                    consumer02);

                var consumer03 = new AsyncEventingBasicConsumer(_consumerChannel);
                consumer03.Received += Consumer_Received;
                _consumerChannel.BasicConsume(
                    _queueName,
                    false,
                    consumer03);
            }
            else
            {
                _logger.LogError("StartBasicConsume can't call on _consumerChannel == null");
            }
        }
```

When there is a need for processing in 3 requests (for example), I call my event Publish, inside a loop with different calls, according to the code below:

```
public void Publish(IntegrationEvent @event)
        {
            if (!_persistentConnection.IsConnected) _persistentConnection.TryConnect();

            var policy = Policy.Handle<BrokerUnreachableException>()
                .Or<SocketException>()
                .WaitAndRetry(_retryCount, retryAttempt => TimeSpan.FromSeconds(Math.Pow(2, retryAttempt)),
                    (ex, time) =>
                    {
                        _logger.LogWarning(ex,
                            "Could not publish event: {EventId} after {Timeout}s ({ExceptionMessage})", @event.Id,
                            $"{time.TotalSeconds:n1}", ex.Message);
                    });

            var eventName = @event.GetType().Name;

            _logger.LogTrace("Creating RabbitMQ channel to publish event: {EventId} ({EventName})", @event.Id,
                eventName);

            using (var channel = _persistentConnection.CreateModel())
            {
                _logger.LogTrace("Declaring RabbitMQ exchange to publish event: {EventId}", @event.Id);

                channel.ExchangeDeclare(BROKER_NAME, "direct");

                var message = JsonSerializer.Serialize(@event, @event.GetType());
                var body = Encoding.UTF8.GetBytes(message);

                policy.Execute(() =>
                {
                    var properties = channel.CreateBasicProperties();
                    properties.DeliveryMode = 2; // persistent

                    _logger.LogTrace("Publishing event to RabbitMQ: {EventId}", @event.Id);

                    channel.BasicQos(prefetchSize: 0, prefetchCount: 10, global: false);


                    channel.BasicPublish(
                        BROKER_NAME,
                        eventName,
                        true,
                        properties,
                        body);
                });
            }
        }
```

When I look at the process in my QUEUES on RabbitMq I have the 3 consumers created (as shown below):

![image](https://user-images.githubusercontent.com/16004192/97238403-1c434200-17c8-11eb-8f8e-9d1463de966b.png)

But the processing is queued, it does not process the 3 requests simultaneously.

If I run 3 instances of the application, I have the parallel; the same applying by sending 3 items to consumers I had only one task at a time.

In additional, Im follow hit of this link: https://www.rabbitmq.com/consumer-prefetch.html

Someone would have any tips, very grateful

**Comment by michaelklishin** [comment]
Thank you for your time.

Team RabbitMQ uses GitHub issues for specific actionable items engineers can work on. GitHub issues are not used for questions, investigations, root cause analysis, discussions of potential issues, etc (as defined by this team).

We get at least a dozen of questions through various venues every single day, often light on details.
At that rate GitHub issues can very quickly turn into a something impossible to navigate and make sense of even for our team. Because GitHub is a tool our team uses heavily nearly every day, the signal/noise ratio of issues is something we care about a lot.

Please post this to [rabbitmq-users](https://groups.google.com/forum/#!forum/rabbitmq-users).

Thank you.

**Comment by michaelklishin** [comment]
See tutorial 2 and the [guide on confirms](https://www.rabbitmq.com/confirms.html). When all consumers are on a shared channel, the prefetch value used and the way you acknowledge messages become critically important. Your consumers use manual acknowledgments but the snippets posted never acknowledge any deliveries, neither they demonstrate what prefetch value may be used.

The same queue page you are looking at to see how many consumers a queue has, has a metric on unacknowledged deliveries.

While not related to consumers in any way, the way your perform publishing is highly suboptimal: opening a new channel per message is not how channels are meant to be used: [Channel Basics](https://www.rabbitmq.com/channels.html#basics), [Publisher Lifecycle](https://www.rabbitmq.com/publishers.html#lifecycle).
