### ISSUE TITLE
7.0 Proposal - Combine BasicDeliver and BasicGetResult into one object for clarity and lazy load properties to save allocations/CPU

### ISSUE THREAD

**Issue by stebet** [rabbitmq/rabbitmq-dotnet-client#969]
I'd like to propose that we combine the RabbitMQ.Client.BasicGetResult and RabbitMQ.Client.Impl.BasicDeliver into the same object since they have the same purpose of containing message data and properties/headers on push/pull delivery of messages. This object can be constructed out of incoming frames and mostly contain memory buffers internally and operations to deserialize the data when needed (wrapped by public properties).

By wrapping the Properties and other data into the same object, we can also just initialize them with the memory buffers when they are received and defer deserializing data for both properties and headers to when they are accessed. This is like what Kestrel does with incoming HTTP requests and can help us save both CPU cycles and allocations and only create objects as they are needed, and since they are being deserialized from memory buffers the deserialization are instant from the client perspective. That also allows to make it clear to consumers that they need to access and operate on the data while they have it as they'll be disposed at the end of message processing/delivery to consumers. It also reduces parameters sent to methods and makes the API cleaner and hopefully more intuitive.

**Comment by michaelklishin** [comment]
They are not the same thing: a `basic.get` response can come back empty while consumer (subscription) delivery has no "empty" equivalent (or rather, it is a non-event). They are separate methods in the protocol as well. I don't think `basic.get` response allocation efficiency is something we should worry about because polling by definition is extremely inefficient and the docs recommend against it.

**Comment by stebet** [comment]
Wouldn't in that case the MessageResponse message just be null as it's indicative of no data?

**Comment by michaelklishin** [comment]
@stebet my point is not that we cannot distinguish between the two. I just think that we should not optimize this: it will go against the protocol structure, no other client library does this, and most importantly, `basic.get` is not a case we should spend time on optimizing. Polling is incredibly inefficient in general, so we would be spinning out wheels IMO.
