### ISSUE TITLE
Connection Thread Performance Issue?

### ISSUE THREAD

**Issue by matthew1471** [rabbitmq/rabbitmq-dotnet-client#97]
Hi,
I've been working on an application that handles a LOT of messages and after optimising my code to every bit of its life believe I have found a performance issue in rabbitmq-dotnet-client v3.5.3.

Visual Studio 2013 performance analysis points out that the majority of the program now spends its time executing this:
```c#
                    while (m_running)
                    {
```
projects\client\RabbitMQ.Client\src\client\impl\Connection.cs

I've noticed that if I have 1 channel open, then I am unable to keep up with the volume of messages, however if I open another channel (presumably MainLoopIteration then runs for longer and has more things to do) say about 3, then the application performs perfectly and spends more time reading messages.

The ironic thing is just running 3 of exactly the same Channels against the same connection is enough to improve the performance enough to keep up in real time.

For my consumers I use ManualResetEvent and AutoResetEvent as that is generally now preferable in threads than using very tight while loops like while (true) or while (m_running) and I wondered if the RabbitMQ client needed the same?

I'm new to the RabbitMQ .NET Client source, does someone more familiar with the code base know if the while loop can be replaced with a semaphore like that used by ManualResetEvent to further improve its performance? Presumably the frame would be written to a BlockingCollection and then the loop would wait for the signal?

See : http://stackoverflow.com/questions/8881396/cpu-usage-increasing-up-to-100-in-infinite-loop-in-thread and http://stackoverflow.com/questions/7402146/cpu-friendly-infinite-loop

Thank you for your time,
Matthew

**Comment by michaelklishin** [comment]
Please ask questions on the mailing list. Opening new channels does not "slow down" I/O loop and even if it did, I don't see how your consumer throughput increases. Using more channels and consumers means a higher degree of concurrency in the client.

In 3.5 you can provide your own task scheduler and dispatch is concurrent, with per-channel ordering preserved. Previously all operations were dispatched on the I/O thread.

**Comment by matthew1471** [comment]
Hi Michael, I saw this as an issue so felt it was best to discuss the issue here.. but if the mailing list is more appropriate I will write it there :-).

Thanks,
Matthew

**Comment by michaelklishin** [comment]
Also, I don't know what kind of profiler you used but sampling profilers will always indicate that the I/O loop is the top item even though all it does is reading and parsing incoming data, potentially waiting for I/O. This cannot be parallelised in practice for a single connection.

The I/O loop can be migrated to newer kernel I/O API now that we require a recent .NET version but
for *clients* it won't make a huge difference. Same with attempts to optimise protocol parser.

Looking at what takes time and/or can be parallelised in your consumers has a lot more potential. Using more channels or even connections (if your link is very good, e.g. 100 GBit/s) is also more likely to yield noticeable improvements.

**Comment by michaelklishin** [comment]
And then there is [a blog post](https://www.rabbitmq.com/blog/2014/04/14/finding-bottlenecks-with-rabbitmq-3-3/) about consumers and QoS settings' effect on throughput.

**Comment by matthew1471** [comment]
>will always indicate that the I/O loop is the top item
when using wait handles / semaphores the Visual Studio 2013 Performance Analysis doesn't show up my threads anymore.. I think it's more that VS is seeing the conditional check as being executed an excessive number of times rather than the actual I/O.. the I/O does come up in the list of top items (which is like you said, exactly what should be expected) but the while loop conditional check should not.

I don't seem to have a problem with the I/O functions, purely the conditional checks. It's running the conditional check a lot (even when there aren't any frames available).

I'll take a look at those blog posts, thank you for your time and comments so far :-)

Regards,
Matthew
