### ISSUE TITLE
7.0 Proposal: BasicPublish with ROM<byte> for exchange and routing key

### ISSUE THREAD

**Issue by bollhals** [rabbitmq/rabbitmq-dotnet-client#972]
The basic publish is one of the "hottest" method we have, so any improvements there are surely very valuable.

Extracted from #970, I propose to extend the IModel interface with a new method for 7.0:
`void BasicPublish(ReadOnlyMemory<byte> exchange, ReadOnlyMemory<byte> routingKey, bool mandatory, IBasicProperties basicProperties, ReadOnlyMemory<byte> body);`

This replaces the expensive string -> byte encoding for the often times same string.

**Comment by stebet** [comment]
I'm all for performance, but I don't really see this as something that will be widely used, but for some very niche cases. IO will always be the bottleneck, not CPU usage.

**Comment by stebet** [comment]
I've just had a second thought about this, and I've gone 180 on my original comment. I think this might be a clever idea for high-perf scenarios. I also remembered that there exists an API that does similar things: https://github.com/StackExchange/StackExchange.Redis/blob/main/src/StackExchange.Redis/Interfaces/IDatabase.cs#L241

The StackExchange.Redis API uses RedisKey structs as key parameters which have implicit conversion to both byte[] and string: https://github.com/StackExchange/StackExchange.Redis/blob/main/src/StackExchange.Redis/RedisKey.cs#L178-L191

**Comment by bollhals** [comment]
To indicate the caching intent for this, we could also define the signature as 
`void BasicPublish(RabbitMqString exchange, RabbitMqString routingKey, bool mandatory, IBasicProperties basicProperties, ReadOnlyMemory<byte> body);`
where RabbitMqString is defined as 
```cs
public readonly struct RabbitMqString 
{ 
    public readonly string Value;
    internal readonly ReadOnlyMemory<byte> CachedBytes;
    public RabbitMqString(string value) { /* implement */ };
}
/**************** OR *****************/
public sealed class RabbitMqString 
{ 
    private ReadOnlyMemory<byte> _cache;
    public string Value { get;}
    internal ReadOnlyMemory<byte> CachedBytes => /* populate _cache if not empty or return _cache */
    public RabbitMqString(string value) { /* implement */ };
}
```

where the struct would build the cache within the ctor, while the class could defer it to it's first use if we want to.

**Comment by bollhals** [comment]
Update from a local running version on this:
|                  Method |       Mean |     Error |    StdDev | Gen 0 | Gen 1 | Gen 2 | Allocated | Code Size |
|------------------------ |-----------:|----------:|----------:|------:|------:|------:|----------:|----------:|
|       BasicPublishWrite | 41.3951 ns | 0.8661 ns | 0.0475 ns |     - |     - |     - |         - |     386 B |
|        BasicPublishSize | 18.5197 ns | 0.1749 ns | 0.0096 ns |     - |     - |     - |         - |     178 B |
| BasicPublishMemoryWrite | 14.3104 ns | 0.6103 ns | 0.0334 ns |     - |     - |     - |         - |     775 B |
|  BasicPublishMemorySize |  0.8075 ns | 0.0310 ns | 0.0017 ns |     - |     - |     - |         - |      39 B |

Obviously the gain increases the larger the string (Exchange / RoutingKey) is. (Benchmark is with "Exchange_OR_RoutingKey").

Another benchmark to serialize into the 3 frames of a message:
|             Method |     Mean |    Error |  StdDev | Ratio | Gen 0 | Gen 1 | Gen 2 | Allocated | Code Size |
|------------------- |---------:|---------:|--------:|------:|------:|------:|------:|----------:|----------:|
|       BasicPublish | 223.9 ns | 13.50 ns | 0.74 ns |  1.00 |     - |     - |     - |         - |    2504 B |
| BasicPublishMemory | 182.1 ns |  7.83 ns | 0.43 ns |  0.81 |     - |     - |     - |         - |    2518 B |

It my does not seem huge, but it increases the throughput on the most relevant hotpath. 
I'll setup a PR for 7.0 in the next days.
