### ISSUE TITLE
ClientProvidedName encoding

### ISSUE THREAD

**Issue by fastfoot** [rabbitmq/rabbitmq-dotnet-client#977]
Value provided to ConnectionFactory.ClientProvidedName is displayed on managamenet GUI with wrong encoding.

![image](https://user-images.githubusercontent.com/34970893/99198051-546ded00-2796-11eb-8d96-00abca81922b.png)

**Comment by fastfoot** [comment]
3.8.3, 3.7.2
C# Client 6.2.1 
.net core 5.0

**Comment by michaelklishin** [comment]
No encoding is expected or specified when the value is stored. Connection metadata fields are treated as arbitrary bags of bytes, and the protocol spec in some cases explicitly expects them to be limited to the ASCII table. This value is supposed to be an identifier, and management UI displays it as is, without assuming any particular encoding (note that your *browser* might be configured to use a particular encoding).

If you can provide evidence that this library specifically incorrectly encodes the provided value, please put together an executable example. Here is [where the value is set in the code](https://github.com/rabbitmq/rabbitmq-dotnet-client/blob/88001ce2e02450b1f75e7b0cf59fd3745b203d9d/projects/RabbitMQ.Client/client/impl/Connection.cs#L1058). There isn't any encoding going on.

I cannot reproduce using two different clients, so my guess is that this may be a browser-side encoding mismatch:

![Screenshot 2020-11-16 at 12 06 29](https://user-images.githubusercontent.com/1090/99233420-41920180-2804-11eb-8e48-1e8b57c1e554.png)

**Comment by fastfoot** [comment]
accepted, my mistake reading config file with wrong encoding.
