### ISSUE TITLE
shouldn't it be DeliveryMode == value cause the deliveryMode will always be set to value 

### ISSUE THREAD

**Issue by srikarjosyam** [rabbitmq/rabbitmq-dotnet-client#979]
https://github.com/rabbitmq/rabbitmq-dotnet-client/blob/34aac15431ca3e637744a2dd37af5f62d1f4b6d3/projects/RabbitMQ.Client/client/impl/BasicProperties.cs#L89

**Comment by michaelklishin** [comment]
Delivery mode is an integer in the protocol but it is a lot more convenient for the user to use a boolean. The setter does try to unconditionally set the value to `1` or `2` depending on the provided boolean value. So the code does what it's supposed to do unless I'm missing something.
