### ISSUE TITLE
Drop immediate flag

### ISSUE THREAD

**Issue by michaelklishin** [rabbitmq/rabbitmq-dotnet-client#98]
It isn't supported as of RabbitMQ 3.0 and was removed in many other clients.

**Comment by micdenny** [comment]
sorry @michaelklishin but this introduce a breaking changes and should be notified in the [Release Highlights](https://github.com/rabbitmq/rabbitmq-server/releases/tag/rabbitmq_v3_6_0), in fact Mr. @Pliner that implemented this in `RabbitMQ.Client` forgot to drop the flag in `EasyNetQ` :smile: and now who upgrade to RabbitMQ.Client v3.6.0 is taking this exception:

```
Method not found: 'Void RabbitMQ.Client.IModel.BasicPublish(System.String, System.String, Boolean, Boolean, RabbitMQ.Client.IBasicProperties, Byte[])'.
```

issued opened also on https://github.com/EasyNetQ/EasyNetQ/issues/527

**Comment by michaelklishin** [comment]
@micdenny OK, sorry about that, I updated release notes.

**Comment by micdenny** [comment]
@michaelklishin thank you

**Comment by Jestar342** [comment]
Should this have been v4, and not v3.6? It's a backwards compatibility breaking change.

**Comment by videlalvaro** [comment]
@Jestar342 so far RabbitMQ doesn't follow SEMVER, that might change in the future

**Comment by Jestar342** [comment]
Ah ok. What versioning scheme does it follow? (and is it documented?)

**Comment by videlalvaro** [comment]
@Jestar342 not documented AFAIK

The format is X.Y.Z

X: rarely increased, this only happens when main internal systems suffer big changes, I would say that perhaps 3.6.0 warranted a major version bump.
Y: Breaking changes and new features, this can probably be seen as the major version of SEMVER
Z: bug fixes

**Comment by Jestar342** [comment]
"Y: Breaking changes and new features, this can probably be seen as the major version of SEMVER"

That's the point of contention here. It should be clear when there is a new feature vs a breaking change. :)

**Comment by michaelklishin** [comment]
RabbitMQ dropped support for this flag in 3.0.

**Comment by videlalvaro** [comment]
When the `Y` value increase, expect both. That's how it is right now.

**Comment by michaelklishin** [comment]
RabbitMQ server hadn't supported this flag for 3 years by the time 3.6.0 shipped. If anything, this was a confusing and misleading API element, which counts for a bug in my books, so it was removed.

In any case, 4.0, 5.0 are reserved for actual *major* changes and this isn't one. There weren't many complaints about this feature removal in the server to start with.

**Comment by michaelklishin** [comment]
Relevant to this is #150. And what does count as a major change and a version bump to 4.0? #83 and #148.
