### ISSUE TITLE
In a queue, under the same connection, multiple threads start multiple channel pull consumption at the same time, and a message is pulled by two channels at the same time.

### ISSUE THREAD

**Issue by HeJiaWang-96** [rabbitmq/rabbitmq-dotnet-client#988]
BUG:In a queue, under the same connection, multiple threads start pulling consumption of multiple channels at the same time. A message is obtained by two channels at the same time, resulting in duplicate messages.
RabbitMQ Version 3.8.9
RabbitMQ.Client 6.2.1
![7Q`JLC`{0SY4~DB8Y2_G83](https://user-images.githubusercontent.com/54062106/102192786-32cb6700-3ef6-11eb-8d38-926dd9b0b2f9.png)

**Comment by michaelklishin** [comment]
Thank you for your time.

Team RabbitMQ uses GitHub issues for specific actionable items engineers can work on. This assumes that we have a certain amount of information to work with.

Getting all the details necessary to reproduce an issue, make a conclusion or even form a hypothesis about what's happening can take a fair amount of time. Our team is multiple orders of magnitude smaller than the RabbitMQ community. Please help others help you by providing a way to reproduce the behavior you're
observing and sharing as much relevant information as possible [on the list](https://groups.google.com/forum/#!forum/rabbitmq-users):

 * Server, client library and plugin (if applicable) versions used
 * Server logs
 * A code example or terminal transcript that can be used to reproduce
 * **Full** exception stack traces (not a single line message)
 * `rabbitmqctl status` (and, if possible, `rabbitmqctl environment` output)
 * Other relevant things about the environment and workload, e.g. OS/systemd logs, [a traffic capture](https://www.rabbitmq.com/amqp-wireshark.html), deployment tool logs, etc

Feel free to edit out hostnames and other potentially sensitive information.

When/if we have a complete enough understanding of what's going on, a recommendation will be provided or a new issues with more context will be filed.

Thank you.

**Comment by michaelklishin** [comment]
This is no evidence of a bug of any kind.

It is perfectly possible for a message to be routed to more than one queue and consumed from those queues in parallel by two consumers. A single message in RabbitMQ is never delivered to two consumers at the same time.

On your screenshot, the deliveries have two different delivery tags that are not sequential (100 and 216), which is evidence of two separate channels being used. That's about as much as we can tell. A [traffic capture](https://www.rabbitmq.com/amqp-wireshark.html) on the consumer end will reveal what the consumers do. See the list of bindings for the target exchange and the list of consumers on every queue involved to find out what may be off.
